### ISSUE TITLE
`lerna publish` fails with some versions of Git on Windows

### ISSUE THREAD

**Issue by zenflow** [lerna/lerna#1133]
## Expected Behavior

As a Windows user with Git installed via Cygwin, I expect to be able to run `lerna publish` successfully.

## Current Behavior

After confirming the publish (i.e. typing "yes"), I get the following error in my console: 

<details><summary><strong>console error</strong></summary><p>

```txt
lerna ERR! execute caught error
lerna ERR! Error: On branch master
lerna ERR! Your branch is up-to-date with 'origin/master'.
lerna ERR!
lerna ERR! Changes not staged for commit:
lerna ERR!      modified:   apps/mtdirect-api/package.json
lerna ERR!      modified:   apps/mtdirect-proxy/package.json
lerna ERR!      modified:   apps/mtdirect-ui-nextjs/package.json
lerna ERR!
lerna ERR! no changes added to commit
lerna ERR!
lerna ERR!     at Function.module.exports.sync (C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\node_modules\execa\index.js:303:26)
lerna ERR!     at Function.execSync (C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\node_modules\lerna\lib\ChildProcessUtilities.js:60:30)
lerna ERR!     at Function.commit (C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\node_modules\lerna\lib\GitUtilities.js:88:39)
lerna ERR!     at PublishCommand.gitCommitAndTagVersionForUpdates (C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\node_modules\lerna\lib\commands\PublishCommand.js:726:30)
lerna ERR!     at PublishCommand.commitAndTagUpdates (C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\node_modules\lerna\lib\commands\PublishCommand.js:702:26)
lerna ERR!     at PublishCommand.execute (C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\node_modules\lerna\lib\commands\PublishCommand.js:307:14)
(node:4536) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
        modified:   apps/mtdirect-api/package.json
        modified:   apps/mtdirect-proxy/package.json
        modified:   apps/mtdirect-ui-nextjs/package.json

no changes added to commit

(node:4536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process
with a non-zero exit code.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mtdirect-monorepo@ publish: `lerna publish --exact --cd-version=prerelease --preid=alpha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mtdirect-monorepo@ publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mbrunetti\AppData\Roaming\npm-cache\_logs\2017-11-21T16_58_34_589Z-debug.log
```
</p></details>

## Steps to Reproduce (for bugs)
1. Be on a Windows machine, with Git installed via Cygwin
2. Make sure there are some changes to publish in at least one of your packages
3. Run `lerna publish`, answering all the prompts
4. Observe error in console

<details><summary><strong>lerna-debug.log</strong></summary><p>

```txt
0 silly input [ 'publish' ]
1 silly flags { _: [ 'publish' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   exact: true,
1 silly flags   'cd-version': 'prerelease',
1 silly flags   cdVersion: 'prerelease',
1 silly flags   preid: 'alpha' }
2 verbose rootPath C:\Users\mbrunetti\Documents\git\mtdirect-monorepo
3 info version 2.5.1
4 info versioning independent
5 silly isInitialized
6 silly isInitialized true
7 silly existsSync C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\VERSION
8 silly initialize attempt
9 silly isDetachedHead
10 silly getCurrentBranch
11 verbose getCurrentBranch master
12 verbose isDetachedHead false
13 silly getCurrentBranch
14 verbose getCurrentBranch master
15 silly getUpdates
16 info Checking for updated packages...
17 silly hasTags
18 verbose hasTags true
19 silly getLastTag
20 verbose getLastTag v1.0.0-alpha.1
21 info Comparing with v1.0.0-alpha.1.
22 silly diffSinceIn v1.0.0-alpha.1 apps/mtdirect-api
23 silly diff apps/mtdirect-api/data/user.js
23 silly diff apps/mtdirect-api/lib/expressFsRouter.js
23 silly diff apps/mtdirect-api/lib/pCall.js
23 silly diff apps/mtdirect-api/lib/startServer.js
23 silly diff apps/mtdirect-api/main.js
23 silly diff apps/mtdirect-api/middlewares/index.js
23 silly diff apps/mtdirect-api/middlewares/passport/index.js
23 silly diff apps/mtdirect-api/middlewares/passport/strategies/usernameAndPassword.js
23 silly diff apps/mtdirect-api/middlewares/sessions/index.js
23 silly diff apps/mtdirect-api/models/.gitkeep
23 silly diff apps/mtdirect-api/nodemon.json
23 silly diff apps/mtdirect-api/package.json
23 silly diff apps/mtdirect-api/process.json
23 silly diff apps/mtdirect-api/routes/auth/getCurrentUser.js
23 silly diff apps/mtdirect-api/routes/auth/index.js
23 silly diff apps/mtdirect-api/routes/auth/login.js
23 silly diff apps/mtdirect-api/routes/auth/logout.js
23 silly diff apps/mtdirect-api/server.js
23 silly diff apps/mtdirect-api/shipitfile.js
23 silly diff apps/mtdirect-api/start.js
24 silly diffSinceIn v1.0.0-alpha.1 apps/mtdirect-proxy
25 silly diff apps/mtdirect-proxy/lib/pCall.js
25 silly diff apps/mtdirect-proxy/lib/startServer.js
25 silly diff apps/mtdirect-proxy/main.js
25 silly diff apps/mtdirect-proxy/package.json
25 silly diff apps/mtdirect-proxy/process.json
25 silly diff apps/mtdirect-proxy/server.js
25 silly diff apps/mtdirect-proxy/shipitfile.js
25 silly diff apps/mtdirect-proxy/start.js
26 silly diffSinceIn v1.0.0-alpha.1 apps/mtdirect-ui-nextjs
27 silly diff apps/mtdirect-ui-nextjs/.babelrc
27 silly diff apps/mtdirect-ui-nextjs/babel.config.js
27 silly diff apps/mtdirect-ui-nextjs/components/App.js
27 silly diff apps/mtdirect-ui-nextjs/components/ErrorMessage.js
27 silly diff apps/mtdirect-ui-nextjs/components/Header.js
27 silly diff apps/mtdirect-ui-nextjs/components/LoginForm.js
27 silly diff apps/mtdirect-ui-nextjs/components/LogoutButton.js
27 silly diff apps/mtdirect-ui-nextjs/lib/auth.js
27 silly diff apps/mtdirect-ui-nextjs/lib/constants.js
27 silly diff apps/mtdirect-ui-nextjs/lib/http.js
27 silly diff apps/mtdirect-ui-nextjs/lib/pCall.js
27 silly diff apps/mtdirect-ui-nextjs/lib/polyfills/fetch.js
27 silly diff apps/mtdirect-ui-nextjs/lib/redirect.js
27 silly diff apps/mtdirect-ui-nextjs/lib/startServer.js
27 silly diff apps/mtdirect-ui-nextjs/main.js
27 silly diff apps/mtdirect-ui-nextjs/next.config.js
27 silly diff apps/mtdirect-ui-nextjs/package.json
27 silly diff apps/mtdirect-ui-nextjs/pages/demo.js
27 silly diff apps/mtdirect-ui-nextjs/pages/index.js
27 silly diff apps/mtdirect-ui-nextjs/pages/login.js
27 silly diff apps/mtdirect-ui-nextjs/process.json
27 silly diff apps/mtdirect-ui-nextjs/server.js
27 silly diff apps/mtdirect-ui-nextjs/shipitfile.js
27 silly diff apps/mtdirect-ui-nextjs/start.js
27 silly diff apps/mtdirect-ui-nextjs/static/favicon.ico
28 verbose updated @manitoulin-transport/mtdirect-api
29 verbose updated @manitoulin-transport/mtdirect-proxy
30 verbose updated @manitoulin-transport/mtdirect-ui-nextjs
31 info Checking for prereleased packages...
32 silly collectDependents
33 silly isPackageDependentOf @manitoulin-transport/mtdirect-api @manitoulin-transport/mtdirect-api
34 silly isPackageDependentOf @manitoulin-transport/mtdirect-api @manitoulin-transport/mtdirect-proxy
35 silly isPackageDependentOf @manitoulin-transport/mtdirect-api @manitoulin-transport/mtdirect-ui-nextjs
36 silly isPackageDependentOf @manitoulin-transport/mtdirect-proxy @manitoulin-transport/mtdirect-api
37 silly isPackageDependentOf @manitoulin-transport/mtdirect-proxy @manitoulin-transport/mtdirect-proxy
38 silly isPackageDependentOf @manitoulin-transport/mtdirect-proxy @manitoulin-transport/mtdirect-ui-nextjs
39 silly isPackageDependentOf @manitoulin-transport/mtdirect-ui-nextjs @manitoulin-transport/mtdirect-api
40 silly isPackageDependentOf @manitoulin-transport/mtdirect-ui-nextjs @manitoulin-transport/mtdirect-proxy
41 silly isPackageDependentOf @manitoulin-transport/mtdirect-ui-nextjs @manitoulin-transport/mtdirect-ui-nextjs
42 silly collectUpdates
43 verbose has filtered update @manitoulin-transport/mtdirect-api
44 verbose has filtered update @manitoulin-transport/mtdirect-proxy
45 verbose has filtered update @manitoulin-transport/mtdirect-ui-nextjs
46 silly initialize success
47 silly execute attempt
48 silly runScriptSync preversion @manitoulin-transport/mtdirect-api
49 silly runScriptSync version @manitoulin-transport/mtdirect-api
50 silly runScriptSync preversion @manitoulin-transport/mtdirect-proxy
51 silly runScriptSync version @manitoulin-transport/mtdirect-proxy
52 silly runScriptSync preversion @manitoulin-transport/mtdirect-ui-nextjs
53 silly runScriptSync version @manitoulin-transport/mtdirect-ui-nextjs
54 silly addFile C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\apps\mtdirect-api\package.json
55 silly addFile C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\apps\mtdirect-proxy\package.json
56 silly addFile C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\apps\mtdirect-ui-nextjs\package.json
57 silly commit Publish
57 silly commit
57 silly commit  - @manitoulin-transport/mtdirect-api@1.0.0-alpha.2
57 silly commit  - @manitoulin-transport/mtdirect-proxy@1.0.0-alpha.2
57 silly commit  - @manitoulin-transport/mtdirect-ui-nextjs@1.0.0-alpha.2
58 verbose commit [ 'commit',
58 verbose commit   '--no-gpg-sign',
58 verbose commit   '-F',
58 verbose commit   'C:\\Users\\MBRUNE~1\\AppData\\Local\\Temp\\6edace2e-5e5e-4e8e-a5fc-add0a96b163d\\lerna-commit.txt' ]
59 error execute caught error
60 error Error: On branch master
60 error Your branch is up-to-date with 'origin/master'.
60 error
60 error Changes not staged for commit:
60 error 	modified:   apps/mtdirect-api/package.json
60 error 	modified:   apps/mtdirect-proxy/package.json
60 error 	modified:   apps/mtdirect-ui-nextjs/package.json
60 error
60 error no changes added to commit
60 error
60 error     at Function.module.exports.sync (C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\node_modules\execa\index.js:303:26)
60 error     at Function.execSync (C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\node_modules\lerna\lib\ChildProcessUtilities.js:59:30)
60 error     at Function.commit (C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\node_modules\lerna\lib\GitUtilities.js:88:39)
60 error     at PublishCommand.gitCommitAndTagVersionForUpdates (C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\node_modules\lerna\lib\commands\PublishCommand.js:726:30)
60 error     at PublishCommand.commitAndTagUpdates (C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\node_modules\lerna\lib\commands\PublishCommand.js:702:26)
60 error     at PublishCommand.execute (C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\node_modules\lerna\lib\commands\PublishCommand.js:307:14)
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| **`git --version`** | **2.14.1** |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 5.5.1 |
| `node --version` | 8.9.0 |

| OS | Version |
| --- | --- |
| Windows | 7 Professional, Service Pack 1 |

**Comment by tivac** [comment]
I run `lerna publish` from `cmd.exe` without issues in Windows 10.

**Comment by zenflow** [comment]
## Problem analysis

The problem is actually with the "addFile" operations (see 54, 55 & 56 in my lerna-debug.log) that happen just before the failing "commit" operation. The "addFile" operations are failing silently (i.e. they don't manage to add the files, but they don't cause an exception which they should)

`git add <file>` does not work when `<file>` is an Windows-formatted absolute path; it must be a Linux-formatted (i.e. path separator must be forward-slash, not back-slash) path, and it cannot be an absolute path starting with e.g. `C:/`.

**This is only an issue with certain versions/builds of Git. It doesn't affect, for instance `git version 2.8.1.windows.1` (portable version of Git installed with SourceTree), but it does affect, for instance `git version 2.8.1.windows.1` (version of Git installed with Cygwin).**

## Proposed solution

Simple solution would be to make `<file>` relative to the Current Working Directory and change back-slashes to forward-slashes. That would fix my problem, and make the "addFile" operation more **portable**.

**Comment by zenflow** [comment]
@tivac What version of Git are you using?

**Comment by zenflow** [comment]
Updated title and original comment, since I did some more investigation and found that the shell (e.g. `cmd.exe` vs `bash`) is not relevant; the version of Git I'm using *is* relevant.

**Comment by tivac** [comment]
@zenflow Sorry, just got back to the right machine. In case it still helps...

```
$ git --version
git version 2.13.0.windows.1
```

**Comment by zenflow** [comment]
Thanks @tivac . This supports my hypothesis that the problem is with Git versions that do **not** have the `.windows` bit in the version name.
