### ISSUE TITLE
Issue with lifecycle hook githook-scripts/postinstall.js:47

### ISSUE THREAD

**Issue by reggi** [lerna/lerna#1155]
```
$ ./node_modules/.bin/lerna --version
2.5.1
$ node -v
v6.8.0
```

```
989 error execute callback with error
990 error Error: Command failed: npm install
990 error npm WARN prefer global marked@0.3.6 should be installed with -g
990 error npm WARN prefer global node-gyp@3.6.2 should be installed with -g
990 error xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
990 error
990 error xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
990 error
990 error ../src/upstream/farmhash-legacy.cc:684:23: warning: unused function 'Shuffle2031' [-Wunused-function]
990 error STATIC_INLINE __m128i Shuffle2031(__m128i x) {
990 error                       ^
990 error 1 warning generated.
990 error clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
990 error clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
990 error /Users/treggi/Desktop/monorepo/packages/my-module/node_modules/githook-scripts/postinstall.js:47
990 error Object.keys(parentModulePackage.scripts)
990 error        ^
990 error
990 error TypeError: Cannot convert undefined or null to object
990 error     at Object.<anonymous> (/Users/treggi/Desktop/monorepo/packages/my-module/node_modules/githook-scripts/postinstall.js:47:8)
990 error     at Module._compile (module.js:570:32)
990 error     at Object.Module._extensions..js (module.js:579:10)
990 error     at Module.load (module.js:487:32)
990 error     at tryModuleLoad (module.js:446:12)
990 error     at Function.Module._load (module.js:438:3)
990 error     at Module.runMain (module.js:604:10)
990 error     at run (bootstrap_node.js:394:7)
990 error     at startup (bootstrap_node.js:149:9)
990 error     at bootstrap_node.js:509:3
990 error npm WARN my-module No repository field.
990 error npm WARN my-module No license field.
990 error npm ERR! Darwin 16.7.0
990 error npm ERR! argv "/Users/treggi/.nvm/versions/node/v6.8.0/bin/node" "/Users/treggi/.nvm/versions/node/v6.8.0/bin/npm" "install"
990 error npm ERR! node v6.8.0
990 error npm ERR! npm  v3.10.8
990 error npm ERR! code ELIFECYCLE
```

**Comment by evocateur** [comment]
> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

You need to fix the actual error (presumably installing Xcode), this isn't lerna's fault.
