### ISSUE TITLE
How does "require('some_module')" work?

### ISSUE THREAD

**Issue by akaRem** [lerna/lerna#1183]
Please describe or point to docs where it is described how module resolution works in lerna.
I created project according to documentation, but I can't run it locally because modules are unavailable to each other. 
And I have no Idea how to fix it.

I created simplified project to reproduce this behavior.

I have such repo structure:
```
.
├── lerna.json
├── node_modules
├── package.json
├── packages
│   ├── a
│   │   ├── index.js
│   │   └── package.json
│   └── b
│       ├── index.js
│       └── package.json
└── yarn.lock
```
lerna.json 
```
{
  "lerna": "2.5.1",
  "version": "0.0.0",
  "packages": ["packages/*"],
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
package.json
```
{
  "workspaces": ["packages/*"]
}
```
packages/a/package.json
```
{
  "name": "@aaaa/a",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "@aaaa/b": "^1.0.0"
  }
}
```
packages/b/package.json
```
{
  "name": "@aaaa/b",
  "version": "1.0.0",
  "main": "index.js"
}
```
packages/a/index.js
```
const b = require("@aaaa/a");
```

## Expected Behavior

I want to run "start" script of repo "a"

## Current Behavior

I run `lerna run start`
And it fails with errror regarding missing module.
```
$ lerna run start
lerna info version 2.5.1
lerna ERR! start Errored while running script in '@aaaa/a'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run start
lerna ERR! module.js:538
lerna ERR!     throw err;
lerna ERR!     ^
lerna ERR!
lerna ERR! Error: Cannot find module '@aaaa/b'
lerna ERR!     at Function.Module._resolveFilename (module.js:536:15)
lerna ERR!     at Function.Module._load (module.js:466:25)
lerna ERR!     at Module.require (module.js:579:17)
lerna ERR!     at require (internal/module.js:11:18)
lerna ERR!     at Object.<anonymous> (/Users/me/Projects/lerna-tst/packages/a/index.js:1:73)
lerna ERR!     at Module._compile (module.js:635:30)
lerna ERR!     at Object.Module._extensions..js (module.js:646:10)
lerna ERR!     at Module.load (module.js:554:32)
lerna ERR!     at tryModuleLoad (module.js:497:12)
lerna ERR!     at Function.Module._load (module.js:489:3)
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! @aaaa/a@1.0.0 start: `node index.js`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the @aaaa/a@1.0.0 start script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR! npm WARN Local package.json exists, but node_modules missing, did you mean to install?
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/me/.npm/_logs/2018-01-08T14_57_26_991Z-debug.log
lerna ERR!
lerna ERR! > @aaaa/a@1.0.0 start /Users/me/Projects/lerna-tst/packages/a
lerna ERR! > node index.js
lerna ERR!
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
(node:28049) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Command failed: npm run start
module.js:538
    throw err;
    ^

Error: Cannot find module '@aaaa/b'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/me/Projects/lerna-tst/packages/a/index.js:1:73)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aaaa/a@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @aaaa/a@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2018-01-08T14_57_26_991Z-debug.log

> @aaaa/a@1.0.0 start /Users/me/Projects/lerna-tst/packages/a
> node index.js


(node:28049) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Steps to Reproduce (for bugs)

1. Create structure as described above
2. lerna init && lerna bootstrap
3. lerna run start
4. see error

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 5.5.1 |
| `yarn --version` | 0.22.0 |
| `node --version` | 8.9.1 |

| OS | Version |
| macOS El Capitan | 10.11.6 |
| NAME | VERSION |

**Comment by akaRem** [comment]
I upgraded some packages and it works.

**Comment by sarfata** [comment]
Still think this ticket was valuable. The doc should explain a bit how things work under the hood to make debugging easier.

**Comment by mbrowne** [comment]
Wasn't working for me either. I think in my case it was because it defaults to npm (as I later realized) and I'm using yarn. In any case, when I learned about [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) I realized that's a better option since I'm using yarn. This worked for me:

    lerna bootstrap --npm-client=yarn --use-workspaces

With this in package.json as described [here](https://github.com/lerna/lerna/tree/master/commands/bootstrap#--use-workspaces):

```json
  "workspaces": [
    "packages/*"
  ]
```
