### ISSUE TITLE
[lerna publish] Can't answer a question unless a user TTY

### ISSUE THREAD

**Issue by diegohaz** [lerna/lerna#1200]
![image](https://user-images.githubusercontent.com/3068563/34919314-de8e5fbc-f948-11e7-99e3-08cc18c97b18.png)

## Expected Behavior

It should publish packages

## Current Behavior

Yarn error: `Can't answer a question unless a user TTY`

## Steps to Reproduce (for bugs)

`lerna publish`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.5",
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'publish' ]
1 silly flags { _: [ 'publish' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   _onRejected: [Function: _onRejected] }
2 verbose rootPath /Users/diegohaz/Projects/schm
3 info version 2.7.0
4 silly isInitialized
5 silly isInitialized true
6 silly existsSync /Users/diegohaz/Projects/schm/VERSION
7 info versioning independent
8 silly initialize attempt
9 silly isDetachedHead
10 silly getCurrentBranch
11 verbose getCurrentBranch master
12 verbose isDetachedHead false
13 silly getCurrentBranch
14 verbose getCurrentBranch master
15 silly getUpdates
16 info Checking for updated packages...
17 silly hasTags
18 verbose hasTags true
19 silly getLastTag
20 verbose getLastTag schm-computed@0.1.0
21 info Comparing with schm-computed@0.1.0.
22 silly diffSinceIn schm-computed@0.1.0 packages/schm-computed
23 silly diff
24 silly diffSinceIn schm-computed@0.1.0 packages/schm-express
25 silly diff packages/schm-express/README.md
25 silly diff packages/schm-express/package.json
25 silly diff packages/schm-express/src/index.js
25 silly diff packages/schm-express/test/__snapshots__/index.test.js.snap
25 silly diff packages/schm-express/test/index.test.js
25 silly diff packages/schm-express/yarn.lock
26 silly diffSinceIn schm-computed@0.1.0 packages/schm-methods
27 silly diff
28 silly diffSinceIn schm-computed@0.1.0 packages/schm-translate
29 silly diff
30 silly diffSinceIn schm-computed@0.1.0 packages/schm
31 silly diff
32 verbose updated schm-express
33 info Checking for prereleased packages...
34 silly collectDependents
35 silly isPackageDependentOf schm-computed schm-express
36 silly isPackageDependentOf schm-express schm-express
37 silly isPackageDependentOf schm schm-express
38 silly isPackageDependentOf schm-methods schm-express
39 silly isPackageDependentOf schm-translate schm-express
40 silly isPackageDependentOf schm schm-express
41 silly collectUpdates
42 verbose has filtered update schm-express
43 silly initialize success
44 silly execute attempt
45 silly runScriptSync preversion schm
46 silly runScriptSync preversion schm-express
47 silly runScriptSync version schm-express
48 silly runScriptSync version schm
49 silly addFile /Users/diegohaz/Projects/schm/packages/schm-express/package.json
50 silly commit Publish
50 silly commit
50 silly commit  - schm-express@0.1.0
51 verbose commit [ 'commit',
51 verbose commit   '--no-gpg-sign',
51 verbose commit   '-F',
51 verbose commit   '/private/var/folders/xk/bgjf56g510s_d9jztklp54z80000gn/T/8c2a5d84-ca6c-446e-960a-f10bbc0e24e6/lerna-commit.txt' ]
52 silly addTag schm-express@0.1.0
53 silly runScriptSync postversion schm-express
54 silly runScriptSync postversion schm
55 info publish Publishing packages to npm...
56 silly existsSync /Users/diegohaz/Projects/schm/packages/schm-express/scripts/prepublish.js
57 verbose execScript No prepublish script found at /Users/diegohaz/Projects/schm/packages/schm-express/scripts/prepublish.js
58 verbose publishing schm-express
59 silly publishTaggedInDir latest schm-express
60 silly getExecOpts { cwd: '/Users/diegohaz/Projects/schm/packages/schm-express' }
61 error publish Retrying failed publish: schm-express
62 verbose publish error undefined
63 verbose publishing schm-express
64 silly publishTaggedInDir latest schm-express
65 silly getExecOpts { cwd: '/Users/diegohaz/Projects/schm/packages/schm-express' }
66 error publish Retrying failed publish: schm-express
67 verbose publish error undefined
68 verbose publishing schm-express
69 silly publishTaggedInDir latest schm-express
70 silly getExecOpts { cwd: '/Users/diegohaz/Projects/schm/packages/schm-express' }
71 error publish Retrying failed publish: schm-express
72 verbose publish error undefined
73 verbose publishing schm-express
74 silly publishTaggedInDir latest schm-express
75 silly getExecOpts { cwd: '/Users/diegohaz/Projects/schm/packages/schm-express' }
76 error publish Retrying failed publish: schm-express
77 verbose publish error undefined
78 verbose publishing schm-express
79 silly publishTaggedInDir latest schm-express
80 silly getExecOpts { cwd: '/Users/diegohaz/Projects/schm/packages/schm-express' }
81 error publish Ran out of retries while publishing schm-express Error: Command failed: yarn publish --tag latest
81 error publish error An unexpected error occurred: "Can't answer a question unless a user TTY".
81 error publish yarn publish v1.3.2
81 error publish [1/4] Bumping version...
81 error publish info Current version: 0.1.0
81 error publish info If you think this is a bug, please open a bug report with the information provided in "/Users/diegohaz/Projects/schm/packages/schm-express/yarn-error.log".
81 error publish info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
81 error publish
81 error publish     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
81 error publish     at <anonymous>
81 error publish     at process._tickCallback (internal/process/next_tick.js:160:7)
82 error execute callback with error
83 error Error: Command failed: yarn publish --tag latest
83 error error An unexpected error occurred: "Can't answer a question unless a user TTY".
83 error yarn publish v1.3.2
83 error [1/4] Bumping version...
83 error info Current version: 0.1.0
83 error info If you think this is a bug, please open a bug report with the information provided in "/Users/diegohaz/Projects/schm/packages/schm-express/yarn-error.log".
83 error info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
83 error
83 error     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
83 error     at <anonymous>
```
</p></details>

## Context

Publishing a package

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.7.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.3.2 |
| `node --version` | v9.4.0 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.1 |

**Comment by evocateur** [comment]
Ugh, I was afraid of something like this. #1145 made this actually use yarn, and yarn apparently has prompts during publish? Yuk.

Anyway, https://github.com/yarnpkg/yarn/pull/2770 (and to a lesser extent https://github.com/yarnpkg/yarn/pull/3820) seem to indicate the answer is `--non-interactive`. We should probably be pass the flag to the new places where `yarn` might be running.

**Comment by evocateur** [comment]
or [`--new-version`](https://yarnpkg.com/en/docs/cli/publish#toc-yarn-publish-new-version), rather

**Comment by mrozbarry** [comment]
Is this actually available to use? I'm on lerna 2.8.0, and get the following:

```
lerna info version 2.8.0
lerna info versioning independent
lerna info Checking for updated packages...
lerna info Comparing with initial commit.
lerna info Checking for prereleased packages...
? Select a new version for @myorg/component (currently 0.0.1) Patch (0.0.2)


Changes:

 - @myorg/component: 0.0.1 => 0.0.2


? Are you sure you want to publish the above changes? Yes
lerna info publish Publishing packages to npm...
lerna ERR! publish Retrying failed publish: @myorg/component
lerna ERR! publish Ran out of retries while publishing @myorg/component Error: Command failed: yarn publish --tag latest --new-version 0.0.2
lerna ERR! publish error An unexpected error occurred: "Can't answer a question unless a user TTY".
lerna ERR! publish [1/4] Bumping version...
lerna ERR! publish info Current version: 0.0.2
lerna ERR! publish [2/4] Logging in...
lerna ERR! publish info npm username: mrozbarry
lerna ERR! publish info npm email: ********@gmail.com
lerna ERR! publish info If you think this is a bug, please open a bug report with the information provided in "/home/mrozbarry/code/work/repo/packages/component/yarn-error.log".
lerna ERR! publish info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
lerna ERR! publish
lerna ERR! publish     at Promise.all.then.arr (/Users/alex/code/work/blue-couch/node_modules/execa/index.js:236:11)
lerna ERR! publish     at <anonymous>
lerna ERR! publish     at process._tickCallback (internal/process/next_tick.js:188:7)
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn publish --tag latest --new-version 0.0.2
lerna ERR! error An unexpected error occurred: "Can't answer a question unless a user TTY".
lerna ERR! [1/4] Bumping version...
lerna ERR! info Current version: 0.0.2
lerna ERR! [2/4] Logging in...
lerna ERR! info npm username: mrozbarry
lerna ERR! info npm email: alex.barry+npm@gmail.com
lerna ERR! info If you think this is a bug, please open a bug report with the information provided in "/home/mrozbarry/code/work/repo/packages/hco-dark/yarn-error.log".
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/home/mrozbarry/code/work/repo/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
```

```bash
$ yarn -v
1.3.2
$ npm -v
5.5.1
$ node -v
8.9.1
$ $(yarn bin)/lerna -v
2.8.0
```

**Comment by evocateur** [comment]
Should be. I’m less and less enamored of letting yarn publish as the bugs pile up.

**Comment by mrozbarry** [comment]
Okay, so I sorted things out. Turns out, yarn doesn't actually ask for your password/create a token on an npmjs account until you do a user-specific thing, ie publish. The problem is it does it via prompt, and only during publish (afaik).

Basically, for `yarn login`, it will ask for my npmjs username and email address, but doesn't go any further. I may open a request with the yarn team for something like `yarn authorize` or `yarn login --with-password`. The only reason I found this out is by creating a new single-component npm package, and running through the steps and saw the prompt running the same set of commands that lerna would.

Is there any reason why lerna can't forward the prompts/stdin? I'd be okay with yarn not being ran in parallel if that's the only blocker.

**Comment by evocateur** [comment]
Great investigation, thanks!

I don’t see a problem with running yarn publish serially, allowing the process to inherit stdio (the only way the prompts could be forwarded). Yarn seems to have problems with parallelism in general, but at least we know now what’s up with publish (in some contexts).

**Comment by pleunv** [comment]
Just ran into this as well, I'm assuming there's not really a workaround for this?

**Comment by pleunv** [comment]
Still seem to be running into this with 3.0.0, outputting the following:

```
lerna ERR! Error: Command failed: yarn publish --tag canary --new-version 1.0.0-build.b3a7707
lerna ERR! error An unexpected error occurred: "Can't answer a question unless a user TTY".
```

The problem is I'm getting this only on the CI which is a dockerized build (Wercker), not sure how I can give you guys more info :/

**Comment by pleunv** [comment]
Ok.... mea culpa. Prerelease is run in a separate pipeline step which needs the `.npmrc` to be configured again with the right token to succeed publishing. Should've thought about that, but was thrown off a bit by the error message I was getting, my bad. Please ignore me :)

**Comment by evocateur** [comment]
Thanks for closing the loop, all the same :)
