### ISSUE TITLE
Lerna add will fail with packages using tagged version (e.g. gulp@next)

### ISSUE THREAD

**Issue by compulim** [lerna/lerna#1306]
## Expected Behavior

Lerna should able to install NPM using tagged version, e.g. `gulp@next`.

## Current Behavior

Lerna fail with `TypeError: Invalid comparator: next` in `semver` package.

### Details
```
lerna ERR! initialize callback with error
lerna ERR! TypeError: Invalid comparator: next
lerna ERR!     at Comparator.parse (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\semver\semver.js:690:11)
lerna ERR!     at new Comparator (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\semver\semver.js:674:8)
lerna ERR!     at C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\semver\semver.js:840:12
lerna ERR!     at Array.map (<anonymous>)
lerna ERR!     at Range.parseRange (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\semver\semver.js:839:13)
lerna ERR!     at Range.<anonymous> (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\semver\semver.js:781:17)
lerna ERR!     at Array.map (<anonymous>)
lerna ERR!     at new Range (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\semver\semver.js:780:40)
lerna ERR!     at Function.intersects (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\semver\semver.js:1306:8)
```

## Possible Solution

Instead of using tagged version like `gulp@next`. Find out the semver tagged by `@next` and run explicitly like `lerna add gulp@4.0.0 --dev --scope=mypackage`.

## Steps to Reproduce (for bugs)

1. Run `lerna add gulp@next --dev -- --scope=mypackage`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.8.0",
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'gulp@next' ]
1 silly flags { _: [ 'add' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   dev: true,
1 silly flags   scope: 'mypackage',
1 silly flags   args: [ 'gulp@next' ] }
2 verbose rootPath C:\Users\JohnDoe\Source\Repos\mypackage
3 info version 2.9.0
4 silly isInitialized
5 silly isInitialized true
6 silly existsSync C:\Users\JohnDoe\Source\Repos\mypackage\VERSION
7 info versioning independent
8 info scope mypackage
9 silly initialize attempt
10 error initialize callback with error
11 error TypeError: Invalid comparator: next
11 error     at Comparator.parse (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\semver\semver.js:690:11)
11 error     at new Comparator (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\semver\semver.js:674:8)
11 error     at C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\semver\semver.js:840:12
11 error     at Array.map (<anonymous>)
11 error     at Range.parseRange (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\semver\semver.js:839:13)
11 error     at Range.<anonymous> (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\semver\semver.js:781:17)
11 error     at Array.map (<anonymous>)
11 error     at new Range (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\semver\semver.js:780:40)
11 error     at Function.intersects (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\semver\semver.js:1306:8)
```
</p></details>

## Context

`npm install gulp` will install `gulp@latest`, which is a tag for `@3.9.1` and is almost 2 years old. Their latest release `@4.0.0` is available thru `gulp@next`.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | `2.9.0` |
| `npm --version`  | `5.6.0` |
| `yarn --version` | N/A |
| `node --version` | `9.6.1` |

| OS | Version |
| --- | --- |
| Windows 10 | 1803 (Insider Fast 17112) |

**Comment by evocateur** [comment]
I'm pretty sure lerna `v3.0.0-alpha.3` (`lerna@next`) supports this accurately. Would you mind testing that?

**Comment by compulim** [comment]
Looks like `v3.0.0-alpha.3` still repro.

```
C:\Users\JohnDoe\Source\Repos\mypackage>node_modules\.bin\lerna add gulp@next --dev --scope=mypackage
lerna info version 3.0.0-alpha.3
lerna info versioning independent
lerna info scope mypackage
lerna ERR! TypeError: Invalid comparator: next
lerna ERR!     at Comparator.parse (C:\Users\JohnDoe\Source\Repos\mypackage\node_modules\semver\semver.js:690:11)
lerna ERR!     at new Comparator (C:\Users\JohnDoe\Source\Repos\mypackage\node_modules\semver\semver.js:674:8)
lerna ERR!     at C:\Users\JohnDoe\Source\Repos\mypackage\node_modules\semver\semver.js:840:12
lerna ERR!     at Array.map (<anonymous>)
lerna ERR!     at Range.parseRange (C:\Users\JohnDoe\Source\Repos\mypackage\node_modules\semver\semver.js:839:13)
lerna ERR!     at Range.<anonymous> (C:\Users\JohnDoe\Source\Repos\mypackage\node_modules\semver\semver.js:781:17)
lerna ERR!     at Array.map (<anonymous>)
lerna ERR!     at new Range (C:\Users\JohnDoe\Source\Repos\mypackage\node_modules\semver\semver.js:780:40)
lerna ERR!     at Function.intersects (C:\Users\JohnDoe\Source\Repos\mypackage\node_modules\semver\semver.js:1306:8)
lerna ERR! lerna Invalid comparator: next
```

**Comment by evocateur** [comment]
@compulim Thanks for checking!

**Comment by compulim** [comment]
❤ it! We are experimenting publishing every `master` branch pushes to `my-package@master`, this fix will be super helpful.
