### ISSUE TITLE
'TypeError: ignorePatterns.map is not a function' when using ignore and --since

### ISSUE THREAD

**Issue by Inlustra** [lerna/lerna#1410]
## Expected Behavior

When running: `lerna exec npm i --ignore package-A --since`
I would expect exec to have been run in all packages except package-A

## Current Behavior
```lerna info version 3.0.0-beta.18
lerna info versioning independent
lerna info filter [ '!**********' ]
lerna info Checking for updated packages...
lerna info Comparing with *********.
lerna ERR! TypeError: ignorePatterns.map is not a function
lerna ERR!     at makeDiffPredicate (/Users/thenairn/Documents/Projects/*****/node_modules/@lerna/collect-updates/lib/make-diff-predicate.js:12:48)
lerna ERR!     at collectUpdates (/Users/thenairn/Documents/Projects/*****/node_modules/@lerna/collect-updates/collect-updates.js:46:21)
lerna ERR!     at chain.then (/Users/thenairn/Documents/Projects/*****/node_modules/@lerna/command/index.js:218:32)
lerna ERR! lerna ignorePatterns.map is not a function```


## Possible Solution
`collect-updates.js`

``` const ignorePatterns = options.ignore || options.ignoreChanges; // "ignore" might be durable
    const hasDiff = makeDiffPredicate(committish, execOpts, ignorePatterns);
    const needsBump = (options.cdVersion || "").startsWith("pre")
      ? () => false
      : /* skip packages that have not been previously prereleased */
        node => semver.prerelease(node.version);```

This is the bugged code, looks like options.ignore can come in not as an array.

## Temporary workaround
Specify the ignore parameter twice.
`lerna exec npm i --ignore package-A --ignore package-A --since`

## Context
lerna info versioning independent

## Your Environment
lerna info version 3.0.0-beta.18

**Comment by evocateur** [comment]
That's actually unintentional, since `--ignore` in the context of collecting updated packages has been changed to `--ignore-changes`, and only applies to `lerna publish`.

Seems like `--since` is the trigger, in this case. In any event, I recently fixed this (inadvertently) by only respecting `--ignore-changes` in this context. `--ignore` filters package names, not git diffs.

**Comment by Inlustra** [comment]
@evocateur So we're not able to run lerna exec in all packages that have changed since last publish? 🤔

**Comment by evocateur** [comment]
You should be able to, now. Is that not the case with the latest beta?

The issue was ignore, which is processed before since, was unintentionally passed into the since calculation. It no longer does that.

**Comment by Inlustra** [comment]
@evocateur Sorry, the reason I deleted my comment was that it was badly phrased and actually I wanted to just ignore one of the packages.

Solution for that was to just use scope 😄 

`lerna exec npm i --since --scope @inlustra/*`
