### ISSUE TITLE
import command: max-buffer not working with flatten

### ISSUE THREAD

**Issue by knownasilya** [lerna/lerna#1411]
## Expected Behavior
The `--flatten` flag to work with the `--max-buffer` flag.

## Current Behavior
Seems like the `--max-buffer` flag negates the `--flatten` flag.

## Steps to Reproduce (for bugs)

1. Clone https://github.com/Strider-CD/strider
2. CD into lerna project folder
2. `lerna import ../strider --max-buffer=100000000 --flatten`
3. Error happens

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ '../strider' ]
1 silly flags { _: [ 'import' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   'max-buffer': 1000000000,
1 silly flags   maxBuffer: 1000000000,
1 silly flags   flatten: true,
1 silly flags   pathToRepo: '../strider' }
2 verbose rootPath /Users/iradchenko/sandbox/strider-project
3 info version 2.11.0
4 silly isInitialized
5 silly isInitialized true
6 silly existsSync /Users/iradchenko/sandbox/strider-project/VERSION
7 info versioning independent
8 silly initialize attempt
9 silly statSync /Users/iradchenko/sandbox/strider
10 silly getWorkspaceRoot
11 verbose getWorkspaceRoot /Users/iradchenko/sandbox/strider-project
12 silly existsSync /Users/iradchenko/sandbox/strider-project/packages/strider
13 silly getCurrentSHA
14 verbose getCurrentSHA 6b11be998fb83464503b7b9371cd9dc132083724
15 info About to import 1323 commits from ../strider into packages/strider
16 silly initialize success
17 silly execute attempt
18 info 390dc5e
19 info ad3efb5
20 info 757830e
21 info 4ba7f52
22 info 1e443c4
// .. truncated
1252 info f69333a
1253 error import Error: Failed to apply commit f69333a.
1253 error import Command failed: git am -3 --keep-non-patch
1253 error import fatal: git diff header lacks filename information when removing 1 leading pathname component (line 30388)
1253 error import error: could not build fake ancestor
1253 error import Applying: Add futurestud.io blog posts for guides (Wip)
1253 error import Patch failed at 0001 Add futurestud.io blog posts for guides (Wip)
1253 error import The copy of the patch that failed is found in: .git/rebase-apply/patch
1253 error import When you have resolved this problem, run "git am --continue".
1253 error import If you prefer to skip this patch, run "git am --skip" instead.
1253 error import To restore the original branch and stop patching, run "git am --abort".
1253 error import
1253 error import Rolling back to previous HEAD (commit 6b11be998fb83464503b7b9371cd9dc132083724).
1253 error import You may try with --flatten to import flat history.
1253 error import     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
1253 error import     at <anonymous>
1253 error import     at process._tickCallback (internal/process/next_tick.js:188:7)
1253 error import  { Error: Failed to apply commit f69333a.
1253 error import Command failed: git am -3 --keep-non-patch
1253 error import fatal: git diff header lacks filename information when removing 1 leading pathname component (line 30388)
1253 error import error: could not build fake ancestor
1253 error import Applying: Add futurestud.io blog posts for guides (Wip)
1253 error import Patch failed at 0001 Add futurestud.io blog posts for guides (Wip)
1253 error import The copy of the patch that failed is found in: .git/rebase-apply/patch
1253 error import When you have resolved this problem, run "git am --continue".
1253 error import If you prefer to skip this patch, run "git am --skip" instead.
1253 error import To restore the original branch and stop patching, run "git am --abort".
1253 error import
1253 error import Rolling back to previous HEAD (commit 6b11be998fb83464503b7b9371cd9dc132083724).
1253 error import You may try with --flatten to import flat history.
1253 error import     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
1253 error import     at <anonymous>
1253 error import     at process._tickCallback (internal/process/next_tick.js:188:7)
1253 error import   stack: 'Error: Failed to apply commit f69333a.\nCommand failed: git am -3 --keep-non-patch\nfatal: git diff header lacks filename information when removing 1 leading pathname component (line 30388)\nerror: could not build fake ancestor\nApplying: Add futurestud.io blog posts for guides (Wip)\nPatch failed at 0001 Add futurestud.io blog posts for guides (Wip)\nThe copy of the patch that failed is found in: .git/rebase-apply/patch\nWhen you have resolved this problem, run "git am --continue".\nIf you prefer to skip this patch, run "git am --skip" instead.\nTo restore the original branch and stop patching, run "git am --abort".\n\nRolling back to previous HEAD (commit 6b11be998fb83464503b7b9371cd9dc132083724).\nYou may try with --flatten to import flat history.\n    at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
1253 error import   code: 128,
1253 error import   killed: false,
1253 error import   stdout: 'Applying: Add futurestud.io blog posts for guides (Wip)\nPatch failed at 0001 Add futurestud.io blog posts for guides (Wip)\nThe copy of the patch that failed is found in: .git/rebase-apply/patch\nWhen you have resolved this problem, run "git am --continue".\nIf you prefer to skip this patch, run "git am --skip" instead.\nTo restore the original branch and stop patching, run "git am --abort".\n',
1253 error import   stderr: 'fatal: git diff header lacks filename information when removing 1 leading pathname component (line 30388)\nerror: could not build fake ancestor\n',
1253 error import   failed: true,
1253 error import   signal: null,
1253 error import   cmd: 'git am -3 --keep-non-patch',
1253 error import   timedOut: false }
1254 error execute callback with error
1255 error Error: Failed to apply commit f69333a.
1255 error Command failed: git am -3 --keep-non-patch
1255 error fatal: git diff header lacks filename information when removing 1 leading pathname component (line 30388)
1255 error error: could not build fake ancestor
1255 error Applying: Add futurestud.io blog posts for guides (Wip)
1255 error Patch failed at 0001 Add futurestud.io blog posts for guides (Wip)
1255 error The copy of the patch that failed is found in: .git/rebase-apply/patch
1255 error When you have resolved this problem, run "git am --continue".
1255 error If you prefer to skip this patch, run "git am --skip" instead.
1255 error To restore the original branch and stop patching, run "git am --abort".
1255 error
1255 error Rolling back to previous HEAD (commit 6b11be998fb83464503b7b9371cd9dc132083724).
1255 error You may try with --flatten to import flat history.
1255 error     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
1255 error     at <anonymous>
```
</p></details>

## Context
I'm tring to import https://github.com/Strider-CD/strider as a lerna project using `lerna import`.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 5.8.0 |
| `yarn --version` | 1.6.0 |
| `node --version` | 8.9.1 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.4 |

**Comment by evocateur** [comment]
This error log does not indicate that the stdio buffer was exceeded:
```
1253 error import fatal: git diff header lacks filename information when removing 1 leading pathname component (line 30388)
```

`--max-buffer` doesn't conflict with the logic of `--flatten`, so I'm pretty sure that's a red herring. Does lerna 3.x (`lerna@next`) exhibit the same error? (I suspect [not](https://github.com/lerna/lerna/commit/f6bae80ffc9f4f3e3370a491fe9af48a98947b8f))

**Comment by knownasilya** [comment]
Agreed that it's a red hearing (I did a debugger and both options were on), looks like `flatten` isn't handling a certain case.

**Comment by knownasilya** [comment]
So I tried installing latest, did `lerna init` (it removed the version in `lerna.json` and updated the version in `package.json`). I ran the command again and got the same failure. The logs show the old version.

I double checked that `node_modules/lerna/package.json` had the right version and did `lerna -v` outside the project and both said 3.0.0-beta.19, where the log says 2.11.0

**Comment by evocateur** [comment]
Lerna 3 will always use the locally-installed version of lerna, if present, even if the global version is different. You’ll need to run `npm install` after `lerna init` (not strictly necessary, could just `npm i -D lerna@next` directly, then `npx lerna import --flatten ../repo/to/import`).

It is still possible that a bug exists, git repositories are extremely variable, and the patch rewriting “import” that lerna does is not the most robust method (because it has to be so general).

**Comment by knownasilya** [comment]
Will try this again with your suggestion.

**Comment by evocateur** [comment]
Lerna 3 is now `latest`, btw, not `next`

**Comment by knownasilya** [comment]
I never go this to work.
