### ISSUE TITLE
err when Are you sure you want to publish the above changes? Yes

### ISSUE THREAD

**Issue by bluelovers** [lerna/lerna#1426]
err when Are you sure you want to publish the above changes? Yes

## Expected Behavior

new to lerna, just wanna see does lerna can work for me or not

## Current Behavior

```
D:\Users\Documents\The Project\nodejs-yarn\ws-create-yarn-workspaces>lerna publish
lerna info version 2.11.0
lerna info versioning independent
lerna info Checking for updated packages...
lerna info Comparing with initial commit.
lerna info Checking for prereleased packages...
? Select a new version for create-yarn-workspaces (currently 1.0.9) (Use arrow
? Select a new version for create-yarn-workspaces (currently 1.0.9) Patch (1.0.
10)

Changes:
 - create-yarn-workspaces: 1.0.9 => 1.0.10

? Are you sure you want to publish the above changes? Yes
lerna ERR! execute caught error
lerna ERR! Error: fatal: Pathspec 'packages/create-yarn-workspaces/package.json' is in submodule 'packages/create-yarn-workspaces'
lerna ERR!
lerna ERR!     at Function.module.exports.sync (C:\Users\USER\AppData\Roaming\npm\node_modules\lerna\node_modules\execa\index.js:303:26)
lerna ERR!     at Function.execSync (C:\Users\USER\AppData\Roaming\npm\node_modules\lerna\lib\ChildProcessUtilities.js:59:30)
lerna ERR!     at Function.addFile (C:\Users\USER\AppData\Roaming\npm\node_modules\lerna\lib\GitUtilities.js:78:39)
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "lerna": "2.11.0",
  "version": "independent"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'publish' ]
1 silly flags { _: [ 'publish' ], 'reject-cycles': false, rejectCycles: false }
2 verbose rootPath D:\Users\Documents\The Project\nodejs-yarn\ws-create-yarn-workspaces
3 info version 2.11.0
4 silly isInitialized
5 silly isInitialized true
6 silly existsSync D:\Users\Documents\The Project\nodejs-yarn\ws-create-yarn-workspaces\VERSION
7 info versioning independent
8 silly initialize attempt
9 silly isDetachedHead
10 silly getCurrentBranch
11 verbose getCurrentBranch master
12 verbose isDetachedHead false
13 silly getCurrentBranch
14 verbose getCurrentBranch master
15 silly getUpdates
16 info Checking for updated packages...
17 silly hasTags
18 verbose hasTags false
19 info Comparing with initial commit.
20 verbose updated create-yarn-workspaces
21 info Checking for prereleased packages...
22 silly collectDependents
23 silly isPackageDependentOf create-yarn-workspaces create-yarn-workspaces
24 silly collectUpdates
25 verbose has filtered update create-yarn-workspaces
26 silly initialize success
27 silly execute attempt
28 silly runScriptSync preversion ws-create-yarn-workspaces
29 silly runScriptSync preversion create-yarn-workspaces
30 silly runScriptSync version create-yarn-workspaces
31 silly runScriptSync version ws-create-yarn-workspaces
32 silly addFile D:\Users\Documents\The Project\nodejs-yarn\ws-create-yarn-workspaces\packages\create-yarn-workspaces\package.json
33 error execute caught error
34 error Error: fatal: Pathspec 'packages/create-yarn-workspaces/package.json' is in submodule 'packages/create-yarn-workspaces'
34 error
34 error     at Function.module.exports.sync (C:\Users\USER\AppData\Roaming\npm\node_modules\lerna\node_modules\execa\index.js:303:26)
34 error     at Function.execSync (C:\Users\USER\AppData\Roaming\npm\node_modules\lerna\lib\ChildProcessUtilities.js:59:30)
34 error     at Function.addFile (C:\Users\USER\AppData\Roaming\npm\node_modules\lerna\lib\GitUtilities.js:78:39)
34 error     at C:\Users\USER\AppData\Roaming\npm\node_modules\lerna\lib\commands\PublishCommand.js:709:41
34 error     at Array.forEach (<anonymous>)
34 error     at PublishCommand.updateUpdatedPackages (C:\Users\USER\AppData\Roaming\npm\node_modules\lerna\lib\commands\PublishCommand.js:708:22)
34 error     at PublishCommand.execute (C:\Users\USER\AppData\Roaming\npm\node_modules\lerna\lib\commands\PublishCommand.js:326:12)

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.6.0 |
| `node --version` | v10.1.0 |

| OS | Version |
| Windows 10 | 1709 |
| NAME | VERSION |

**Comment by doug-wade** [comment]
Unfortunately, this project setup is one that [Lerna does not support](https://github.com/lerna/lerna/issues/457#issuecomment-268101436).
