### ISSUE TITLE
Cannot find module '@org/name' when trying to run express server

### ISSUE THREAD

**Issue by benoj** [lerna/lerna#1456]
## Expected Behavior
It resolved
## Current Behavior
When I am trying to run an express server (which is a package) I am not able to resolve the package even though I can see it is in the node_modules folder inside the package.

## Steps to Reproduce (for bugs)

Unsure if this is reproducable?

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "npmClient": "yarn",
  "packages": [
    "packages/*",
    "services/*"
  ],
  "version": "0.2.8"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'start' ]
1 silly flags { _: [ 'run' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   script: 'start',
1 silly flags   args: [] }
2 verbose rootPath /Users/benflowers/Projects/myapp/myapp-backend-monorepo
3 info version 2.11.0
4 silly existsSync /Users/benflowers/Projects/myapp/myapp-backend-monorepo/VERSION
5 silly initialize attempt
6 silly initialize success
7 silly execute attempt
8 silly runScriptInDir start [] myapp-backend-api
9 silly getExecOpts { cwd: '/Users/benflowers/Projects/myapp/myapp-backend-monorepo/packages/myapp-backend-api' }
10 error start Errored while running script in 'backend-api'
11 error execute callback with error
12 error Error: Command failed: yarn run start
12 error module.js:549
12 error     throw err;
12 error     ^
12 error
12 error Error: Cannot find module '@myorg/myser'
12 error     at Function.Module._resolveFilename (module.js:547:15)
12 error     at Function.Module._load (module.js:474:25)
12 error     at Module.require (module.js:596:17)
12 error     at require (internal/module.js:11:18)
12 error     at Object.<anonymous> (/Users/benflowers/Projects/myapp/myapp-backend-monorepo/packages/myapp-backend-api/lib/application/ApplicationService/setRating.js:38:17)
12 error     at Module._compile (module.js:652:30)
12 error     at Object.Module._extensions..js (module.js:663:10)
12 error     at Module.load (module.js:565:32)
12 error     at tryModuleLoad (module.js:505:12)
12 error     at Function.Module._load (module.js:497:3)
12 error error Command failed with exit code 1.
12 error yarn run v0.24.5
12 error $ node  ./lib/server.js
12 error info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12 error
12 error     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
12 error     at <anonymous>


```
</p></details>

## Context

I am trying to pull out some shared logic between microservices (packages contains express microservice, services contains shared logic) - when trying to run getting a resolution error.

## Your Environment

Typescript, Express, 

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 0.24.5 |
| `node --version` | 8.11.2 |

| OS | Version |
macOS High Sierra 10.13.4 
-->

**Comment by benoj** [comment]
Ridiculously simple error - drained hours of time... whoops

**Comment by mxmzb** [comment]
@benoj maybe you could provide some more information what caused it so others can find this and not waste hours?
