### ISSUE TITLE
Support `--scope <packages-folder>/*`

### ISSUE THREAD

**Issue by MatejBransky** [lerna/lerna#1458]
It seems that it doesn't work if you want, for example, call `lerna exec --scope packages/*` (script for all packages in `./packages/` folder. I want this because I have two folders: one for packages and one for examples.
Because of that I have to, temporarily, use prefixes in names (`packages/package-components-foo`, `packages/package-utils`) with `lerna exec --scope package-* -- babel src --out-dir lib`.

#### Example:
npm script:
`lerna exec --scope packages/* -- babel src --out-dir lib`

## Expected Behavior
Calls for all packages in `./packages` folder.

## Current Behavior
Error: No packages found that match scope 'packages/*'.

## Possible Solution

I don't know how to implement it but it should be possible.

<details><summary>root package.json</summary><p>

(only specific for monorepo with Yarn workspaces)
```json
{
  "workspaces": ["examples/*", "packages/*"],
}
```
</p></details>

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "version": "0.0.0",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'babel', 'src', '--out-dir', 'lib', '--watch' ]
1 silly flags { _: [ 'exec' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   stream: true,
1 silly flags   parallel: true,
1 silly flags   scope: 'packages/*',
1 silly flags   since: '',
1 silly flags   command: 'babel',
1 silly flags   args: [ 'src', '--out-dir', 'lib', '--watch' ] }
2 verbose rootPath C:\Users\m24ma\Documents\projekty\_sandbox\lerna\scope
3 info version 2.11.0
4 silly existsSync C:\Users\m24ma\Documents\projekty\_sandbox\lerna\scope\VERSION
5 info scope packages/*
6 error EPACKAGES Errored while collecting packages and package graph
7 error Error: No packages found that match scope 'packages/*'
7 error     at Function.filterPackages (C:\Users\m24ma\Documents\projekty\_sandbox\lerna\scope\node_modules\lerna\lib\PackageUtilities.js:252:17)
7 error     at ExecCommand.runPreparations (C:\Users\m24ma\Documents\projekty\_sandbox\lerna\scope\node_modules\lerna\lib\Command.js:333:60)
7 error     at C:\Users\m24ma\Documents\projekty\_sandbox\lerna\scope\node_modules\lerna\lib\Command.js:209:18
7 error     at new Promise (<anonymous>)
7 error     at ExecCommand.run (C:\Users\m24ma\Documents\projekty\_sandbox\lerna\scope\node_modules\lerna\lib\Command.js:193:14)
7 error     at Object.handler (C:\Users\m24ma\Documents\projekty\_sandbox\lerna\scope\node_modules\lerna\lib\commands\ExecCommand.js:45:14)
7 error     at Object.self.runCommand (C:\Users\m24ma\Documents\projekty\_sandbox\lerna\scope\node_modules\yargs\lib\command.js:233:22)
7 error     at Object.Yargs.self._parseArgs (C:\Users\m24ma\Documents\projekty\_sandbox\lerna\scope\node_modules\yargs\yargs.js:990:30)
7 error     at Object.Yargs.self.parse (C:\Users\m24ma\Documents\projekty\_sandbox\lerna\scope\node_modules\yargs\yargs.js:532:23)

```
</p></details>

## Context

It is useful when you have special directory for apps and special one for packages. These two groups maybe needs totally different bundle configs and scripts.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 6.1.0 |
| `yarn --version` | 1.7.0 |
| `node --version` | 10.3.0 |

| OS | Version |
| --- | --- |
| Windows 10 | 1803 |

**Comment by dptoot** [comment]
@MatejMazur I believe omitting the scope flag entirely form your command would allow your exec to run in all packages be default.

Hope this helps.

**Comment by MatejMazur** [comment]
Hi, thanks for your response. :worried: Sorry I wasn't enough clear. I don't want to allow exec for all packages. I want it only for folder `packages`. I have two folders: one for packages (`packages`) and one for apps (`examples`). But really thanks because I've updated my comment at least.

**Comment by MatejMazur** [comment]
@evocateur I don't understand. Can you write an example?

This is my folder structure:

```
monorepo
├── examples
│   ├── foo-playground
│   ├── bar-app
│   └── another-example
└── packages
    ├── sum
    ├── components
    └── calc
```
How do you apply `lerna exec` only to examples or only to packages?

**Comment by sp3c1** [comment]
Researching this myself. I think there is something like [that](https://github.com/lerna/lerna#flags). 

With would mean you should enforce some naming in the packages and then

```
lerna --scope=packages-* exec ....
```

should do the trick. But yeah, would be nice to be able to do `./packages/*`

**Comment by XBeg9** [comment]
+1 very strange that I can't use a folder instead of package-names. Any plans for such featuer?

**Comment by rjhilgefort** [comment]
Would really like to have this feature- it's painful to have list everything out. Any reason this issue is gone cold?

**Comment by dvhuy** [comment]
I have the same issue. I really need this to organize, structure our code easier. 
Hope this will happen sooner.

**Comment by evocateur** [comment]
> Any reason this issue is gone cold?

Lack of contributions?

**Comment by andrewmclagan** [comment]
haha yeah

> I want it, but i dont want to do it myself.

**Comment by trusktr** [comment]
This would be a nice productivity booster.

**Comment by mikestopcontinues** [comment]
This has been a great way to fill in the gaps...
https://github.com/folke/ultra-runner
