### ISSUE TITLE
`lerna exec npm outdated` fails to resolve packages

### ISSUE THREAD

**Issue by craigbeck** [lerna/lerna#1468]
## Expected Behavior

`lerna exec npm outdated` should (and used to) run `npm outdated` successfully in each package in the repository reporting on the outdated packages.

## Current Behavior

```
$ npx lerna exec npm outdated 
lerna info version 2.11.0
Package             Current  Wanted  Latest  Location
redux-localstorage  MISSING   0.4.0   0.4.1  @premise/premise-core
lerna ERR! exec Errored while executing 'npm outdated' in '@premise/premise-core'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm outdated
lerna ERR!     at Promise.all.then.arr (/Users/craigbeck/dev/premise-frontend-v3/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
{ Error: Command failed: npm outdated
    at Promise.all.then.arr (/Users/craigbeck/dev/premise-frontend-v3/node_modules/lerna/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:178:7)
  code: 1,
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'npm outdated',
  timedOut: false,
  exitCode: 1 }

```

## Steps to Reproduce (for bugs)

1. run `npx lerna exec npm outdated`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "hoist": true,
  "packages": [
    "packages/*",
    "packages/libs/*",
    "packages/mobile-webviews/*",
    "packages/webapps/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'npm', 'outdated' ]
1 silly flags { _: [ 'exec' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   command: 'npm',
1 silly flags   args: [ 'outdated' ] }
2 verbose rootPath /Users/craigbeck/dev/premise-frontend-v3
3 info version 2.11.0
4 silly existsSync /Users/craigbeck/dev/premise-frontend-v3/VERSION
5 silly initialize attempt
6 silly initialize success
7 silly execute attempt
8 error exec Errored while executing 'npm outdated' in '@premise/premise-core'
9 error execute callback with error
10 error Error: Command failed: npm outdated
10 error     at Promise.all.then.arr (/Users/craigbeck/dev/premise-frontend-v3/node_modules/lerna/node_modules/execa/index.js:236:11)
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 6.1.0 |
| `yarn --version` | n/a |
| `node --version` | 10.0.0 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.5 |

**Comment by evocateur** [comment]
This is an npm problem, related to the fact you're hoisting. I've toyed with the idea of re-implementing `npm outdated` for lerna, but it's a bit beyond the capacity of one person (me, the only active maintainer).

**Comment by craigbeck** [comment]
hmm, it used to work

**Comment by evocateur** [comment]
You're hoisting, there's no possible way it used to work with the same config (the dependencies literally are not where npm expects them, hence the error)
