### ISSUE TITLE
Lerna not publishing to private registry

### ISSUE THREAD

**Issue by phun-ky** [lerna/lerna#1477]
## Expected Behavior
Using:

    lerna publish 

Should publish my packages to the provided private registry

## Current Behavior

    lerna publish

Throws error:

    lerna ERR! publish npm ERR! code ENEEDAUTH
    lerna ERR! publish npm ERR! need auth auth required for publishing
    lerna ERR! publish npm ERR! need auth You need to authorize this machine using `npm adduser`

## Steps to Reproduce (for bugs)

`.npmrc`:

    registry="https://<org>.myget.org/F/<project>/auth/<key>/npm/"

`package.json`:

    "publishConfig": {
      "registry": "https://<org>.myget.org/F/<project>/auth/<key>/npm/,
      "access": "public"
    },

I am authenticated with the private registry, and also use the preauthenticated URL.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "packages": [
    "packages/*"
  ],
  "version": "0.1.2",
  "command": {
    "init": {
      "exact": true
    }
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'publish' ]
1 silly flags { _: [ 'publish' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   'force-publish': true,
1 silly flags   forcePublish: true }
2 verbose rootPath /mnt/c/path/to/project/Workspace/<projectScope>
3 info version 2.11.0
4 silly isInitialized
5 silly isInitialized true
6 silly existsSync /mnt/c/path/to/project/Workspace/<projectScope>/VERSION
7 silly initialize attempt
8 info current version 0.1.1
9 silly isDetachedHead
10 silly getCurrentBranch
11 verbose getCurrentBranch registry
12 verbose isDetachedHead false
13 silly getCurrentBranch
14 verbose getCurrentBranch registry
15 silly getUpdates
16 info Checking for updated packages...
17 silly hasTags
18 verbose hasTags true
19 silly getLastTag
20 verbose getLastTag v0.1.1
21 info Comparing with v0.1.1.
22 verbose updated @<projectScope>/bundle
23 verbose updated @<projectScope>/button
24 verbose updated @<projectScope>/color
25 verbose updated @<projectScope>/core
26 info Checking for prereleased packages...
27 silly collectDependents
28 silly isPackageDependentOf @<projectScope>/bundle @<projectScope>/bundle
29 silly isPackageDependentOf @<projectScope>/button @<projectScope>/bundle
30 silly isPackageDependentOf @<projectScope>/core @<projectScope>/bundle
31 silly isPackageDependentOf @<projectScope>/color @<projectScope>/bundle
32 silly isPackageDependentOf @<projectScope>/core @<projectScope>/bundle
33 silly isPackageDependentOf @<projectScope>/bundle @<projectScope>/button
34 verbose dependent @<projectScope>/bundle depends on @<projectScope>/button
35 silly isPackageDependentOf @<projectScope>/bundle @<projectScope>/color
36 verbose dependent @<projectScope>/bundle depends on @<projectScope>/color
37 silly isPackageDependentOf @<projectScope>/bundle @<projectScope>/core
38 verbose dependent @<projectScope>/bundle depends on @<projectScope>/core
39 silly isPackageDependentOf @<projectScope>/button @<projectScope>/bundle
40 silly isPackageDependentOf @<projectScope>/button @<projectScope>/button
41 silly isPackageDependentOf @<projectScope>/core @<projectScope>/button
42 silly isPackageDependentOf @<projectScope>/button @<projectScope>/color
43 silly isPackageDependentOf @<projectScope>/core @<projectScope>/color
44 silly isPackageDependentOf @<projectScope>/button @<projectScope>/core
45 verbose dependent @<projectScope>/button depends on @<projectScope>/core
46 silly isPackageDependentOf @<projectScope>/color @<projectScope>/bundle
47 silly isPackageDependentOf @<projectScope>/color @<projectScope>/button
48 silly isPackageDependentOf @<projectScope>/color @<projectScope>/color
49 silly isPackageDependentOf @<projectScope>/color @<projectScope>/core
50 silly isPackageDependentOf @<projectScope>/core @<projectScope>/bundle
51 silly isPackageDependentOf @<projectScope>/core @<projectScope>/button
52 silly isPackageDependentOf @<projectScope>/core @<projectScope>/color
53 silly isPackageDependentOf @<projectScope>/core @<projectScope>/core
54 silly collectUpdates
55 verbose has filtered update @<projectScope>/bundle
56 verbose has filtered update @<projectScope>/button
57 verbose has filtered update @<projectScope>/color
58 verbose has filtered update @<projectScope>/core
59 silly initialize success
60 silly execute attempt
61 silly addFile /mnt/c/path/to/project/Workspace/<projectScope>/lerna.json
62 silly runScriptSync preversion @<projectScope>/<projectScope>
63 silly runScriptSync preversion @<projectScope>/bundle
64 silly runScriptSync version @<projectScope>/bundle
65 silly runScriptSync preversion @<projectScope>/button
66 silly runScriptSync version @<projectScope>/button
67 silly runScriptSync preversion @<projectScope>/color
68 silly runScriptSync version @<projectScope>/color
69 silly runScriptSync preversion @<projectScope>/core
70 silly runScriptSync version @<projectScope>/core
71 silly runScriptSync version @<projectScope>/<projectScope>
72 silly addFile /mnt/c/path/to/project/Workspace/<projectScope>/packages/bundle/package.json
73 silly addFile /mnt/c/path/to/project/Workspace/<projectScope>/packages/button/package.json
74 silly addFile /mnt/c/path/to/project/Workspace/<projectScope>/packages/color/package.json
75 silly addFile /mnt/c/path/to/project/Workspace/<projectScope>/packages/core/package.json
76 silly commit v0.1.2
77 verbose commit [ 'commit', '--no-verify', '-m', 'v0.1.2' ]
78 silly addTag v0.1.2
79 silly runScriptSync postversion @<projectScope>/bundle
80 silly runScriptSync postversion @<projectScope>/button
81 silly runScriptSync postversion @<projectScope>/color
82 silly runScriptSync postversion @<projectScope>/core
83 silly runScriptSync postversion @<projectScope>/<projectScope>
84 info publish Publishing packages to npm...
85 silly existsSync /mnt/c/path/to/project/Workspace/<projectScope>/packages/bundle/scripts/prepublish.js
86 verbose execScript No prepublish script found at /mnt/c/path/to/project/Workspace/<projectScope>/packages/bundle/scripts/prepublish.js
87 silly existsSync /mnt/c/path/to/project/Workspace/<projectScope>/packages/button/scripts/prepublish.js
88 verbose execScript No prepublish script found at /mnt/c/path/to/project/Workspace/<projectScope>/packages/button/scripts/prepublish.js
89 silly existsSync /mnt/c/path/to/project/Workspace/<projectScope>/packages/color/scripts/prepublish.js
90 verbose execScript No prepublish script found at /mnt/c/path/to/project/Workspace/<projectScope>/packages/color/scripts/prepublish.js
91 silly existsSync /mnt/c/path/to/project/Workspace/<projectScope>/packages/core/scripts/prepublish.js
92 verbose execScript No prepublish script found at /mnt/c/path/to/project/Workspace/<projectScope>/packages/core/scripts/prepublish.js
93 verbose publishing @<projectScope>/color
94 silly publishTaggedInDir latest color
95 silly getExecOpts { cwd: '/mnt/c/path/to/project/Workspace/<projectScope>/packages/color' }
96 verbose publishing @<projectScope>/core
97 silly publishTaggedInDir latest core
98 silly getExecOpts { cwd: '/mnt/c/path/to/project/Workspace/<projectScope>/packages/core' }
99 error publish Retrying failed publish: @<projectScope>/color
100 verbose publish error undefined
101 verbose publishing @<projectScope>/color
102 silly publishTaggedInDir latest color
103 silly getExecOpts { cwd: '/mnt/c/path/to/project/Workspace/<projectScope>/packages/color' }
104 error publish Retrying failed publish: @<projectScope>/core
105 verbose publish error undefined
106 verbose publishing @<projectScope>/core
107 silly publishTaggedInDir latest core
108 silly getExecOpts { cwd: '/mnt/c/path/to/project/Workspace/<projectScope>/packages/core' }
109 error publish Retrying failed publish: @<projectScope>/color
110 verbose publish error undefined
111 verbose publishing @<projectScope>/color
112 silly publishTaggedInDir latest color
113 silly getExecOpts { cwd: '/mnt/c/path/to/project/Workspace/<projectScope>/packages/color' }
114 error publish Retrying failed publish: @<projectScope>/core
115 verbose publish error undefined
116 verbose publishing @<projectScope>/core
117 silly publishTaggedInDir latest core
118 silly getExecOpts { cwd: '/mnt/c/path/to/project/Workspace/<projectScope>/packages/core' }
119 error publish Retrying failed publish: @<projectScope>/color
120 verbose publish error undefined
121 verbose publishing @<projectScope>/color
122 silly publishTaggedInDir latest color
123 silly getExecOpts { cwd: '/mnt/c/path/to/project/Workspace/<projectScope>/packages/color' }
124 error publish Retrying failed publish: @<projectScope>/core
125 verbose publish error undefined
126 verbose publishing @<projectScope>/core
127 silly publishTaggedInDir latest core
128 silly getExecOpts { cwd: '/mnt/c/path/to/project/Workspace/<projectScope>/packages/core' }
129 error publish Retrying failed publish: @<projectScope>/color
130 verbose publish error undefined
131 verbose publishing @<projectScope>/color
132 silly publishTaggedInDir latest color
133 silly getExecOpts { cwd: '/mnt/c/path/to/project/Workspace/<projectScope>/packages/color' }
134 error publish Retrying failed publish: @<projectScope>/core
135 verbose publish error undefined
136 verbose publishing @<projectScope>/core
137 silly publishTaggedInDir latest core
138 silly getExecOpts { cwd: '/mnt/c/path/to/project/Workspace/<projectScope>/packages/core' }
139 error publish Ran out of retries while publishing @<projectScope>/color Error: Command failed: npm publish --tag latest
139 error publish npm ERR! code ENEEDAUTH
139 error publish npm ERR! need auth auth required for publishing
139 error publish npm ERR! need auth You need to authorize this machine using `npm adduser`
139 error publish
139 error publish npm ERR! A complete log of this run can be found in:
139 error publish npm ERR!     /root/.npm/_logs/2018-06-18T13_47_22_564Z-debug.log
139 error publish
139 error publish     at Promise.all.then.arr (/root/.nvm/versions/node/v8.11.1/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
139 error publish     at <anonymous>
139 error publish     at process._tickCallback (internal/process/next_tick.js:188:7)
140 error execute callback with error
141 error Error: Command failed: npm publish --tag latest
141 error npm ERR! code ENEEDAUTH
141 error npm ERR! need auth auth required for publishing
141 error npm ERR! need auth You need to authorize this machine using `npm adduser`
141 error
141 error npm ERR! A complete log of this run can be found in:
141 error npm ERR!     /root/.npm/_logs/2018-06-18T13_47_22_564Z-debug.log
141 error
141 error     at Promise.all.then.arr (/root/.nvm/versions/node/v8.11.1/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
141 error     at <anonymous>

```
</p></details>

## Context
I can't publish to the private registry. It seems that `lerna publish` is ignoring the private registry configuration.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0|
| `npm --version`  | 5.8.0 |
| `node --version` | 8.11.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Windows with Ubuntu Bash| 10.*|

**Comment by phun-ky** [comment]
:man_facepalming: :duck: yeah.. nothing to see here, don't mind me. The issue was with the credentials on the private npm registry and how the `.npmrc` really should be configed.. :1st_place_medal:

**Comment by guybensh** [comment]
Hi @phun-ky !

Can you please elaborate on how the .npmrc should be config?
I'm experiencing the same problem.

Thanks

**Comment by jharris4** [comment]
I have my `.npmrc` setup like the above, but started getting this issue after upgrading from lerna `2.11.0` to `3.0.3`

```
lerna info git Pushing tags...
lerna success version finished
npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2018-08-13T14_37_14_397Z-debug.log

lerna ERR! EREGISTRY Connection to npm registry failed
```

Doing the following DOES successfully publish the package though:

```
cd packages/the-package
npm publish
```
