### ISSUE TITLE
Lerna Publish fails with angular-bitbucket

### ISSUE THREAD

**Issue by codeNoobie** [lerna/lerna#1491]
Lerna publish command with --conventional-commits and changelog-preset set to angular-bitbucket is failing. The command works fine when I remove the changelog-preset option.

## Expected Behavior

Lerna publish should work fine with angular-bitbucket changelog preset.

## Current Behavior

The command fails because it is unable to find angular-bitbucket module. In the old 2.7 version, I don't remember adding angular-bitbucket to npm modules separately. Nevertheless, I added the [conventional-changelog-angular-bitbucket](https://www.npmjs.com/package/conventional-changelog-angular-bitbucket) separately, but still I got the same error message.

Please see this error.

> lerna info version 3.0.0-beta.21
> lerna verb rootPath <Home-Dir>
> lerna info current version 0.0.1
> lerna info Checking for updated packages...
> lerna verb hasTags true
> lerna info Comparing with v0.0.0.
> lerna verb updated Lib1
> lerna verb updated Lib2
> lerna verb getChangelogConfig Cannot find module 'angular-bitbucket'
> lerna info getChangelogConfig Auto-prefixing conventional-commits preset 'angular-bitbucket'
> lerna verb fixed increment 0.0.1 by undefined
> lerna verb fixed increment 0.0.1 by undefined
> lerna ERR! TypeError: Invalid Version: null
> lerna ERR!     at new SemVer (<Home-Dir>/node_modules/semver/semver.js:291:11)
> lerna ERR!     at compare (<Home-Dir>/node_modules/semver/semver.js:578:10)
> lerna ERR!     at Function.gt (<Home-Dir>/node_modules/semver/semver.js:607:10)
> lerna ERR!     at versions.forEach.bump (<Home-Dir>/node_modules/@lerna/publish/index.js:373:22)
> lerna ERR!     at Map.forEach (<anonymous>)
> lerna ERR!     at chain.then.versions (<Home-Dir>/node_modules/@lerna/publish/index.js:372:18)
> lerna ERR!     at <anonymous>
> lerna ERR! lerna Invalid Version: null
> error Command failed with exit code 1.

The command works fine when i remove the angular-bitbucket option. Am I doing something wrong with the setup? 

## Steps to Reproduce (for bugs)

1. Install the latest Lerna package
2. Run `lerna publish --changelog-preset angular-bitbucket `

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "libs/*"
  ],
  "command": {
    "publish": {
      "conventionalCommits": true,
      "gitRemote": "origin",
      "message": "chore(release): publish %s"
    }
  },
  "npmClient": "yarn",
  "useWorkspaces": true,
  "loglevel": "silent",
  "version": "0.0.1"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
0 silly argv { _: [ 'publish' ],
0 silly argv   help: false,
0 silly argv   h: false,
0 silly argv   version: false,
0 silly argv   v: false,
0 silly argv   'reject-cycles': undefined,
0 silly argv   rejectCycles: undefined,
0 silly argv   progress: undefined,
0 silly argv   sort: undefined,
0 silly argv   ci: false,
0 silly argv   'conventional-commits': undefined,
0 silly argv   conventionalCommits: undefined,
0 silly argv   exact: undefined,
0 silly argv   'skip-git': true,
0 silly argv   skipGit: true,
0 silly argv   'skip-npm': true,
0 silly argv   skipNpm: true,
0 silly argv   'temp-tag': undefined,
0 silly argv   tempTag: undefined,
0 silly argv   yes: undefined,
0 silly argv   'changelog-preset': 'angular-bitbucket',
0 silly argv   changelogPreset: 'angular-bitbucket',
0 silly argv   loglevel: 'verbose',
0 silly argv   lernaVersion: '3.0.0-beta.21',
0 silly argv   '$0': '<HOME_DIR>/node_modules/.bin/lerna',
0 silly argv   concurrency: undefined,
0 silly argv   'max-buffer': undefined,
0 silly argv   'allow-branch': undefined,
0 silly argv   canary: undefined,
0 silly argv   'cd-version': undefined,
0 silly argv   'git-remote': undefined,
0 silly argv   'ignore-changes': undefined,
0 silly argv   message: undefined,
0 silly argv   'npm-tag': undefined,
0 silly argv   'npm-client': undefined,
0 silly argv   registry: undefined,
0 silly argv   preid: undefined,
0 silly argv   'repo-version': undefined,
0 silly argv   ignore: undefined }
1 info version 3.0.0-beta.21
2 verbose rootPath <HOME_DIR>
3 info current version 0.0.1
4 info Checking for updated packages...
5 silly hasTags
6 verbose hasTags true
7 info Comparing with v0.0.0.
8 silly diffSinceIn v0.0.0 libs/lib1
   <silly diffs>
10 silly diffSinceIn v0.0.0 libs/lib2
11 <silly diffs>
12 verbose updated lib1
13 verbose updated lib2
14 silly batched [ PackageGraphNode {
14 silly batched     name: 'lib1',
14 silly batched     externalDependencies: Map {},
14 silly batched     localDependencies: Map {},
14 silly batched     localDependents: Map {} },
14 silly batched   PackageGraphNode {
14 silly batched     name: 'lib2',
14 silly batched     externalDependencies: Map {},
14 silly batched     localDependencies: Map {},
14 silly batched     localDependents: Map {} } ]
15 silly fixed for @appd/dash-core at /Users/anand.tiwary/appdynamics/dash-kit/libs/dash-core
16 verbose getChangelogConfig Cannot find module 'angular-bitbucket'
17 info getChangelogConfig Auto-prefixing conventional-commits preset 'angular-bitbucket'
18 verbose fixed increment 0.0.1 by undefined
19 silly fixed for @appd/dash-widgets at /Users/anand.tiwary/appdynamics/dash-kit/libs/dash-widgets
20 verbose fixed increment 0.0.1 by undefined
21 error TypeError: Invalid Version: null
21 error     at new SemVer (<HOME_DIR>/node_modules/semver/semver.js:291:11)
21 error     at compare (<HOME_DIR>/node_modules/semver/semver.js:578:10)
21 error     at Function.gt (<HOME_DIR>/node_modules/semver/semver.js:607:10)
21 error     at versions.forEach.bump (<HOME_DIR>/node_modules/@lerna/publish/index.js:373:22)
21 error     at Map.forEach (<anonymous>)
21 error     at chain.then.versions (<HOME_DIR>/node_modules/@lerna/publish/index.js:372:18)
21 error     at <anonymous>
```

</p></details>

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->
Trying to publish libs with changelog on Bitbucket.
## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-beta.21 |
| `npm --version`  | 6.1.0 |
| `yarn --version` | 1.7.1 |
| `node --version` | v9.8.0 |

| OS | Version |
| --- | --- |
| macOS High Sierra  | 10.13.2 |

**Comment by codeNoobie** [comment]
@evocateur Any suggestions on this please?

**Comment by codeNoobie** [comment]
I understand. But it is a loss of functionality for us. I will check with conventional-changelog maintainers regarding adding support for bitbucket.

Thanks!!
