### ISSUE TITLE
How to check for outdated dependencies in packages.

### ISSUE THREAD

**Issue by hannadrehman** [lerna/lerna#1501]
I am trying to convert our existing projects into a Lerna project. so I have created all packages for different repositories and setup all tools and config for my project. everything is working fine. 

I want to know how to list all dependencies in my packages that are outdated. I wish to keep my project up to date with all new updates.
## Expected Behavior
I want to run `npm outdated` or any lerna command which lists all dependencies that have changed/updated.

## Current Behavior
when i run `npm outdated` or `lerna exec npm outdated` in my local package it obviously fails because i am using local packages which is not there in npm repo .. (react-elements-md is my local package) 
```
npm ERR! code E404
npm ERR! 404 Not found : react-elements-md
npm ERR! 404 
npm ERR! 404  'react-elements-md' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akashtalreja/.npm/_logs/2018-07-16T14_43_51_022Z-debug.log
lerna ERR! exec Errored while executing 'npm outdated' in 'react-redux-sagas'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm outdated
lerna ERR!     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: npm outdated
    at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  code: 1,
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'npm outdated',
  timedOut: false,
  exitCode: 1 }
```
## Possible Solution
possible solution i can think of some command like `lerna outdated` which would list down the dependencies in a packages that can updated.

## Steps to Reproduce (for bugs)
hit `npm outdated` in any package that used your local repository
<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details>
<summary>
  am i missing something ? it looks quite simple there must be a way to update npm dependencies. and keep your project updated. i also read in some issue @evocateur mentioning 
"If you're never publishing packages to a registry (public or private), I
don't recommend using lerna. There is no shame in relative path imports." .
. since i am not going to publish anyway, should i really use lerna in my project ?
</summary>
<p>

</p></details>

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 6.2.0 |
| `yarn --version` | 1.6.0 |
| `node --version` | 9.6.1 |

| OS | Version |
|  macOS High Sierra | 10.13.3-= |
| NAME | VERSION |

**Comment by evocateur** [comment]
If you use relative file specifiers and upgrade to lerna 3, this error would be avoided. However, it then exposes another `npm outdated` error when everything is hoisted. So `lerna outdated` would still be useful for those situations.

If you’re using yarn, you could use workspaces and get this sort of functionality as a yarn command, I believe.

**Comment by tivac** [comment]
I'm using `lerna@3`

```
npm outdated && npx lerna exec --no-bail -- npm outdated
```

Seems to do what you'd expect.

**Comment by sibelius** [comment]
anyway of doing this using `yarn outdated`?

right now it is hard to validate outdated in only one package when using multiples packages

**Comment by hannadrehman** [comment]
i am using `lerna@3.4.1` and `yarn outdated` gives me all outdated dependencies across all packages.

**Comment by thealjey** [comment]
@evocateur 
I am forced to use npm and lerna at work, because I am not allowed to use yarn (it's a bank, lots of restrictions)
and the lack of such a basic and simple feature is just very surprising to me
are you guys even working on it at all? because all of the issues that I could find about this are closed
would a pull request, assuming I can even figure out how to do it, for this feature be considered or is there another reason this command does not exist?

**Comment by tivac** [comment]
I ended up modifying my approach so it was easier to read.

https://github.com/tivac/modular-css/blob/master/lerna/outdated.js

invoked via

```json
"outdated": "lerna exec -- node ../../lerna/outdated.js",
```

**Comment by justingorham** [comment]
Not sure if this ehlps anyone, but [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) Helps me with this situation without depending on yarn.

**Comment by hannadrehman** [comment]
@justingorham i use `yarn outdated` works perfectly plus i use `lerna-update-wizard` to update dependencies

**Comment by justingorham** [comment]
@hannadrehman That was for folks who can't or don't use yarn for whatever reason (full disclosure, I do use yarn when permissible). Installing npm-check-updates and running lerna exec -- ncu gives them the same functionality.

**Comment by FrederickEngelhardt** [comment]
> I'm using `lerna@3`
> 
> ```
> npm outdated && npx lerna exec --no-bail -- npm outdated
> ```
> 
> Seems to do what you'd expect.

This works for me. Is there anything wrong with this approach? We're sticking with npm right now and for the near future.

**Comment by davidmurdoch** [comment]
> npm outdated && npx lerna exec --no-bail -- npm outdated

This approach won't work in the case when you have packages that haven't yet been published to npm, as `npm outdated` will error as soon as it tries a package that isn't published.

**Comment by joshxyzhimself** [comment]
I do the following


```sh
# check for updates
npx lerna exec --no-bail "pwd && npm outdated"

# manually update any major versions
# done iby editing each package.json

# use update
npx lerna exec --no-bail "pwd && npm update"

# reverts to using symlink locally (if my understanding is correct)
npx lerna bootstrap
```

**Comment by jcpeden** [comment]
> I ended up modifying my approach so it was easier to read.
> 
> https://github.com/tivac/modular-css/blob/master/lerna/outdated.js
> 
> invoked via
> 
> ```json
> "outdated": "lerna exec -- node ../../lerna/outdated.js",
> ```

This link is no longer available. Are you able to check and re-share?
