### ISSUE TITLE
multiple dev server hmr get error

### ISSUE THREAD

**Issue by lichnow** [lerna/lerna#1504]
## Expected Behavior
`lerna run hot` will run webpack dev-server in hot model for every packages,so it will open more then one port `8080`.

## Current Behavior
because of open multiple some port named `8080`,node will show the error
```
lerna ERR! yarn run watch stderr:
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1335:14)
    at listenInCluster (net.js:1383:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1509:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1362:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.

lerna ERR! yarn run watch exited 1 in 'dashboard-module'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
```

## Possible Solution
is possible to run `dev-server hmr` on multiple packages?

## Steps to Reproduce (for bugs)

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "modules/*"
  ],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent",
  "command": {
    "run": {
      "stream": true
    },
    "bootstrap": {
      "ignore": "Member"
    }
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
yarn run v1.7.0
$ node_modules/.bin/encore dev-server --hot
Running webpack-dev-server ...

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run watch stderr:
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1335:14)
    at listenInCluster (net.js:1383:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1509:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1362:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.

lerna ERR! yarn run watch exited 1 in 'dashboard-module'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
```
</p></details>

## Context
when i run `lerna run hot` to fact run webpack dev-server --hot for every packages will work fine

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-beta.21 |
| `npm --version`  | 6.2.0 |
| `yarn --version` | 1.7.0 |
| `node --version` | v10.6.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.4 |

**Comment by evocateur** [comment]
You don't need to run a webpack build in every package, you should be able to run it from the root.

Closing because this isn't a lerna problem, but a problem in whatever provides the `encore` executable.
