### ISSUE TITLE
Lerna throws on publish

### ISSUE THREAD

**Issue by IAmTheVex** [lerna/lerna#1517]
When i run lerna publish inside my project (https://github.com/IAmTheVex/zuu) i get an error

## Expected Behavior
Lerna should publish the repository

## Current Behavior
Lerna throws an exception

## Steps to Reproduce (for bugs)
1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "packages": [
    "packages/*"
  ],
  "version": "4.0.1-rc8"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'publish' ]
1 silly flags { _: [ 'publish' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   'skip-git': true,
1 silly flags   skipGit: true }
2 verbose rootPath /Users/vex/p/zuu
3 info version 2.11.0
4 silly isInitialized
5 silly isInitialized true
6 silly existsSync /Users/vex/p/zuu/VERSION
7 silly initialize attempt
8 info current version 4.0.1-rc8
9 silly getUpdates
10 info Checking for updated packages...
11 silly hasTags
12 verbose hasTags true
13 silly getLastTag
14 error initialize caught error
15 error Error: fatal: No tags can describe 'be619ac63b6c4c9281d82ee92d613d1a9c5e73a4'.
15 error Try --always, or create some tags.
15 error
15 error     at Function.module.exports.sync (/Users/vex/.nvm/versions/node/v8.11.2/lib/node_modules/lerna/node_modules/execa/index.js:303:26)
15 error     at Function.execSync (/Users/vex/.nvm/versions/node/v8.11.2/lib/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
15 error     at Function.getLastTag (/Users/vex/.nvm/versions/node/v8.11.2/lib/node_modules/lerna/lib/GitUtilities.js:162:53)
15 error     at UpdatedPackagesCollector.collectUpdatedPackages (/Users/vex/.nvm/versions/node/v8.11.2/lib/node_modules/lerna/lib/UpdatedPackagesCollector.js:112:42)
15 error     at UpdatedPackagesCollector.getUpdates (/Users/vex/.nvm/versions/node/v8.11.2/lib/node_modules/lerna/lib/UpdatedPackagesCollector.js:88:35)
15 error     at PublishCommand.initialize (/Users/vex/.nvm/versions/node/v8.11.2/lib/node_modules/lerna/lib/commands/PublishCommand.js:275:67)
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 6.2.0 |
| `yarn --version` | - |
| `node --version` | 8.11.2 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13 |

**Comment by IAmTheVex** [comment]
Well i had `--skip-git` on... why should it care?

**Comment by evocateur** [comment]
`--skip-git` is the worst-named option ever, it only skips git commit and push. It doesn't remove the requirement for git.
