### ISSUE TITLE
version tags like 'canary', 'next' can't be resolved by `lerna add`

### ISSUE THREAD

**Issue by rashidul0405** [lerna/lerna#1529]
`lerna add react-scripts@next --scope='@example/admin'` (https://www.npmjs.com/package/react-scripts)
 
- Version tags (https://docs.npmjs.com/getting-started/using-tags) can't be resolved by `lerna add`. only `pkg@latest`tag works.

## Expected Behavior

`lerna add` should resolve that tag and take appropriate action on it. workaround right now is as follow:
`lerna exec yarn add react-scripts@next --scope='@example/admin'`

## Current Behavior

produces following error:
```
lerna info version 2.11.0
lerna info versioning independent
lerna info scope @friflyt/utemagasinet
lerna ERR! initialize callback with error
lerna ERR! TypeError: Invalid comparator: next
lerna ERR!     at Comparator.parse (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:690:11)
lerna ERR!     at new Comparator (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:674:8)
lerna ERR!     at /Users/rislam/.config/yarn/global/node_modules/semver/semver.js:840:12
lerna ERR!     at Array.map (<anonymous>)
lerna ERR!     at Range.parseRange (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:839:13)
lerna ERR!     at Range.<anonymous> (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:781:17)
lerna ERR!     at Array.map (<anonymous>)
lerna ERR!     at new Range (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:780:40)
lerna ERR!     at Function.intersects (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:1306:8)
{ TypeError: Invalid comparator: next
    at Comparator.parse (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:690:11)
    at new Comparator (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:674:8)
    at /Users/rislam/.config/yarn/global/node_modules/semver/semver.js:840:12
    at Array.map (<anonymous>)
    at Range.parseRange (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:839:13)
    at Range.<anonymous> (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:781:17)
    at Array.map (<anonymous>)
    at new Range (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:780:40)
    at Function.intersects (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:1306:8)
    at getRangeToReference (/Users/rislam/.config/yarn/global/node_modules/lerna/lib/commands/AddCommand.js:313:35) exitCode: 1 }
```
## Possible Solution

No idea for now, need to dig into source code. I can try if you think this is an issue.

## Steps to Reproduce (for bugs)

1. Above command will do the trick

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'react-scripts@next' ]
1 silly flags { _: [ 'add' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   dev: false,
1 silly flags   D: false,
1 silly flags   scope: '@friflyt/utemagasinet',
1 silly flags   args: [ 'react-scripts@next' ] }
2 verbose rootPath /Users/rislam/Sites/next
3 info version 2.11.0
4 silly isInitialized
5 silly isInitialized true
6 silly existsSync /Users/rislam/Sites/next/VERSION
7 info versioning independent
8 info scope @friflyt/utemagasinet
9 silly initialize attempt
10 error initialize callback with error
11 error TypeError: Invalid comparator: next
11 error     at Comparator.parse (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:690:11)
11 error     at new Comparator (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:674:8)
11 error     at /Users/rislam/.config/yarn/global/node_modules/semver/semver.js:840:12
11 error     at Array.map (<anonymous>)
11 error     at Range.parseRange (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:839:13)
11 error     at Range.<anonymous> (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:781:17)
11 error     at Array.map (<anonymous>)
11 error     at new Range (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:780:40)
11 error     at Function.intersects (/Users/rislam/.config/yarn/global/node_modules/semver/semver.js:1306:8)

```
</p></details>

## Context

N/A

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `yarn --version` | 1.7.0 |
| `node --version` | 10.5.0 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.6 |

**Comment by rashidul0405** [comment]
sorry it's working, it just can't override.

**Comment by evocateur** [comment]
Yeah, sorry, `lerna upgrade` is still unimplemented.
