### ISSUE TITLE
lerna init breaks if lerna.json not already present

### ISSUE THREAD

**Issue by Leeds-eBooks** [lerna/lerna#154]
```sh
$ npm-run lerna init

Lerna v2.0.0-beta.11
Creating packages folder.
Updating package.json.
Creating lerna.json.
Errored while running InitCommand.execute
TypeError: Object.assign cannot be called with null or undefined
    at toObject (/Users/ben/Dev/Git/test-lerna/node_modules/lerna/node_modules/object-assign/index.js:8:9)
    at module.exports (/Users/ben/Dev/Git/test-lerna/node_modules/lerna/node_modules/object-assign/index.js:60:11)
    at InitCommand.ensureLernaJson (/Users/ben/Dev/Git/test-lerna/node_modules/lerna/lib/commands/InitCommand.js:127:34)
    at InitCommand.execute (/Users/ben/Dev/Git/test-lerna/node_modules/lerna/lib/commands/InitCommand.js:62:12)
    at InitCommand._attempt (/Users/ben/Dev/Git/test-lerna/node_modules/lerna/lib/Command.js:148:21)
    at /Users/ben/Dev/Git/test-lerna/node_modules/lerna/lib/Command.js:133:15
    at /Users/ben/Dev/Git/test-lerna/node_modules/lerna/lib/Command.js:157:13
    at InitCommand.initialize (/Users/ben/Dev/Git/test-lerna/node_modules/lerna/lib/commands/InitCommand.js:55:7)
    at InitCommand._attempt (/Users/ben/Dev/Git/test-lerna/node_modules/lerna/lib/Command.js:148:21)
    at InitCommand.runCommand (/Users/ben/Dev/Git/test-lerna/node_modules/lerna/lib/Command.js:132:12)
```

If I add a `lerna.json` file that contains only `{}` before running `lerna init`, everything works fine, no errors. Looking at `/Users/ben/Dev/Git/test-lerna/node_modules/lerna/lib/commands/InitCommand.js` it seems that no `lerna.json` file ever gets created if one doesn't exist already.

**Comment by hzoo** [comment]
Ok weird that's a bug then - it does say `Creating lerna.json.` so it should since we don't expect a new project to have it
