### ISSUE TITLE
Git Hosted Sibling Semver not supporting custom hosts when publishing

### ISSUE THREAD

**Issue by hiendv** [lerna/lerna#1550]
## Expected Behavior
Lerna correctly publishs the packages to our own git server.
`git+ssh://git@git.mycompany.com:username/package.git#semver:^0.1.0`

## Current Behavior
`TypeError: Cannot set property 'committish' of undefined`
Since [npm/hosted-git-info](https://github.com/npm/hosted-git-info) only supports [Github, Bitbucket and Gitlab](https://github.com/npm/hosted-git-info#supported-hosts), `hosted` is `undefined`
https://github.com/lerna/lerna/blob/v3.0.0-rc.0/core/package/index.js#L153

## Steps to Reproduce (for bugs)

1. `lerna init`
2. Specify a git hosted package as the dependency
3. `lerna publish`
4. `TypeError: Cannot set property 'committish' of undefined`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "packages": [
    "packages/*"
  ],
  "version": "0.1.0",
  "useGitVersion": true,
  "gitVersionPrefix": "v"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv { _: [ 'publish' ],
0 silly argv   progress: true,
0 silly argv   sort: true,
0 silly argv   ci: false,
0 silly argv   loglevel: 'info',
0 silly argv   lernaVersion: '3.0.0-rc.0',
0 silly argv   '$0': 'lerna' }
1 info version 3.0.0-rc.0
2 verbose rootPath /tmp/package-monorepo
3 info current version 0.1.0
4 silly isAnythingCommitted
5 verbose isAnythingCommitted 1
6 silly currentBranch
7 verbose currentBranch master
8 silly isBehindUpstream
9 silly isBehindUpstream master is behind origin/master by 0 commit(s) and ahead by 1
10 silly hasTags
11 verbose hasTags false
12 info Looking for changed packages since initial commit.
13 verbose updated @scoped/package-example
14 verbose updated @scoped/package
15 error TypeError: Cannot set property 'committish' of undefined
15 error     at Package.updateLocalDependency (/tmp/package-monorepo/node_modules/@lerna/package/index.js:155:25)
15 error     at Promise.resolve.then.then (/tmp/package-monorepo/node_modules/@lerna/publish/index.js:519:23)

```
</p></details>

## Context
Publishing a git hosted package to a custom host

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-rc.0 |
| `npm --version`  | 6.3.0 |
| `yarn --version` | VERSION |
| `node --version` | v10.6.0 |

**Comment by hiendv** [comment]
Duplicates:
https://github.com/lerna/lerna/issues/571#issuecomment-405281350
https://github.com/lerna/lerna/issues/1277#issuecomment-369088714
