### ISSUE TITLE
TypeError: Invalid Version: undefined on lerna publish

### ISSUE THREAD

**Issue by carrickjason** [lerna/lerna#1570]
`lerna publish` fails and throws an error from semver `TypeError: Invalid Version: undefined`

![screen shot 2018-08-14 at 12 49 37 pm](https://user-images.githubusercontent.com/12468946/44112030-3baf741e-9fc1-11e8-8f5f-d04daa28ece2.png)

## Steps to Reproduce (for bugs)
Exact command run was `lerna publish --npm-tag test`.
Then selected Prerelease with `alpha` id.

```json
{
  "lerna": "3.0.4",
  "command": {
    "init": {
      "exact": true
    },
    "publish": {
      "message": "chore(release): publish %s",
      "allowBranch": [
        "@test/babel-build"
      ],
      "ignoreChanges": [
        "packages/docs"
      ]
    }
  },
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "version": "3.0.0-alpha.5"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
30 error TypeError: Invalid Version: undefined
30 error     at new SemVer (/Users/jcarrick/Sites/react-common-components/node_modules/semver/semver.js:291:11)
30 error     at compare (/Users/jcarrick/Sites/react-common-components/node_modules/semver/semver.js:578:10)
30 error     at eq (/Users/jcarrick/Sites/react-common-components/node_modules/semver/semver.js:617:10)
30 error     at Function.diff (/Users/jcarrick/Sites/react-common-components/node_modules/semver/semver.js:512:7)
30 error     at isBreakingChange (/Users/jcarrick/Sites/react-common-components/node_modules/@lerna/version/lib/is-breaking-change.js:8:30)
30 error     at versions (/Users/jcarrick/Sites/react-common-components/node_modules/@lerna/version/index.js:152:36)
30 error     at pReduce (/Users/jcarrick/Sites/react-common-components/node_modules/p-waterfall/index.js:4:73)
30 error     at Promise.all.then.value (/Users/jcarrick/Sites/react-common-components/node_modules/p-reduce/index.js:16:10)
30 error     at <anonymous>
```
</p></details>

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.4 |
| `yarn --version` | 1.9.4 |
| `node --version` | 8.11.3 |

**Comment by carrickjason** [comment]
Apologies, A package.json file in one of my packages got destroyed.
