### ISSUE TITLE
lerna add: ENOTFOUND registry.npmjs.org

### ISSUE THREAD

**Issue by schabluk** [lerna/lerna#1572]
Hi,

I cannot install packages with lerna while working behind corporate firewall.

> npx lerna add --no-private --dev @babel/plugin-proposal-object-rest-spread

Installing with `yarn` or `npm` works fine.

Proxy settings:
```
HTTP_PROXY=http://proxy:8080
HTTPS_PROXY=http://proxy:8080

export HTTP_PROXY HTTPS_PROXY

npm config set proxy 'http://username:password@proxy:8080'
npm config set https-proxy 'http://username:password@proxy:8080'
npm config set strict-ssl false
npm config set registry 'https://registry.npmjs.org'

yarn config set proxy 'http://username:password@proxy:8080'
yarn config set https-proxy 'http://username:password@proxy:8080'
yarn config set strict-ssl false
yarn config set registry 'https://registry.yarnpkg.com'
```

## Expected Behavior

Package is being installed to all no-private packages.

## Current Behavior

```$ npx lerna add --no-private --dev @babel/plugin-proposal-object-rest-spread
$ npx lerna add --no-private --dev @babel/plugin-proposal-object-rest-spread

lerna info version 3.0.6
lerna ERR! RequestError: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
lerna ERR!     at ClientRequest.req.once.err (/home/user/mono/node_modules/got/index.js:73:21)
lerna ERR!     at Object.onceWrapper (events.js:315:30)
lerna ERR!     at emitOne (events.js:116:13)
lerna ERR!     at ClientRequest.emit (events.js:211:7)
lerna ERR!     at TLSSocket.socketErrorListener (_http_client.js:387:9)
lerna ERR!     at emitOne (events.js:116:13)
lerna ERR!     at TLSSocket.emit (events.js:211:7)
lerna ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
lerna ERR!     at _combinedTickCallback (internal/process/next_tick.js:138:11)
lerna ERR! lerna getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
```

## Steps to Reproduce (for bugs)
Using `learna add` behind corporate firewall.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0",
  "npmClient": "yarn",
  "useWorkspaces": true
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv { _: [ 'add' ],
0 silly argv   progress: true,
0 silly argv   ci: false,
0 silly argv   private: false,
0 silly argv   dev: true,
0 silly argv   D: true,
0 silly argv   loglevel: 'info',
0 silly argv   globs: [],
0 silly argv   lernaVersion: '3.0.6',
0 silly argv   '$0': 'node_modules/.bin/lerna',
0 silly argv   pkg: '@babel/plugin-proposal-object-rest-spread' }
1 info version 3.0.6
2 verbose rootPath /home/user/mono
3 error RequestError: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
3 error     at ClientRequest.req.once.err (/home/user/mono/node_modules/got/index.js:73:21)
3 error     at Object.onceWrapper (events.js:315:30)
3 error     at emitOne (events.js:116:13)
3 error     at ClientRequest.emit (events.js:211:7)
3 error     at TLSSocket.socketErrorListener (_http_client.js:387:9)
3 error     at emitOne (events.js:116:13)
3 error     at TLSSocket.emit (events.js:211:7)
3 error     at emitErrorNT (internal/streams/destroy.js:64:8)
3 error     at _combinedTickCallback (internal/process/next_tick.js:138:11)
```
</p></details>

## Context
> How has this issue affected you?

This issue affects my workflow, as I have to manually install shared dependecies.

> What are you trying to accomplish?

I'm trying to setup dev environment, where all packages share the same assets (scss, fonts) and build configs (webpack). The assumpion is, that all modules will build using the same version of @babel transpilers and other webpack loaders.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.6 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.9.4 |
| `node --version` | 8.11.3 |

| OS | Version |
| --- | --- |
| Ubuntu | 4.4.0-21-generic |

**Comment by evocateur** [comment]
Essentially the same as #1539, and I appreciate the detailed context, that helps quite a lot. We'll need to replace [`package-json`](https://github.com/sindresorhus/package-json) with `pacote`'s new [`packument()` API](https://github.com/zkat/pacote#packument).

**Comment by schabluk** [comment]
@evocateur I added more detailed context. I hope that's helpful.
