### ISSUE TITLE
lerna publish error `EWHOAMI Authentication error. Use `npm whoami` to troubleshoot.`

### ISSUE THREAD

**Issue by JaosnHsieh** [lerna/lerna#1574]
When publish to my private npm registry ( built by verdaccio@3.6.0 ), `npm publish` would work as expected but `lerna publish` lead to unexpected error. 
## Expected Behavior

`lerna publish` should successfully publish packages  to my private registry as `npm publish` does.

## Current Behavior

publish failed and show below error message
```
Are you sure you want to publish these packages? Yes
lerna info git Pushing tags...
lerna info publish Publishing packages to npm...
lerna WARN ETHIRDPARTY Skipping ping of http://localhost:4873 as most third-party registries do not support advanced npm functionality
npm http request GET http://localhost:4873/-/org/miuser/package?format=cli
npm http 404 http://localhost:4873/-/org/miuser/package?format=cli
npm http request GET http://localhost:4873/-/user/miuser/package?format=cli
npm http 404 http://localhost:4873/-/user/miuser/package?format=cli
npm ERR! code E404
npm ERR! 404 File not found : -/user/miuser/package

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jasonhsieh/.npm/_logs/2018-08-17T10_40_01_580Z-debug.log

lerna ERR! EWHOAMI Authentication error. Use `npm whoami` to troubleshoot.

```

## Possible Solution

instead of `lerna publish`, add a flag to `lerna publish --no-verify-access` would work.

## Steps to Reproduce (for bugs)

1. `npm i -g lerna@3.0.0-rc.0`
2. `npm i -g verdaccio@3.6.0`
3. run verdaccio by `verdaccio`
4. `cd your-lerna-project`
5. ensure `lerna.json`  has registry set as below
```
`{
  "packages": [
    "packages/*"
  ],
  "registry": "http://localhost:4873",
  "version": "1.0.27"
}
`
```
6. `npm set registry http://localhost:4873`
7. `npm adduser --registry http://localhost:4873` then type user info
8. `npm login` then type the user created on step.7
9. `lerna pubsh`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "registry": "http://localhost:4873",
  "version": "1.0.27"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```

```npm debug.log
22 verbose stack Error: File not found : -/user/miuser/package
22 verbose stack     at makeError (/home/jasonhsieh/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:316:12)
22 verbose stack     at RegClient.<anonymous> (/home/jasonhsieh/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:14)
22 verbose stack     at Request._callback (/home/jasonhsieh/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
22 verbose stack     at Request.self.callback (/home/jasonhsieh/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/request/request.js:185:22)
22 verbose stack     at emitTwo (events.js:126:13)
22 verbose stack     at Request.emit (events.js:214:7)
22 verbose stack     at Request.<anonymous> (/home/jasonhsieh/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/request/request.js:1157:10)
22 verbose stack     at emitOne (events.js:116:13)
22 verbose stack     at Request.emit (events.js:211:7)
22 verbose stack     at IncomingMessage.<anonymous> (/home/jasonhsieh/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/request/request.js:1079:12)
23 verbose statusCode 404
24 verbose cwd /home/jasonhsieh/git/lerna-test
25 verbose Linux 4.15.0-30-generic
26 verbose argv "/home/jasonhsieh/.nvm/versions/node/v8.11.3/bin/node" "/home/jasonhsieh/.nvm/versions/node/v8.11.3/bin/npm" "access" "ls-packages" "--fetch-retries=0" "--loglevel=http"
27 verbose node v8.11.3
28 verbose npm  v6.4.0
29 error code E404
30 error 404 File not found : -/user/miuser/package
31 verbose exit [ 1, true ]

```
</p></details>

## Context

Trying to publish my package to my private registry.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-rc.0 |
| `npm --version`  | 6.4.0 |
| `yarn --version` | 1.9.4 |
| `node --version` | v8.11.3 |

| OS | Version |
| --- | --- |
| Ubuntu | 16.10 |

**Comment by evocateur** [comment]
`--no-verify-access` was added in v3.0.4
