### ISSUE TITLE
commit everything but lerna version warning 'working tree has uncommitted changes'

### ISSUE THREAD

**Issue by imsobear** [lerna/lerna#1591]
## Expected Behavior

Publish success

## Current Behavior

Publish failed and I don't know which error caused, and why have these errors:

- `lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.`
- `npm ERR! 404 not_found document not found: -/user/ice-admin/package
`

```bash
➜  iceland-packages git:(master) npm run publish

> iceland-packages@1.0.0 publish /Users/sobear/work/iceland/iceland-packages
> lerna publish

lerna notice cli v3.1.2
lerna info versioning independent
lerna info Looking for changed packages since @ali/iceland-dsl2code@0.7.42
? Select a new version for @ali/iceland-dsl2code (currently 0.7.42) Patch (0.7.43)
? Select a new version for @ali/iceland-intelligent-layout (currently 0.2.32) Patch (0.2.33)

Changes:
 - @ali/iceland-dsl2code: 0.7.42 => 0.7.43
 - @ali/iceland-intelligent-layout: 0.2.32 => 0.2.33

? Are you sure you want to publish these packages? Yes
lerna info lifecycle iceland-packages@1.0.0~version: iceland-packages@1.0.0

> iceland-packages@1.0.0 version /Users/sobear/work/iceland/iceland-packages
> lerna version

lerna notice cli v3.1.2
lerna info versioning independent
lerna info Looking for changed packages since @ali/iceland-dsl2code@0.7.42
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.
lerna info lifecycle iceland-packages@1.0.0~version: Failed to exec version script
lerna ERR! lifecycle error running version in iceland-packages
lerna ERR! lifecycle  Error: iceland-packages@1.0.0 version: `lerna version`
lerna ERR! lifecycle Exit status 1
lerna ERR! lifecycle     at EventEmitter.<anonymous> (/Users/sobear/work/iceland/iceland-packages/node_modules/_npm-lifecycle@2.1.0@npm-lifecycle/index.js:301:16)
lerna ERR! lifecycle     at emitTwo (events.js:126:13)
lerna ERR! lifecycle     at EventEmitter.emit (events.js:214:7)
lerna ERR! lifecycle     at ChildProcess.<anonymous> (/Users/sobear/work/iceland/iceland-packages/node_modules/_npm-lifecycle@2.1.0@npm-lifecycle/lib/spawn.js:55:14)
lerna ERR! lifecycle     at emitTwo (events.js:126:13)
lerna ERR! lifecycle     at ChildProcess.emit (events.js:214:7)
lerna ERR! lifecycle     at maybeClose (internal/child_process.js:925:16)
lerna ERR! lifecycle     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
lerna info git Pushing tags...
lerna info publish Publishing packages to npm...
lerna WARN ETHIRDPARTY Skipping ping of http://registry.npm.private.com as most third-party registries do not support advanced npm functionality
npm http request GET http://registry.npm.private.com/-/org/ice-admin/package?format=cli
npm http 404 http://registry.npm.private.com/-/org/ice-admin/package?format=cli
npm http request GET http://registry.npm.private.com/-/user/ice-admin/package?format=cli
npm http 404 http://registry.npm.private.com/-/user/ice-admin/package?format=cli
npm ERR! code E404
npm ERR! 404 not_found document not found: -/user/ice-admin/package

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sobear/.npm/_logs/2018-08-21T07_13_41_117Z-debug.log

lerna ERR! EWHOAMI Authentication error. Use `npm whoami` to troubleshoot.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iceland-packages@1.0.0 publish: `lerna publish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iceland-packages@1.0.0 publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sobear/.npm/_logs/2018-08-21T07_13_41_145Z-debug.log
```

## lerna.json

```json
{
  "lerna": "3.1.2",
  "packages": [
    "packages/*"
  ],
  "command": {
    "publish": {
      "ignoreChanges": [
        "demo",
        "test",
        "*.md"
      ]
    }
  },
  "version": "independent",
  "npmClient": "xnpm",
  "registry": "http://registry.npm.private.com"
}
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  |8.11.1 |
| `yarn --version` | VERSION |
| `node --version` |5.6.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.13.4 |

**Comment by imsobear** [comment]
```
➜  iceland-packages git:(master) git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
➜  iceland-packages git:(master) ./node_modules/.bin/lerna version patch
lerna notice cli v3.1.2
lerna info versioning independent
lerna info Looking for changed packages since @ali/iceland-data-engine@0.3.19

Changes:
 - @ali/iceland-dsl2code: 0.7.44 => 0.7.45
 - @ali/iceland-editor: 0.2.68 => 0.2.69
 - @ali/iceland-paint: 1.2.32 => 1.2.33
 - @ali/iceland-plugin-property-panel: 0.1.97 => 0.1.98
 - @ali/iceland-widget-richtext: 0.2.35 => 0.2.36
 - @ali/iceland-workbench: 1.4.45 => 1.4.46

? Are you sure you want to create these versions? Yes
lerna info lifecycle iceland-packages@1.0.0~version: iceland-packages@1.0.0

> iceland-packages@1.0.0 version /Users/sobear/work/iceland/iceland-packages
> lerna version

lerna notice cli v3.1.2
lerna info versioning independent
lerna info Looking for changed packages since @ali/iceland-data-engine@0.3.19
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.
lerna info lifecycle iceland-packages@1.0.0~version: Failed to exec version script
lerna ERR! lifecycle error running version in iceland-packages
lerna ERR! lifecycle  Error: iceland-packages@1.0.0 version: `lerna version`
lerna ERR! lifecycle Exit status 1
lerna ERR! lifecycle     at EventEmitter.<anonymous> (/Users/sobear/work/iceland/iceland-packages/node_modules/_npm-lifecycle@2.1.0@npm-lifecycle/index.js:301:16)
lerna ERR! lifecycle     at emitTwo (events.js:126:13)
lerna ERR! lifecycle     at EventEmitter.emit (events.js:214:7)
lerna ERR! lifecycle     at ChildProcess.<anonymous> (/Users/sobear/work/iceland/iceland-packages/node_modules/_npm-lifecycle@2.1.0@npm-lifecycle/lib/spawn.js:55:14)
lerna ERR! lifecycle     at emitTwo (events.js:126:13)
lerna ERR! lifecycle     at ChildProcess.emit (events.js:214:7)
lerna ERR! lifecycle     at maybeClose (internal/child_process.js:925:16)
lerna ERR! lifecycle     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
lerna info git Pushing tags...
lerna success version finished
```

**Comment by imsobear** [comment]
and `--force-publish` option is not useful:

```
➜  iceland-packages git:(master) ./node_modules/.bin/lerna version --force-publish=*
lerna notice cli v3.1.2
lerna info versioning independent
lerna notice Current HEAD is already released, skipping change detection.
lerna success No changed packages to version
```

**Comment by djskinner** [comment]
We've just bumped lerna and are now hitting this issue. The problem is that we generate a `.npmrc` file on CI with the relevant credentials (we don't want think committed to source control) so there's always going to be this uncommitted change in the working tree (and always was, lerna never complained before)

**Comment by evocateur** [comment]
@imsobear You appear to have a `version` lifecycle that calls `lerna version`? That will be called recursively, so you should probably rename the script or remove it altogether.

**Comment by imsobear** [comment]
@evocateur When i removed the `"version": "lerna version"` npm script from root package.json `lerna version` cmd works well, but `lerna publish` not works:

```
➜  iceland-packages git:(master) ./node_modules/.bin/lerna version patch
lerna notice cli v3.1.2
lerna info versioning independent
lerna info Looking for changed packages since @xxx/iceland-dsl2code@0.7.45

Changes:
 - @xxx/iceland-dsl2code: 0.7.46 => 0.7.47

? Are you sure you want to create these versions? Yes
lerna info git Pushing tags...
lerna success version finished
➜  iceland-packages git:(master) ./node_modules/.bin/lerna publish
lerna notice cli v3.1.2
lerna info versioning independent
lerna notice Current HEAD is already released, skipping change detection.
lerna success No changed packages to publish
```

looks no package published. 😕

**Comment by imsobear** [comment]
when i run `publish` directly(no version cmd before), I get some error message: 

```
➜  iceland-packages git:(master) ./node_modules/.bin/lerna changed
lerna notice cli v3.1.2
lerna info versioning independent
lerna info Looking for changed packages since @ali/iceland-data-engine@0.3.21
@ali/iceland-dsl2code
lerna success found 1 package ready to publish
➜  iceland-packages git:(master) ./node_modules/.bin/lerna publish patch
lerna notice cli v3.1.2
lerna info versioning independent
lerna info Looking for changed packages since @ali/iceland-data-engine@0.3.21

Changes:
 - @ali/iceland-dsl2code: 0.7.47 => 0.7.48

? Are you sure you want to publish these packages? Yes
lerna info git Pushing tags...
lerna info publish Publishing packages to npm...
lerna WARN ETHIRDPARTY Skipping ping of http://registry.npm.private.com as most third-party registries do not support advanced npm functionality
npm http request GET http://registry.npm.private.com/-/org/ice-admin/package?format=cli
npm http 404 http://registry.npm.private.com/-/org/ice-admin/package?format=cli
npm http request GET http://registry.npm.private.com/-/user/ice-admin/package?format=cli
npm http 404 http://registry.npm.private.com/-/user/ice-admin/package?format=cli
npm ERR! code E404
npm ERR! 404 not_found document not found: -/user/ice-admin/package

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sobear/.npm/_logs/2018-08-21T15_44_29_267Z-debug.log

lerna ERR! EWHOAMI Authentication error. Use `npm whoami` to troubleshoot.
``` 

I don't understand lerna need check third-party registry what ability in version 3.x.

**Comment by evocateur** [comment]
If you've already run `lerna version` and you're on the same tagged commit, you need to run `lerna publish from-git`, otherwise it will fail just as you've reported.

I've never heard of `http://registry.npm.private.com/`, but it sounds like it isn't API-compatible with the public npm registry. You can pass `--no-verify-registry` and `--no-verify-access` to `lerna publish` to disable those checks.

**Comment by imsobear** [comment]
@evocateur works! thanks for your reply. 👍 

And `http://registry.npm.private.com/` is my company internal registry, `private` just a example. I think the internal registry missing some abilities compared to npm.

**Comment by imsobear** [comment]
Hi, @evocateur I can't find the API(`/-/user/:scope/package`) on [npm-registry API docs](https://github.com/npm/registry/blob/ac13bcae48e1ca5e62ef9fd3585f30a7fc7734e5/docs/orgs/memberships.md). So where did you find this API?

**Comment by evocateur** [comment]
It was in the error messages as I was testing the feature.

**Comment by vegawong** [comment]
https://github.com/verdaccio/verdaccio/issues/937   
Is this issue cause that?
