### ISSUE TITLE
ETARGET error installing lerna

### ISSUE THREAD

**Issue by usergenic** [lerna/lerna#1593]
```
$ npm install lerna
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @lerna/changed@^3.1.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@lerna/cli'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brendanb/.npm/_logs/2018-08-21T18_20_37_011Z-debug.log
$ cat /Users/brendanb/.npm/_logs/2018-08-21T18_20_37_011Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/brendanb/.nvm/versions/node/v9.11.2/bin/node',
1 verbose cli   '/Users/brendanb/.nvm/versions/node/v9.11.2/bin/npm',
1 verbose cli   'install',
1 verbose cli   'lerna' ]
2 info using npm@6.4.0
3 info using node@v9.11.2
4 verbose npm-session 6c4b39043c73ac87
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/lerna 99ms
8 silly pacote tag manifest for lerna@latest fetched in 124ms
9 timing stage:loadCurrentTree Completed in 316ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule lerna@3.1.4 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/npmlog 49ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/import-local 50ms (from cache)
19 silly pacote range manifest for npmlog@^4.1.2 fetched in 51ms
20 silly resolveWithNewModule npmlog@4.1.2 checking installable status
21 silly pacote range manifest for import-local@^1.0.0 fetched in 53ms
22 silly resolveWithNewModule import-local@1.0.0 checking installable status
23 http fetch GET 200 https://registry.npmjs.org/@lerna%2fcli 116ms
24 silly pacote range manifest for @lerna/cli@^3.1.4 fetched in 120ms
25 silly resolveWithNewModule @lerna/cli@3.1.4 checking installable status
26 http fetch GET 200 https://registry.npmjs.org/@lerna%2fadd 18ms (from cache)
27 http fetch GET 200 https://registry.npmjs.org/@lerna%2fbootstrap 16ms (from cache)
28 http fetch GET 200 https://registry.npmjs.org/@lerna%2fchanged 16ms (from cache)
29 http fetch GET 200 https://registry.npmjs.org/@lerna%2fclean 15ms (from cache)
30 silly registry:manifest no matching version for @lerna/changed@^3.1.3 in the cache. Forcing revalidation
31 silly registry:manifest no matching version for @lerna/clean@^3.1.3 in the cache. Forcing revalidation
32 http fetch GET 200 https://registry.npmjs.org/@lerna%2fcreate 19ms (from cache)
33 http fetch GET 200 https://registry.npmjs.org/@lerna%2fdiff 18ms (from cache)
34 http fetch GET 200 https://registry.npmjs.org/@lerna%2fexec 19ms (from cache)
35 silly registry:manifest no matching version for @lerna/create@^3.1.3 in the cache. Forcing revalidation
36 silly registry:manifest no matching version for @lerna/diff@^3.1.3 in the cache. Forcing revalidation
37 silly registry:manifest no matching version for @lerna/exec@^3.1.3 in the cache. Forcing revalidation
38 http fetch GET 200 https://registry.npmjs.org/@lerna%2fglobal-options 22ms (from cache)
39 http fetch GET 200 https://registry.npmjs.org/@lerna%2fimport 22ms (from cache)
40 silly registry:manifest no matching version for @lerna/global-options@^3.1.3 in the cache. Forcing revalidation
41 silly registry:manifest no matching version for @lerna/import@^3.1.3 in the cache. Forcing revalidation
42 http fetch GET 200 https://registry.npmjs.org/@lerna%2finit 24ms (from cache)
43 silly registry:manifest no matching version for @lerna/init@^3.1.3 in the cache. Forcing revalidation
44 silly pacote range manifest for @lerna/add@^3.1.4 fetched in 32ms
45 silly resolveWithNewModule @lerna/add@3.1.4 checking installable status
46 silly pacote range manifest for @lerna/bootstrap@^3.1.4 fetched in 32ms
47 silly resolveWithNewModule @lerna/bootstrap@3.1.4 checking installable status
48 http fetch GET 200 https://registry.npmjs.org/@lerna%2flink 17ms (from cache)
49 http fetch GET 200 https://registry.npmjs.org/@lerna%2flist 18ms (from cache)
50 silly registry:manifest no matching version for @lerna/list@^3.1.3 in the cache. Forcing revalidation
51 silly pacote range manifest for @lerna/link@^3.1.4 fetched in 21ms
52 silly resolveWithNewModule @lerna/link@3.1.4 checking installable status
53 http fetch GET 200 https://registry.npmjs.org/@lerna%2fpublish 6ms (from cache)
54 silly registry:manifest no matching version for @lerna/publish@^3.1.3 in the cache. Forcing revalidation
55 http fetch GET 304 https://registry.npmjs.org/@lerna%2fchanged 68ms (from cache)
56 silly fetchPackageMetaData error for @lerna/changed@^3.1.3 No matching version found for @lerna/changed@^3.1.3
57 http fetch GET 200 https://registry.npmjs.org/@lerna%2frun 2ms (from cache)
58 silly registry:manifest no matching version for @lerna/run@^3.1.3 in the cache. Forcing revalidation
59 http fetch GET 304 https://registry.npmjs.org/@lerna%2fcreate 77ms (from cache)
60 silly fetchPackageMetaData error for @lerna/create@^3.1.3 No matching version found for @lerna/create@^3.1.3
61 http fetch GET 200 https://registry.npmjs.org/@lerna%2fversion 2ms (from cache)
62 silly registry:manifest no matching version for @lerna/version@^3.1.3 in the cache. Forcing revalidation
63 http fetch GET 304 https://registry.npmjs.org/@lerna%2fdiff 96ms (from cache)
64 silly fetchPackageMetaData error for @lerna/diff@^3.1.3 No matching version found for @lerna/diff@^3.1.3
65 http fetch GET 200 https://registry.npmjs.org/dedent 2ms (from cache)
66 silly pacote range manifest for dedent@^0.7.0 fetched in 5ms
67 silly resolveWithNewModule dedent@0.7.0 checking installable status
68 http fetch GET 304 https://registry.npmjs.org/@lerna%2fimport 108ms (from cache)
69 silly fetchPackageMetaData error for @lerna/import@^3.1.3 No matching version found for @lerna/import@^3.1.3
70 http fetch GET 304 https://registry.npmjs.org/@lerna%2fglobal-options 111ms (from cache)
71 silly fetchPackageMetaData error for @lerna/global-options@^3.1.3 No matching version found for @lerna/global-options@^3.1.3
72 http fetch GET 304 https://registry.npmjs.org/@lerna%2frun 49ms (from cache)
73 silly fetchPackageMetaData error for @lerna/run@^3.1.3 No matching version found for @lerna/run@^3.1.3
74 http fetch GET 304 https://registry.npmjs.org/yargs 23ms (from cache)
75 silly pacote range manifest for yargs@^12.0.1 fetched in 27ms
76 silly resolveWithNewModule yargs@12.0.1 checking installable status
77 http fetch GET 304 https://registry.npmjs.org/@lerna%2fclean 146ms (from cache)
78 silly fetchPackageMetaData error for @lerna/clean@^3.1.3 No matching version found for @lerna/clean@^3.1.3
79 http fetch GET 304 https://registry.npmjs.org/@lerna%2fexec 169ms (from cache)
80 silly fetchPackageMetaData error for @lerna/exec@^3.1.3 No matching version found for @lerna/exec@^3.1.3
81 http fetch GET 304 https://registry.npmjs.org/@lerna%2flist 123ms (from cache)
82 silly fetchPackageMetaData error for @lerna/list@^3.1.3 No matching version found for @lerna/list@^3.1.3
83 http fetch GET 304 https://registry.npmjs.org/@lerna%2finit 170ms (from cache)
84 silly fetchPackageMetaData error for @lerna/init@^3.1.3 No matching version found for @lerna/init@^3.1.3
85 http fetch GET 304 https://registry.npmjs.org/@lerna%2fpublish 128ms (from cache)
86 silly fetchPackageMetaData error for @lerna/publish@^3.1.3 No matching version found for @lerna/publish@^3.1.3
87 http fetch GET 304 https://registry.npmjs.org/@lerna%2fversion 128ms (from cache)
88 silly fetchPackageMetaData error for @lerna/version@^3.1.3 No matching version found for @lerna/version@^3.1.3
89 timing stage:rollbackFailedOptional Completed in 1ms
90 timing stage:runTopLevelLifecycles Completed in 691ms
91 silly saveTree test-lerna
91 silly saveTree └─┬ lerna@3.1.4
91 silly saveTree   ├─┬ @lerna/cli@3.1.4
91 silly saveTree   │ ├─┬ @lerna/add@3.1.4
91 silly saveTree   │ │ ├─┬ @lerna/bootstrap@3.1.4
91 silly saveTree   │ │ │ ├── dedent@0.7.0
91 silly saveTree   │ │ │ └── npmlog@4.1.2
91 silly saveTree   │ │ └── dedent@0.7.0
91 silly saveTree   │ ├── @lerna/bootstrap@3.1.4
91 silly saveTree   │ ├── @lerna/link@3.1.4
91 silly saveTree   │ ├── dedent@0.7.0
91 silly saveTree   │ ├── npmlog@4.1.2
91 silly saveTree   │ └── yargs@12.0.1
91 silly saveTree   ├── import-local@1.0.0
91 silly saveTree   └── npmlog@4.1.2
92 verbose type range
93 verbose stack @lerna/changed: No matching version found for @lerna/changed@^3.1.3
93 verbose stack     at pickManifest (/Users/brendanb/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:65:11)
93 verbose stack     at fetchPackument.then.packument (/Users/brendanb/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:52:18)
93 verbose stack     at tryCatcher (/Users/brendanb/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
93 verbose stack     at Promise._settlePromiseFromHandler (/Users/brendanb/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
93 verbose stack     at Promise._settlePromise (/Users/brendanb/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
93 verbose stack     at Promise._settlePromise0 (/Users/brendanb/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
93 verbose stack     at Promise._settlePromises (/Users/brendanb/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
93 verbose stack     at Async._drainQueue (/Users/brendanb/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
93 verbose stack     at Async._drainQueues (/Users/brendanb/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
93 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/brendanb/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
93 verbose stack     at runCallback (timers.js:763:18)
93 verbose stack     at tryOnImmediate (timers.js:734:5)
93 verbose stack     at processImmediate (timers.js:716:5)
94 verbose cwd /Users/brendanb/src/scratch/test-lerna
95 verbose Darwin 17.7.0
96 verbose argv "/Users/brendanb/.nvm/versions/node/v9.11.2/bin/node" "/Users/brendanb/.nvm/versions/node/v9.11.2/bin/npm" "install" "lerna"
97 verbose node v9.11.2
98 verbose npm  v6.4.0
99 error code ETARGET
100 error notarget No matching version found for @lerna/changed@^3.1.3
101 error notarget In most cases you or one of your dependencies are requesting
101 error notarget a package version that doesn't exist.
101 error notarget
101 error notarget It was specified as a dependency of '@lerna/cli'
102 verbose exit [ 1, true ]
```

**Comment by sginn** [comment]
the cascading dependencies are wreaking havoc.  I tried to force an earlier install of @lerna/cli, but then I get the same issue with @lerna/add

Further, trying to install an older lerna master also is broken:
```
$ npm i lerna@3.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @lerna/diff@^3.1.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@lerna/cli'
npm ERR! notarget 

```

**Comment by evocateur** [comment]
I'm not really sure what to say, https://www.npmjs.com/package/@lerna/changed reflects the correct version, and I was just able to install the latest version successfully in a temp directory...

```bash
$ mkdir /tmp/clean-install
$ cd /tmp/clean-install
$ npm init -y
$ npm i -D --prefer-online --cache=.local-cache lerna

+ lerna@3.1.4
added 605 packages from 313 contributors and audited 35730 packages in 38.555s

$ npm ls @lerna/changed
clean-install@1.0.0 /private/tmp/clean-install
└─┬ lerna@3.1.4
  └─┬ @lerna/cli@3.1.4
    └── @lerna/changed@3.1.3
```

**Comment by usergenic** [comment]
hmm. maybe there's some kind of issue in the npm fabric.  but I just ran those same commands and still fail-town.

**Comment by sginn** [comment]
most likely there is problems with npm propagating the recent releases.  

I managed to get a 3.1.2 install with the following:

``` npm i @lerna/cli@3.1.2 @lerna/add@3.1.2 @lerna/bootstrap@3.1.2 @lerna/link@3.1.2 lerna@3.1.2```

**Comment by usergenic** [comment]
FWIW, re https://status.npmjs.org/ ...

![screen shot 2018-08-21 at 11 49 56 am](https://user-images.githubusercontent.com/578/44422584-60778f80-a538-11e8-8033-89c51a2826b5.png)


```
$ npm install @lerna/changed@3.1.3 -D --prefer-online --cache=.local-cache
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @lerna/changed@3.1.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brendanb/src/scratch/test-lerna-again/.local-cache/_logs/2018-08-21T18_47_59_193Z-debug.log
$ cat /Users/brendanb/src/scratch/test-lerna-again/.local-cache/_logs/2018-08-21T18_47_59_193Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/brendanb/.nvm/versions/node/v10.5.0/bin/node',
1 verbose cli   '/Users/brendanb/.nvm/versions/node/v10.5.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@lerna/changed@3.1.3',
1 verbose cli   '-D',
1 verbose cli   '--prefer-online',
1 verbose cli   '--cache=.local-cache' ]
2 info using npm@6.4.0
3 info using node@v10.5.0
4 verbose npm-session 2f92eaedd1267156
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/@lerna%2fchanged 194ms
8 silly registry:manifest no matching version for @lerna/changed@3.1.3 in the cache. Forcing revalidation
9 http fetch GET 304 https://registry.npmjs.org/@lerna%2fchanged 58ms (from cache)
10 silly fetchPackageMetaData error for @lerna/changed@3.1.3 No matching version found for @lerna/changed@3.1.3
11 timing stage:rollbackFailedOptional Completed in 1ms
12 timing stage:runTopLevelLifecycles Completed in 473ms
13 verbose type version
14 verbose stack @lerna/changed: No matching version found for @lerna/changed@3.1.3
14 verbose stack     at pickManifest (/Users/brendanb/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:65:11)
14 verbose stack     at fetchPackument.then.packument (/Users/brendanb/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:52:18)
14 verbose stack     at tryCatcher (/Users/brendanb/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
14 verbose stack     at Promise._settlePromiseFromHandler (/Users/brendanb/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
14 verbose stack     at Promise._settlePromise (/Users/brendanb/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
14 verbose stack     at Promise._settlePromise0 (/Users/brendanb/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
14 verbose stack     at Promise._settlePromises (/Users/brendanb/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
14 verbose stack     at Async._drainQueue (/Users/brendanb/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
14 verbose stack     at Async._drainQueues (/Users/brendanb/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
14 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/brendanb/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
14 verbose stack     at runCallback (timers.js:696:18)
14 verbose stack     at tryOnImmediate (timers.js:667:5)
14 verbose stack     at processImmediate (timers.js:649:5)
15 verbose cwd /Users/brendanb/src/scratch/test-lerna-again
16 verbose Darwin 17.7.0
17 verbose argv "/Users/brendanb/.nvm/versions/node/v10.5.0/bin/node" "/Users/brendanb/.nvm/versions/node/v10.5.0/bin/npm" "install" "@lerna/changed@3.1.3" "-D" "--prefer-online" "--cache=.local-cache"
18 verbose node v10.5.0
19 verbose npm  v6.4.0
20 error code ETARGET
21 error notarget No matching version found for @lerna/changed@3.1.3
22 error notarget In most cases you or one of your dependencies are requesting
22 error notarget a package version that doesn't exist.
23 verbose exit [ 1, true ]
```

**Comment by usergenic** [comment]
sigh. okay not a lerna-specific issue.  thanks!

**Comment by usergenic** [comment]
- Aug 21, 18:18 UTC
Packument cache purging degradation
Resolved - Newly-published package visibility should be back to normal. 
- Aug 21, 18:00 UTC
Monitoring - The upstream service is now green and package-version availability should be returning to normal. Continuing to monitor. 
- Aug 21, 17:51 UTC
Update - Package visibility is affected by this issue in Cloudflare's API services: https://www.cloudflarestatus.com/incidents/1xns6llkx7l5 
- Aug 21, 17:49 UTC
Identified - Due to an upstream issue we are seeing delays between package publishes and availability.

**Comment by zachwolf** [comment]
Sorry if this is the wrong place, but it seems related.

Is there something under the covers that is trying to pull the latest lerna at npm install? Our `package.json` has lerna pinned at `3.0.0-beta.21`. However running `yarn` gives this massive error `error Couldn't find any versions for "@lerna/command" that matches "^3.1.3"`.

<details>
<summary>
full error log
</summary>
yarn
yarn install v1.7.0
warning package.json: No license field
[1/4] 🔍  Resolving packages...
error Couldn't find any versions for "@lerna/command" that matches "^3.1.3"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find any versions for "@lerna/create" that matches "^3.1.3"
    at MessageError.ExtendableBuiltin (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:52213:13)
    at Generator.next (<anonymous>)
    at step (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find any versions for "@lerna/diff" that matches "^3.1.3"
    at MessageError.ExtendableBuiltin (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:52213:13)
    at Generator.next (<anonymous>)
    at step (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find any versions for "@lerna/exec" that matches "^3.1.3"
    at MessageError.ExtendableBuiltin (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:52213:13)
    at Generator.next (<anonymous>)
    at step (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find any versions for "@lerna/global-options" that matches "^3.1.3"
    at MessageError.ExtendableBuiltin (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:52213:13)
    at Generator.next (<anonymous>)
    at step (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find any versions for "@lerna/changed" that matches "^3.1.3"
    at MessageError.ExtendableBuiltin (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:52213:13)
    at Generator.next (<anonymous>)
    at step (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find any versions for "@lerna/clean" that matches "^3.1.3"
    at MessageError.ExtendableBuiltin (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:52213:13)
    at Generator.next (<anonymous>)
    at step (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find any versions for "@lerna/publish" that matches "^3.1.3"
    at MessageError.ExtendableBuiltin (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:52213:13)
    at Generator.next (<anonymous>)
    at step (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find any versions for "@lerna/init" that matches "^3.1.3"
    at MessageError.ExtendableBuiltin (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:52213:13)
    at Generator.next (<anonymous>)
    at step (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find any versions for "@lerna/import" that matches "^3.1.3"
    at MessageError.ExtendableBuiltin (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:52213:13)
    at Generator.next (<anonymous>)
    at step (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find any versions for "@lerna/list" that matches "^3.1.3"
    at MessageError.ExtendableBuiltin (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:52213:13)
    at Generator.next (<anonymous>)
    at step (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find any versions for "@lerna/run" that matches "^3.1.3"
    at MessageError.ExtendableBuiltin (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:52213:13)
    at Generator.next (<anonymous>)
    at step (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find any versions for "@lerna/version" that matches "^3.1.3"
    at MessageError.ExtendableBuiltin (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:52213:13)
    at Generator.next (<anonymous>)
    at step (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find any versions for "@lerna/command" that matches "^3.1.3"
    at MessageError.ExtendableBuiltin (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:52213:13)
    at Generator.next (<anonymous>)
    at step (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find any versions for "@lerna/command" that matches "^3.1.3"
    at MessageError.ExtendableBuiltin (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:52213:13)
    at Generator.next (<anonymous>)
    at step (/Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/z002nw7/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
</details>


From what I expected newly deployed versions shouldn't have negative effects on existing setups. I realize this is only loosely related to lerna, sorry if it's noise in the thread.

**Comment by eviL-ivan** [comment]
Same issue, fix by package-lock

**Comment by evocateur** [comment]
@zachwolf You should have a lockfile if you're using Yarn, otherwise you can expect breakage like that all the time.

`lerna@3.0.0-beta.21` has a transitive dependency on `@lerna/command@^3.0.0-beta.21`, and `^3.0.0-beta.21` is certainly satisfied by `3.1.3` (play with https://semver.npmjs.com/ to demonstrate).

**Comment by evocateur** [comment]
Closing this as an upstream issue.
