### ISSUE TITLE
Lerna publish failing because it cannot access Git using SSH keys

### ISSUE THREAD

**Issue by spoldman** [lerna/lerna#1615]
When I try to do lerna publish it failed because it cannot access Git private repository. I'm using SSH keys to authenticate to Git. So the @lerna/child_process cannot handle Git commands that require input from user like passphrase for the SSH key. Doing the same command 'git remote update' works as expected in the command line, asking for the passphrase if needed before continuing.

## Current Behavior
```json
yarn lerna publish --no-verify-access --no-verify-registry
yarn run v1.9.4
$ C:\Code\Frontend\Cosmic\node_modules\.bin\lerna publish --no-verify-access --no-verify-registry
lerna notice cli v3.1.4
lerna info versioning independent
lerna ERR! Error: Command failed: git remote update
lerna ERR! git@****: Permission denied (publickey).
lerna ERR! fatal: Could not read from remote repository.
lerna ERR!
lerna ERR! Please make sure you have the correct access rights
lerna ERR! and the repository exists.
lerna ERR! error: Could not fetch origin
lerna ERR!
lerna ERR! Fetching origin
lerna ERR!
lerna ERR!     at makeError (C:\Code\Frontend\Cosmic\node_modules\@lerna\child-process\node_modules\execa\index.js:172:9)
lerna ERR!     at Function.module.exports.sync (C:\Code\Frontend\Cosmic\node_modules\@lerna\child-process\node_modules\execa\index.js:341:15)
lerna ERR!     at Object.execSync (C:\Code\Frontend\Cosmic\node_modules\@lerna\child-process\index.js:22:16)
lerna ERR!     at updateRemote (C:\Code\Frontend\Cosmic\node_modules\@lerna\version\lib\is-behind-upstream.js:26:16)
lerna ERR!     at isBehindUpstream (C:\Code\Frontend\Cosmic\node_modules\@lerna\version\lib\is-behind-upstream.js:11:3)
lerna ERR!     at VersionCommand.initialize (C:\Code\Frontend\Cosmic\node_modules\@lerna\version\index.js:107:7)
lerna ERR!     at Promise.resolve.then (C:\Code\Frontend\Cosmic\node_modules\@lerna\command\index.js:245:24)
lerna ERR! Error: Command failed: git remote update
lerna ERR! git@****: Permission denied (publickey).
lerna ERR! fatal: Could not read from remote repository.
```

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true
}

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.1.4 |
| `yarn --version` | 1.9.4 |
| `node --version` | 8.11.4 |

| OS |
| --- | 
| Windows 10 |

**Comment by spoldman** [comment]
This was working before in version 2

**Comment by spoldman** [comment]
There was something wrong with my SSH agent so this can probably be closed.
