### ISSUE TITLE
TypeError: this.stream.clearLine is not a function

### ISSUE THREAD

**Issue by reggi** [lerna/lerna#164]
Hey, trying to get my CI tool to work with `lerna` everything works great locally but fails on the CI system.

```
> lerna bootstrap && nf run -- sh ./bin/test

Lerna bootstrap v1.1.2

Current version: 1.0.0
Version file location: /home/u10440/src/repo/my-project/VERSION
Packages location: /home/u10440/src/repo/my-project/packages

/home/u10440/src/repo/my-project/node_modules/lerna/node_modules/progress/lib/node-progress.js:177
    this.stream.clearLine();
                ^

TypeError: this.stream.clearLine is not a function
    at ProgressBar.terminate (/home/u10440/src/repo/my-project/node_modules/lerna/node_modules/progress/lib/node-progress.js:177:17)
    at ProgressBar.tick (/home/u10440/src/repo/my-project/node_modules/lerna/node_modules/progress/lib/node-progress.js:91:10)
    at /home/u10440/src/repo/my-project/node_modules/lerna/lib/progress-bar.js:16:9
    at /home/u10440/src/repo/my-project/node_modules/lerna/lib/commands/bootstrap.js:88:25
    at /home/u10440/src/repo/my-project/node_modules/lerna/node_modules/async/lib/async.js:718:13
    at iterate (/home/u10440/src/repo/my-project/node_modules/lerna/node_modules/async/lib/async.js:262:13)
    at /home/u10440/src/repo/my-project/node_modules/lerna/node_modules/async/lib/async.js:274:29
    at /home/u10440/src/repo/my-project/node_modules/lerna/node_modules/async/lib/async.js:44:16
    at /home/u10440/src/repo/my-project/node_modules/lerna/node_modules/async/lib/async.js:723:17
    at /home/u10440/src/repo/my-project/node_modules/lerna/node_modules/async/lib/async.js:167:37

npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "/usr/local/node/4.2.2/bin/node" "/usr/local/node/4.2.1/bin/npm" "run" "test-ci"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! my-project@1.0.0 test-ci: `lerna bootstrap && nf run -- sh ./bin/test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@1.0.0 test-ci script 'lerna bootstrap && nf run -- sh ./bin/test'.
npm ERR! This is most likely a problem with the my-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna bootstrap && nf run -- sh ./bin/test
npm ERR! You can get their info via:
npm ERR!     npm owner ls my-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/u10440/src/repo/my-project/npm-debug.log
```

**Comment by gamtiq** [comment]
I also have this error when I try to bootstrap `babel` in Windows.

**Comment by thejameskyle** [comment]
@laurentdesmet is this handled by your PR #236?

**Comment by laurentdesmet** [comment]
Sorry for the late response, at work we use PR #236 to bootstrap on Windows and this seems to work fine, so I suggest to test if the problem still exists with PR #236.

**Comment by thejameskyle** [comment]
Okay closing since #236 was merged
