### ISSUE TITLE
symlink files on windows break bootstrapping

### ISSUE THREAD

**Issue by irbrownie** [lerna/lerna#1659]
When importing an IOS library in a ReactNative application if symlinks are created and then attempted to be bootstrapped in windows we get this error: lerna ERR! EPACKAGES Errored while collecting packages and package graph
lerna ERR! Error: EPERM: operation not permitted, scandir 'C:\Users\isbrown\Documents\projects\core-frontend\packages\platforms\mobile-app\ios\AppsFlyer\AppsFlyerLib.framework\Headers
lerna ERR!     at Object.fs.readdirSync (fs.js:904:18)
lerna ERR!     at GlobSync._readdir (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:288:41)
lerna ERR!     at GlobSync._readdirInGlobStar (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:267:20)
lerna ERR!     at GlobSync._readdir (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:276:17)
lerna ERR!     at GlobSync._processGlobStar (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:351:22)
lerna ERR!     at GlobSync._process (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:130:10)
lerna ERR!     at GlobSync._processGlobStar (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:384:10)
lerna ERR!     at GlobSync._process (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:130:10)
lerna ERR!     at GlobSync._processGlobStar (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:384:10)
This looks 

## Expected Behavior
I would expect symlinks to either be ignored on windows or handled correctly so that globbing a symlink doesn't break everything.

## Current Behavior
When attempting to bootstrap when .symlink files exist on windows it will not let you continue.

## Possible Solution
This might be a flag in node-glob or globby to properly handle these in windows.

## Steps to Reproduce (for bugs)
1. add a .symlink file created in OSX to your project
2. clone onto a windows machine (any)
3. try to run lerna bootstrap
4. it should blow up

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.11.0",
  "packages": [
    "packages/core/**",
    "packages/platforms/**",
    "packages/tooling/**"
  ],
  "version": "0.0.0",
  "npmClient": "npm",
  "hoist": true
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input []
1 silly flags { _: [ 'bootstrap' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   args: [] }
2 verbose rootPath C:\Users\isbrown\Documents\projects\core-frontend
3 info version 2.11.0
4 silly existsSync C:\Users\isbrown\Documents\projects\core-frontend\VERSION
5 info ignore packages/platforms/mobile-app/ios/
6 error EPACKAGES Errored while collecting packages and package graph
7 error Error: EPERM: operation not permitted, scandir 'C:\Users\isbrown\Documents\projects\core-frontend\packages\platforms\mobile-app\ios\AppsFlyer\AppsFlyerLib.framework\Headers'
7 error     at Object.fs.readdirSync (fs.js:904:18)
7 error     at GlobSync._readdir (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:288:41)
7 error     at GlobSync._readdirInGlobStar (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:267:20)
7 error     at GlobSync._readdir (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:276:17)
7 error     at GlobSync._processGlobStar (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:351:22)
7 error     at GlobSync._process (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:130:10)
7 error     at GlobSync._processGlobStar (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:384:10)
7 error     at GlobSync._process (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:130:10)
7 error     at GlobSync._processGlobStar (C:\Users\isbrown\AppData\Roaming\npm\node_modules\lerna\node_modules\glob\sync.js:384:10)
```
</p></details>

## Context
Attempting to create a mono repo where we include React Native/Angular/React. After merging React Native project in from an OSX machine we started having this issue.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 6.2.0 |
| `node --version` | 8.9.4|

| OS | Version |
| Windows 10 | VERSION |

**Comment by irbrownie** [comment]
I also attempted this with lerna 3 and had the same issue.

**Comment by irbrownie** [comment]
Is it possible that we can choose to ignore .symlink files if we are on windows?

**Comment by evocateur** [comment]
I'm a little confused why the globstars (`**`) are necessary in your `packages` config? Recursively nesting `package.json` files is a bit odd when they're rooted in subdirectories already.

(There's no strict requirement for the `packages` directory to exist in the path, either, but that's orthogonal)
