### ISSUE TITLE
Lerna Publish Command Failed

### ISSUE THREAD

**Issue by mjgchase** [lerna/lerna#1674]
## Expected Behavior

Package Should publish

## Current Behaviour
Tried to publish, results below
lerna ERR! Error: Command failed: git rev-list --left-right --count origin/master...master
lerna ERR! fatal: ambiguous argument 'origin/master...master': unknown revision or path not in the working tree.
lerna ERR! Use '--' to separate paths from revisions, like this:
lerna ERR! 'git <command> [<revision>...] -- [<file>...]'

## Steps to Reproduce (for bugs)

1.Create a lerna repo
2.Add first package
3.lerna boostrap
4.lerna publish

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
12 error Error: Command failed: git rev-list --left-right --count origin/master...master
12 error fatal: ambiguous argument 'origin/master...master': unknown revision or path not in the working tree.
12 error Use '--' to separate paths from revisions, like this:
12 error 'git <command> [<revision>...] -- [<file>...]'
12 error
12 error
12 error     at makeError (/home/matt/mcjb-projects/mcjb-nexus/node_modules/execa/index.js:174:9)
12 error     at Function.module.exports.sync (/home/matt/mcjb-projects/mcjb-nexus/node_modules/execa/index.js:338:15)
12 error     at Object.execSync (/home/matt/mcjb-projects/mcjb-nexus/node_modules/@lerna/child-process/index.js:22:16)
12 error     at countLeftRight (/home/matt/mcjb-projects/mcjb-nexus/node_modules/@lerna/version/lib/is-behind-upstream.js:30:31)
12 error     at isBehindUpstream (/home/matt/mcjb-projects/mcjb-nexus/node_modules/@lerna/version/lib/is-behind-upstream.js:14:27)
12 error     at VersionCommand.initialize (/home/matt/mcjb-projects/mcjb-nexus/node_modules/@lerna/version/index.js:109:7)

## Your Environment
git  2.17.1
npm  6.4.1
node 10.9.0
lerna 3.3.2
linux mint 19

**Comment by swashata** [comment]
Just FYI, I had a very similar issue. I `copy-pasta` some code for `lerna.json`, without realizing what it was doing. I had set `command.publish.gitRemote` as `upstream` instead of `origin` (my setup).

Maybe it will help someone in need.

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.1",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "registry": "https://registry.npmjs.org/",
  "command": {
    "publish": {
      "allowBranch": "master",
      "conventionalCommits": true,
      "gitRemote": "origin",
      "message": "chore(release): publish %s"
    }
  }
}
```
