### ISSUE TITLE
Unexpected behavior working with git submodules lerna version

### ISSUE THREAD

**Issue by wellyal** [lerna/lerna#1776]
I have added submodule projects on my lerna project. When I've tried to `lerna version` I was asked to select which version I wanted to be updated for (major, minor etc) for each project. Then when I've finished I got an error

## Expected Behavior
Update all versions on my submodules with no error

## Current Behavior
The versions gets updated on my submodules but an error pops up

## Steps to Reproduce (for bugs)
1. lerna init --independent
2. add git submodules to packages folder
3. lerna version from root folder

<details><summary>lerna.json</summary><p>

```json
{
  "name": "root",
  "private": true,
  "devDependencies": {
    "lerna": "^3.4.3"
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
silly gitAdd [ '/Users/wellyngton.leitao/Easynvest/lerna-portal-bootstrap/packages/easynvest.client.easguide/package.json',
23 silly gitAdd   '/Users/wellyngton.leitao/Easynvest/lerna-portal-bootstrap/packages/easynvest.client.commons/package.json',
23 silly gitAdd   '/Users/wellyngton.leitao/Easynvest/lerna-portal-bootstrap/packages/easynvest.client.stalker/package.json',
23 silly gitAdd   '/Users/wellyngton.leitao/Easynvest/lerna-portal-bootstrap/packages/easynvest.client.settings/package.json',
23 silly gitAdd   '/Users/wellyngton.leitao/Easynvest/lerna-portal-bootstrap/packages/easynvest.client.investments/package.json',
23 silly gitAdd   '/Users/wellyngton.leitao/Easynvest/lerna-portal-bootstrap/packages/easynvest.client.registry/package.json' ]
24 error Error: Command failed: git add -- packages/easynvest.client.easguide/package.json packages/easynvest.client.commons/package.json packages/easynvest.client.stalker/package.json packages/easynvest.client.settings/package.json packages/easynvest.client.investments/package.json packages/easynvest.client.registry/package.json
24 error fatal: Pathspec 'packages/easynvest.client.commons/package.json' is in submodule 'packages/easynvest.client.commons'
24 error
24 error     at makeError (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:174:9)
24 error     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:278:16)

<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.10.1 |
| `node --version` | v11.1.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.6 |

**Comment by evocateur** [comment]
Git submodules are not supported by lerna, sorry.
