### ISSUE TITLE
Remove duplicate lerna error logs?

### ISSUE THREAD

**Issue by yifanyang** [lerna/lerna#1790]
Our project consists of 20+ packages, and we are using lerna to parallelly execute npm test command in each individual package. However if some tests in one package failed, the same error logs are printed to stdout multiple times by lerna, which causes some confusion for us when debugging a problem. 

## Current Behavior

Here is an [example log](https://travis-ci.org/firebase/firebase-js-sdk/jobs/452183556) from one of our Travis runs where lerna duplicated the same error log multiple times. The skeleton of the log output:
```
[========== test setup ==========]

$ lerna run --parallel test
lerna info version 2.10.1
lerna info versioning independent
lerna info run in 26 package(s): npm run test

[========== calling npm test script in all packages ==========]
[========== interleaved test logs from all packages starts to display ==========]

[========== here a test case from @firebase/testing package failed: ==========]
@firebase/testing:   Testing Module Tests
@firebase/testing:     ✓ assertSucceeds() iff success
@firebase/testing:     ✓ assertFails() iff failure
@firebase/testing:     ✓ initializeTestApp() with auth=null does not set access token (194ms)
@firebase/testing:     ✓ initializeTestApp() with auth sets the correct access token (179ms)
@firebase/testing:     ✓ initializeAdminApp() sets the access token to "owner"
@firebase/testing:     ✓ loadDatabaseRules() throws if no databaseName or rules (42ms)
firebase-browserify-test: $ karma start --single-run
@firebase/testing:     ✓ loadDatabaseRules() tries to make a network request (579ms)
@firebase/testing:     ✓ loadFirestoreRules() succeeds on valid input (318ms)
@firebase/testing:     1) apps() returns apps created with initializeTestApp
@firebase/testing:     ✓ there is a way to get database timestamps
@firebase/testing:     ✓ there is a way to get firestore timestamps
@firebase/testing:   10 passing (3s)
@firebase/testing:   1 failing
@firebase/testing:   1) Testing Module Tests
@firebase/testing:        apps() returns apps created with initializeTestApp:
@firebase/testing:      Error: auth must be an object with a 'sub' or 'uid' field
@firebase/testing:       at createUnsecuredJwt (src/api/index.ts:67:11)
@firebase/testing:       at Object.initializeTestApp (src/api/index.ts:90:20)
@firebase/testing:       at Context.<anonymous> (test/database.test.ts:120:20)
@firebase/testing:       at step (/home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:133:27)
@firebase/testing:       at Object.next (/home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:114:57)
@firebase/testing:       at /home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:107:75
@firebase/testing:       at new Promise (<anonymous>)
@firebase/testing:       at Object.__awaiter (/home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:103:16)
@firebase/testing:       at Context.<anonymous> (test/database.test.ts:190:24)
@firebase/testing: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@firebase/testing: error Command failed with exit code 1.

[========== same error logs prefixed with 'lerna ERR!': ==========]
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run test
lerna ERR! (node:8868) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
lerna ERR! error Command failed with exit code 1.
lerna ERR! 
lerna ERR! $ TS_NODE_CACHE=NO nyc --reporter lcovonly -- mocha 'test/{,!(browser)/**/}*.test.ts' --require ts-node/register/type-check --retries 5 --timeout 5000 --exit
lerna ERR! 
lerna ERR! 
lerna ERR!   Testing Module Tests
lerna ERR!     ✓ assertSucceeds() iff success
lerna ERR!     ✓ assertFails() iff failure
lerna ERR!     ✓ initializeTestApp() with auth=null does not set access token (194ms)
lerna ERR!     ✓ initializeTestApp() with auth sets the correct access token (179ms)
lerna ERR!     ✓ initializeAdminApp() sets the access token to "owner"
lerna ERR!     ✓ loadDatabaseRules() throws if no databaseName or rules (42ms)
lerna ERR!     ✓ loadDatabaseRules() tries to make a network request (579ms)
lerna ERR!     ✓ loadFirestoreRules() succeeds on valid input (318ms)
lerna ERR!     1) apps() returns apps created with initializeTestApp
lerna ERR!     ✓ there is a way to get database timestamps
lerna ERR!     ✓ there is a way to get firestore timestamps
lerna ERR! 
lerna ERR! 
lerna ERR!   10 passing (3s)
lerna ERR!   1 failing
lerna ERR! 
lerna ERR!   1) Testing Module Tests
lerna ERR!        apps() returns apps created with initializeTestApp:
lerna ERR!      Error: auth must be an object with a 'sub' or 'uid' field
lerna ERR!       at createUnsecuredJwt (src/api/index.ts:67:11)
lerna ERR!       at Object.initializeTestApp (src/api/index.ts:90:20)
lerna ERR!       at Context.<anonymous> (test/database.test.ts:120:20)
lerna ERR!       at step (/home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:133:27)
lerna ERR!       at Object.next (/home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:114:57)
lerna ERR!       at /home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:107:75
lerna ERR!       at new Promise (<anonymous>)
lerna ERR!       at Object.__awaiter (/home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:103:16)
lerna ERR!       at Context.<anonymous> (test/database.test.ts:190:24)
lerna ERR! 
lerna ERR! 
lerna ERR! 
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/home/travis/build/firebase/firebase-js-sdk/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>

[========== other tests continue to run ==========]

[========== same error logs duplicated for another two times in this error object: ==========]
{ Error: Command failed: yarn run test
(node:8868) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
error Command failed with exit code 1.
$ TS_NODE_CACHE=NO nyc --reporter lcovonly -- mocha 'test/{,!(browser)/**/}*.test.ts' --require ts-node/register/type-check --retries 5 --timeout 5000 --exit
  Testing Module Tests
    ✓ assertSucceeds() iff success
    ✓ assertFails() iff failure
    ✓ initializeTestApp() with auth=null does not set access token (194ms)
    ✓ initializeTestApp() with auth sets the correct access token (179ms)
    ✓ initializeAdminApp() sets the access token to "owner"
    ✓ loadDatabaseRules() throws if no databaseName or rules (42ms)
    ✓ loadDatabaseRules() tries to make a network request (579ms)
    ✓ loadFirestoreRules() succeeds on valid input (318ms)
    1) apps() returns apps created with initializeTestApp
    ✓ there is a way to get database timestamps
    ✓ there is a way to get firestore timestamps
  10 passing (3s)
  1 failing
  1) Testing Module Tests
       apps() returns apps created with initializeTestApp:
     Error: auth must be an object with a 'sub' or 'uid' field
      at createUnsecuredJwt (src/api/index.ts:67:11)
      at Object.initializeTestApp (src/api/index.ts:90:20)
      at Context.<anonymous> (test/database.test.ts:120:20)
      at step (/home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:133:27)
      at Object.next (/home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:114:57)
      at /home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:107:75
      at new Promise (<anonymous>)
      at Object.__awaiter (/home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:103:16)
      at Context.<anonymous> (test/database.test.ts:190:24)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    at Promise.all.then.arr (/home/travis/build/firebase/firebase-js-sdk/node_modules/lerna/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  code: 1,
  killed: false,
  stdout: '$ TS_NODE_CACHE=NO nyc --reporter lcovonly -- mocha \'test/{,!(browser)/**/}*.test.ts\' --require ts-node/register/type-check --retries 5 --timeout 5000 --exit\n\n\n  Testing Module Tests\n    ✓ assertSucceeds() iff success\n    ✓ assertFails() iff failure\n    ✓ initializeTestApp() with auth=null does not set access token (194ms)\n    ✓ initializeTestApp() with auth sets the correct access token (179ms)\n    ✓ initializeAdminApp() sets the access token to "owner"\n    ✓ loadDatabaseRules() throws if no databaseName or rules (42ms)\n    ✓ loadDatabaseRules() tries to make a network request (579ms)\n    ✓ loadFirestoreRules() succeeds on valid input (318ms)\n    1) apps() returns apps created with initializeTestApp\n    ✓ there is a way to get database timestamps\n    ✓ there is a way to get firestore timestamps\n\n\n  10 passing (3s)\n  1 failing\n\n  1) Testing Module Tests\n       apps() returns apps created with initializeTestApp:\n     Error: auth must be an object with a \'sub\' or \'uid\' field\n      at createUnsecuredJwt (src/api/index.ts:67:11)\n      at Object.initializeTestApp (src/api/index.ts:90:20)\n      at Context.<anonymous> (test/database.test.ts:120:20)\n      at step (/home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:133:27)\n      at Object.next (/home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:114:57)\n      at /home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:107:75\n      at new Promise (<anonymous>)\n      at Object.__awaiter (/home/travis/build/firebase/firebase-js-sdk/node_modules/tslib/tslib.js:103:16)\n      at Context.<anonymous> (test/database.test.ts:190:24)\n\n\n\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: '(node:8868) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead\nerror Command failed with exit code 1.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run test',
  timedOut: false,
  exitCode: 1 }
```
The error logs are confusing especially when the stdout and stderr contains more lines. For example: [here](https://travis-ci.org/firebase/firebase-js-sdk/jobs/452223646) 'stdout' contains thousands of lines, and it gets duplicated 4 times. This makes it hard for us to locate and identify the problem.

## Expected Behavior

Cleaner error logs in some way?

## Possible Solution

I might be missing use cases where it's necessary to output same error information multiple times. But in our situation, duplicated logs are useless and confusing. Is it possible to provide a way for user to control the verbosity of lerna error message?

I'd be happy to discuss more use cases or contribute to this effort if you think it's a good idea.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.10.1 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.10.1 |
| `node --version` | 8.12.0 |

**Comment by mnutt** [comment]
We're running into this issue too, and it causes Travis CI to truncate the logs since `stdout` is very long and gets repeated by lerna. The source of the duplicates are here:

https://github.com/lerna/lerna/blob/436cfe1/core/command/lib/log-package-error.js#L10-L18

Would it be worth considering having this logging controlled by the loglevel? The desire would be to have a loglevel that produced stdout/stderr while streaming the commands, but didn't log the entire stdout/stderr when reporting errors.

**Comment by mnutt** [comment]
Hey @evocateur, I'm curious if you'd accept a PR to turn the logging down? Our use case is pretty similar to the one above, where we have a number of projects in a monorepo and use `lerna` with `--since` to only run tests on projects that have changed between commits. There's a fair amount of stdout, which lerna ends up duplicating if any test fails.

**Comment by evocateur** [comment]
@mnutt I don't want to turn lerna into a general purpose error log parser, so I'm not really sure where this needs to happen. Controlling the linked output by loglevel sounds like a good start.
