### ISSUE TITLE
[Feature]: scope by package folder

### ISSUE THREAD

**Issue by veeramarni** [lerna/lerna#1840]
## Expected Behavior

Same as "`--scope`" except it (ex. `lerna exec`) only runs based on the package folder selected. For example
"`--scope-dir [packages/*, modules/*]`". If we have multiple folders defined like below

`lerna.json`
```
{
  "packages": [
    "packages/*",
    "servers/*",
    "packages-modules/**",
}
```

It is very useful when we have large repo and we can choose some packages to run `lerna exec` like `watch` when we work on those packages specificially.

## Current Behavior

There is no filtering by `packages` defined. Only option is by customizing the packages name and using something like `--scope packages-*`. This would force the users to change the packages names just to make the scope to work.

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
I am certainly sympathetic to using directory globs as filter arguments; I even added it to `lerna add` as trailing variadic positional arguments because I wanted to use it so badly. I'd rather it was a positional argument instead of a flag, but that decision largely depends on the current semantics of a given command.

The devil, as always, is in the details. I don't think this ability should be extended to _all_ subcommands. What commands _specifically_ do you want this directory glob filtering available to?

**Comment by veeramarni** [comment]
As mentioned, I would like to run `watch` only for the packages in one or two directories where I will be changing the code. 

For example: instead of running `webpack` watch in all the packages.
`lerna exec --stream --parallel -- webpack --watch`  running for all 99 packages, I want to run on 

I would like it to run on fewer packages based on the directory.
`lerna exec --scope-dir [packages/*, modules/*] --stream --parallel -- webpack --watch` so it would be limited to 10 packages.

Let me know if it makes sense.

**Comment by evocateur** [comment]
Why not just run webpack directly on those paths? It seems rather convoluted to do it with lerna.

**Comment by veeramarni** [comment]
I mean, not just specific to `webpack`, within lerna to filter packages directories. But if you have a suggestion for `webpack` as a temporary workaround would be great.
Currently, we GC errors when we have `watch` running on 28 packages.

watch: `lerna exec --no-sort --ignore *server --stream --parallel -- webpack --watch`

```
lerna ERR! <--- JS stacktrace --->
lerna ERR!
lerna ERR! ==== JS stack trace =========================================
lerna ERR!
lerna ERR!     0: ExitFrame [pc: 0x321b8b0dbe3d]
lerna ERR!     1: StubFrame [pc: 0x321b8b08d40b]
lerna ERR!     2: ConstructFrame [pc: 0x321b8b08cfa3]
lerna ERR! Security context: 0x1ed92019e6e1 <JSObject>
lerna ERR!     3: /* anonymous */ [0x1ed99e249c89] [/Users/test-project/node_modules/acorn/dist/acorn.js:~2058] [pc=0x321b8bbf1f8f](this=0x1ed9225acc59 <Parser map = 0x1ed90883ae89>,base=0x1ed90fb86a89 <Node map =...
lerna ERR!
lerna ERR!
lerna ERR!     at makeError (/Users/test-project/node_modules/@lerna/child-process/node_modules/execa/index.js:174:9)
lerna ERR!     at Promise.all.then.arr (/Users/test-project/node_modules/@lerna/child-process/node_modules/execa/index.js:278:16)
lerna WARN complete Waiting for 28 child processes to exit. CTRL-C to exit immediately.
lerna ERR! lerna Command failed: webpack --watch
lerna ERR! lerna FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

```

**Comment by evocateur** [comment]
I'm not a webpack expert, but it should be possible to use `@lerna/project`'s `getPackages()` export in your root `webpack.config.js` to identify all the entry points and configure their respective outputs. Or use [Pectin](https://github.com/evocateur/pectin#getting-started) (my preference vs webpack for building packages), which incidentally demonstrates [how to locate Lerna-managed packages and sort them topologically](https://github.com/evocateur/pectin/blob/166c29deda38d457f454c9b3cf04b04d286e16ef/packages/pectin-api/lib/pectin-api.js#L25-L28).

**Comment by damienwebdev** [comment]
@evocateur just add an additional use-case here, when I'm doing:

```bash
lerna run [scriptName]
```

I often find myself having to overcomplicate my scriptNames in my packages in order to be able to separate them according.

Generically, in my project I have "packages" and "apps". Sometimes I only want to build packages, and sometimes only apps, but I end up doing the following in my packages, due to this limitation:

```json
{
...
  scripts: {
    "build": "dowhatever",
    "build:packages": "dowhatever",
  }
...
}
```

Having this feature would make my life easier.

**Comment by 0gust1** [comment]
We have a similar need. I posted my use case in the thread of #1937 

Thanks for the alternates tips, btw !

**Comment by damienwebdev** [comment]
@evocateur I'd be willing to pick this up. This is how I'd plan to implement it in `filter-options`:

```js
lerna COMMAND --packages="packages/*,servers/*, packages-modules/**"
```

This would add support to all commands that support `filter-options`, and I think be the most obvious. Clearly, this would be overriding the `packages` flag in `lerna.json`, but I think it is a fairly obvious choice. If you don't see any issue with this, I can get started on this.

**Comment by jure** [comment]
Our use case is that we have packages neatly separated into e.g. `packages/server/*` and `packages/client/*`, and we'd like to run a build step using `lerna exec` only for the client components. The package names don't reflect their client or server nature, they're merely e.g. `@namespace/component-x`, so filtering by package name isn't useful.

**Comment by RecuencoJones** [comment]
Our use case is similar to @damienwebdev and @jure, we have some libraries which have deliverable packages, example directories and sometimes applications.

We'd love to be able to have our scripts somehow like this:

```
  "scripts": {
    "setup": "npm run lerna:init && npm run lerna:bootstrap",
    "lerna:init": "lerna init",
    "lerna:bootstrap": "lerna bootstrap --scope 'packages/*' --no-ci",
    "lerna:exec": "lerna exec",
    "lerna:publish": "lerna exec --scope 'packages/*' -- safe-publish",
    "reinstall:examples": "lerna bootstrap --scope 'examples/*' --no-ci",
    "run:examples": "lerna exec --scope 'examples/*' npm run all",
    "lint": "eslint scripts packages",
    "examples": "npm run reinstall:examples && npm run run:examples"
  },
```

**Comment by loopmode** [comment]
Due to this shortcoming I've used awkward naming conventions in a couple of projects already, e.g. `@client/` and `@server/` package scopes etc, just for the sake of control via lerna `--scope`.
This can become bulky, tedious or unmaintainable quickly, depending on the project's requirements.

A filesystem-based filter option (presumably glob) would help a lot. Feels like a missing standard feature somehow :)

**Comment by luxaritas** [comment]
Tagging on - would love to `lerna run` based off of a package directory for similar reasons - there are some directories that only have "library" packages, one with client packages, one with server packages, etc. Would love not to have to prefix all my server packages with `server-` or whatnot in order to run them all in one go.

**Comment by jamiter** [comment]
@damienwebdev, did you ever had the opportunity to implement your proposal? It seems like a nice approach to just overrule the packages definition.

FYI, we're using the same approach of having apps and packages.

**Comment by FrozenKiwi** [comment]
@evocateur @damienwebdev Is/has anyone worked on this?  It seems fairly straight-forward - correct me if I'm wrong, but adding the filter to https://github.com/lerna/lerna/blob/6cb8ab2d4af7ce25c812e8fb05cd04650105705f/utils/filter-packages/filter-packages.js#L22:10 doesn't seem awfully difficult (as long as your ok with adding the path to pkg itself - from what i can tell that info is not passed along with the pkg object).

**Comment by FrozenKiwi** [comment]
I would lean towards using --scope-path instead of --packages: simply because scope is the related option (so more likely to be googled).

**Comment by arminrosu** [comment]
In case ends up here from Google - this is a workaround I am using:

```bash
lerna run build --scope={$(lerna list --all --parseable --toposort --long | grep -E -- 'packages/|modules/' | sed -E "s/[^:]+:([^:]+).+/\1/" | paste -d , -s -)}
```

**Where:**

```bash
lerna list --all --parseable --toposort --long
```

Lists all packages, with directory paths, package name and version. E.g.:

```bash
/Users/gulliver/example-repo/packages/axios:axios:0.21.0
/Users/gulliver/example-repo/modules/lodash:lodash:4.17.0:PRIVATE
/Users/gulliver/example-repo/utils/typescript:typescript:4.0.0
```

---

```bash
grep -E -- 'packages/|modules/'
```

Filters the output to include `packages/` or `modules/`, e.g.:

```bash
/Users/gulliver/example-repo/packages/axios:axios:0.21.0
/Users/gulliver/example-repo/modules/lodash:lodash:4.17.0:PRIVATE
```

---

```bash
sed -E "s/[^:]+:([^:]+).+/\1/" 
```

Get the package name from the output using a regexp. E.g.:

```bash
axios
lodash
```

---

```bash
paste -d , -s -
```

Concatenate the lines into a single string separated by `,` with no trailing `,`. E.g.:

```
axios,lodash
```

---

```bash
lerna run build --scope={axios,lodash}
```

Runs `build` in every package matching the `{axios,lodash}` glob, which is essentially a list of packages, since there are no wildcards.

---

Hope that helps, and sorry for the wrong explanation, I hope it's not adding noise to the existing conversation.

**Comment by 3rd-Eden** [comment]
Going to add +1 to this feature, my specific use-case is running migration, codemods, or other sorts of automation against a specific set of packages e.g. `packages/components/**`. While you can get away with the awful CLI hack that is posted above, this really is functionality that should be baked into the project. 

Other monorepo supported tools such as [pnpm already allow `./directory` as part of their filter syntax](https://medium.com/pnpm/pnpm-vs-lerna-filtering-in-a-multi-package-repository-1f68bc644d6a).

**Comment by SebTVisage** [comment]
Any news on this? This feature is really lacking for us since our mono-repo have a frontend & backend folder. Most of the time we want to bulk `lerna run` for all projects under one of these folder.

As @3rd-Eden mentioned this is supported by pnpm for years already. And I'd use pnpm run instead of lerna run, but the output is much more readable from lerna.
