### ISSUE TITLE
lerna run fails with UnhandledPromiseRejectionWarning: TypeError: entry.isFile is not a function

### ISSUE THREAD

**Issue by tyler-johnson** [lerna/lerna#1850]
Seems like a recent update to fast-glob (https://github.com/mrmlnc/fast-glob/releases/tag/2.2.5) broke something in the run command. Not really sure who to pin this on, so I am starting here. Issue is probably some where else in the dependency chain.

Any calls to `lerna run` fail with:

```
node:3170) UnhandledPromiseRejectionWarning: TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/Users/tyler/Development/pagedip-apps/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/Users/tyler/Development/pagedip-apps/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /Users/tyler/Development/pagedip-apps/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /Users/tyler/Development/pagedip-apps/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.8.5 |
| `npm --version`  | 6.5.0 |
| `yarn --version` | 1.12.3 |
| `node --version` | 11.5.0 |

**Comment by GuyMograbi** [comment]
@evocateur  I am installing lerna globally. 
How can I use lockfiles?? is lerna using lockfiles? 

Why is this bug closed?

**Comment by evocateur** [comment]
Lerna does not control `fast-glob`, thus there is nothing for Lerna to do in this situation.

You shouldn't install lerna globally, there's no need. It should only be in local `devDependencies`, just like any other dev tool (`eslint`, `jest`, etc).

Yes, I realize the website tells you to do just that. It should be updated to remove that recommendation. PRs welcome.
