### ISSUE TITLE
lerna bootstrap fails but npm install still works

### ISSUE THREAD

**Issue by jamesparker01** [lerna/lerna#1914]
We have a library of components, that seem to fail randomly fail to build.

## Expected Behavior

`lerna bootstrap` installs the packages correctly

## Current Behavior

`lerna bootstrap` fails with the following debug.log

```
688 timing audit body Completed in 1ms
689 silly lifecycle @organisation/package-name@1.0.0~install: Returned: code: 1  signal: null
690 info lifecycle @organisation/package-name@1.0.0~install: Failed to exec install script
691 verbose stack Error: @organisation/package-name@1.0.0 install: `cd ../ && lerna bootstrap`
691 verbose stack Exit status 1
691 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
691 verbose stack     at EventEmitter.emit (events.js:197:13)
691 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
691 verbose stack     at ChildProcess.emit (events.js:197:13)
691 verbose stack     at maybeClose (internal/child_process.js:978:16)
691 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
692 verbose pkgid @organisation/package-name@1.0.0
693 verbose cwd C:\code\src\components\package-name
694 verbose Windows_NT 10.0.17134
695 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
696 verbose node v11.8.0
697 verbose npm  v6.5.0
698 error code ELIFECYCLE
699 error errno 1
700 error @organisation/package-name@1.0.0 install: `cd ../../ && lerna bootstrap`
700 error Exit status 1
701 error Failed at the @organisation/package-name@1.0.0 install script.
701 error This is probably not a problem with npm. There is likely additional logging output above.
702 verbose exit [ 1, true ]
```

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "packages": [
    "components/*"
  ],
  "version": "independent"
}
```
</p></details>

<details><summary>package.json</summary><p>

```json
{
  "name": "@organisation/package-name",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "neutrino build",
    "start": "neutrino start",
    "test": "neutrino test",
    "install": "cd ../ && lerna bootstrap"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.18.0",
    "react": "^16.6.0",
    "react-dom": "^16.6.0",
    "react-hot-loader": "^4.3.11",
    "victory": "^31.2.0"
  },
  "devDependencies": {
    "@neutrinojs/react": "^8.3.0",
    "babel-eslint": "^10.0.1",
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.6.0",
    "eslint": "^5.9.0",
    "eslint-plugin-jest": "^22.1.2",
    "eslint-plugin-json": "^1.3.2",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-react": "^7.11.1",
    "neutrino": "^8.3.0",
    "prop-types": "^15.6.2",
    "raf": "^3.4.1"
  }
}
```
</p></details>

## Context

We are unable to use lerna in this project, and may have to find a new solution.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.10.7 |
| `npm --version`  | 6.5.0 |
| `node --version` | v11.8.0 |

| OS | Version |
| --- | --- |
| Windows 10 | 1803 |

**Comment by evocateur** [comment]
You shouldn't have an `install` script in _any_ package. The only place you'd need `lerna bootstrap` would be a `prepare` script in the root, for example. Also, you should move all your devDependencies to the root (where you also presumably have lerna installed).

**Comment by kylegoetz** [comment]
>Also, you should move all your devDependencies to the root (where you also presumably have lerna installed).

What does that mean? I cloned a repo, ran `lerna bootstrap`, and all the packages were installed in the sub-package `node_modules` paths.
