### ISSUE TITLE
Error publishing - git tags pushed

### ISSUE THREAD

**Issue by MMT-LD** [lerna/lerna#1917]
Pushing to private verdaccio worked 7 days ago using same lerna and repo... but when committed, and lerna publish ran, git tags were pushed and then an error occurred. I now can't publish even after i manually change the readme for my package to bump up the number. I get the same error (current behaviour below).
## Expected Behavior
Publish to private verdaccio

## Current Behavior
lerna http fetch PUT 500 <private verdaccio url> 70776ms attempt #3
lerna ERR! Error: 500 Internal Server Error - PUT <private verdaccio url>
lerna ERR!     at res.buffer.catch.then.body (/Users/<name>/projects/packages/node_modules/npm-registry-fetch/check-response.js:104:15)
lerna ERR! lerna 500 Internal Server Error - PUT <private verdaccio>

## Possible Solution
Not sure how to publish to verdaccio

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "lerna": "3.4.1",
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "allowBranch": "master",
      "conventionalCommits": true,
      "message": "chore(release): updated release notes and package versions"
    }
  }
}
```
</p></details>

## Context
i basically need to push my package to private verdaccio that would be great

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.11.0 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.9.4 |
| `node --version` | v10.15.1 |

| OS | macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
Since the version of Lerna you're reporting didn't exist 7 days ago, I'm going to assume it was a different version of lerna, and quite possibly the underlying `npm-registry-fetch` library. Can you verify that for me, please?

As for publishing to the registry:

* If _none_ of the packages published successfully, but the git changes and tags were pushed, you can use this command to recover:
  
  ```
  npx lerna publish from-git
  ```

* If _some_ of the packages successfully published during the initial `lerna publish`, you can use this command to publish the remaining:
  
  ```
  npx lerna publish from-package
  ```

If possible, I would also appreciate a full `lerna-debug.log`, if you have it. Thanks.

**Comment by MMT-LD** [comment]
```
0 silly argv { _: [ 'publish' ],
0 silly argv   registry: '<registry-url>',
0 silly argv   composed: 'publish',
0 silly argv   lernaVersion: '3.10.6',
0 silly argv   '$0': 'lerna' }
1 notice cli v3.10.6
2 verbose rootPath /Users/<user>/projects/packages
3 info versioning independent
4 verbose session 1f26a92fc008a75c
5 verbose user-agent lerna/3.10.6/node@v10.15.1+x64 (darwin)
6 verbose git-describe undefined => "<package-name>@1.5.5-1-gdcba2ad"
7 silly git-describe parsed => {"lastTagName":"<package-name>@1.5.5","lastVersion":"1.5.5","refCount":"1","sha":"dcba2ad","isDirty":false}
8 silly argv { _: [ 'publish' ],
8 silly argv   registry: '<registry-url>',
8 silly argv   composed: 'publish',
8 silly argv   lernaVersion: '3.10.6' }
9 verbose rootPath /Users/<user>/projects/packages
10 silly isAnythingCommitted
11 verbose isAnythingCommitted 1
12 silly currentBranch
13 verbose currentBranch master
14 silly remoteBranchExists
15 silly isBehindUpstream
16 silly isBehindUpstream master is behind origin/master by 0 commit(s) and ahead by 0
17 silly hasTags
18 verbose hasTags true
19 silly git-describe.sync "<package-name>@1.5.5-1-gdcba2ad" => {"lastTagName":"<package-name>@1.5.5","lastVersion":"1.5.5","refCount":"1","sha":"dcba2ad","isDirty":false}
20 info Looking for changed packages since <package-name>@1.5.5
21 silly diffSinceIn <package-name>@1.5.5 <package-url>
22 silly diff <package-url>/README.md
23 silly diffSinceIn <package-name>@1.5.5 packages/<path>
24 silly diff packages/<path>/README.md
25 verbose updated <package-name>
26 verbose updated <package-name>
27 verbose git-describe undefined => "<package-name>@1.5.5-1-gdcba2ad"
28 silly git-describe parsed => {"lastTagName":"<package-name>@1.5.5","lastVersion":"1.5.5","refCount":"1","sha":"dcba2ad","isDirty":false}
29 silly independent for <package-name> at /Users/<user>/projects/packages/<package-url>
30 verbose independent increment 1.5.5 by patch
31 silly independent for <package-name> at /Users/<user>/projects/packages/packages/<path>
32 verbose independent increment 1.4.5 by patch
33 silly batched [ PackageGraphNode {
33 silly batched     name: '<package-name>',
33 silly batched     externalDependencies:
33 silly batched      Map {
33 silly batched        '@babel/plugin-syntax-dynamic-import' => [Object],
33 silly batched        '@storybook/addon-actions' => [Object],
33 silly batched        '@storybook/addon-console' => [Object],
33 silly batched        '@storybook/addon-links' => [Object],
33 silly batched        '@storybook/addon-options' => [Object],
33 silly batched        '@storybook/addon-storysource' => [Object],
33 silly batched        '@storybook/addon-viewport' => [Object],
33 silly batched        '@storybook/react' => [Object],
33 silly batched        'babel-jest' => [Object],
33 silly batched        'babel-loader' => [Object],
33 silly batched        'babel-plugin-emotion' => [Object],
33 silly batched        'babel-plugin-inline-react-svg' => [Object],
33 silly batched        'babel-plugin-transform-es2015-modules-commonjs' => [Object],
33 silly batched        'babel-plugin-transform-object-rest-spread' => [Object],
33 silly batched        'enzyme' => [Object],
33 silly batched        'enzyme-adapter-react-16' => [Object],
33 silly batched        'eslint-plugin-emotion' => [Object],
33 silly batched        'glob-loader' => [Object],
33 silly batched        'identity-obj-proxy' => [Object],
33 silly batched        'jest' => [Object],
33 silly batched        'jest-prop-type-error' => [Object],
33 silly batched        'prettier' => [Object],
33 silly batched        'react-test-renderer' => [Object],
33 silly batched        'rimraf' => [Object],
33 silly batched        'storybook-addon-jsx' => [Object],
33 silly batched        '@babel/polyfill' => [Object],
33 silly batched        '@emotion/core' => [Object],
33 silly batched        '@emotion/styled' => [Object],
33 silly batched        '@stst-cs/design-system' => [Object],
33 silly batched        'deepmerge' => [Object],
33 silly batched        'emotion' => [Object],
33 silly batched        'emotion-server' => [Object],
33 silly batched        'emotion-theming' => [Object],
33 silly batched        'lodash.flowright' => [Object],
33 silly batched        'lodash.get' => [Object],
33 silly batched        'prop-types' => [Object],
33 silly batched        'react' => [Object],
33 silly batched        'react-dom' => [Object],
33 silly batched        'react-emotion' => [Object] },
33 silly batched     localDependencies: Map {},
33 silly batched     localDependents: Map { '<package-name>' => [PackageGraphNode] } } ]
34 silly batched [ PackageGraphNode {
34 silly batched     name: '<package-name>',
34 silly batched     externalDependencies:
34 silly batched      Map {
34 silly batched        '@babel/plugin-syntax-dynamic-import' => [Object],
34 silly batched        '@storybook/addon-actions' => [Object],
34 silly batched        '@storybook/addon-console' => [Object],
34 silly batched        '@storybook/addon-links' => [Object],
34 silly batched        '@storybook/addon-options' => [Object],
34 silly batched        '@storybook/addon-storysource' => [Object],
34 silly batched        '@storybook/addon-viewport' => [Object],
34 silly batched        '@storybook/react' => [Object],
34 silly batched        'babel-jest' => [Object],
34 silly batched        'babel-loader' => [Object],
34 silly batched        'babel-plugin-emotion' => [Object],
34 silly batched        'babel-plugin-inline-react-svg' => [Object],
34 silly batched        'babel-plugin-transform-es2015-modules-commonjs' => [Object],
34 silly batched        'babel-plugin-transform-object-rest-spread' => [Object],
34 silly batched        'enzyme' => [Object],
34 silly batched        'enzyme-adapter-react-16' => [Object],
34 silly batched        'eslint-plugin-emotion' => [Object],
34 silly batched        'glob-loader' => [Object],
34 silly batched        'identity-obj-proxy' => [Object],
34 silly batched        'jest' => [Object],
34 silly batched        'jest-prop-type-error' => [Object],
34 silly batched        'prettier' => [Object],
34 silly batched        'react-test-renderer' => [Object],
34 silly batched        'rimraf' => [Object],
34 silly batched        'storybook-addon-jsx' => [Object],
34 silly batched        '@babel/polyfill' => [Object],
34 silly batched        '@emotion/core' => [Object],
34 silly batched        '@emotion/styled' => [Object],
34 silly batched        '@stst-cs/design-system' => [Object],
34 silly batched        'emotion' => [Object],
34 silly batched        'emotion-server' => [Object],
34 silly batched        'emotion-theming' => [Object],
34 silly batched        'lodash.flowright' => [Object],
34 silly batched        'lodash.get' => [Object],
34 silly batched        'prop-types' => [Object],
34 silly batched        'react' => [Object],
34 silly batched        'react-dom' => [Object],
34 silly batched        'react-emotion' => [Object] },
34 silly batched     localDependencies: Map {},
34 silly batched     localDependents: Map {} } ]
35 silly lifecycle No script for "preversion" in "packages", continuing
36 silly lifecycle No script for "preversion" in "<package-name>", continuing
37 silly lifecycle No script for "version" in "<package-name>", continuing
38 silly independent for <package-name> at /Users/<user>/projects/packages/<package-url>
39 silly independent writing new entry: "## [1.5.6](<git-url>/compare/<package-name>@1.5.5...<package-name>@1.5.6) (2019-02-08)\n\n**Note:** Version bump only for package <package-name>\n\n\n\n"
40 verbose independent wrote /Users/<user>/projects/packages/<package-url>/CHANGELOG.md
41 silly lifecycle No script for "preversion" in "<package-name>", continuing
42 silly lifecycle No script for "version" in "<package-name>", continuing
43 silly independent for <package-name> at /Users/<user>/projects/packages/packages/<path>
44 silly independent writing new entry: "## [1.4.6](<git-url>/compare/<package-name>@1.4.5...<package-name>@1.4.6) (2019-02-08)\n\n**Note:** Version bump only for package <package-name>\n\n\n\n"
45 verbose independent wrote /Users/<user>/projects/packages/packages/<path>/CHANGELOG.md
46 silly lifecycle No script for "version" in "packages", continuing
47 silly gitAdd [ '/Users/<user>/projects/packages/<package-url>/package.json',
47 silly gitAdd   '/Users/<user>/projects/packages/<package-url>/CHANGELOG.md',
47 silly gitAdd   '/Users/<user>/projects/packages/packages/<path>/package.json',
47 silly gitAdd   '/Users/<user>/projects/packages/packages/<path>/CHANGELOG.md' ]
48 silly gitCommit chore(release): updated release notes and package versions
48 silly gitCommit
48 silly gitCommit  - <package-name>@1.5.6
48 silly gitCommit  - <package-name>@1.4.6
49 verbose git [ 'commit',
49 verbose git   '-F',
49 verbose git   '/private/var/folders/p1/5cm4zjnd5yn7cc91cgpxj0j40000gp/T/7ec7afd5-1f09-444a-8ed1-fc65496bc973/lerna-commit.txt' ]
50 silly gitTag <package-name>@1.5.6
51 verbose git [ 'tag',
51 verbose git   '<package-name>@1.5.6',
51 verbose git   '-m',
51 verbose git   '<package-name>@1.5.6' ]
52 silly gitTag <package-name>@1.4.6
53 verbose git [ 'tag',
53 verbose git   '<package-name>@1.4.6',
53 verbose git   '-m',
53 verbose git   '<package-name>@1.4.6' ]
54 silly lifecycle No script for "postversion" in "<package-name>", continuing
55 silly lifecycle No script for "postversion" in "<package-name>", continuing
56 silly lifecycle No script for "postversion" in "packages", continuing
57 info git Pushing tags...
58 silly gitPush origin master
59 silly batched [ PackageGraphNode {
59 silly batched     name: '<package-name>',
59 silly batched     externalDependencies:
59 silly batched      Map {
59 silly batched        '@babel/polyfill' => [Object],
59 silly batched        '@emotion/core' => [Object],
59 silly batched        '@emotion/styled' => [Object],
59 silly batched        '@stst-cs/design-system' => [Object],
59 silly batched        'deepmerge' => [Object],
59 silly batched        'emotion' => [Object],
59 silly batched        'emotion-server' => [Object],
59 silly batched        'emotion-theming' => [Object],
59 silly batched        'lodash.flowright' => [Object],
59 silly batched        'lodash.get' => [Object],
59 silly batched        'prop-types' => [Object],
59 silly batched        'react' => [Object],
59 silly batched        'react-dom' => [Object],
59 silly batched        'react-emotion' => [Object] },
59 silly batched     localDependencies: Map {},
59 silly batched     localDependents: Map { '<package-name>' => [PackageGraphNode] } } ]
60 silly batched [ PackageGraphNode {
60 silly batched     name: '<package-name>',
60 silly batched     externalDependencies:
60 silly batched      Map {
60 silly batched        '@babel/polyfill' => [Object],
60 silly batched        '@emotion/core' => [Object],
60 silly batched        '@emotion/styled' => [Object],
60 silly batched        '@stst-cs/design-system' => [Object],
60 silly batched        'emotion' => [Object],
60 silly batched        'emotion-server' => [Object],
60 silly batched        'emotion-theming' => [Object],
60 silly batched        'lodash.flowright' => [Object],
60 silly batched        'lodash.get' => [Object],
60 silly batched        'prop-types' => [Object],
60 silly batched        'react' => [Object],
60 silly batched        'react-dom' => [Object],
60 silly batched        'react-emotion' => [Object] },
60 silly batched     localDependencies: Map {},
60 silly batched     localDependents: Map {} } ]
61 info publish Publishing packages to npm...
62 notice Skipping all user and access validation due to third-party registry
63 notice Make sure you're authenticated properly ¯\_(ツ)_/¯
64 warn ENOLICENSE Packages <package-name>, <package-name> are missing a license
65 silly getCurrentSHA
66 verbose getCurrentSHA f76ec286c6e37c991fbe93407770aa7429bc1b53
67 silly lifecycle No script for "prepublish" in "packages", continuing
68 silly lifecycle No script for "prepare" in "packages", continuing
69 silly lifecycle "prepublishOnly" starting in "packages"
70 info lifecycle packages@undefined~prepublishOnly: packages@undefined
71 verbose lifecycle packages@undefined~prepublishOnly: unsafe-perm in lifecycle true
72 verbose lifecycle packages@undefined~prepublishOnly: PATH: /Users/</user>/projects/packages/node_modules/npm-lifecycle/node-gyp-bin:/Users/<user>/projects/packages/node_modules/.bin:/Users/<user>/.nvm/versions/node/v10.15.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/munki:/opt/X11/bin
73 verbose lifecycle packages@undefined~prepublishOnly: CWD: /Users/<user>/projects/packages
74 silly lifecycle packages@undefined~prepublishOnly: Args: [ '-c', 'yarn build' ]
75 silly lifecycle packages@undefined~prepublishOnly: Returned: code: 0  signal: null
76 silly lifecycle "prepublishOnly" finished in "packages"
77 silly lifecycle No script for "prepack" in "packages", continuing
78 verbose pack-directory <package-url>
79 silly lifecycle No script for "prepublish" in "<package-name>", continuing
80 silly lifecycle No script for "prepare" in "<package-name>", continuing
81 silly lifecycle No script for "prepublishOnly" in "<package-name>", continuing
82 silly lifecycle No script for "prepack" in "<package-name>", continuing
83 silly lifecycle No script for "postpack" in "<package-name>", continuing
84 verbose packed <package-name> <package-url></package-url>
85 verbose pack-directory packages/<path>
86 silly lifecycle No script for "prepublish" in "<package-name>", continuing
87 silly lifecycle No script for "prepare" in "<package-name>", continuing
88 silly lifecycle No script for "prepublishOnly" in "<package-name>", continuing
89 silly lifecycle No script for "prepack" in "<package-name>", continuing
90 silly lifecycle No script for "postpack" in "<package-name>", continuing
91 verbose packed <package-name> packages/<path>
92 silly lifecycle No script for "postpack" in "packages", continuing
93 verbose publish <package-name>
94 http fetch PUT 500 <verdaccio-url> 70776ms attempt #3
95 error Error: 500 Internal Server Error - PUT <verdaccio url>
95 error     at res.buffer.catch.then.body (/Users/<user>/projects/packages/node_modules/npm-registry-fetch/check-response.js:104:15)

```

**Comment by evocateur** [comment]
> Im assuming i run this from the top level.

 Yes, `lerna` commands should always be run from the top-level of a monorepo (wherever the `lerna.json` is).

Verdaccio isn't being very helpful here, as a 500 gives no _reason_ why the `PUT` failed. If a local Verdaccio works, that (probably?) means your authentication for the remote Verdaccio instance is insufficient, or some other problem with the remote instance that I'm not equipped to debug.

**Comment by MMT-LD** [comment]
@evocateur thanks for your help here. Last one ... i think... ```npx lerna publish from-git``` can i run this more then once if none of the packages were published. I think i know ```npx lerna publish from-package``` can be run multiple times as this would bail if the package already lives on the registry

**Comment by evocateur** [comment]
Yep, you've got it right.

**Comment by egemon** [comment]
Sorry, so the cause was in unproper auth for verdaccio?

**Comment by evocateur** [comment]
@egemon Yes, as far as I can tell. Third-party registry support for authentication endpoints varies so wildly Lerna doesn't even bother trying.

**Comment by evocateur** [comment]
Closing due to inactivity, there's nothing Lerna can do here.
