### ISSUE TITLE
Releasing on protected branch

### ISSUE THREAD

**Issue by lukasjuhas** [lerna/lerna#1957]
Hello, thanks for a great tool.

We have a protected master branch becase we want to enforce pull requests reviewes before merging as well as prevent accidental merging to master directly.

## Expected Behavior
I would like to be able publish packages no matter if primary branch is protected

## Current Behavior
Currently, if user is not administrator, and error is thrown. 

## Possible Solution
No idea if there is any way around this, but I would appreciate suggestions on how to go around this and keep the primary branch protected.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
Are you sure you want to publish these packages? Yes
lerna info git Pushing tags...
lerna ERR! Error: Command failed: git push --follow-tags --no-verify origin master
lerna ERR! remote: error: GH006: Protected branch update failed for refs/heads/master.
lerna ERR! remote: error: At least 1 approving review is required by reviewers with write access.
lerna ERR! To https://github.com/company/repo.git
lerna ERR!  * [new tag]         @company/repo-package@0.3.6 -> @company/repo-package@0.3.6
lerna ERR!  ! [remote rejected] master -> master (protected branch hook declined)
lerna ERR! error: failed to push some refs to ‘https://github.com/company/repo.git’
lerna ERR!
lerna ERR!     at makeError (/Users/{censored}/node_modules/execa/index.js:174:9)
lerna ERR!     at Promise.all.then.arr (/Users/{censored}/node_modules/execa/index.js:278:16)
lerna ERR! Error: Command failed: git push --follow-tags --no-verify origin master
lerna ERR! remote: error: GH006: Protected branch update failed for refs/heads/master.
lerna ERR! remote: error: At least 1 approving review is required by reviewers with write access.
lerna ERR! To https://github.com/company/repo.git
lerna ERR!  * [new tag]         @company/repo-package@0.3.6 -> @company/repo-package@0.3.6
lerna ERR!  ! [remote rejected] master -> master (protected branch hook declined)
lerna ERR! error: failed to push some refs to ‘https://github.com/company/repo.git’
lerna ERR!
lerna ERR!     at makeError (/Users/{censored}/node_modules/execa/index.js:174:9)
lerna ERR!     at Promise.all.then.arr (/Users/{censored}/node_modules/execa/index.js:278:16)
lerna ERR! lerna Command failed: git push --follow-tags --no-verify origin master
lerna ERR! lerna remote: error: GH006: Protected branch update failed for refs/heads/master.
lerna ERR! lerna remote: error: At least 1 approving review is required by reviewers with write access.
lerna ERR! lerna To https://github.com/company/repo.git
lerna ERR! lerna  * [new tag]         @company/repo-package@0.3.6 -> @company/repo-package@0.3.6
lerna ERR! lerna  ! [remote rejected] master -> master (protected branch hook declined)
lerna ERR! lerna error: failed to push some refs to ‘https://github.com/company/repo.git’
lerna ERR! lerna
error Command failed with exit code 1.
```
</p></details>

## Context
I would like to be able publish packages no matter if primary branch is protected or even if user is not an Administrator of the org or repo.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.10.7 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.13.0 |
| `node --version` | v10.15.1 |

| OS | Version |
| --- | --- |
| macOS | 10.14.3  |

**Comment by kachkaev** [comment]
Hey @lukasjuhas have you found a decent workaround? I'm trying to wrap my head around this problem too.

**Comment by lukasjuhas** [comment]
Hi @kachkaev. Unfortunatelly no workaround. I tried several suggestions I found across Github but none of them are sufficient.. hoping to get some input, suggestion or possible feature here.

**Comment by kachkaev** [comment]
Thanks for your reply! What's your current approach to releasing and having branch policies? Which trade-offs did you choose in the end?

**Comment by lukasjuhas** [comment]
Bascally, because the team is quite small for now.. one of administrators of the org account publishes packages when PRs are merged to master (that's the only branch we release from). 

We have tried something along the lines of creating a "release" branch and release packages through there but then, after the branch is merge to master, lerna thinks it's a change that has not been released yet and it wants to release it again so that doesn't really work. The only way around really, is to just disable the protection.. if you can't / don't want to do that (like we do), you just get administrators of the org to release if it's possible. Hopefully someone will come up with sufficient workaround. I would love to find time and dig into this and possibly find a solution that I could submit but I cannot see this any time soon..

The main problem of protected branch is that unless you are administrator, you cannot push to master directly. That becomes a problem, when you publish packages, lerna on your behalf is trying to push to master changes in version in `package.json`. 

However, there might be actually possiblity of maintaininig version manually.. I believe there are some lerna options that allow you to do this.. e.g. you bumb version yourself.. so when releasing you are not asked to enter version.. but I can imagine this gets quite hard to maintain.. But I'm not quite sure about this 👀

**Comment by evocateur** [comment]
I would question the necessity of locking `master` first, frankly. It's not going to magically protect you from _all_ mistakes.

In any event, as long as you're willing to sacrifice the specificity that Lerna achieves through git tags, you can run `lerna version --no-git-tag-version` to prepare a PR (which will bump everything, as you've mangled the previous tags through merging), merge that PR into master, and then run `lerna publish from-package --yes` (maybe in CI? up to you), which does not make a commit or tag and publishes any local packages whose version does not exist in the configured registry.

But again, I would recommend reconsidering what you're _really_ gaining by locking `master`, given the tradeoff of losing all relevant git tags and partially-applied publishes.

**Comment by lukasjuhas** [comment]
Hi @evocateur, thank you for your input and suggestions. And of course thanks for lerna!

I do get your point. The main reason for locking `master` is to add rules such as :
> Require pull request reviews before merging When enabled, all commits must be made to a non-protected branch and submitted via a pull request with the required number of approving reviews and no changes requested before it can be merged into a branch that matches this rule. 

And

> Require status checks to pass before merging Choose which status checks must pass before branches can be merged into a branch that matches this rule. When enabled, commits must first be pushed to another branch, then merged or pushed directly to a branch that matches this rule after status checks have passed. 

The problem is, in our repo, various member of team are contributing to it, including junior staff members that are more likely to make a mistake and e.g. merge PR without a review etc. Although this would be managable, and we could always revert.. at scale this might get difficult to keep track of.

I do understand that this is not really problem of lerna but more rules and politics in our team, I was just wondering if there is a way how to keep branch protected and publish packages which I get is not possible at the moment. Now the question is, if someone would take this challenge on, is it possible to achieve this at all?

So I do think being able to lock master does make sense and is common practice, and being to publish via lerna would be a really good feature and would help other people that have been having the same issue.

Thank you

**Comment by bennypowers** [comment]
Locking master may be required for compliance reasons e.g. SOC2 compliance.

**Comment by rafalmaciejewski** [comment]
Somehow it works for semantic-release, but not for lerna. Maybe there is a solution to be found there.

**Comment by GabeL7r** [comment]
We particularly like to lock master so we can take advantage of codeowners and number of reviewers required before being able to merge.

**Comment by unional** [comment]
I gave it a try and this is still failing:
https://github.com/unional/async-fp/blob/master/.github/workflows/nodejs.yml

But based what what I understand, it should work.
The `$GITHUB_TOKEN` have write access to the repo.
https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token

I also tried using a Personal Access Token with these permissions:
![image](https://user-images.githubusercontent.com/3254987/76714001-c6f76c00-66e1-11ea-9139-45852e023f6f.png)

And it still doesn't work.

**Comment by tanjacky** [comment]
@unional I think you need to disable the `Require status checks to pass before merging` setting for your master branch.

**Comment by unional** [comment]
@tanjacky I think that's not the case. With `allow force pushes`, I can push localling directly to the `master` branch, with `Require status checks to pass before merging` remain on (this is the main point for the protected branch).

Since I can do it locally, as the same user, I should be able to do the same on CI. That's the part I don't understand.

**Comment by pwrnrd** [comment]
Thank you @lukasjuhas for creating this issue!

I'm new to Lerna and I was wondering whether the following could work as a work-around for the time being?

```bash
lerna version --no-push 
git push <MY_REMOTE> <MY_BRANCH> 
```

Subsequently you can create a PR for the branch <MY_BRANCH>.

**Comment by JamesHenry** [comment]
I don't think it's actually been confirmed on this thread, but are we all running into this issue when using **github actions**, specifically?

I am running into the issue on `typescript-eslint`, you can see the configuration here:

https://github.com/typescript-eslint/typescript-eslint/commit/19516dee04c37e33ca176d1e5715457f6bdf37d7

And the resulting failure from running the action here:

https://github.com/typescript-eslint/typescript-eslint/runs/1084722742?check_suite_focus=true

-------

I have an Azure DevOps release pipeline using the exact same lerna configuration using the _exact same PAT_ and it works without issue.

I don't understand what github actions is doing differently, but I've added my report above to this issue opened only a couple of days ago on the checkout action. Hopefully one of the maintainers over there will know where to report this...

https://github.com/actions/checkout/issues/344

**Comment by iDVB** [comment]
We were experiencing this same issue.

We were running the same `GH_TOKEN=NOTTELLING lerna publish` locally in the `master` branch and it was all working...
- tag is pushed to github repo
- `package.json` commit is pushed
- release is created
- package version is published to node registry.

Only when running it in Github Actions was it failing to get past the Review Check that admins (PAT) should not have to deal with.

**[FIX]**
It seems like the `actions/checkout@v2` step was setting the `git config + token` and persisting it throughout the remaining GitHub Action steps. Even if we had a step after it that would do this...
```
      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/$GITHUB_REPOSITORY
```
it would still use the default 'GITHUB_TOKEN' (without admin permissions to bypass reviews)

after sifting there many articles and issues we found this one on [semantic-release](https://github.com/semantic-release/git/issues/196#issuecomment-600842086) that gave us the fix.

You can either set the `token` in the `actions/checkout@v2` step
```
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
```

or **[untested]** use the `persist-credentials: false` to stop it from persisting the default config
```
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
```
but then you likely need a step to setup the git config auth as in the first code sample above ⬆️

**Comment by DiegoRBaquero** [comment]
Thank you for this!!! Upgrading to checkout@v2 broke it but `with:
          persist-credentials: false` was perfect solution

**Comment by DavidHe1127** [comment]
Ran into this issue as well. Tried all different approaches but none of them really works. Is turning off protection the only workaround?

**Comment by andreieuganox** [comment]
```
 - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_GITHUB }}

- name: "Version"
      env:
        GH_TOKEN: ${{ secrets.PAT_GITHUB }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        npx lerna version --exact --conventional-commits --create-release github --message "Publish [skip ci]" --yes
```

This works on GH Actions. Please note `--message "Publish [skip ci]"` flag, as you are using personal access token that will trigger Action  on Lerna Publish commit... Unfortunately did not find more elegant way, any suggestions are welcome.

**Comment by web-padawan** [comment]
In case anyone else faces this problem, here are scripts that we use to handle release from protected master:

<details>
<summary>Disable branch protection</summary>

```sh
#!/usr/bin/env bash

curl \
-X PUT \
https://api.github.com/repos/vaadin/web-components/branches/%CheckoutBranch%/protection \
-H "Accept: application/vnd.github.luke-cage-preview+json" \
-H "Authorization: token ${GITHUB_TOKEN}" \
-H "Content-Type: application/json" \
--data-binary @- <<DATA
{
  "required_status_checks": null,
  "enforce_admins": false,
  "required_pull_request_reviews": null,
  "required_linear_history": false,
  "allow_force_pushes": false,
  "allow_deletions": false,
  "required_conversation_resolution": false,
  "restrictions": null
}
DATA
```

</details>

<details>
<summary>Re-enable branch protection</summary>

```sh
#!/bin/bash

if [ "%CheckoutBranch%" = "master" ]; then
curl \
-X PUT \
https://api.github.com/repos/vaadin/web-components/branches/%CheckoutBranch%/protection \
-H "Accept: application/vnd.github.luke-cage-preview+json" \
-H "Authorization: token $GITHUB_TOKEN" \
-H "Content-Type: application/json" \
--data-binary @- <<DATA
{
  "required_status_checks":{
    "strict": false,
    "contexts": [
      "Unit tests",
      "Visual tests",
      "Lint"
    ]
  },
  "enforce_admins": true,
  "required_pull_request_reviews": {
    "dismiss_stale_reviews": false,
    "require_code_owner_reviews": false
  },
  "required_linear_history": true,
  "allow_force_pushes": false,
  "allow_deletions": false,
  "required_conversation_resolution": false,
  "restrictions": null
}
DATA
else
curl \
-X DELETE \
-H "Accept: application/vnd.github.v3+json" \
-H "Authorization: token $GITHUB_TOKEN" \
https://api.github.com/repos/vaadin/web-components/branches/%CheckoutBranch%/protection
fi
```

</details>

**Comment by Vinzius** [comment]
I ran into this issue as well, here a few more remarks to make this work:
* The GitHub token must be from a member with admin access. Most of the time it should be "you", but it could be a "bot" or someone else, so make sure the user has admin access to the repository.
* AND, make sure the checkbox `Include administrators` is NOT checked.
* Note: no need for "orga" permissions (for the GitHub token), just repository permissions.

**Comment by EdwardIrby** [comment]
> ```
>  - name: Checkout
>       uses: actions/checkout@v2
>       with:
>         token: ${{ secrets.PAT_GITHUB }}
> 
> - name: "Version"
>       env:
>         GH_TOKEN: ${{ secrets.PAT_GITHUB }}
>       run: |
>         git config user.name "${{ github.actor }}"
>         git config user.email "${{ github.actor}}@users.noreply.github.com"
>         npx lerna version --exact --conventional-commits --create-release github --message "Publish [skip ci]" --yes
> ```
> 
> This works on GH Actions. Please note `--message "Publish [skip ci]"` flag, as you are using personal access token that will trigger Action on Lerna Publish commit... Unfortunately did not find more elegant way, any suggestions are welcome.

Can confirm this works and is pretty much the only way.

**Comment by JamesHenry** [comment]
Hi Folks, I'm going to close this old issue as there is nothing that can be done on the lerna side. It's a fundamental VCS provider/workflow issue. I hope GH builds some native (secure) workflow for it in the future.

You might be interested in checking out `typescript-eslint` to see how I "solved" this for us. It uses protected GitHub environments and a whole separate bot user that we've had for many years and it ultimately produces entries like https://github.com/typescript-eslint/typescript-eslint/commit/2c6aeeec238dfea860b9f3c146a55f8f49f15cf5 on main.

It uses [Nx release](https://nx.dev/docs/features/manage-releases) rather than Lerna, but the core concerns at the VCS level are the same (so this still remains relevant https://github.com/actions/checkout/issues/344)
