### ISSUE TITLE
Can't publish to public npm registery

### ISSUE THREAD

**Issue by stavalfi** [lerna/lerna#1969]
## Expected Behavior
Be able to publish an package under `packages` folder to npm registery.
my package's package.json contains:
```json
"publicConfig": {
    "access": "public"
  }
```
* My npm organization is: `stavalfi1` and it's public.

## Current Behavior
```
lerna info execute Skipping GitHub releases
lerna info git Pushing tags...
lerna info publish Publishing packages to npm...
lerna info Verifying npm credentials
lerna http fetch GET 200 https://registry.npmjs.org/-/npm/v1/user 1520ms
lerna http fetch GET 200 https://registry.npmjs.org/-/org/stavalfi-lerna/package?format=cli 893ms
lerna WARN lifecycle Skipping root "prepublish" because it has already been called
lerna http fetch PUT 402 https://registry.npmjs.org/@stavalfi1%2fpackage1 613ms
lerna ERR! E402 You must sign up for private packages
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stavalfi1@0.0.0 publish: `lerna publish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the stavalfi1@0.0.0 publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

## Steps to Reproduce (for bugs)
1. Minimal example: https://github.com/stavalfi/learn-lerna
2. Run: `npm run publish`
3. Choose any version you like to publish

<details><summary>lerna.json before running `npm run publish`</summary><p>
```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

<details><summary>lerna.json after running `npm run publish`</summary><p>
```json
{
  "packages": [
    "packages/*"
  ],
  "version": "1.0.0"
}
```
</p></details>

There is no lerna-debug.log because lerna didn't throw any error.

<details><summary>npm.log</summary><p>

```txt
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'publish' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose run-script [ 'prepublish', 'publish', 'postpublish' ]
5 info lifecycle stavalfi1@0.0.0~prepublish: stavalfi1@0.0.0
6 info lifecycle stavalfi1@0.0.0~publish: stavalfi1@0.0.0
7 verbose lifecycle stavalfi1@0.0.0~publish: unsafe-perm in lifecycle true
8 verbose lifecycle stavalfi1@0.0.0~publish: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/stavalfi/WebstormProjects/learn-lerna/node_modules/.bin:/Users/stavalfi/.yarn/bin:/Users/stavalfi/.config/yarn/global/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/stavalfi/WebstormProjects/learn-lerna/node_modules/.bin
9 verbose lifecycle stavalfi1@0.0.0~publish: CWD: /Users/stavalfi/WebstormProjects/learn-lerna
10 silly lifecycle stavalfi1@0.0.0~publish: Args: [ '-c', 'lerna publish' ]
11 silly lifecycle stavalfi1@0.0.0~publish: Returned: code: 1  signal: null
12 info lifecycle stavalfi1@0.0.0~publish: Failed to exec publish script
13 verbose stack Error: stavalfi1@0.0.0 publish: `lerna publish`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid stavalfi1@0.0.0
15 verbose cwd /Users/stavalfi/WebstormProjects/learn-lerna
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "publish"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error stavalfi1@0.0.0 publish: `lerna publish`
22 error Exit status 1
23 error Failed at the stavalfi1@0.0.0 publish script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
</p></details>

## Context
I'm trying to do a super-simple toturial of lerna: [Setting up a monorepo with Lerna for a TypeScript project](https://blog.logrocket.com/setting-up-a-monorepo-with-lerna-for-a-typescript-project-b6a81fe8e4f8)

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | 1.13.0 |
| `node --version` | 10.15.3 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.2 |

**Comment by goroya** [comment]
me too

**Comment by KaboomFox** [comment]
me too

**Comment by evocateur** [comment]
1. You shouldn't name the root script `publish`, it's a significant name in the npm ecosystem that can cause all sorts of problems when used to run Lerna commands. Naming it `release` would avoid the ambiguity.
2. "publicConfig" is not the right key, it is [publishConfig](https://docs.npmjs.com/files/package.json#publishconfig).

**Comment by stavalfi** [comment]
thanks
