### ISSUE TITLE
[Internal] Investigate test issues

### ISSUE THREAD

**Issue by hzoo** [lerna/lerna#207]
This has been happening on and off for a while

Example issue https://travis-ci.org/lerna/lerna/jobs/136348436

``` sh
1) UpdatedCommand Basic should list changes:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at _exitWithCode.js:12:7
      at UpdatedCommand._complete (Command.js:151:7)
      at Command.js:115:14
      at Command.js:135:11
      at UpdatedCommand.execute (UpdatedCommand.js:25:5)
      at UpdatedCommand._attempt (Command.js:126:7)
      at Command.js:114:12
      at Command.js:135:11
      at UpdatedCommand.initialize (UpdatedCommand.js:14:5)
      at UpdatedCommand._attempt (Command.js:126:7)
      at UpdatedCommand.runCommand (Command.js:113:10)
      at Context.<anonymous> (UpdatedCommand.js:45:22)
      at _initFixture.js:33:5
```

**Comment by rygine** [comment]
I got this today, but it went away with another run.

```
1) UpdatedCommand Basic should list changes with --force-publish [package,package]:
     SyntaxError: Unexpected end of JSON input
      at Object.parse (native)
      at new Repository (Repository.js:22:29)
      at UpdatedCommand.Command (Command.js:17:23)
      at new UpdatedCommand (src/commands/UpdatedCommand.js:32:83)
      at Context.<anonymous> (UpdatedCommand.js:79:30)
      at _initFixture.js:33:5
      at node_modules/cpr/lib/index.js:239:9
      at Object.Stack.test (node_modules/cpr/lib/stack.js:31:27)
      at node_modules/cpr/lib/stack.js:25:18
      at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by thejameskyle** [comment]
I'm pretty sure that the timeout ones are because of something else erroring and causing `done()` never to be called, not that something is taking very long.

**Comment by wtgtybhertgeghgtwtg** [comment]
I know `lerna` isn't technically a Babel project, but maybe https://github.com/babel/babel/issues/5197 might help?

**Comment by phpnode** [comment]
This is happening a lot for https://github.com/codemix/flow-runtime which uses lerna, tests fail randomly on travis (never locally) - kicking the tests off again usually fixes the issue but the bug is always related to being unable to find particular node modules, usually mocha. I wonder if this is a general issue with travis and symlinks.

**Comment by evocateur** [comment]
A lot of these issues I ironed out when switching to Jest in #635, and they were mostly synchronous `fs` race conditions during setup/teardown of a given test case. I'm in the process of converting a lot of these synchronous operations into mocked assertions (#714) with additional CLI integration tests.

I'm going to close this, as Jest did indeed help, among many other recent optimizations.
