### ISSUE TITLE
lerna changed returns ambiguous code

### ISSUE THREAD

**Issue by csuvikg** [lerna/lerna#2161]
In our continuous integration pipeline we use `lerna changed --include-merged-tags --loglevel=silent --json` to collect changed packages for the next step. When there are no changes, this command fails with a return code of 1 and an empty result. In this case we still want to go on executing the build process. However, lately there was an invalid `package.json` file in one of the packages. Turns out lerna returns the same result (error code 1, empty result) in this case, too. This caused a faulty build.
As a user, it would be really helpful to be able to distinguish between response being "no changes" or "invalid files", for example, based on the response code.
Our current workaround is to do a `lerna list` first, that fails only when there are invalid files.

## Expected Behavior
`lerna changed` returns a different code for no changes, and for errors

## Current Behavior
`lerna changed` returns the same error response in both scenarios

## Possible Solution
Return a different response code for these cases.

## Steps to Reproduce (for bugs)
 - run `lerna changed --include-merged-tags --loglevel=silent --json` with a broken `package.json` in one of the projects (make the json invalid)
 - run it without changes in the projects
 - compared outputs are the same

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.0.0",
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "command": {
    "publish": {
      "ignoreChanges": [
        "**/package-lock.json"
      ],
      "registry": "https://artifactory-us.prezi.com/api/npm/npm/",
      "bump": "patch"
    }
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv { _: [ 'changed' ],
0 silly argv   'include-merged-tags': true,
0 silly argv   includeMergedTags: true,
0 silly argv   loglevel: 'silent',
0 silly argv   json: true,
0 silly argv   composed: 'changed',
0 silly argv   lernaVersion: '3.4.2',
0 silly argv   '$0': 'node_modules/.bin/lerna' }
1 notice cli v3.4.2
2 verbose rootPath /Users/csuvikg/projects/frontend-packages
3 info versioning independent
4 error JSONError: Unexpected string in JSON at position 2790 while parsing '{  "name": "@prezi/viewer-lite",  "ver' in packages/viewer-lite/package.json
4 error     at module.exports (/Users/csuvikg/projects/frontend-packages/node_modules/parse-json/index.js:26:19)
4 error     at parse (/Users/csuvikg/projects/frontend-packages/node_modules/load-json-file/index.js:8:29)
```
</p></details>

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.2 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.15.2 |
| `node --version` | v10.10.0 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.5 |

**Comment by evocateur** [comment]
Maybe don't silence the logs? Trust me, they won't pollute the JSON output, as they are emitted on `stderr` (where logs belong), not `stdout`.

I suppose different exit statuses could be done, though I have no idea what those would be. As for the invalid JSON, that strikes me as a test validation issue, not _strictly_ the responsibility of `lerna changed` to surface effectively.

**Comment by endreymarcell** [comment]
The part where I disagree with Lerna's current logic is returning 1 if there are no changed packages. I think it's a mistake to use an error code here. Saying that no packages have changed is a perfectly acceptable response from the script, I don't consider it an 'error scenario' that should be signaled with an exit code - I'm going to parse the output anyway, and if it's empty, I'll just stop the build.
I think it's totatlly fine for Lerna to return 1 if the `package.json` is corrupt, or in any other true failure cases, since those are indeed cases where Lerna encountered an error and cannot execute the command.

**Comment by QuestionAndAnswer** [comment]
Agree with @endreymarcell as I'm facing the same issue. ```lerna changed``` is trying to detect changes and the response might be list of changed packages, and it's should be acceptablet to have empty list, but this should be list anyway. And from program execution standpoint - program completed correctly and expects such conditions, so nothing prevent's it from functioning correctly, therefore there shouldn't be any error code emit. Meanwhile broken packages or anything that potentially breaks following program execution reasonable to throw and return error code.

**Comment by JakeElder** [comment]
I agree, I would expect the output of `lerna changed --json` to be `[]` and the exit code to be 0 when there are no changes.
