### ISSUE TITLE
Publish error: lerna publish from-git "Cannot destructure property `pkg` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by java-james** [lerna/lerna#2290]
Error running `lerna publish from-git`.

## Expected Behavior
Publish should run picking up tags in the current commit and publishing the packages.
## Current Behavior
```
lerna notice cli v3.16.4
lerna info versioning independent
lerna WARN Yarn's registry proxy is broken, replacing with public npm registry
lerna WARN If you don't have an npm token, you should exit and run `npm login`
lerna ERR! TypeError: Cannot destructure property `pkg` of 'undefined' or 'null'.
lerna ERR!     at updates.map (/Users/james/Development/lerna-test/node_modules/@lerna/publish/index.js:274:43)
lerna ERR!     at Array.map (<anonymous>)
lerna ERR!     at chain.then.updates (/Users/james/Development/lerna-test/node_modules/@lerna/publish/index.js:274:39)
lerna ERR! lerna Cannot destructure property `pkg` of 'undefined' or 'null'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Possible Solution
Unsure

## Steps to Reproduce (for bugs)
1. Create a lerna project using independent versioning and conventional commits
2. Release to NPM registry
4. Make a few feature changes using conventional commit messages
3. Run `lerna version --conventional-commits` to create a release commit
4. Run 'lerna publish --from-git'
5. Examine failure to run the command

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "packages": ["packages/*"],
  "command": {
    "publish": {
      "conventionalCommits": true
    },
    "version": {
      "allowBranch": "master",
      "message": "chore(release): publish [skip ci]"
    }
  }
}
```
</p></details>

## Context
Trying to create a release process the releaser can run version without commiting, amend changelogs, comitting, manually adding tags then run a publish from git.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | 1.17.3 |
| `node --version` | v10.16.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Mojave | 10.14.6 |

**Comment by java-james** [comment]
Having a dig into `node_modules/@lerna/publish/index.js:274:43`
Updates var has an empty element.

**Comment by java-james** [comment]
After debugging `matchingPattern` method in lerna I discovered a tag that was pushed spelt one of the package names incorrectly.
