### ISSUE TITLE
regenerate changelog via lerna exec and conventional-changelog fails on windows

### ISSUE THREAD

**Issue by diminutivesloop** [lerna/lerna#2499]
## Expected Behavior
I should be able to re-generate the changelogs for my project running the command [specified here](https://github.com/lerna/lerna/tree/master/commands/version#generating-initial-changelogs).
```
lerna exec --concurrency 1 --stream -- 'conventional-changelog --preset angular --release-count 0 --commit-path $PWD --pkg $PWD/package.json --outfile $PWD/CHANGELOG.md --verbose --lerna-package $LERNA_PACKAGE_NAME'
```

## Current Behavior
When I run that command I get the following error:
```
info cli using local version of lerna
lerna notice cli v3.16.4
lerna info versioning independent
lerna info Executing command in 5 packages: "conventional-changelog --preset angular-bitbucket --release-count 0 --commit-path $PWD --pkg $PWD/package.json --outfile $PWD/CHANGELOG.md --verbose --lerna-package $LERNA_PACKAGE_NAME"
@fds/assets: Preset: "angular-bitbucket" does not exist
@fds/assets: events.js:174
@fds/assets:       throw er; // Unhandled 'error' event
@fds/assets:       ^
@fds/assets: Error: ENOENT: no such file or directory, open 'G:\projects\fds\packages\assets\$PWD\CHANGELOG.md'
@fds/assets: Emitted 'error' event at:
@fds/assets:     at errorOrDestroy (internal/streams/destroy.js:107:12)
@fds/assets:     at WriteStream.onerror (_stream_readable.js:733:7)
@fds/assets:     at WriteStream.emit (events.js:198:13)
@fds/assets:     at lazyFs.open (internal/fs/streams.js:277:12)
@fds/assets:     at FSReqWrap.args [as oncomplete] (fs.js:140:20)
lerna ERR! conventional-changelog --preset angular-bitbucket --release-count 0 --commit-path $PWD --pkg $PWD/package.json --outfile $PWD/CHANGELOG.md --verbose --lerna-package $LERNA_PACKAGE_NAME exited 2 in '@fds/assets'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
```
This appears to be the result of the environment variables not being properly resolved by `lerna exec`. This is confirmed when I run `lerna exec -- 'echo $PWD'` and get this output:
```
info cli using local version of lerna
lerna notice cli v3.16.4
lerna info versioning independent
lerna info Executing command in 5 packages: "echo $PWD"
$PWD
$PWD
$PWD
$PWD
$PWD
lerna success exec Executed command in 5 packages: "echo $PWD"
```
I also tried modifying the command by removing the single quotes and escaping `$` characters with `\` as follows:
```
lerna exec --concurrency 1 --stream -- conventional-changelog --preset angular-bitbucket --release-count 0 --commit-path \$PWD --pkg \$PWD/package.json --outfile \$PWD/CHANGELOG.md --verbose --lerna-package \$LERNA_PACKAGE_NAME
```
However while the command didn't fail as before it only output the modified changelogs to the terminal without modifying the changelog files.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "version": "independent",
  "command": {
    "version": {
      "changelogPreset": "angular-bitbucket"
    }
  }
}
```
</p></details>

## Context
I'm trying to regenerate my changelogs since the default config produces broken commit links to our instance of Bitbucket Server. I'm currently trying to use the angular-bitbucket preset but I may just have to create a custom preset. Honestly Lerna could use much better documentation on how changelogs are generated and how they can be customized.

## Your Environment

I'm running all commands in a VSCode integrated terminal with the Git Bash shell.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.13.4|
| `node --version` | v10.16.3|

| OS | Version |
| --- | --- |
| Windows 10 | 1809 |

**Comment by diminutivesloop** [comment]
Ok looks like the shell `lerna exec` runs commands in is determined by the platform so I needed to update the command to use cmd.exe compatible environment variables and syntax:
```
npx lerna exec --concurrency 1 --stream -- conventional-changelog --preset angular --release-count 0 --commit-path ^%CD^% --pkg ^%CD^%/package.json --outfile ^%CD^%/CHANGELOG.md --lerna-package ^%LERNA_PACKAGE_NAME^%
```

Now the changelogs that were generated group all changes under a single version rather than grouping them in the same releases as before but that's probably an issue with conventional-changelog.

**Comment by diminutivesloop** [comment]
Closing because I no longer work on the project for which this issue was applicable so I'm not well situated to try reproducing it.
