### ISSUE TITLE
[feature] support for git submodules

### ISSUE THREAD

**Issue by trusktr** [lerna/lerna#2517]
Lerna `v3.20.2`

I tried running `lerna version`, accepted all default answers, and eventually hit this:

## Current Behavior

```
lerna ERR! Error: Command failed: git add -- packages/cli/package.json packages/cli/package-lock.json packages/live-code/package.json packages/live-code/package-lock.json packages/docsifyjs+docsify/package.json packages/docsifyjs+docsify/package-lock.json packages/variable/package.json ... etc ...
lerna ERR! fatal: Pathspec 'packages/cli/package.json' is in submodule 'packages/cli'
```

## Expected Behavior

I was hoping it would work with git submodules.

For various reasons, I have all my packages as git submodules. Basically I want to have an "umbrella repo" and not a "monorepo".

## Possible Solution

Maybe Lerna can detect submodules, and instead of adding the files it modified, it would `cd` into the submodules and call `git add` inside of them, and make individual version commits in each submodule.

## Workaround

For now, I can run `lerna run release:patch` and just have the `release:patch` script in each package do the work (or similar with `release:minor`, etc). Lerna is still great at running the commands across all the packages.

I'm enjoying Lerna with my git submodules! I've been using it to run builds and tests across all of my packages, which was the original goal that I was looking to achieve, and Lerna had enough features to make that work in a nice way (alternative tools do not work well with git submodules at all, or didn't have the features I was looking for, namely Rush.js).

**Comment by dilame** [comment]
I support this feature request. Submodules do make sense. I want to use it for granular access control to my packages.

**Comment by dilame** [comment]
It is not hard to detect if a package is a submodule 
https://www.npmjs.com/package/is-git-repository

**Comment by deviprsd** [comment]
https://github.com/mateodelnorte/meta check this out

**Comment by hotlong** [comment]
+1

**Comment by dobromyslov** [comment]
@deviprsd thanks for the hint. Tried meta (https://github.com/mateodelnorte/meta) and it looks like meta is better choice for cases like this one: https://blog.nrwl.io/dev-workflow-using-git-submodules-and-yarn-workspaces-14fd06c07964

**Comment by alita-moore** [comment]
Is this supported in lerna now? I see that nx is supported, how would I integrate it? (assuming nx is waht I think it is) sorry if I'm naive..

**Comment by agaudreault-jive** [comment]
Lerna seems to be **failing** when there is a **submodule** in the repo
```
$ lerna list
info cli using local version of lerna
lerna notice cli v7.1.5
lerna info versioning independent
my-module
lerna success found 1 package
```

After I init a submodule, (anywhere in the repo), even if I specify the `packages` path explicitly, I get
```
$ lerna list
info cli using local version of lerna
lerna notice cli v7.1.5
lerna ERR! Error: GenericFailure
lerna ERR!     at REDACTED/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:29:87
lerna ERR!     at Generator.next (<anonymous>)
lerna ERR!     at fulfilled (REDACTED/node_modules/tslib/tslib.js:166:62)
lerna ERR! lerna GenericFailure
```

**Comment by trusktr** [comment]
@agaudreault-jive  I'm using lerna with workspaces as git submodules, and `lerna list` works for me. I think you should open a bug report for that one.

---

What I would love is to use `lerna version`/`lerna publish` with git submodules so that it will

- read the commits from each git submodule for determining the conventional commits
- version each package and commit the result inside each submodule
- push each modified submodule separately

---

Other stuff such as running commands across git submodules is working well, as Lerna in that case does not care about anything related to git when it is doing that, it is only looking at package.json in each directory, and running the scripts.

**Comment by nidin** [comment]
Any update on this feature request?
