### ISSUE TITLE
fatal: bad revision 'undefined'

### ISSUE THREAD

**Issue by bluelovers** [lerna/lerna#2532]
## Steps to Reproduce (for bugs)

1. lerna publish

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "command": {
    "publish": {
      "ignoreChanges": [
        "**/node_modules/**",
        "**/__snapshots__/**",
        "**/__fixtures__/**",
        "**/test/**",
        "**/__tests__/**",
        "*.map",
        "*.spec.*",
        "*.test.*",
        ".gitrepo"
      ],
      "message": "chore(release): publish",
      "bump": "patch",
      "conventionalCommits": true,
      "conventionalGraduate": true
    },
    "run": {
      "stream": true
    },
    "exec": {
      "stream": true
    }
  },
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
23 error Error: Command failed: git diff --name-only  -- packages/dot-properties-loader
23 error fatal: bad revision 'undefined'
23 error
23 error
23 error     at makeError (C:\Users\User\AppData\Roaming\npm\node_modules\lerna\node_modules\execa\index.js:174:9)
23 error     at Function.module.exports.sync (C:\Users\User\AppData\Roaming\npm\node_modules\lerna\node_modules\execa\index.js:338:15)
23 error     at Object.execSync (C:\Users\User\AppData\Roaming\npm\node_modules\lerna\node_modules\@lerna\child-process\index.js:26:16)
23 error     at diffSinceIn (C:\Users\User\AppData\Roaming\npm\node_modules\lerna\node_modules\@lerna\collect-updates\lib\make-diff-predicate.js:63:23)
23 error     at hasDiffSinceThatIsntIgnored (C:\Users\User\AppData\Roaming\npm\node_modules\lerna\node_modules\@lerna\collect-updates\lib\make-diff-predicate.js:27:18)
23 error     at isCandidate (C:\Users\User\AppData\Roaming\npm\node_modules\lerna\node_modules\@lerna\collect-updates\collect-updates.js:88:77)
23 error     at C:\Users\User\AppData\Roaming\npm\node_modules\lerna\node_modules\@lerna\collect-updates\lib\collect-packages.js:11:9
23 error     at Map.forEach (<anonymous>)
23 error     at collectPackages (C:\Users\User\AppData\Roaming\npm\node_modules\lerna\node_modules\@lerna\collect-updates\lib\collect-packages.js:10:12)
23 error     at collectUpdates (C:\Users\User\AppData\Roaming\npm\node_modules\lerna\node_modules\@lerna\collect-updates\collect-updates.js:87:10)
23 error     at VersionCommand.initialize (C:\Users\User\AppData\Roaming\npm\node_modules\lerna\node_modules\@lerna\version\index.js:188:20)
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.14.4 |
| `yarn --version` | 1.22.0 |
| `node --version` | v13.12.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by Lornz-** [comment]
@bluelovers I got the same issue when I try to publish on merging a feature branch into master in CI environment. It seems to be the `conventional-graduate` option which makes it failed when you don't have any prerelease packages yet. I removed it and it works now. I still try to figure out how can I make it work if I want to make prereleases in local environment and ensure all prereleases versioned packages are graduated to stable versions in the next merge. Lerna is still new for me so I would wait for more details from someone who knows it better than me.

**Comment by blendsdk** [comment]
I have exactly the same problem. I want the `develop` branch to be released as `app-1.0.0-dev` and `master` branch to be released as `app-1.0.0`. Somehow if `conventional-graduate` does not encounter the `-dev` it breaks causing the CI/CD to fail. Any idea how this can be fixed?

**Comment by zslucky** [comment]
Same issue, `conventional-graduate` breakdown my CI process due to no prerelease packages...

**Comment by rohit-b4** [comment]
Facing same issue

**Comment by hunter2009** [comment]
Same issue here. Publish tag version on `test/*`branch, only publish official version on `master` branch. 
And I'm confused, because we had two projects, one can work, anthor facing the issue

**Comment by moughxyz** [comment]
You can do something like this if using GitHub workflows:

```
      - name: Bump Prod Version Graduate
        continue-on-error: true
        id: graduateRelease
        run: yarn lerna version --conventional-graduate --conventional-commits --yes

      - name: Bump Prod Version Fallback
        if: ${{ always() && steps.graduateRelease.outcome == 'failure'  }}
        run: |
          echo Falling back to non-graduate release due to https://github.com/lerna/lerna/issues/2532
          git stash
          yarn lerna version --conventional-commits --yes
```

**Comment by emlai** [comment]
My issue was that the GitHub checkout actions doesn't fetch the full history/tags by default. The fix was to specify `fetch-depth: 0`:

```yaml
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags, required for Lerna
```

**Comment by ramachintaguntla-wb** [comment]
Has anyone found a work around to graduating the packages from prerelease? The graduate command still throws the "fatal: bad revision 'undefined' error in our Github actions

**Comment by tutods** [comment]
> @bluelovers I got the same issue when I try to publish on merging a feature branch into master in CI environment. It seems to be the `conventional-graduate` option which makes it failed when you don't have any prerelease packages yet. I removed it and it works now. I still try to figure out how can I make it work if I want to make prereleases in local environment and ensure all prereleases versioned packages are graduated to stable versions in the next merge. Lerna is still new for me so I would wait for more details from someone who knows it better than me.

If I try without the `conventional-graduate` I receive this on my action:
```
lerna ERR! E401 authentication token not provided
lerna ERR! errno "undefined" is not a valid exit code - exiting with code 1
```
Any idea why?
