### ISSUE TITLE
I receive a 404 error from npm for local packages on actions such as npm remove unrelated-package

### ISSUE THREAD

**Issue by chanced** [lerna/lerna#2569]
## Expected Behavior
I'm not sure it's a bug or not. I'm new to Lerna and it could simply be that I am messing up the workflow. 

I would expect to be able to run commands like `npm uninstall whatever` within a package.

## Current Behavior
`npm uninstall koa` is causing npm to error out on commands other than `npm install new-package` (where `new-package` is an actual package on npm).

```txt
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@project%2fcore - Not found
npm ERR! 404 
npm ERR! 404  '@project/core@0.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'api'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chance/.npm/_logs/2020-05-04T01_46_15_761Z-debug.log
```

## Steps to Reproduce (for bugs)

1. clone [this repo](https://github.com/chanced/lernaexp)
2. bootstrap
3. `cd packages/api`
4. run `npm uninstall koa`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "version": "0.0.1"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv {
0 silly argv   _: [ 'create' ],
0 silly argv   lernaVersion: '3.20.2',
0 silly argv   '$0': 'lerna',
0 silly argv   name: 'core'
0 silly argv }
1 notice cli v3.20.2
2 verbose rootPath /Users/chance/Projects/lernaexp
3 warn ENOREMOTE No git remote found, skipping repository property
4 error TypeError: Cannot read property 'trim' of undefined
4 error     at module.exports (/usr/local/lib/node_modules/lerna/node_modules/validate-npm-package-license/index.js:60:20)
4 error     at /usr/local/lib/node_modules/lerna/node_modules/@lerna/create/lib/lerna-module-data.js:140:19
4 error     at PromZard.<anonymous> (/usr/local/lib/node_modules/lerna/node_modules/promzard/promzard.js:226:19)
4 error     at onError (/usr/local/lib/node_modules/lerna/node_modules/read/lib/read.js:94:12)
4 error     at Interface.<anonymous> (/usr/local/lib/node_modules/lerna/node_modules/read/lib/read.js:66:5)
4 error     at Interface.emit (events.js:315:20)
4 error     at Interface._ttyWrite (readline.js:873:16)
4 error     at ReadStream.onkeypress (readline.js:213:10)
4 error     at ReadStream.emit (events.js:315:20)
4 error     at emitKeys (internal/readline/utils.js:335:14)
4 error     at emitKeys.next (<anonymous>)
4 error     at ReadStream.onData (readline.js:1140:36)
4 error     at ReadStream.emit (events.js:315:20)
4 error     at addChunk (_stream_readable.js:300:12)
4 error     at readableAddChunk (_stream_readable.js:276:9)
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.14.4 |
| `yarn --version` |  ------ |
| `node --version` | v14.1.0 |

| OS | Version |
| --- | --- |
| macOS Catalina | 10.15.4 |

**Comment by mirages** [comment]
I have the same problem. Is there any solution?

**Comment by lewiscutey** [comment]
It may be a permission issue of npm.
