### ISSUE TITLE
Lerna import fails

### ISSUE THREAD

**Issue by fusionstrings** [lerna/lerna#269]
I am trying to use `lerna import`to import module repos in lerna packages. It gives me error. below is lerna.debug output

```zsh
lerna(info)    Lerna v2.0.0-beta.24
lerna(debug)   Attempting running ImportCommand.initialize
lerna(error)   Errored while running ImportCommand.initialize
    Error: No repository found at "https://github.com/fusionstrings/tridev.git"
        at ImportCommand.initialize (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/lerna/lib/commands/ImportCommand.js:79:27)
        at ImportCommand._attempt (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/lerna/lib/Command.js:157:21)
        at ImportCommand.runCommand (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/lerna/lib/Command.js:141:12)
        at ImportCommand.run (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/lerna/lib/Command.js:65:12)
        at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/lerna/bin/lerna.js:58:11)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Function.Module.runMain (module.js:441:10)

```

Here is a dummy project to replicate the issue.

https://ide.c9.io/fusionstrings/lerna-test

I did try with local and global installs.

**Comment by hzoo** [comment]
`lerna import` takes a path to a local git repo not a url like `https://github.com/fusionstrings/tridev.git` although it could potentially be a feature

**Comment by fusionstrings** [comment]
that explains, thanks 👍

**Comment by emirotin** [comment]
Could this be reconsidered and added as a useful feature? I quite often find myself cloning the repo just to import it into the monorepo project and then delete.
