### ISSUE TITLE
`lerna publish` unable to authenticate with Artifactory

### ISSUE THREAD

**Issue by lauraglasu** [lerna/lerna#2730]
We're trying to run `lerna publish` in Jenkins. We're using private Artifactory and configuring the auth via `.npmrc` file. `lerna publish`  fails to authenticate successfully.

## Expected Behavior
Using the same `.npmrc` file we're able to successfully run `yarn publish` after building the packages separately, so we'd expect Lerna to be able to do the same.

- if Lerna requires different configuration in order to authenticate with private npm registries like Artifactory it would be useful for that to be documented
- if Lerna doesn't support auth via the .npmrc file it would be nice for it to do so or to offer some alternative

## Current Behavior

When running `lerna publish` we get:
```
...
14:29:46  lerna info publish Publishing packages to npm...
14:29:46  lerna notice Skipping all user and access validation due to third-party registry
14:29:46  lerna notice Make sure you're authenticated properly ¯\_(ツ)_/¯
14:29:48  lerna http fetch PUT 401 https://artifactory.???/api/npm/???/??? 2819ms
14:29:48  lerna ERR! E401 Unable to authenticate, need: Basic realm="Artifactory Realm"
14:29:48  error Command failed with exit code 1.
```

## Possible Solution
- support auth via .npmrc file

## Steps to Reproduce (for bugs)
.npmrc file looks like this:
```
@???:registry=https://artifactory.???.???.net/api/npm/???/
//artifactory.???.???.net/api/npm/???/:_password=${ARTIFACTORY_TOKEN}
//artifactory.???.???.net/api/npm/???/:username=???
//artifactory.???.???.net/api/npm/???/:email=???@???.com
//artifactory.???.???.net/api/npm/???/:always-auth=true
```
and we run the command `lerna publish`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "conventionalCommits": true,
      "yes": true,
      "message": "chore(release): publish",
      "exact": true
    }
  }
}

```
</p></details>

## Context
At the moment we're doing a hacky workaround to publish our packages by running:
- `lerna version` to get the versions bumps required
- `yarn lerna run` to build the new packages
- publish with `yarn publish`

Overall it feels like we're unable to use Lerna as it was intended

## Your Environment
Running the build in Jenkins in a Debian stretch docker container

| Executable | Version |
| ---: | :--- |
| `lerna --version` | v3.22.1 |
| `npm --version`  | 6.14.5 |
| `yarn --version` | 1.22.4 |
| `node --version` | v12.18.1 |

| OS | Version |
| --- | --- |
| Debian | GNU/Linux 9 (stretch)|

**Comment by zfael** [comment]
![image](https://user-images.githubusercontent.com/17169912/99729710-11639080-2a9a-11eb-8db5-e71fa65dc042.png)

I just faced this issue today using the latest Lerna code and haven't found a workaround to work with Artifactory. 
I've tried with **.npmrc**, having the registry configured on package.json and passing it as a command arg but didn't work 😞

I'll try to dig more on this but just a heads up that you not alone @lauraglasu 👍

**Comment by Fnxxxxo** [comment]
Meet this but with Nexus
```
lerna info execute Skipping releases
lerna info git Pushing tags...
lerna info publish Publishing packages to npm...
lerna notice Skipping all user and access validation due to third-party registry
lerna notice Make sure you're authenticated properly ¯\_(ツ)_/¯
lerna http fetch PUT 401 ****** 603ms
lerna ERR! E401 Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"

```

**Comment by deepankarmalhan** [comment]
Running into this exact error with Artifactory, tried setting `.npmrc` file with authentication token inside of it, passing in token as an argument to `lerna publish` and much more. The error below:

```
[Pipeline] { (Publish To Artifactory)
[Pipeline] script
[Pipeline] {
[Pipeline] wrap
[Pipeline] {
[Pipeline] httpRequest
HttpMethod: GET
URL: https://hostname/artifactory/api/npm/npm-local/auth/@scope
Using authentication: token
Sending request to url: https://hostname/artifactory/api/npm/npm-local/auth/@scope
Response Code: HTTP/1.1 200 OK
Success code from [100‥399]
[Pipeline] writeFile
[Pipeline] sh
+ cp ./.npmrc /home/jenkins/.npmrc
[Pipeline] sh
+ npx lerna publish --yes --no-git-tag-version --no-push 1.0.6
lerna notice cli v3.22.1
lerna info versioning independent
lerna info ci enabled
lerna notice FYI git repository validation has been skipped, please ensure your version bumps are correct
lerna info Assuming all packages changed
lerna WARN version Skipping working tree validation, proceed at your own risk

Changes:
 - @scope/packageOne: 0.0.1 => 1.0.6
 - @scope/packageTwo: 0.0.1 => 1.0.6
 - @scope/packageThree: 0.0.1 => 1.0.6

lerna info auto-confirmed 
lerna info execute Skipping git tag/commit
lerna info execute Skipping git push
lerna info execute Skipping releases
lerna info publish Publishing packages to npm...
lerna notice Skipping all user and access validation due to third-party registry
lerna notice Make sure you're authenticated properly ��\_(���)_/��
lerna http fetch PUT 403 https://hostname/artifactory/api/npm/npm-local/@scope/packageOne128ms
lerna ERR! E403 forbidden
20:18:28.489891 durable_task_monitor.go:63: exit status 1
[Pipeline] }
```

I can manually publish the sub-modules by themselves using `npm publish`.

**Comment by deepankarmalhan** [comment]
Update, got it to work by having this in my `.npmrc` file:
```
@scope=https://hostname/artifactory/api/npm/npm-virtual/
//hostname/artifactory/api/npm/npm-virtual/:_password=<BASE64_PASSWORD>
//hostname/artifactory/api/npm/npm-virtual/:username=<USERNAME>
//hostname/artifactory/api/npm/npm-virtual/:email=<EMAIL>
//hostname/artifactory/api/npm/npm-virtual/:always-auth=true
registry=https://hostname/artifactory/api/npm/npm-virtual/
```

And then I ran `npx lerna publish from-package` and it worked!

**Comment by orest22** [comment]
> Update, got it to work by having this in my `.npmrc` file:
> 
> ```
> @scope=https://hostname/artifactory/api/npm/npm-virtual/
> //hostname/artifactory/api/npm/npm-virtual/:_password=<BASE64_PASSWORD>
> //hostname/artifactory/api/npm/npm-virtual/:username=<USERNAME>
> //hostname/artifactory/api/npm/npm-virtual/:email=<EMAIL>
> //hostname/artifactory/api/npm/npm-virtual/:always-auth=true
> registry=https://hostname/artifactory/api/npm/npm-virtual/
> ```
> 
> And then I ran `npx lerna publish from-package` and it worked!

Weird, I am still getting the same issue. Could you please share your `lerna.json` configs?

**Comment by deepankarmalhan** [comment]
```json
{
	"version": "independent",
	"packages": [
	  "packages/*"
	],
	"command": {
	  "add": {
		"registry": "https://hostname/artifactory/api/npm/npm-repo"
	  },
	  "create": {
		"registry": "https://hostname/artifactory/api/npm/npm-repo",
		"access": "restricted"
	  },
	  "publish": {
		"registry": "https://hostname/artifactory/api/npm/npm-repo",
		"verifyAccess": false,
		"ignoreChanges": [
		  "*.md",
		  "*/test/*"
		]
	  }
	}
  }
  ```
  
  Hope this helps!

**Comment by orest22** [comment]
My issue was supper dump, it was an issue with GitHub secrets. I also wanted to mention that for some reason my email was replaced with ENTER_YOUR_EMAIL_HERE so I had to do this in order to get everything correct. 

Run on Linux (sed might not work for macOS)
```
curl -u$ARTIFACTORY_USERNAME:$ARTIFACTORY_API_KEY https://host/artifactory/api/npm/npm-packages/auth/scope > ~/.npmrc
sed -i -e "s!ENTER_YOUR_EMAIL_HERE!$ARTIFACTORY_EMAIL!" ~/.npmrc
```

Here https://www.jfrog.com/confluence/display/JFROG/npm+Registry/#npmRegistry-UsingBasicAuthentication is specifically mentioned that npm publish will not work if you don't have your email set.

**Comment by deepankarmalhan** [comment]
Makes sense, glad it worked out! FYI for anyone who sees this in the future, `sed` works on macOS but needs an additional `''` after `-i` flag and then the rest of the command.

**Comment by evisong** [comment]
In my case, with the `~/.npmrc` below, `lerna publish` works well in _lerna 3.22.0_:

```
_auth=ABCDEFGHIJKLMN...opqrstuvwxyz0123456789==
always-auth = false

email=ci-user@example.com
registry=https://artifactory.example.com/api/npm/private-npm
```

but _**fails** in lerna 4.0.0_, with the following 403 error:

```
lerna http fetch PUT 403 https://artifactory.example.com/api/npm/private-npm/@example%2fprivate-pkg 4450ms
lerna sill HttpErrorGeneral: 403 Forbidden - PUT https://artifactory.example.com/api/npm/private-npm/@example%2fprivate-pkg - forbidden
lerna sill     at .../node_modules/npm-registry-fetch/check-response.js:134:15
lerna sill     at async publish (.../node_modules/libnpmpublish/publish.js:43:12)
...
lerna sill     at async run (...node_modules/p-queue/dist/index.js:163:29) {
lerna sill   headers: [Object: null prototype] { ... },
lerna sill   statusCode: 403,
lerna sill   code: 'E403',
lerna sill   method: 'PUT',
lerna sill   uri: 'https://artifactory.example.com/api/npm/private-npm/@example%2fprivate-pkg',
lerna sill   body: {
lerna sill     error: 'forbidden',
lerna sill     reason: "Cannot deploy to '@example/private-pkg/-/@example/private-pkg-1.0.0.tgz"
lerna sill   },
lerna sill   pkgid: '@example/private-pkg@1.0.0'
lerna sill }
lerna ERR! E403 forbidden
```

Prepending registry URL prefix to `_auth` solves the issue:

```
//artifactory.example.com/api/npm/private-npm/:_auth=ABCDEFGHIJKLMN...opqrstuvwxyz0123456789==
always-auth = false

email=ci-user@example.com
registry=https://artifactory.example.com/api/npm/private-npm
```

**Comment by saulske** [comment]
I had to downgrade to @3.22.0 in order to have it working. Other options did not help. 4.0.0 is not stable.

**Comment by mecograph** [comment]
As we have two repos in our Artifactory registry (one which acts as installer source and one for publishing) the solution by @evisong was leading me into the right direction. We had to prefix the `_auth` with the repo from where we install our packages and additionally add `registry` and `_auth` for the publishing part:

```
registry=https://artifactory.example.com/api/npm/reading-repo
_auth = ABCDEFGHIJKLMN...opqrstuvwxyz0123456789==
//artifactory.example.com/api/npm/publishing-repo/:_auth = ABCDEFGHIJKLMN...opqrstuvwxyz0123456789==
email = ci-user@example.com
always-auth = true
```

**Comment by william-will-angi** [comment]
+1 Downgrading to lerna@3.22.1 resolved these issues for us

**Comment by wldcordeiro** [comment]
So is there a fix coming for v4.x? Don't think it's tenable to have people on prior major versions in the long term.

**Comment by sebaplaza** [comment]
There is a possible solution to this ?

The only way to make artifactory work is using the 3.x branch ?

**Comment by peimanja** [comment]
Any updates?

**Comment by MiguelSOliveira** [comment]
also had to revert. is lerna still being maintained? is there a fix coming for v4?

**Comment by ggblee** [comment]
> Update, got it to work by having this in my `.npmrc` file:
> 
> ```
> @scope=https://hostname/artifactory/api/npm/npm-virtual/
> //hostname/artifactory/api/npm/npm-virtual/:_password=<BASE64_PASSWORD>
> //hostname/artifactory/api/npm/npm-virtual/:username=<USERNAME>
> //hostname/artifactory/api/npm/npm-virtual/:email=<EMAIL>
> //hostname/artifactory/api/npm/npm-virtual/:always-auth=true
> registry=https://hostname/artifactory/api/npm/npm-virtual/
> ```
> 
> And then I ran `npx lerna publish from-package` and it worked!

i had all these changes in my `.npmrc` and i was still running into the same issue, i.e.
```
lerna http fetch PUT 403 https://hostname/artifactory/api/npm/npm-local/@scope/packageOne128ms
lerna ERR! E403 forbidden
```
it turns out i was trying to publish a version into artifactory that already existed 😅 
i was testing `lerna publish` with prereleases locally and accidentally published a version
manually bumping the version in `package.json` to the existing version in artifactory and re-running `lerna publish` worked for me!

i'm guessing this would also happen if multiple packages are being published and there is one or more package version collisions.

**Comment by peterlawless** [comment]
I encountered this issue upon upgrading from Lerna 3.22 to 4.0.  The `lerna publish` command would error with a 401.  What worked for me was having both a "regular" `_auth` in the npm config _and_ another prepended with the registry URL as @evisong first recommended:

```
npm config set registry https://artifactory.example.com/api/npm/private-npm
npm config set _auth ABCDEFGHIJKLMN...opqrstuvwxyz0123456789==
npm config set //artifactory.example.com/api/npm/private-npm/:_auth ABCDEFGHIJKLMN...opqrstuvwxyz0123456789==
npm config set always-auth try
```

**Comment by JamesHenry** [comment]
Now that Nrwl has taken over stewardship we are going to take a look into this issue!

In the meantime, as was hit upon but not explicitly called out here: https://github.com/lerna/lerna/issues/2730#issuecomment-764733233

...you can use `"verifyAccess": false` in your lerna.json publish config, or pass `--no-verify-access` to the `lerna publish` command to get it to skip the auth step, which I think should unblock at lot of folks on this thread.

It is likely that the logic which validates the npm auth piece just needs to be expanded/fixed and as mentioned we will look into that very soon as we also want to address the highly related: https://github.com/lerna/lerna/issues/2788

**Comment by jackfarzan** [comment]
Is this still an open issue? I'm experiencing a similar issue (authenticating with artifactory registry on Jenkins) and haven't found a workaround. Downgrading lerna or using the no verify access flag haven't helped.

**Comment by sebaplaza** [comment]
Because of this unsolved issue, i migrated to turborepo + [changesets](https://github.com/changesets/changesets).

**Comment by dptoot** [comment]
@JamesHenry This issue remains for all of us that are stuck on corporate and private repos.  It makes lerna essentially unusable.  I have to believe this is a priority.

**Comment by rbirkgit** [comment]
I just tried Lerna 6.4.1 and still get:

> lerna ERR! E403 forbidden

What can we do to get this fixed? We are stuck with lerna v3 and cannot update.

**Comment by chaimabenkaddour** [comment]
hello, i have the same issue while trying to lerna pubish to private Nexus repository with (_auth=base64 representation of "user:password":) in my .npmrc its working by npm publish here what i get with lerna publish:
lerna ERR! E401 Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager" 

Any solution please, that makes Lerna publish unusable :(

**Comment by chaimabenkaddour** [comment]
> hello, i have the same issue while trying to lerna pubish to private Nexus repository with (_auth=base64 representation of "user:password":) in my .npmrc its working by npm publish here what i get with lerna publish: lerna ERR! E401 Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"
> 
> Any solution please, that makes Lerna publish unusable :(

i found a workaround that works for me it's to add overrides to my npm package.json

"overrides": {
    "libnpmpublish": "4.0.0"
  }
Thanks to this person who suggested this workaround  https://github.com/lerna/lerna/issues/2904

**Comment by MarianoVicenteBA** [comment]
I've been struggling with this all week, and my final result ended up being a combination of https://github.com/lerna/lerna/issues/2730#issuecomment-1500225665 and https://github.com/lerna/lerna/issues/2730#issuecomment-1122847075

🤷

**Comment by YuesIt17** [comment]
Hi! If you're interested, I wrote my [**article about lerna + jfrog artifactory** ](https://dev.to/eugene_yues_17/how-to-create-an-npm-packages-using-rollupjs-lernajs-jfrog-artifactory-2g80), there's more info and examples of my projects there.
