### ISSUE TITLE
lerna ERR! warning: LF will be replaced by CRLF in packages/xxxx/package.json.

### ISSUE THREAD

**Issue by StitchC** [lerna/lerna#2763]
## Expected Behavior

run "lerna version" command suceessfully and no error emit

## Current Behavior

run "lerna version" command emit this error

## Possible Solution

no solution

## Steps to Reproduce (for bugs)

1. use a windows pc
2. commit your work space file
3. run "lerna version --no-push --conventional-commits --create-release gitlab" 
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "packages": [
    "templates/*"
  ],
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
0 silly argv {
0 silly argv   _: [ 'version' ],
0 silly argv   push: false,
0 silly argv   'conventional-commits': true,
0 silly argv   conventionalCommits: true,
0 silly argv   'create-release': 'gitlab',
0 silly argv   createRelease: 'gitlab',
0 silly argv   lernaVersion: '3.22.1',
0 silly argv   '$0': 'node_modules\\lerna\\cli.js'
0 silly argv }
1 notice cli v3.22.1
2 verbose rootPath F:\work\soul-templates-vendor
3 info versioning independent
4 silly isAnythingCommitted
5 verbose isAnythingCommitted 1
6 silly currentBranch
7 verbose currentBranch master
8 silly hasTags
9 verbose hasTags true
10 silly git-describe.sync "function-module@0.0.1-alpha.0-6-gf5809e5" => {"lastTagName":"function-module@0.0.1-alpha.0","lastVersion":"0.0.1-alpha.0","refCount":"6","sha":"f5809e5","isDirty":false}
11 info Looking for changed packages since function-module@0.0.1-alpha.0
12 silly checking diff templates/function-module
13 silly found diff in templates/function-module/CHANGELOG.md
13 silly found diff in templates/function-module/license
13 silly found diff in templates/function-module/package.json
13 silly found diff in templates/function-module/src/index.ts
14 verbose filtered diff [
14 verbose filtered diff   'templates/function-module/CHANGELOG.md',
14 verbose filtered diff   'templates/function-module/license',
14 verbose filtered diff   'templates/function-module/package.json',
14 verbose filtered diff   'templates/function-module/src/index.ts'
14 verbose filtered diff ]
15 silly checking diff templates/project-starter
16 silly found diff in templates/project-starter/CHANGELOG.md
16 silly found diff in templates/project-starter/license
16 silly found diff in templates/project-starter/package.json
17 verbose filtered diff [
17 verbose filtered diff   'templates/project-starter/CHANGELOG.md',
17 verbose filtered diff   'templates/project-starter/license',
17 verbose filtered diff   'templates/project-starter/package.json'
17 verbose filtered diff ]
18 verbose updated function-module
19 verbose updated project-starter
20 verbose git-describe undefined => "function-module@0.0.1-alpha.0-6-gf5809e5"
21 silly git-describe parsed => {"lastTagName":"function-module@0.0.1-alpha.0","lastVersion":"0.0.1-alpha.0","refCount":"6","sha":"f5809e5","isDirty":false}
22 silly independent for function-module at F:\work\soul-templates-vendor\templates\function-module
23 verbose getChangelogConfig using preset "conventional-changelog-angular"
24 silly npa Result {
24 silly npa   type: 'tag',
24 silly npa   registry: true,
24 silly npa   where: undefined,
24 silly npa   raw: 'conventional-changelog-angular',
24 silly npa   name: 'conventional-changelog-angular',
24 silly npa   escapedName: 'conventional-changelog-angular',
24 silly npa   scope: undefined,
24 silly npa   rawSpec: '',
24 silly npa   saveSpec: null,
24 silly npa   fetchSpec: 'latest',
24 silly npa   gitRange: undefined,
24 silly npa   gitCommittish: undefined,
24 silly npa   hosted: undefined
24 silly npa }
25 verbose getChangelogConfig Attempting to resolve preset "conventional-changelog-angular"
26 info getChangelogConfig Successfully resolved preset "conventional-changelog-angular"
27 verbose independent increment 0.0.0 by minor
28 silly independent for project-starter at F:\work\soul-templates-vendor\templates\project-starter
29 verbose independent increment 0.0.0 by minor
30 info execute Skipping git push
31 info execute Skipping releases
32 silly lifecycle No script for "preversion" in "soul-templates-vendor", continuing
33 silly lifecycle No script for "preversion" in "function-module", continuing
34 silly lifecycle No script for "preversion" in "project-starter", continuing
35 silly lifecycle No script for "version" in "project-starter", continuing
36 silly independent for project-starter at F:\work\soul-templates-vendor\templates\project-starter
37 silly lifecycle No script for "version" in "function-module", continuing
38 silly independent for function-module at F:\work\soul-templates-vendor\templates\function-module
39 silly independent writing new entry: "# 0.1.0 (2020-11-18)\n\n\n### Features\n\n* 增加发布脚本 ([683e7d6](https://gz-gitlab.vipthink.cn/app/pc/soul-templates-vendor/commit/683e7d6140e9466c93bb19e8aa9d378ba09fc953))\n\n\n\n"
40 silly independent writing new entry: "# [0.1.0](https://gz-gitlab.vipthink.cn/app/pc/soul-templates-vendor/compare/function-module@0.0.1-alpha.0...function-module@0.1.0) (2020-11-18)\n\n\n### Features\n\n* 增加发布脚本 ([683e7d6](https://gz-gitlab.vipthink.cn/app/pc/soul-templates-vendor/commit/683e7d6140e9466c93bb19e8aa9d378ba09fc953))\n\n\n\n"
41 verbose independent wrote F:\work\soul-templates-vendor\templates\project-starter\CHANGELOG.md
42 verbose independent wrote F:\work\soul-templates-vendor\templates\function-module\CHANGELOG.md
43 silly lifecycle No script for "version" in "soul-templates-vendor", continuing
44 silly gitAdd [
44 silly gitAdd   'templates/project-starter/package.json',
44 silly gitAdd   'templates/project-starter/package-lock.json',
44 silly gitAdd   'templates/function-module/package.json',
44 silly gitAdd   'templates/function-module/package-lock.json',
44 silly gitAdd   'templates/project-starter/CHANGELOG.md',
44 silly gitAdd   'templates/function-module/CHANGELOG.md'
44 silly gitAdd ]
45 error Error: Command failed: git add -- templates/project-starter/package.json templates/project-starter/package-lock.json templates/function-module/package.json templates/function-module/package-lock.json templates/project-starter/CHANGELOG.md templates/function-module/CHANGELOG.md
45 error warning: LF will be replaced by CRLF in templates/function-module/CHANGELOG.md.
45 error The file will have its original line endings in your working directory
45 error warning: LF will be replaced by CRLF in templates/function-module/package.json.
45 error The file will have its original line endings in your working directory
45 error warning: LF will be replaced by CRLF in templates/project-starter/CHANGELOG.md.
45 error The file will have its original line endings in your working directory
45 error warning: LF will be replaced by CRLF in templates/project-starter/package.json.
45 error The file will have its original line endings in your working directory
45 error The following paths are ignored by one of your .gitignore files:
45 error templates/function-module/package-lock.json
45 error templates/project-starter/package-lock.json
45 error Use -f if you really want to add them.
45 error
45 error     at makeError (F:\work\soul-templates-vendor\node_modules\execa\index.js:174:9)
45 error     at F:\work\soul-templates-vendor\node_modules\execa\index.js:278:16
45 error     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1|
| `npm --version`  | 6.14.6|
| `yarn --version` | 1.13.0|
| `node --version` | 12.18.3|

| OS | Version |
| --- | --- |
| windows 10 | 18363 |

**Comment by StitchC** [comment]
it seems is a git warning why will cause the process error exit ？

**Comment by eti666** [comment]
> 

> @wincent

**Comment by ghiscoding** [comment]
I got this warning too, I found this Youtube video [Fix warning: LF will be replaced by CRLF | GIT](https://www.youtube.com/watch?v=E3ZasQEOdRY) and also see that Lerna itself has a [.gitattributes](https://github.com/lerna/lerna/blob/main/.gitattributes) most probably to avoid these warnings/errors, I'll give that a try
