### ISSUE TITLE
lerna run failing: a package cannot see a top-level dependency

### ISSUE THREAD

**Issue by staltz** [lerna/lerna#281]
Basically I'm running `lerna run test` and the first package cannot see a dependency like `tslint`, which is installed on the top-level.

top-level package.json (sibling to lerna.json) has:
```js
{
  "private": true,
  "license": "MIT",
  "devDependencies": {
...
    "tslint": "3.13.0",
...
  }
}
```

And the first package in `packages` will use `tslint` in its `test` script.

I ran on the top-level: `npm i; lerna bootstrap` and then I made sure that it installed tslint in the top-level node_modules, and package-specific dependencies in each package node_modules. Then I ran `lerna run test` and got the error:

```
lerna(info)    Lerna v2.0.0-beta.24
lerna(info)    Independent Versioning Mode
lerna(debug)   Attempting running RunCommand.initialize
lerna(debug)   Successfully ran RunCommand.initialize
lerna(debug)   Attempting running RunCommand.execute
lerna(error)   Errored while running npm script 'test' in 'cycle-lerna-sandbox-base'
    Error: Command failed: npm run test 
    sh: tslint: command not found
    
    npm ERR! Darwin 15.5.0
    npm ERR! argv "/Users/staltz/.nvm/versions/node/v6.1.0/bin/node" "/Users/staltz/.nvm/versions/node/v6.1.0/bin/npm" "run" "lint"
    npm ERR! node v6.1.0
    npm ERR! npm  v3.8.6
    npm ERR! file sh
    npm ERR! code ELIFECYCLE
    npm ERR! errno ENOENT
    npm ERR! syscall spawn
    npm ERR! cycle-lerna-sandbox-base@4.0.1 lint: `tslint -c tslint.json src/*.ts`
    npm ERR! spawn ENOENT
    npm ERR! 
    npm ERR! Failed at the cycle-lerna-sandbox-base@4.0.1 lint script 'tslint -c tslint.json src/*.ts'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the cycle-lerna-sandbox-base package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     tslint -c tslint.json src/*.ts
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs cycle-lerna-sandbox-base
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls cycle-lerna-sandbox-base
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/staltz/oss/lerna-test/packages/base/npm-debug.log
    
    npm ERR! Darwin 15.5.0
    npm ERR! argv "/Users/staltz/.nvm/versions/node/v6.1.0/bin/node" "/Users/staltz/.nvm/versions/node/v6.1.0/bin/npm" "run" "test"
    npm ERR! node v6.1.0
    npm ERR! npm  v3.8.6
    npm ERR! code ELIFECYCLE
    npm ERR! cycle-lerna-sandbox-base@4.0.1 test: `npm run lint && npm run mocha`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the cycle-lerna-sandbox-base@4.0.1 test script 'npm run lint && npm run mocha'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the cycle-lerna-sandbox-base package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm run lint && npm run mocha
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs cycle-lerna-sandbox-base
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls cycle-lerna-sandbox-base
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/staltz/oss/lerna-test/packages/base/npm-debug.log
    
        at ChildProcess.exithandler (child_process.js:202:12)
        at emitTwo (events.js:106:13)
        at ChildProcess.emit (events.js:191:7)
        at maybeClose (internal/child_process.js:850:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
lerna(error)   Errored while running RunCommand.execute
```

**Comment by thejameskyle** [comment]
If you want the lint to be installed at the top-level, whats the reasoning behind putting individual scripts within each `package.json` for it rather than one at the top-level?

**Comment by staltz** [comment]
It's possible that I have a package written in TypeScript and another written in JS/Babel, so each package defines how to run its lint script. In general this isn't about linting, I'm just surprised that lerna doesn't use the top-level package.json dependencies as "common" dependencies that each package has access to.

**Comment by thejameskyle** [comment]
Lerna does nothing special with npm dependencies outside of the cross package proxying. It doesn't even technically know about the top level node_modules

**Comment by staltz** [comment]
So I misunderstood.

**Comment by anilanar** [comment]
I wonder, what does "Common devDependencies" in the homepage talk about? If what you say is true, then that part in README is terribly misleading.
