### ISSUE TITLE
Could not handle  __non_webpack_require__ while building 

### ISSUE THREAD

**Issue by mamin-crest** [lerna/lerna#2828]
I'm using __non_webpack_require__ in one of my package in App. When I run/build individual package using webpack, it's working fine. but when I try to built parent/main App using `lerna run build`,  It's trying to resolve module inside __non_webpack_require__  , which throws the Error.

PS: After Some deugging, I found out that, one of my package is dependent on another. which is the root cause of the issue.
At first run,  __non_webpack_require__ get replaced by require and in second time. it's causing the issue.

Any workaround for this issue?

## Expected Behavior
It should not try to resolve dependency with __non_webpack_require__ keyword. I don't how lerna is handling building process Internally. but I found Webpack independently working fine.  

## Current Behavior
Trying to resolve module dependency inside __non_webpack_require__  

## Possible Solution
It should not resolve the depedency

## Steps to Reproduce (for bugs)
1. in main app/folder have configuration related to lerna
2. Setup two packages in packages folder.
3. One of package using __non_webpack_require__  keyword in code
4. build main/parent package

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0",
  "commands": {
    "publish": {
      "ignore": ["*.md"]
    }
  },
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'build' ]
1 silly flags {
1 silly flags   _: [ 'run' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   script: 'build',
1 silly flags   args: []
1 silly flags }
2 verbose rootPath /home/user/Code/form2
3 info version 2.11.0
4 silly existsSync /home/user/Code/form2/VERSION
5 silly initialize attempt
6 silly initialize success
7 silly execute attempt
8 silly runScriptInDir build [] form-2
9 silly getExecOpts { cwd: '/home/user/Code/form2/packages/form-2' }
10 silly runScriptInDir build [] form-app
11 silly getExecOpts { cwd: '/home/user/Code/form2/packages/form-app' }
12 error build Errored while running script in '@app/form-app'
13 error execute callback with error
14 error Error: Command failed: yarn run build
14 error ModuleNotFoundError: Module not found: Error: Can't resolve 'custom' in '/home/user/Code/form2/packages/form-2'
14 error     at /home/user/Code/form2/node_modules/webpack/lib/Compilation.js:925:10
14 error     at /home/user/Code/form2/node_modules/webpack/lib/ContextModuleFactory.js:143:23
14 error     at /home/user/Code/form2/node_modules/neo-async/async.js:2830:7
14 error     at /home/user/Code/form2/node_modules/neo-async/async.js:6877:13
14 error     at /home/user/Code/form2/node_modules/webpack/lib/ContextModuleFactory.js:118:26
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/Resolver.js:213:14
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/Resolver.js:285:5
14 error     at eval (eval at create (/home/user/Code/form2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/Resolver.js:285:5
14 error     at eval (eval at create (/home/user/Code/form2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/Resolver.js:285:5
14 error     at eval (eval at create (/home/user/Code/form2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/Resolver.js:285:5
14 error     at eval (eval at create (/home/user/Code/form2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/Resolver.js:285:5
14 error     at eval (eval at create (/home/user/Code/form2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/Resolver.js:285:5
14 error     at eval (eval at create (/home/user/Code/form2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/Resolver.js:285:5
14 error     at eval (eval at create (/home/user/Code/form2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/Resolver.js:285:5
14 error     at eval (eval at create (/home/user/Code/form2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/Resolver.js:285:5
14 error     at eval (eval at create (/home/user/Code/form2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/Resolver.js:285:5
14 error     at eval (eval at create (/home/user/Code/form2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/RootPlugin.js:37:38
14 error     at _next2 (eval at create (/home/user/Code/form2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
14 error     at eval (eval at create (/home/user/Code/form2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
14 error     at /home/user/Code/form2/node_modules/enhanced-resolve/lib/Resolver.js:285:5
14 error resolve 'custom' in '/home/user/Code/form2/packages/form-2'
14 error   Parsed request is a module
14 error   using description file: /home/user/Code/form2/packages/form-2/package.json (relative path: .)
14 error     Field 'browser' doesn't contain a valid alias configuration
14 error     resolve as module
14 error       /home/user/Code/form2/packages/node_modules doesn't exist or is not a directory
14 error       /home/user/Code/node_modules doesn't exist or is not a directory
14 error       /home/user/node_modules doesn't exist or is not a directory
14 error       /home/node_modules doesn't exist or is not a directory
14 error       /node_modules doesn't exist or is not a directory
14 error       looking for modules in /home/user/Code/form2/packages/form-2/node_modules
14 error         using description file: /home/user/Code/form2/packages/form-2/package.json (relative path: ./node_modules)
14 error           Field 'browser' doesn't contain a valid alias configuration
14 error       looking for modules in /home/user/Code/form2/node_modules
14 error         using description file: /home/user/Code/form2/package.json (relative path: ./node_modules)
14 error           Field 'browser' doesn't contain a valid alias configuration
14 error           using description file: /home/user/Code/form2/packages/form-2/package.json (relative path: ./node_modules/custom)
14 error             as directory
14 error               /home/user/Code/form2/packages/form-2/node_modules/custom doesn't exist
14 error           using description file: /home/user/Code/form2/package.json (relative path: ./node_modules/custom)
14 error             as directory
14 error               /home/user/Code/form2/node_modules/custom doesn't exist
14 error error Command failed with exit code 1.
14 error $ NODE_ENV=production webpack --bail
14 error info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
14 error
14 error     at /home/user/Code/form2/node_modules/lerna/node_modules/execa/index.js:236:11


<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context
So, I just want to use custom js files at run time. Below is my code snippet for that:
```
_loadHook(module) {
        let myPromise = new Promise(function(myResolve, myReject) {
            __non_webpack_require__(['custom/' + module], (Hook) => {
                this.hook = new Hook(
                    Config,
                    this.inputName,
                    this.state,
                    this.util
                );
                myResolve(Hook);
            }
          );
        })
        return myPromise;
    };
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 6.14.10 |
| `yarn --version` | 1.22.5 |
| `node --version` | 14.15.4|

| OS | Version |
| --- | --- |
| CentOS | 8 |

PS: I'm not expert in build process or something. also not sure about whether, this bug is related to lerna. but I'm getting this error after running `lerna run build`,

**Comment by mamin-crest** [comment]
Closing the issue as it's not related to lerna
