### ISSUE TITLE
Lerna command in AWS Codebuild

### ISSUE THREAD

**Issue by s1mrankaur** [lerna/lerna#2848]
```
    Error: Cannot find module '.'
    Require stack:
    - /codebuild/output/src309915592/src/node_modules/.bin/lerna
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
        at Function.Module._load (internal/modules/cjs/loader.js:687:27)
        at Module.require (internal/modules/cjs/loader.js:903:19)
        at require (internal/modules/cjs/helpers.js:74:18)
        at Object.<anonymous> (/codebuild/output/src309915592/src/node_modules/.bin/lerna:11:3)
        at Module._compile (internal/modules/cjs/loader.js:1015:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
        at Module.load (internal/modules/cjs/loader.js:879:32)
        at Function.Module._load (internal/modules/cjs/loader.js:724:14)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [ '/codebuild/output/src309915592/src/node_modules/.bin/lerna' ]
    }
```

I get this error on running the test command:

`    lerna run --stream test --parallel
`
Also, tried with

`    lerna run --stream test --parallel --scope tenant-registration-service
`
In the services, test script looks like,

`    "test": "serverless-bundle test --verbose --coverage",
`
I installed Lerna globally in the pipeline.  How do I debug this? What module is it not able to find? It looks like it already has lerna installed which it should.

`npm run test` command runs just fine on the local system.

**Comment by quintstoffers** [comment]
I recall there being an issue where symlinks aren't handled correctly when using caches:
https://forums.aws.amazon.com/thread.jspa?threadID=271667

Perhaps you're running into that?
