### ISSUE TITLE
lerna publish error

### ISSUE THREAD

**Issue by LanFly** [lerna/lerna#2868]
## Current Behavior
`lerna ERR! Error: Command failed with exit code 1: git commit -F /private/var/folders/26/cwn6kn0j0cjbfw4f0g3ksplr0000gp/T/47be6128-b5a1-4161-a30f-397b2bee77b9/lerna-commit.txt`

## Steps to Reproduce (for bugs)

1. do something changes
2. git commit && git push
3. lerna publish

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "tnpm",
  "version": "independent",
  "registry": "https://registry.npm.xxx.com/",
  "packages": [
    "packages/*"
  ],
  "command": {
    "bootstrap": {
      "npmClientArgs": [
        "--by=yarn",
        "network",
        "--ignore-engines",
        "--enable-lockfile"
      ]
    },
    "test": {
      "npmClientArgs": ["--ignore ", "xxx"]
    }
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
52 error Error: Command failed with exit code 1: git commit -F /private/var/folders/26/cwn6kn0j0cjbfw4f0g3ksplr0000gp/T/47be6128-b5a1-4161-a30f-397b2bee77b9/lerna-commit.txt
52 error On branch dev
52 error Your branch is up to date with 'origin/dev'.
52 error
52 error Untracked files:
52 error 	lerna-debug.log
52 error
52 error nothing added to commit but untracked files present
52 error     at makeError (/Users/lan/.nvm/versions/node/v10.22.0/lib/node_modules/lerna/node_modules/_execa@5.0.0@execa/lib/error.js:59:11)
52 error     at handlePromise (/Users/lan/.nvm/versions/node/v10.22.0/lib/node_modules/lerna/node_modules/_execa@5.0.0@execa/index.js:114:26)

```
</p></details>

## Context
The command `git commit -F /private/var/folders/26/cwn6kn0j0cjbfw4f0g3ksplr0000gp/T/47be6128-b5a1-4161-a30f-397b2bee77b9/lerna-commit.txt` exit code 1.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 6.14.6 |
| `yarn --version` | v1.22.5 |
| `node --version` | v10.22.0 |

| OS | Version |
| --- | --- |
| macOS Catalina | 10.15.7 |

**Comment by SamWeichangyue** [comment]
i have the same error, have you solved this problem

**Comment by suiboyu** [comment]
I have the same error，have you solved this problem。If you have solved it, please let me know。

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

In the case of this specific issue, we will please need clear steps to reproduce in order to begin looking into it. 

Please head over to https://github.com/lerna/repro, fork the repo and apply the changes necessary to reproduce the bug. Then open a PR to that https://github.com/lerna/repro repo and comment back to this thread with the PR number so that we can take a look into the problem and provide a fix.

Many thanks! 🙏
