### ISSUE TITLE
`lerna run tsc` error on version v4.0.0

### ISSUE THREAD

**Issue by gavin-c-tcg** [lerna/lerna#2917]
example: github 
https://github.com/vladotesanovic/hospital-sdk

lerna@4.0.0 can not `lerna run tsc` , but lerna@3.22.1 is ok

## Expected Behavior
`npm install`
`npm i lerna@4.0.0`
`lerna bootstrap`
`lerna run tsc` => Expected OK

## Current Behavior
`npm install`
`npm i lerna@4.0.0`
`lerna bootstrap`
`lerna run tsc` => Current ERROR

## Steps to Reproduce (for bugs)
1. git clone  https://github.com/vladotesanovic/hospital-sdk
2. cd hospital-sdk
3. npm i
4. npm i lerna@4.0.0
5. lerna bootstrap
6. lerna run tsc

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.4"
}

```
</p></details>

<details><summary>debug.log</summary><p>

```txt
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'tsc'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose run-script [ 'pretsc', 'tsc', 'posttsc' ]
5 info lifecycle @hospital-sdk/doctor@0.0.4~pretsc: @hospital-sdk/doctor@0.0.4
6 info lifecycle @hospital-sdk/doctor@0.0.4~tsc: @hospital-sdk/doctor@0.0.4
7 verbose lifecycle @hospital-sdk/doctor@0.0.4~tsc: unsafe-perm in lifecycle true
8 verbose lifecycle @hospital-sdk/doctor@0.0.4~tsc: PATH: C:\Users\User\AppData\Roaming\nvm\v12.18.2\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\User\code\__github\hospital-sdk\packages\doctor\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\User\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Users\User\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\Program Files (x86)\Yarn\bin;C:\Program Files\PuTTY;C:\ProgramData\chocolatey\bin;C:\application\Apache24\bin;C:\application\instantclient_19_6;C:\application\nginx-1.19.0;C:\Program Files\OpenJDK\openjdk-8u282-b08\bin;C:\Users\User\AppData\Local\Android\Sdk\platform-tools;C:\Users\User\AppData\Local\Android\Sdk\emulator;C:\Users\User\AppData\Local\Android\Sdk\tools;C:\Users\User\AppData\Local\Android\Sdk\tools\bin;C:\Program Files\Git\cmd;C:\Program Files\Geth;C:\Users\User\AppData\Local\Programs\Python\Python39\Scripts;C:\Users\User\AppData\Local\Programs\Python\Python39;C:\Users\User\anaconda3;C:\Users\User\anaconda3\Library\mingw-w64\bin;C:\Users\User\anaconda3\Library\usr\bin;C:\Users\User\anaconda3\Library\bin;C:\Users\User\anaconda3\Scripts;C:\Users\User\.windows-build-tools\python27;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Users\User\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\User\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\User\AppData\Local\Yarn\bin;C:\Users\User\AppData\Local\Programs\Fiddler;C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin;C:\Users\User\AppData\Local\hyper\app-3.0.2\resources\bin;C:\Users\User\AppData\Local\Microsoft\WindowsApps
9 verbose lifecycle @hospital-sdk/doctor@0.0.4~tsc: CWD: C:\Users\User\code\__github\hospital-sdk\packages\doctor
10 silly lifecycle @hospital-sdk/doctor@0.0.4~tsc: Args: [ '/d /s /c', 'tsc' ]
11 silly lifecycle @hospital-sdk/doctor@0.0.4~tsc: Returned: code: 1  signal: null
12 info lifecycle @hospital-sdk/doctor@0.0.4~tsc: Failed to exec tsc script
13 verbose stack Error: @hospital-sdk/doctor@0.0.4 tsc: `tsc`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\User\AppData\Roaming\nvm\v12.18.2\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\User\AppData\Roaming\nvm\v12.18.2\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @hospital-sdk/doctor@0.0.4
15 verbose cwd C:\Users\User\code\__github\hospital-sdk\packages\doctor
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "tsc"
18 verbose node v12.18.2
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error @hospital-sdk/doctor@0.0.4 tsc: `tsc`
22 error Exit status 1
23 error Failed at the @hospital-sdk/doctor@0.0.4 tsc script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0|
| `npm --version`  | 6.14.5|
| `yarn --version` | 1.22.0 |
| `node --version` | v12.18.2|

| OS | Version |
| --- | --- |
| NAME | VERSION |
Windows 10

**Comment by JamesHenry** [comment]
Closing for housekeeping as this issue is 5 years old (predating our stewardship of the project) and relates to very old versions. Please consider giving the latest lerna a try, it's come a long way!
