### ISSUE TITLE
Lerna doest not respect `strict-ssl=false` in .npmrc

### ISSUE THREAD

**Issue by krtek4** [lerna/lerna#2942]
We have a private nexus repository with its own self-signed certificate. Both the `.npmrc` in my home folder and the project folder have the `strict-ssl=false` line correctly set up to accomodate for this.

However, Lerna still errors when publishing :
```
lerna ERR! SELF_SIGNED_CERT_IN_CHAIN request to https://nexus.vs.ch/repository/npm-private/@cci%2futils failed, reason: self signed certificate in certificate chain
lerna ERR! FetchError: request to https://nexus.vs.ch/repository/npm-private/@cci%2futils failed, reason: self signed certificate in certificate chain
lerna ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/lerna/node_modules/minipass-fetch/lib/index.js:97:14)
```

## Expected Behavior
Lerna correctly respects the content of the `.npmrc` file

## Current Behavior
The  `strict-ssl=false` configuration seems to be ignored

## Steps to Reproduce (for bugs)
1. Setup a private npm repository with a self signed certificate
2. Try publishing to it

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "xxxxx"
  ],
  "version": "independent",
  "command": {
    "publish": {
      "conventionalCommits": true,
      "registry": "xxxxxx"
    },
    "version": {
      "message": "chore(release): release"
    }
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv {
0 silly argv   _: [ 'publish' ],
0 silly argv   composed: 'publish',
0 silly argv   lernaVersion: '4.0.0',
0 silly argv   '$0': '/usr/local/bin/lerna'
0 silly argv }
1 notice cli v4.0.0
2 verbose rootPath /mnt/c/dev/Projects/XXX/xxx-packages
3 info versioning independent
4 verbose session d0c12b0878b93be7
5 verbose user-agent lerna/4.0.0/node@v12.21.0+x64 (linux)
6 silly argv { _: [ 'publish' ], composed: 'publish', lernaVersion: '4.0.0' }
7 verbose rootPath /mnt/c/dev/Projects/XXX/xxx-packages
8 silly isAnythingCommitted
9 verbose isAnythingCommitted 1
10 silly getCurrentBranch
11 verbose currentBranch master
12 silly remoteBranchExists
13 silly isBehindUpstream
14 silly isBehindUpstream master is behind origin/master by 0 commit(s) and ahead by 0
15 silly hasTags
16 verbose hasTags false
17 info Assuming all packages changed
18 verbose updated @xxx/xxxxx
19 verbose git-describe undefined => "0066586"
20 silly git-describe parsed => {"refCount":"212","sha":"0066586","isDirty":false}
21 silly independent for @xxx/xxxxx at /mnt/c/dev/Projects/XXX/xxx-packages/projects/xxx-xxxxx
22 verbose getChangelogConfig using preset "conventional-changelog-angular"
23 silly npa Result {
23 silly npa   type: 'tag',
23 silly npa   registry: true,
23 silly npa   where: undefined,
23 silly npa   raw: 'conventional-changelog-angular',
23 silly npa   name: 'conventional-changelog-angular',
23 silly npa   escapedName: 'conventional-changelog-angular',
23 silly npa   scope: undefined,
23 silly npa   rawSpec: '',
23 silly npa   saveSpec: null,
23 silly npa   fetchSpec: 'latest',
23 silly npa   gitRange: undefined,
23 silly npa   gitCommittish: undefined,
23 silly npa   hosted: undefined
23 silly npa }
24 verbose getChangelogConfig Attempting to resolve preset "conventional-changelog-angular"
25 info getChangelogConfig Successfully resolved preset "conventional-changelog-angular"
26 verbose independent increment 0.1.2 by minor
27 info execute Skipping releases
28 silly lifecycle No script for "preversion" in "xxx-packages", continuing
29 silly lifecycle No script for "preversion" in "@xxx/xxxxx", continuing
30 silly lifecycle No script for "version" in "@xxx/xxxxx", continuing
31 silly independent for @xxx/xxxxx at /mnt/c/dev/Projects/XXX/xxx-packages/projects/xxx-xxxxx
32 silly independent writing new entry: "# 0.2.0 (2021-07-08)\n\n\n### Features\n\n* publishing using lerna ([0066586](https://git.vs.ch/xxx/packages/commits/00665865c48f6a0333e481b79710cce87019d2d0))\n\n\n\n"
33 verbose independent wrote /mnt/c/dev/Projects/XXX/xxx-packages/projects/xxx-xxxxx/CHANGELOG.md
34 silly lifecycle No script for "version" in "xxx-packages", continuing
35 silly gitAdd [
35 silly gitAdd   'projects/xxx-xxxxx/package.json',
35 silly gitAdd   'projects/xxx-xxxxx/package-lock.json',
35 silly gitAdd   'projects/xxx-xxxxx/CHANGELOG.md'
35 silly gitAdd ]
36 silly gitCommit chore(release): release
36 silly gitCommit
36 silly gitCommit  - @xxx/xxxxx@0.2.0
37 verbose git [
37 verbose git   'commit',
37 verbose git   '-F',
37 verbose git   '/tmp/2296cd43-25a0-418e-9189-86e3c3d7f5bf/lerna-commit.txt'
37 verbose git ]
38 silly gitTag @xxx/xxxxx@0.2.0
39 verbose git [ 'tag', '@xxx/xxxxx@0.2.0', '-m', '@xxx/xxxxx@0.2.0' ]
40 silly lifecycle No script for "postversion" in "@xxx/xxxxx", continuing
41 silly lifecycle No script for "postversion" in "xxx-packages", continuing
42 info git Pushing tags...
43 silly gitPush origin master
44 info publish Publishing packages to npm...
45 notice Skipping all user and access validation due to third-party registry
46 notice Make sure you're authenticated properly ¯\_(ツ)_/¯
47 warn ENOLICENSE Package @xxx/xxxxx is missing a license.
47 warn ENOLICENSE One way to fix this is to add a LICENSE.md file to the root of this repository.
47 warn ENOLICENSE See https://choosealicense.com for additional guidance.
48 silly getCurrentSHA
49 verbose getCurrentSHA 4afde950e84bbfaceeb3fd336adfd9c58a9d85c5
50 silly lifecycle No script for "prepublish" in "xxx-packages", continuing
51 silly lifecycle "prepare" starting in "xxx-packages"
52 info lifecycle xxx-packages@0.0.0~prepare: xxx-packages@0.0.0
53 verbose lifecycle xxx-packages@0.0.0~prepare: unsafe-perm in lifecycle true
54 verbose lifecycle xxx-packages@0.0.0~prepare: PATH: /usr/local/lib/node_modules/lerna/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/dev/Projects/XXX/xxx-packages/node_modules/.bin:/home/gilcrt/bin:./:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/dev/bin:/mnt/c/dev/Java/jdk-11/bin:/mnt/c/dev/Java/apache-maven-3.6.1/bin:/mnt/c/oracle/12.2.0/clientx64/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/OpenJDK/bin:/mnt/c/Program Files (x86)/Origin Client:/mnt/c/Program Files/nodejs/:/mnt/c/WINDOWS/system32/config/systemprofile/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files (x86)/Java/jre1.8.0_161/bin:/mnt/c/Program Files (x86)/OpenText/Viewer/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Webex/Plugins:/mnt/c/Users/gilcrt/AppData/Local/Microsoft/WindowsApps
55 verbose lifecycle xxx-packages@0.0.0~prepare: CWD: /mnt/c/dev/Projects/XXX/xxx-packages
56 silly lifecycle xxx-packages@0.0.0~prepare: Args: [ '-c', 'husky install' ]
57 silly lifecycle xxx-packages@0.0.0~prepare: Returned: code: 0  signal: null
58 silly lifecycle "prepare" finished in "xxx-packages"
59 silly lifecycle No script for "prepublishOnly" in "xxx-packages", continuing
60 silly lifecycle No script for "prepack" in "xxx-packages", continuing
61 verbose pack-directory dist/xxx-xxxxx
62 silly lifecycle No script for "prepublish" in "@xxx/xxxxx", continuing
63 silly lifecycle No script for "prepare" in "@xxx/xxxxx", continuing
64 silly lifecycle "prepublishOnly" starting in "@xxx/xxxxx"
65 info lifecycle @xxx/xxxxx@0.2.0~prepublishOnly: @xxx/xxxxx@0.2.0
66 verbose lifecycle @xxx/xxxxx@0.2.0~prepublishOnly: unsafe-perm in lifecycle true
67 verbose lifecycle @xxx/xxxxx@0.2.0~prepublishOnly: PATH: /usr/local/lib/node_modules/lerna/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/dev/Projects/XXX/xxx-packages/projects/xxx-xxxxx/node_modules/.bin:/home/gilcrt/bin:./:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/dev/bin:/mnt/c/dev/Java/jdk-11/bin:/mnt/c/dev/Java/apache-maven-3.6.1/bin:/mnt/c/oracle/12.2.0/clientx64/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/OpenJDK/bin:/mnt/c/Program Files (x86)/Origin Client:/mnt/c/Program Files/nodejs/:/mnt/c/WINDOWS/system32/config/systemprofile/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files (x86)/Java/jre1.8.0_161/bin:/mnt/c/Program Files (x86)/OpenText/Viewer/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Webex/Plugins:/mnt/c/Users/gilcrt/AppData/Local/Microsoft/WindowsApps
68 verbose lifecycle @xxx/xxxxx@0.2.0~prepublishOnly: CWD: /mnt/c/dev/Projects/XXX/xxx-packages/projects/xxx-xxxxx
69 silly lifecycle @xxx/xxxxx@0.2.0~prepublishOnly: Args: [ '-c', 'npm run lint && npm run test && npm run build' ]
70 silly lifecycle @xxx/xxxxx@0.2.0~prepublishOnly: Returned: code: 0  signal: null
71 silly lifecycle "prepublishOnly" finished in "@xxx/xxxxx"
72 silly lifecycle No script for "prepack" in "@xxx/xxxxx", continuing
73 silly lifecycle No script for "postpack" in "@xxx/xxxxx", continuing
74 verbose packed dist/xxx-xxxxx
75 silly lifecycle No script for "postpack" in "xxx-packages", continuing
76 verbose publish @xxx/xxxxx
77 silly FetchError: request to https://xxxxx.xxx.xx/repository/npm-private/@xxx%2fxxxxx failed, reason: self signed certificate in certificate chain
77 silly     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/lerna/node_modules/minipass-fetch/lib/index.js:97:14)
77 silly     at ClientRequest.emit (events.js:314:20)
77 silly     at TLSSocket.socketErrorListener (_http_client.js:427:9)
77 silly     at TLSSocket.emit (events.js:326:22)
77 silly     at emitErrorNT (internal/streams/destroy.js:92:8)
77 silly     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
77 silly     at processTicksAndRejections (internal/process/task_queues.js:84:21)
77 silly  FetchError: request to https://xxxxx.xxx.xx/repository/npm-private/@xxx%2fxxxxx failed, reason: self signed certificate in certificate chain
77 silly     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/lerna/node_modules/minipass-fetch/lib/index.js:97:14)
77 silly     at ClientRequest.emit (events.js:314:20)
77 silly     at TLSSocket.socketErrorListener (_http_client.js:427:9)
77 silly     at TLSSocket.emit (events.js:326:22)
77 silly     at emitErrorNT (internal/streams/destroy.js:92:8)
77 silly     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
77 silly     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
77 silly   code: 'SELF_SIGNED_CERT_IN_CHAIN',
77 silly   errno: 'SELF_SIGNED_CERT_IN_CHAIN',
77 silly   type: 'system'
77 silly }
78 error SELF_SIGNED_CERT_IN_CHAIN request to https://xxxxx.xxx.xx/repository/npm-private/@xxx%2fxxxxx failed, reason: self signed certificate in certificate chain
79 error FetchError: request to https://xxxxx.xxx.xx/repository/npm-private/@xxx%2fxxxxx failed, reason: self signed certificate in certificate chain
79 error     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/lerna/node_modules/minipass-fetch/lib/index.js:97:14)
79 error     at ClientRequest.emit (events.js:314:20)
79 error     at TLSSocket.socketErrorListener (_http_client.js:427:9)
79 error     at TLSSocket.emit (events.js:326:22)
79 error     at emitErrorNT (internal/streams/destroy.js:92:8)
79 error     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)

```
</p></details>

## Context
I try to publish a package to a private repository and I am not able to :)

**I tried with Lerna 3.22.1 and it worked fine, so this is a regression with the 4.0.0 version.**

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0|
| `npm --version`  | 6.11.3|
| `node --version` | v12.21.0|

Running on Debian Bullseye inside a WSL container on Windows 10

**Comment by 10hendersonm** [comment]
Temporary workaround:

```
npm config strictSSL false
```

I'm working up a PR for this right now.

**Comment by tugkankibar** [comment]
Same issue seems to be happening with yarn as well

**Comment by jamesg1** [comment]
Yeah I hit this today using a private registry. The usual SSL false checks not working so will try that workaround.
