### ISSUE TITLE
lerna --scope does not seem to work

### ISSUE THREAD

**Issue by jpSimkins** [lerna/lerna#2967]
## Expected Behavior
When running (this is a simple one to show that even this will not work as I was using a list of them originially and that is what the log file shows):
```
npm run --scope=@olympusat-devops/core test
```
I expect the test to only be run on the package I specified. This is not the case, it runs on all packages.

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "npmClient": "npm",
  "packages": [
    "accounts/**",
    "packages/**"
  ],
  "command": {
    "publish": {
      "conventionalCommits": true,
      "message": "chore(release): publish",
      "ignoreChanges": [
        "accounts/**"
      ]
    }
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/jpsimkins/.nvm/versions/node/v14.17.4/bin/node',
1 verbose cli   '/home/jpsimkins/.nvm/versions/node/v14.17.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   '--scope={@olympusat-devops/core',
1 verbose cli   '@olympusat-devops/oly-bastion',
1 verbose cli   '@olympusat-devops/oly-cloudfront-templates',
1 verbose cli   '@olympusat-devops/oly-efs',
1 verbose cli   '@olympusat-devops/oly-pipeline',
1 verbose cli   '@olympusat-devops/oly-pipeline-default-image',
1 verbose cli   '@olympusat-devops/oly-pipeline-templates',
1 verbose cli   '@olympusat-devops/oly-rds-wordpress',
1 verbose cli   '@olympusat-devops/oly-s3-replication-destination',
1 verbose cli   '@olympusat-devops/oly-s3-replication-source',
1 verbose cli   '@olympusat-devops/oly-vpc',
1 verbose cli   '@olympusat-devops/oly-web-bucket}',
1 verbose cli   'test'
1 verbose cli ]
2 info using npm@6.14.14
3 info using node@v14.17.4
4 verbose stack Error: missing script: @olympusat-devops/oly-bastion
4 verbose stack     at run (/home/jpsimkins/.nvm/versions/node/v14.17.4/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /home/jpsimkins/.nvm/versions/node/v14.17.4/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /home/jpsimkins/.nvm/versions/node/v14.17.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack     at /home/jpsimkins/.nvm/versions/node/v14.17.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/home/jpsimkins/.nvm/versions/node/v14.17.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/home/jpsimkins/.nvm/versions/node/v14.17.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/home/jpsimkins/.nvm/versions/node/v14.17.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack     at /home/jpsimkins/.nvm/versions/node/v14.17.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:281:12
4 verbose stack     at /home/jpsimkins/.nvm/versions/node/v14.17.4/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
5 verbose cwd /home/jpsimkins/DevOps/oly-iac-mono-repo/aws/development
6 verbose Linux 5.11.0-25-generic
7 verbose argv "/home/jpsimkins/.nvm/versions/node/v14.17.4/bin/node" "/home/jpsimkins/.nvm/versions/node/v14.17.4/bin/npm" "run" "--scope={@olympusat-devops/core" "@olympusat-devops/oly-bastion" "@olympusat-devops/oly-cloudfront-templates" "@olympusat-devops/oly-efs" "@olympusat-devops/oly-pipeline" "@olympusat-devops/oly-pipeline-default-image" "@olympusat-devops/oly-pipeline-templates" "@olympusat-devops/oly-rds-wordpress" "@olympusat-devops/oly-s3-replication-destination" "@olympusat-devops/oly-s3-replication-source" "@olympusat-devops/oly-vpc" "@olympusat-devops/oly-web-bucket}" "test"
8 verbose node v14.17.4
9 verbose npm  v6.14.14
10 error missing script: @olympusat-devops/oly-bastion
11 verbose exit [ 1, true ]
```
</p></details>

<details><summary>Folder Structure</summary><p>

```text
├── accounts
│   ├── olympusat-development-dev
│   ├── README.md
│   └── us-east-1/
│       ├── cdk.context.json
│       ├── cdk.json
│       ├── cdk.out
│       │   └── ...
│       ├── jest.config.js
│       ├── node_modules
│       │   └── @olympusat-devops
│       │       ├── core -> ../../../../../packages/core
│       │       ├── oly-bastion -> ../../../../../packages/oly-bastion
│       │       ├── oly-efs -> ../../../../../packages/oly-efs
│       │       ├── oly-pipeline -> ../../../../../packages/oly-pipeline
│       │       ├── oly-pipeline-default-image -> ../../../../../packages/oly-pipeline-default-image
│       │       ├── oly-pipeline-templates -> ../../../../../packages/oly-pipeline-templates
│       │       ├── oly-rds-wordpress -> ../../../../../packages/oly-rds-wordpress
│       │       ├── oly-s3-replication-destination -> ../../../../../packages/oly-s3-replication-destination
│       │       ├── oly-s3-replication-source -> ../../../../../packages/oly-s3-replication-source
│       │       ├── oly-vpc -> ../../../../../packages/oly-vpc
│       │       └── oly-web-bucket -> ../../../../../packages/oly-web-bucket
│       ├── package.json
│       ├── README.md
│       ├── src
│       │   ├── index.ts
│       │   └── stacks
│       │       └── ...
│       ├── tests
│       │   └── ...
│       ├── tsconfig.dev.json
│       └── tsconfig.json
├── lerna.json
├── node_modules
│   ├── ...
├── package.json
├── package-lock.json
├── packages
│   ├── core
│   ├── oly-bastion
│   ├── oly-cloudfront-templates
│   ├── oly-efs
│   ├── oly-pipeline
│   ├── oly-pipeline-default-image
│   ├── oly-pipeline-templates
│   ├── oly-rds-wordpress
│   ├── oly-s3-replication-destination
│   ├── oly-s3-replication-source
│   ├── oly-vpc
│   ├── oly-web-bucket
│   └── README.md
├── README.md
└── tsconfig.json
```
</p></details>

## Context

I am trying to run tests on a specific set of packages. What I need is what was indicated to not be implemented by issue #1370

I have two directories that are:
1. `accounts` that are used for testing the packages for development 
    - This is IaC so I test it before I publish the packages to ensure it builds exactly what I want
    - This needs to be linked to the local packages to simplify development
2. `packages` the actual packages that are built and need to be tested

When I run tests on all packages, it also runs tests on the accounts. Sure, I can rename the script but that is not ideal to me. Ideally, I would prefer to use `--scope` to restrict what is run. I have yet to get this working and I have tried numerous different methods to get this to work. I have tried with the full package name (e.g. `@olympusat-devops/core`) and I have tried with the name after the company namespace (e.g. `core`). Neither has worked for me.

I only have the `accounts/*` added to `packages` as this is the only way to link the local packages. Otherwise, I have to do my own npm install and link local packages myself that is not ideal for me. Unless I am missing something, this is the only way to accomplish this by using `lerna bootstrap --force-local --hoist`

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `npm --version`  | 6.14.14 |
| `yarn --version` | N/A |
| `node --version` | v14.17.4 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Ubuntu | 20.04 |

**Comment by jpSimkins** [comment]
stupid me... I used `npm` when I should be using `lerna`...
