### ISSUE TITLE
Error upon adding two or more `--dist-tag` calls

### ISSUE THREAD

**Issue by JackHowa** [lerna/lerna#3061]
## Expected Behavior

`npx lerna publish 0.0.0-test-tag.f --no-git-tag-version --no-push --dist-tag test-tag --dist-tag test-tag-2  --canary` 

I would expect two dist tags to be added `test-tag` and test-tag-2`. However, I'm getting an error: 

```
lerna ERR! TypeError: distTag.trim is not a function
lerna ERR!     at PublishCommand.initialize (/Users/howardj/sites/fusion-theme-blocks/node_modules/@lerna/publish/index.js:143:36)
lerna ERR! lerna distTag.trim is not a function
```

## Current Behavior

One dist-tag only available to be added 

## Possible Solution
Two or more dist-tags able to be added 

## Steps to Reproduce (for bugs)

1. `npx lerna publish 0.0.0-test-tag.f --no-git-tag-version --no-push --dist-tag test-tag --dist-tag test-tag-2  --canary`

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "blocks/*",
    "components/*"
  ],
  "version": "5.14.1",
  "ignoreChanges": [
    "**/node_modules/**",
    "**/package-lock.json"
  ],
  "version": "independent",
  "command": {
    "publish": {
      "ignoreChanges": [
        "package.json",
        "CHANGELOG.md",
        "package-lock.json"
      ],
      "conventionalCommits": true,
      "message": "chore(release): publish",
      "registry": "https://npm.pkg.github.com",
      "allowBranch": [
        "stable",
        "beta",
        "rc",
        "canary"
      ]
    }
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv {
0 silly argv   _: [ 'publish' ],
0 silly argv   'git-tag-version': false,
0 silly argv   gitTagVersion: false,
0 silly argv   push: false,
0 silly argv   'dist-tag': [ 'test-tag', 'test-tag-2' ],
0 silly argv   distTag: [ 'test-tag', 'test-tag-2' ],
0 silly argv   canary: true,
0 silly argv   c: true,
0 silly argv   composed: 'publish',
0 silly argv   lernaVersion: '4.0.0',
0 silly argv   '$0': 'node_modules/.bin/lerna',
0 silly argv   bump: '0.0.0-test-tag.f'
0 silly argv }
1 notice cli v4.0.0
2 verbose rootPath /Users/howardj/sites/fusion-theme-blocks
3 info versioning independent
4 info canary enabled
5 verbose session 11f33b6a9ac66a41
6 verbose user-agent lerna/4.0.0/node@v12.22.1+x64 (darwin)
7 error TypeError: distTag.trim is not a function
7 error     at PublishCommand.initialize (/Users/howardj/sites/fusion-theme-blocks/node_modules/@lerna/publish/index.js:143:36)
```
</p></details>

## Context
We're trying to get two release channels in sync via dist-tags

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 6.14.12 |
| `node --version` | v12.22.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by JackHowa** [comment]
Figured out an alternate solution with tagging
