### ISSUE TITLE
[Question] --scope can't be applied twice in the same command

### ISSUE THREAD

**Issue by ianwremmel** [lerna/lerna#308]
For example

```
lerna exec --scope category-a* --scope category-b* pwd
```

fails with 

```
Lerna v2.0.0-beta.25
Scoping to packages that match 'category-a*,category-b*'
Errored while running ExecCommand.initialize
TypeError: glob pattern string required
    at minimatch (/Users/ian/projects/spark-js-sdk/node_modules/lerna/node_modules/minimatch/minimatch.js:94:11)
    at /Users/ian/projects/spark-js-sdk/node_modules/lerna/lib/PackageUtilities.js:117:44
    at Array.filter (native)
    at Function.filterPackages (/Users/ian/projects/spark-js-sdk/node_modules/lerna/lib/PackageUtilities.js:113:29)
    at ExecCommand.initialize (/Users/ian/projects/spark-js-sdk/node_modules/lerna/lib/commands/ExecCommand.js:57:54)
    at ExecCommand._attempt (/Users/ian/projects/spark-js-sdk/node_modules/lerna/lib/Command.js:157:21)
    at ExecCommand.runCommand (/Users/ian/projects/spark-js-sdk/node_modules/lerna/lib/Command.js:141:12)
    at ExecCommand.run (/Users/ian/projects/spark-js-sdk/node_modules/lerna/lib/Command.js:65:12)
    at Object.<anonymous> (/Users/ian/projects/spark-js-sdk/node_modules/lerna/bin/lerna.js:58:11)
    at Module._compile (module.js:410:26)
```

which appears to be minimatch seeing that as a single string instead of an array of strings.

**Comment by rygine** [comment]
@ianwremmel what about applying a more complex glob to get the desired effect?

`lerna exec --scope 'category-@(a|b)*' pwd`

**Comment by ianwremmel** [comment]
Before I saw your response, I ended up just using bash, but after experimenting now, it doesn't look like that'll work. The following line doesn't match anything even though just just `bin` and just `test-helper` do

```
lerna -- exec pwd --scope "@ciscospark/(bin|test-helper)-*"
```

(The repo in question is https://github.com/ciscospark/spark-js-sdk)

Like I said, I've already solved it for myself so there's no major hurry from my end, but it seems like there's either a bug or some missing documentation here somewhere.

**Comment by rygine** [comment]
@ianwremmel update your glob

```sh
➜  spark-js-sdk git:(master) ✗ lerna exec pwd --scope "@ciscospark/@(bin|test-helper)-*"
Lerna v2.0.0-beta.28
Scoping to packages that match '@ciscospark/@(bin|test-helper)-*'
/Users/ry/Projects/spark-js-sdk/packages/bin-sauce-connect
/Users/ry/Projects/spark-js-sdk/packages/bin-walk
/Users/ry/Projects/spark-js-sdk/packages/test-helper-automation
/Users/ry/Projects/spark-js-sdk/packages/test-helper-chai
/Users/ry/Projects/spark-js-sdk/packages/test-helper-file
/Users/ry/Projects/spark-js-sdk/packages/test-helper-make-local-url
/Users/ry/Projects/spark-js-sdk/packages/test-helper-mocha
/Users/ry/Projects/spark-js-sdk/packages/test-helper-mock-spark
/Users/ry/Projects/spark-js-sdk/packages/test-helper-retry
/Users/ry/Projects/spark-js-sdk/packages/test-helper-server
/Users/ry/Projects/spark-js-sdk/packages/test-helper-sinon
/Users/ry/Projects/spark-js-sdk/packages/test-helper-test-users
```

**Comment by Guria** [comment]
Have to define multiple bootstrap calls because I am not able to list all interested packages in one glob.
https://github.com/cerebral/cerebral/blob/b2be293f037aa2244fd6b3782c778bc6ef042c02/.travis.yml#L28-L32

**Comment by doug-wade** [comment]
@Guria you should be able to use a more complex, something like 
```
lerna bootstrap --scope "(function-tree|cerebral|cerebral-forms|cerebral-provider-http|cerebral-router"
```
