### ISSUE TITLE
error when package has no name

### ISSUE THREAD

**Issue by trusktr** [lerna/lerna#3086]
An error is thrown when a package has no `name` field in its package.json:

```
lerna ERR! TypeError: Cannot read properties of undefined (reading 'split')
lerna ERR!     at Minimatch.match (/home/trusktr/src/lume+lume/node_modules/minimatch/minimatch.js:743:9)
lerna ERR!     at /home/trusktr/src/lume+lume/node_modules/minimatch/minimatch.js:717:15
lerna ERR!     at Array.filter (<anonymous>)
lerna ERR!     at Function.minimatch.match (/home/trusktr/src/lume+lume/node_modules/minimatch/minimatch.js:716:15)
lerna ERR!     at module.exports (/home/trusktr/src/lume+lume/node_modules/multimatch/index.js:25:39)
lerna ERR!     at filterPackages (/home/trusktr/src/lume+lume/node_modules/@lerna/filter-packages/filter-packages.js:47:28)
lerna ERR! lerna Cannot read properties of undefined (reading 'split')
```

In my case, the package is a root package, not used by anything else (f.e., `docs/` folder that has project documentation, not a library).

## Expected Behavior

It shouldn't fail, and the package should result in dependencies being linked in.

## Current Behavior

It fails because the `pnames` array passed to `multimatch` has an `undefined` value.

## Possible Solution

Not sure. Some sort of special handling for non-name projects. I think it should be fine, and if they have no name, then simply nothing else can depend on them, but dependencies of the no-name project can still be linked in.

## Steps to Reproduce (for bugs)

Make a package with no `name` field, try to bootstrap.

The rest of the template was irrelevant.

## Workaround

Simple: just add a `name` to the project's package.json.

**Comment by rake7h** [comment]
issue still exist on v6.4.1

**Comment by JamesHenry** [comment]
Hi Folks,

This issue related to the legacy package management capabilities of Lerna. The world in which Lerna had to manage package installation and linking concerns because of gaps in the ecosystem no longer exists, we are blessed to have many great options now, not just `npm` (which has also massively improved since the early days).

In June 2023, in Lerna `7.0.0`, we removed the `lerna bootstrap`, `lerna add` and `lerna link` commands in Lerna by default. Over two years later, in September 2025 (Lerna `9.0.0`), the commands were finally fully removed.

We provided some guidance at the time on how to migrate existing codebases to use native package manager features here: https://lerna.js.org/docs/legacy-package-management

I'll close this one as no action is applicable, but please always feel free to open a fresh issue giving as much context as possible when using the latest and greatest and we'll take a look. I'm making sure we close older issues like this one to free up bandwidth to make sure we tackle what matters most to users in 2026.

Many thanks for your contributions to Lerna!
