### ISSUE TITLE
4.0.0 can't import package

### ISSUE THREAD

**Issue by chendishen** [lerna/lerna#3093]
## Expected Behavior
lerna import D:\xxx --flatten --max-buffer=10000000000000000000000000
I hope it can be imported normally

## Current Behavior
lerna ERR! import Rolling back to previous HEAD (commit ba7fc267a19fbedbfa85d4221c93639c50e747f5)
lerna ERR! Error: Command failed with exit code 128: git am --abort
lerna ERR! fatal: Resolve operation not in progress, we are not resuming.

## Possible Solution
 --flatten and --max-buffer can't fixed this

## Steps to Reproduce (for bugs)
1.lerna init --independent    
2.lerna import D:\xxx --flatten --max-buffer=10000000000000000000000000

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv {
0 silly argv   _: [ 'import' ],
0 silly argv   flatten: true,
0 silly argv   'max-buffer': 1e+25,
0 silly argv   maxBuffer: 1e+25,
0 silly argv   lernaVersion: '4.0.0',
0 silly argv   '$0': 'C:\\Users\\chends\\AppData\\Roaming\\npm\\node_modules\\lerna\\cli.js',
0 silly argv   dir: 'D:\\workplace\\wx-material'
0 silly argv }
1 notice cli v4.0.0
2 verbose rootPath D:\workplace\wx-material-lerna
3 info versioning independent
4 info About to import 531 commits from D:\workplace\wx-material into packages\wx-material
5 info 10a8f267
6 info 83308ce8
7 info fd11360e
8 info f84ae084
9 info 087fddbf
10 info c8e08755
11 info 1472bbae
12 info 35503737
13 info 60483572
14 info 94b69aba
15 info 94a05936
16 info 1cdc648a
17 info dc5d8868
18 info 58fac6b2
19 info 0bb2ae90
20 info 16097dc8
21 info 1283dc16
22 info 32d7b7cf
23 info a1f91599
24 info 7137dac5
25 info f8db4d68
26 info 8fa5e9a1
27 info 2176de09
28 info dba44ccc
29 info 18673a04
30 info 4df5a80a
31 info 3300f1f4
32 info e1df4377
33 info 6a42b73b
34 info da275a80
35 info cb5c081a
36 info b1eb87e9
37 info 1491c01b
38 info 262ab006
39 info 0dc96712
40 info 5716d569
41 info f9a0c8df
42 error import Rolling back to previous HEAD (commit ba7fc267a19fbedbfa85d4221c93639c50e747f5)
43 error Error: Command failed with exit code 128: git am --abort
43 error fatal: Resolve operation not in progress, we are not resuming.
43 error     at makeError (D:\workplace\wx-material-lerna\node_modules\execa\lib\error.js:60:11)
43 error     at Function.module.exports.sync (D:\workplace\wx-material-lerna\node_modules\execa\index.js:194:17)
43 error     at Object.execSync (D:\workplace\wx-material-lerna\node_modules\@lerna\child-process\index.js:39:16)
43 error     at ImportCommand.execSync (D:\workplace\wx-material-lerna\node_modules\@lerna\import\index.js:141:25)
43 error     at D:\workplace\wx-material-lerna\node_modules\@lerna\import\index.js:280:14

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0|
| `npm --version`  | 6.14.14|
| `yarn --version` | 1.22.11|
| `node --version` | v14.17.5|

**Comment by ghiculescualexandru** [comment]
after lerna init, you need to commit the local changes for the momorepo and then try to import

**Comment by JamesHenry** [comment]
I'm sorry @ghiculescualexandru I'm not 100% clear on what you are reporting here.

Is the summary of your report that you wish you didn't have to commit outstanding changes in your git working tree before running `lerna import`?

(One other thing I would say is that you should not be initializing a new lerna repo with an old major version, always use the latest major version whenever possible)

**Comment by JamesHenry** [comment]
Closing as stale
