### ISSUE TITLE
[HELP] Using lerna-managed vue or react projects, an error is reported after ssr is enabled and packaged

### ISSUE THREAD

**Issue by see** [lerna/lerna#3100]
https://github.com/see/ssr-demo

## Current Behavior

Using lerna-managed vue or react projects, an error is reported after ssr is enabled and packaged
```
(node:97731) UnhandledPromiseRejectionWarning: Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at R (/Users/ying/workspace/FEProjects/ssr-demo/dist/admin-react/node/static/js/main.01e60cfb.js:2:5394)
    at t.useContext (/Users/ying/workspace/FEProjects/ssr-demo/dist/admin-react/node/static/js/main.01e60cfb.js:2:7108)
    at C (/Users/ying/workspace/FEProjects/ssr-demo/dist/admin-react/node/static/js/main.01e60cfb.js:2:14117)
    at A (/Users/ying/workspace/FEProjects/ssr-demo/dist/admin-react/node/static/js/main.01e60cfb.js:2:15285)
    at processChild (/Users/ying/workspace/FEProjects/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/ying/workspace/FEProjects/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/ying/workspace/FEProjects/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/ying/workspace/FEProjects/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/Users/ying/workspace/FEProjects/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at /Users/ying/workspace/FEProjects/ssr-demo/server2.js:29:22
(Use `node --trace-warnings ...` to show where the warning was created)
(node:97731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

## Steps to Reproduce (for bugs)

1. yarn install
2. yarn build:admin-react
3. node server2

**Comment by see** [comment]
#[vuejs/core#5641](https://github.com/vuejs/core/issues/5641)
