### ISSUE TITLE
Lerna with Node 16 does not Symlink Peer Dependent packages

### ISSUE THREAD

**Issue by Dipak1991** [lerna/lerna#3207]
## Current Behavior

When we have peer dependency on local package npm bootstrap fails.  It basically tried to download the package instead of symlinking local package. 

```
D:\Git\lerna-peer-dep-issue>npm i

> postinstall
> npx lerna bootstrap -- --stream

lerna notice cli v5.1.6
lerna info Bootstrapping 3 packages
lerna info Installing external dependencies
lerna ERR! npm install --stream exited 1 in 'b'
lerna ERR! npm install --stream stderr:
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: b@1.0.0
npm WARN Found: inneraaa@undefined
npm WARN node_modules/inneraaa
npm WARN   peer inneraaa@">=1.0.0" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer inneraaa@">=1.0.0" from the root project
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/inneraaa - Not found
npm ERR! 404
npm ERR! 404  'inneraaa@>=1.0.0' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\91909\AppData\Local\npm-cache\_logs\2022-06-27T12_09_22_055Z-debug-0.log
lerna ERR! npm install --stream exited 1 in 'b'
npm ERR! code 1
npm ERR! path D:\Git\lerna-peer-dep-issue
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\91909\AppData\Local\Temp\postinstall-1656331754037.cmd

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\91909\AppData\Local\npm-cache\_logs\2022-06-27T12_09_10_208Z-debug-0.log
```

## Expected Behavior

Peer dependencies should also be symlinked while bootstrapping sub packages.

## Steps to Reproduce

Clone the repository and just run npm i. 

Repo - https://github.com/Dipak1991/lerna-peer-dep-issue

### Lerna Configuration

```json

{
  "packages": ["packages/*"],
  "useNx": false,
  "version": "0.0.0"
}
```

### Environment

  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.13.1 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.22.0.
  npmPackages:
    lerna: ^5.1.6 => 5.1.6

### Lerna log

```
0 silly argv {
0 silly argv   _: [ 'bootstrap' ],
0 silly argv   '--': [ '--stream' ],
0 silly argv   lernaVersion: '5.1.6',
0 silly argv   '$0': 'node_modules\\lerna\\cli.js'
0 silly argv }
1 notice cli v5.1.6
2 verbose rootPath D:\Git\lerna-peer-dep-issue
3 silly npmConfig {
3 silly npmConfig   registry: undefined,
3 silly npmConfig   npmClient: 'npm',
3 silly npmConfig   npmClientArgs: [ '--stream' ],
3 silly npmConfig   mutex: undefined
3 silly npmConfig }
4 info Bootstrapping 3 packages
5 verbose lifecycle preinstall
6 silly lifecycle No script for "preinstall" in "b", continuing
7 silly lifecycle No script for "preinstall" in "inneraaa", continuing
8 silly lifecycle No script for "preinstall" in "c", continuing
9 silly hasDependencyInstalled b react
10 silly hasDependencyInstalled inneraaa react
11 silly hasDependencyInstalled b react-dom
12 silly hasDependencyInstalled inneraaa react-dom
13 silly root dependencies {}
14 silly leaf dependencies {}
15 info Installing external dependencies
16 verbose actions 2 actions, concurrency 8
17 silly npmInstallDependencies b [ 'react@17.0.0', 'react-dom@17.0.0' ]
18 silly npmInstallDependencies backup D:\Git\lerna-peer-dep-issue\packages\b\package.json
19 silly npmInstallDependencies inneraaa [ 'react@17.0.0', 'react-dom@17.0.0' ]
20 silly npmInstallDependencies backup D:\Git\lerna-peer-dep-issue\packages\inneraaa\package.json
21 silly npmInstallDependencies writing tempJson {
21 silly npmInstallDependencies   name: 'inneraaa',
21 silly npmInstallDependencies   version: '1.0.0',
21 silly npmInstallDependencies   description: '',
21 silly npmInstallDependencies   main: 'index.js',
21 silly npmInstallDependencies   dependencies: { react: '17.0.0', 'react-dom': '17.0.0' },
21 silly npmInstallDependencies   author: '',
21 silly npmInstallDependencies   license: 'ISC'
21 silly npmInstallDependencies }
22 silly npmInstallDependencies writing tempJson {
22 silly npmInstallDependencies   name: 'b',
22 silly npmInstallDependencies   version: '1.0.0',
22 silly npmInstallDependencies   description: '',
22 silly npmInstallDependencies   main: 'index.js',
22 silly npmInstallDependencies   dependencies: { react: '17.0.0', 'react-dom': '17.0.0' },
22 silly npmInstallDependencies   peerDependencies: { inneraaa: '>=1.0.0' },
22 silly npmInstallDependencies   author: '',
22 silly npmInstallDependencies   license: 'ISC'
22 silly npmInstallDependencies }
23 silly getNpmExecOpts D:\Git\lerna-peer-dep-issue\packages\b undefined
24 silly npmInstall [ 'npm', [ 'install', '--stream' ] ]
25 silly getNpmExecOpts D:\Git\lerna-peer-dep-issue\packages\inneraaa undefined
26 silly npmInstall [ 'npm', [ 'install', '--stream' ] ]
27 silly npmInstallDependencies cleanup D:\Git\lerna-peer-dep-issue\packages\inneraaa\package.json
28 error Error: ENOENT: no such file or directory, rename 'D:\Git\lerna-peer-dep-issue\packages\inneraaa\package.json.lerna_backup' -> 'D:\Git\lerna-peer-dep-issue\packages\inneraaa\package.json'
28 error     at Object.renameSync (node:fs:980:3)
28 error     at cleanup (D:\Git\lerna-peer-dep-issue\node_modules\@lerna\npm-install\npm-install.js:70:10)
28 error     at done (D:\Git\lerna-peer-dep-issue\node_modules\@lerna\npm-install\npm-install.js:78:7)
28 error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by ghiscoding** [comment]
as mentioned by original Lerna's author in this recent [comment](https://github.com/lerna/lerna/discussions/3140#discussioncomment-3033079) `bootstrap` should be deprecated in the future, basically you don't need `lerna bootstrap` anymore since all package managers support workspaces and do a better job at linking than Lerna could do with bootstrap. You seem to be using Yarn classic, if that's the case then consider using [yarn workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/) and also enable `--use-workspaces` flag and you should have better result.

**Comment by Squad1991** [comment]
@ghiscoding - I am using npm 8. I agree that bootstrap will be deprecated in future but for now is there any workaround to fix this issue?

**Comment by dls314** [comment]
@Squad1991 - Does bootstrap work for you if you include peer dependencies as dev dependencies?

**Comment by JamesHenry** [comment]
Hi Folks,

This issue related to the legacy package management capabilities of Lerna. The world in which Lerna had to manage package installation and linking concerns because of gaps in the ecosystem no longer exists, we are blessed to have many great options now, not just `npm` (which has also massively improved since the early days).

In June 2023, in Lerna `7.0.0`, we removed the `lerna bootstrap`, `lerna add` and `lerna link` commands in Lerna by default. Over two years later, in September 2025 (Lerna `9.0.0`), the commands were finally fully removed.

We provided some guidance at the time on how to migrate existing codebases to use native package manager features here: https://lerna.js.org/docs/legacy-package-management

I'll close this one as no action is applicable, but please always feel free to open a fresh issue giving as much context as possible when using the latest and greatest and we'll take a look. I'm making sure we close older issues like this one to free up bandwidth to make sure we tackle what matters most to users in 2026.

Many thanks for your contributions to Lerna!
