### ISSUE TITLE
leran useNx  v5.1.6 Error: PropertyNameExpected in tsconfig.json at position 

### ISSUE THREAD

**Issue by DreamPWJ** [lerna/lerna#3219]
```sh
lerna notice cli v5.1.6
lerna info versioning independent
lerna ERR! Error: PropertyNameExpected in E:\repo\react-frontend-monorepo\tsconfig.base.json at position 6376
lerna ERR!     at parseJson (E:\repo\react-frontend-monorepo\node_modules\nx\src\utils\json.js:23:15)
lerna ERR!     at readJsonFile (E:\repo\react-frontend-monorepo\node_modules\nx\src\utils\fileutils.js:23:37)
lerna ERR!     at readRootTsConfig (E:\repo\react-frontend-monorepo\node_modules\nx\src\project-graph\build-project-graph.js:245:45)
lerna ERR!     at E:\repo\react-frontend-monorepo\node_modules\nx\src\project-graph\build-project-graph.js:38:30
lerna ERR!     at Generator.next (<anonymous>)
lerna ERR!     at E:\repo\react-frontend-monorepo\node_modules\tslib\tslib.js:118:75
lerna ERR!     at new Promise (<anonymous>)
lerna ERR!     at Object.__awaiter (E:\repo\react-frontend-monorepo\node_modules\tslib\tslib.js:114:16)
lerna ERR!     at buildProjectGraphUsingProjectFileMap (E:\repo\react-frontend-monorepo\node_modules\nx\src\project-graph\build-project-graph.js:33:20)
lerna ERR! lerna PropertyNameExpected in E:\repo\react-frontend-monorepo\tsconfig.base.json at position 6376
lerna ERR! lerna
lerna ERR! lerna Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
lerna ERR! lerna If the error persists, please run "nx reset".
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@1.0.0 build:ts: `lerna run compile:ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the root@1.0.0 build:ts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2022-07-05T00_54_09_093Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@1.0.0 build:all: `npm run build:ts && npm run gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the root@1.0.0 build:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2022-07-05T00_54_09_272Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@1.0.0 bootstrap:all: `lerna bootstrap && npm run build:all`
npm ERR! Exit status 1
```

```jsonc
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */

    /* Basic Options */
    // "incremental": true,                         /* Enable incremental compilation */
    "target": "es2019",
    /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "esnext",
    /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    "lib": [
      "es2019",
      "dom"
    ],
    /* Specify library files to be included in the compilation. */
    "allowJs": true,
    /* Allow javascript files to be compiled. */
    // "checkJs": true,                             /* Report errors in .js files. */
    /* Specify JSX code generation: 'preserve', 'react-native', 'react', 'react-jsx' or 'react-jsxdev'. */
    "jsx": "react",
    "declaration": true,
    /* Generates corresponding '.d.ts' file. */
    "declarationMap": true,
    /* Generates a sourcemap for each corresponding '.d.ts' file. */
    "sourceMap": true,
    /* Generates corresponding '.map' file. */
    // "outFile": "./",                             /* Concatenate and emit output to single file. */
    // "outDir": "./",                              /* Redirect output structure to the directory. */
    // "rootDir": "./",                             /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    "composite": true,
    /* Enable project compilation */
    // "tsBuildInfoFile": "./",                     /* Specify file to store incremental compilation information */
    // "removeComments": true,                      /* Do not emit comments to output. */
    // "noEmit": true,                              /* Do not emit outputs. */
    "importHelpers": true,
    /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,                  /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,                     /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */

    /* Strict Type-Checking Options */
    "strict": false,
    /* Enable all strict type-checking options. */
    "noImplicitAny": false,
    /* Raise error on expressions and declarations with an implied 'any' type. */
    "strictNullChecks": true,
    /* Enable strict null checks. */
    // "strictFunctionTypes": true,                 /* Enable strict checking of function types. */
    // "strictBindCallApply": true,    WW             /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
    // "strictPropertyInitialization": trZue,        /* Enable strict checking of property initialization in classes. */
    "noImplicitThis": true,
    /* Raise error on 'this' expressions with an implied 'any' type. */
    // "alwaysStrict": true,                        /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    "noUnusedLocals": true,
    /* Report errors on unused locals. */
    "noUnusedParameters": true,
    /* Report errors on unused parameters. */
    "noImplicitReturns": true,
    /* Report error when not all code paths in function return a value. */
    "noFallthroughCasesInSwitch": true,
    /* Report errors for fallthrough cases in switch statement. */
    "noUncheckedIndexedAccess": true,
    /* Include 'undefined' in index signature results */
    // "noPropertyAccessFromIndexSignature": true,  /* Require undeclared properties from index signatures to use element accesses. */
    "importsNotUsedAsValues": "error",
    /* Module Resolution Options */
    "moduleResolution": "node",
    /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    "baseUrl": "./",
    /* Base directory to resolve non-absolute module names. */
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
    /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": [],                              /* List of root folders whose combined content represents the structure of the project at runtime. */
    // "typeRoots": [],                             /* List of folders to include type definitions from. */
    "types": [],
    /* Type declaration files to be included in compilation. */
    "allowSyntheticDefaultImports": true,
    /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "suppressImplicitAnyIndexErrors": true,
    /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    // "preserveSymlinks": true,                    /* Do not resolve the real path of symlinks. */
    // "allowUmdGlobalAccess": true,                /* Allow accessing UMD globals from modules. */

    /* Source Map Options */
    // "sourceRoot": "",                            /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                               /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,                     /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                       /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    // "experimentalDecorators": true,              /* Enables experimental support for ES7 decorators. */
    // "emitDecoratorMetadata": true,               /* Enables experimental support for emitting type metadata for decorators. */

    /* Advanced Options */
    "skipLibCheck": true,
    /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": false,
    /* Disallow inconsistently-cased references to the same file. */
  }
}
```

**Comment by JamesHenry** [comment]
@DreamPWJ Please take a look at how I have updated your embedded outputs/configs (using three backticks instead of one for multi-line blocks makes them render much more clearly).

I believe I can see the issue - you have a trailing comma after your final JSON property `"forceConsistentCasingInFileNames": false,`. Trailing commas are not valid in JSON. If you strip that trailing comma then this will likely fix the problem.

I will close this here, as there is nothing that can be done on the lerna side, because this is an error coming from within Nx's internals.

Therefore, if removing the trailing comma does not help please report this over on the Nx repo: [`nrwl/nx`](https://github.com/nrwl/nx)
