### ISSUE TITLE
packageConfigs getter silently fails if no root package.json can be found

### ISSUE THREAD

**Issue by donmahallem** [lerna/lerna#3272]
## Current Behavior

Currently https://github.com/lerna/lerna/blob/5cfcd3a3209be547c3f259220453e5fd620fa10b/core/project/index.js#L166-L173 just swallows the `Error: ENOENT: no such file or directory, open '[...]\package.json'` Error if the expected `package.json` file is not found under this path https://github.com/lerna/lerna/blob/5cfcd3a3209be547c3f259220453e5fd620fa10b/core/project/index.js#L151-L152

I will just crash with
```txt
TypeError: Cannot read properties of undefined (reading 'get')
      at Project.get packageConfigs [as packageConfigs] (node_modules\@lerna\project\index.js:124:23)
      at Project.get fileFinder [as fileFinder] (node_modules\@lerna\project\index.js:214:55)
```

## Expected Behavior

It should throw an exception that the expected package.json file was not found. I would like errors like that not to be swallowed like they are currently.

## Steps to Reproduce

Run getPackages static method from @lerna/project on a folder which doesn't contain a package.json right next to a lerna.json. Before `@lerna/project@5.3.0` this wasn't an issue as far as I can tell.

**Comment by JamesHenry** [comment]
Closing as stale, the current code throws `ENOPKG`
