### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by Rauno56** [lerna/lerna#3325]
## Current Behavior

Our CI started failing very recently installing lerna globally:
https://github.com/open-telemetry/opentelemetry-js-contrib/runs/8273293064?check_suite_focus=true

```
Run npm install -g lerna
/usr/local/bin/lerna -> /usr/local/lib/node_modules/lerna/cli.js

> @parcel/watcher@2.0.[4](https://github.com/open-telemetry/opentelemetry-js-contrib/runs/8273293064?check_suite_focus=true#step:4:5) install /usr/local/lib/node_modules/lerna/node_modules/@parcel/watcher
> node-gyp-build


> nx@14.7.0 postinstall /usr/local/lib/node_modules/lerna/node_modules/nx
> node ./bin/compute-project-graph

internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at validateString (internal/validators.js:124:11)
    at join (path.js:1148:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/lerna/node_modules/nx/src/daemon/tmp-dir.js:19:46)
    at Module._compile (internal/modules/cjs/loader.js:108[5](https://github.com/open-telemetry/opentelemetry-js-contrib/runs/8273293064?check_suite_focus=true#step:4:6):14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/lerna/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x[6](https://github.com/open-telemetry/opentelemetry-js-contrib/runs/8273293064?check_suite_focus=true#step:4:7)4"})

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2022-0[9](https://github.com/open-telemetry/opentelemetry-js-contrib/runs/8273293064?check_suite_focus=true#step:4:10)-09T15_21_[14](https://github.com/open-telemetry/opentelemetry-js-contrib/runs/8273293064?check_suite_focus=true#step:4:15)_[35](https://github.com/open-telemetry/opentelemetry-js-contrib/runs/8273293064?check_suite_focus=true#step:4:36)5Z-debug.log
Error: Process completed with exit code 1.
```

## Expected Behavior

This has run without any problems for years now.

## Steps to Reproduce

I haven't been able to repro locally yet. Seemed to arise with the release of `nx@14.7`.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "npm",
  "packages": [
    "packages/*",
    "metapackages/*",
    "plugins/node/*",
    "plugins/node/*/examples",
    "plugins/web/*",
    "plugins/web/*/examples",
    "propagators/*",
    "detectors/node/*"
  ],
  "version": "independent",
  "changelog": {
    "repo": "open-telemetry/opentelemetry-js-contrib",
    "labels": {
      "breaking": ":boom: Breaking Change",
      "bug": ":bug: (Bug Fix)",
      "core": ":wrench: Core",
      "document": ":books: (Refine Doc)",
      "enhancement": ":rocket: (Enhancement)",
      "feature-request": ":sparkles: (Feature)",
      "internal": ":house: Internal"
    },
    "cacheDir": ".changelog",
    "ignoreCommitters": [
      "github-actions"
    ]
  }
}
```

</p></details>

### Environment

```
  Environment info:

  System:
    OS: Linux 5.15 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.17 - /usr/local/bin/npm
  Utilities:
    Git: 2.20.1 - /usr/bin/git
```

**Comment by JamesHenry** [comment]
Sorry about that @Rauno56 please can you try rerunning it? There was a bug which should now have been fixed

**Comment by oreasek** [comment]
Hey, we've got this issue too here, rerunning it is not solving the issue

**Comment by JamesHenry** [comment]
@oreasek is it exactly the same scenario, with a global lerna install? Are you seeing 14.7.0 in your logs?

**Comment by oreasek** [comment]
> @oreasek is it exactly the same scenario, with a global lerna install? Are you seeing 14.7.0 in your logs?

it is a global install and I don't see **14.7.0**. I see **14.7.1**

**Comment by Rauno56** [comment]
Rerunning did not help me either: https://github.com/Rauno56/opentelemetry-js-contrib/runs/8276136351?check_suite_focus=true

**Comment by JamesHenry** [comment]
Thanks a lot @oreasek @Rauno56 - another patch has been released, please can you try again?

**Comment by oreasek** [comment]
> Thanks a lot @oreasek @Rauno56 - another patch has been released, please can you try again?

@JamesHenry on our end it is passing now, thanks for quick reaction :1st_place_medal:

**Comment by JamesHenry** [comment]
Thanks a lot for confirming so quickly as well!

@Rauno56 if you experience any more issues please feel free to reopen, but I think we should be good now

**Comment by Rauno56** [comment]
The last patch seems to have fixed it. Thanks, @JamesHenry, for resolving it so quick!

**Comment by JamesHenry** [comment]
Great, thanks for confirming!
