### ISSUE TITLE
lerna ERR! TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by zqinmiao** [lerna/lerna#3343]
## Current Behavior

There are two packages，`package-a` and `package-b`. 

`package-b`  dependencies `package-a`，using the Workspace protocol.

`package-b`
```json
{
"name": "package-b",
"version": "1.0.1",
"dependencies": {
    "package-a": "workspace:*"
  }
}
```

## Expected Behavior

Run  `npx lerna publish from-package`

Expected successful publish

## Steps to Reproduce

```bash
$ npx lerna publish from-package
lerna notice cli v5.5.2
lerna info versioning independent
lerna WARN Unable to determine published version, assuming "package-b" unpublished.

Found 1 package to publish:
 - package-b => 1.0.1

? Are you sure you want to publish these packages? Yes
lerna info publish Publishing packages to npm...
lerna WARN ENOLICENSE Package package-b is missing a license.
lerna WARN ENOLICENSE One way to fix this is to add a LICENSE.md file to the root of this repository.
lerna WARN ENOLICENSE See https://choosealicense.com for additional guidance.
lerna ERR! TypeError: Cannot read property 'version' of undefined
lerna ERR!     at /Users/xxx/node_modules/.pnpm/@lerna+package-graph@5.5.2/node_modules/@lerna/package-graph/index.js:80:37
lerna ERR!     at Array.forEach (<anonymous>)
lerna ERR!     at /Users/xxx/node_modules/.pnpm/@lerna+package-graph@5.5.2/node_modules/@lerna/package-graph/index.js:60:38
lerna ERR!     at Map.forEach (<anonymous>)
lerna ERR!     at new PackageGraph (/Users/xxx/node_modules/.pnpm/@lerna+package-graph@5.5.2/node_modules/@lerna/package-graph/index.js:49:10)
lerna ERR!     at new QueryGraph (/Users/xxx/node_modules/.pnpm/@lerna+query-graph@5.5.2/node_modules/@lerna/query-graph/query-graph.js:48:18)
lerna ERR!     at runTopologically (/Users/xxx/node_modules/.pnpm/@lerna+run-topologically@5.5.2/node_modules/@lerna/run-topologically/run-topologically.js:23:17)
lerna ERR!     at PublishCommand.topoMapPackages (/Users/xxx/node_modules/.pnpm/@lerna+publish@5.5.2/node_modules/@lerna/publish/index.js:639:12)
lerna ERR! lerna Cannot read property 'version' of undefined
```

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "useNx": true,
  "useWorkspaces": true,
  "npmClient": "pnpm",
  "version": "independent"
}
```

</p></details>

</p></details>

### Environment
* macOS Monterey 12.5, Apple M1 Pro
* node@v14.20.0
* pnpm@v7.9.0
* lerna@5.5.2

**Comment by gablabelle** [comment]
We have the same problem. Tested with both `lerna version` & `lerna publish`  locally and in our bitbucket pipeline.

```
pnpm -v
7.12.2
pnpm lerna -v
5.6.1
```

**Comment by fahslaj** [comment]
Hi everyone, thank you for your engagement on this issue. It has since been addressed in PR #3358. The problem should be fixed with Lerna version 5.6.2.

**Comment by zqinmiao** [comment]
> Hi everyone, thank you for your engagement on this issue. It has since been addressed in PR #3358. The problem should be fixed with Lerna version 5.6.2.

@fahslaj Thanks. I've tried,the problem has been solved in Lerna version 5.6.2

**Comment by changyoungoh** [comment]
@fahslaj It reproduces on version 6.0.1. Should I use version 5 ?

**Comment by GNARGNARDAVE** [comment]
Yeah, I see the same issue on 6.0.5
