### ISSUE TITLE
[Bug v6]: lerna run test 

### ISSUE THREAD

**Issue by deleonio** [lerna/lerna#3379]
Everything works - but ...

<img width="704" alt="image" src="https://user-images.githubusercontent.com/6279703/195969622-4e43d688-8682-4e04-b31f-b3d295f7b029.png">

`lerna.json`
```
{
	"packages": [
                ...
		"packages/create-kolibri",
                ...
	],
        ...
}

```

v5 only packages/create-kolibri/package.json was triggert

```
lerna notice cli v5.6.2
lerna info Executing command in 1 package: "npm run test"
```

v6 all package.json in packages/create-kolibri were triggert

```
lerna notice cli v6.0.1
Skipping project found at packages/create-kolibri/templates/next.js since project {{kebab name}} already exists at packages/create-kolibri/templates/angular! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/create-kolibri/templates/react since project {{kebab name}} already exists at packages/create-kolibri/templates/angular! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/create-kolibri/templates/solid since project {{kebab name}} already exists at packages/create-kolibri/templates/angular! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/create-kolibri/templates/static since project {{kebab name}} already exists at packages/create-kolibri/templates/angular! Specify a unique name for the project to allow Nx to differentiate between the two projects.

> @public-ui/components:test

> @public-ui/components@1.1.10-rc.0 test /Users/moppitz/Workspace/kolibri/lib/packages/library
> cross-env NODE_ENV=test stencil test --spec --json --outputFile jest-test-results.json
[05:44.1]  @stencil/core
[05:44.3]  v2.18.1 😛
[05:44.8]  testing spec files
[05:44.9]  jest args: --spec --json --outputFile jest-test-results.json
           --max-workers=8
```

**Comment by HitkoDev** [comment]
Same here.

It seems that NX tries to read projects from `angular.json`, ignoring `"packages"` config in `lerna.json`.

**Comment by MirKml** [comment]
As @HitkoDev describes, it seems that lerna ignores its own settings for package list and respects only weird angular.json.
If it's really true, it's bug which can stop people migrate to newly announced Nx usage in v6. I think.

**Comment by HitkoDev** [comment]
Here's a quick repro: https://stackblitz.com/edit/node-muuq3n?file=lerna.json

Running `yarn build` with Nx enabled throws the following error:
```
lerna run build
lerna notice cli v6.0.1
lerna ERR! Error: Invalid projects: @foo-org/foo-api, @foo-org/foo-lib
lerna ERR!     at checkForInvalidProjects (/home/projects/node-muuq3n/node_modules/nx/src/command-line/run-many.js:45:15)
lerna ERR!     at projectsToRun (/home/projects/node-muuq3n/node_modules/nx/src/command-line/run-many.js:38:5)
lerna ERR!     at eval (/home/projects/node-muuq3n/node_modules/nx/src/command-line/run-many.js:23:26)
lerna ERR!     at Generator.next (<anonymous>)
lerna ERR! lerna Invalid projects: @foo-org/foo-api, @foo-org/foo-lib
```

With Nx disabled it builds normally.

**Comment by JamesHenry** [comment]
Thanks a lot for the minimal repro @HitkoDev - the immediate workaround is to align the project names with the package names, but we know that is suboptimal.

We will add detection into the Nx task runner so that it knows when it is being used in the context of a standard Angular CLI workspace with lerna.

**Comment by fahslaj** [comment]
Closing this as it shouldn't be an issue with modern versions of Lerna and Nx.
