### ISSUE TITLE
Lerna v6 is not compatible with Node v12: `SyntaxError: Unexpected token '.'`

### ISSUE THREAD

**Issue by subzero10** [lerna/lerna#3394]
## Current Behavior

After upgrading to lerna v6 (from v5), we are getting the following error on our CI with node v12 when running `lerna bootstrap`:
```
SyntaxError: Unexpected token '.'
```

There are no errors when node v14 and v16, which points me to believe that lerna v6 is not compatible with node v12. If yes, was this intentional? Because I did not see anywhere in lerna changelog that node v12 is no longer supported (or did I miss it?).

## Expected Behavior

`lerna bootstrap` to complete without errors.

## Steps to Reproduce

Run lerna bootstrap in a repository with node v12.
You can see the CI failing [here](https://github.com/honeybadger-io/honeybadger-js/actions/runs/3344575223/jobs/5539082735).

### Failure Logs / Configuration

```
> root@undefined install /home/runner/work/honeybadger-js/honeybadger-js
> lerna bootstrap

/home/runner/work/honeybadger-js/honeybadger-js/node_modules/@lerna/package-graph/index.js:79
            if (depNode?.version) {
                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:[16](https://github.com/honeybadger-io/honeybadger-js/actions/runs/3344575223/jobs/5539082735#step:4:17))
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:[18](https://github.com/honeybadger-io/honeybadger-js/actions/runs/3344575223/jobs/5539082735#step:4:19))
    at Object.<anonymous> (/home/runner/work/honeybadger-js/honeybadger-js/node_modules/@lerna/query-graph/query-graph.js:3:26)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@undefined install: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the root@undefined install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/[20](https://github.com/honeybadger-io/honeybadger-js/actions/runs/3344575223/jobs/5539082735#step:4:21)[22](https://github.com/honeybadger-io/honeybadger-js/actions/runs/3344575223/jobs/5539082735#step:4:23)-10-[28](https://github.com/honeybadger-io/honeybadger-js/actions/runs/3344575223/jobs/5539082735#step:4:29)T10_05_20_016Z-debug.log
Error: Process completed with exit code 1.
```

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "useNx": false,
  "version": "4.6.1"
}
```

</p></details>

### Environment

I'm running this in Github Actions. This is the [workflow file](https://github.com/honeybadger-io/honeybadger-js/actions/runs/3344575223/workflow).

**Comment by subzero10** [comment]
Hmm, I went a bit further down the changelog and saw that node v12 support was stopped with lerna v5. Strangely, our CI did not complain until lerna v6.
