### ISSUE TITLE
Gitignored projects are not found in createProjectGraphAsync causing lerna invalid project error

### ISSUE THREAD

**Issue by simonireilly** [lerna/lerna#3416]
## Current Behavior

I create a new project in CI that is gitignored

This is to ensure my templating tool continues to produce valid valid new packages with my default tools

Because it is in the gitignore'd list of folders it is not found in `allProjects` 

```
Checking projects {
  nxArgs: {
    projects: [
      '@simon/apm',
      '@simon/cli',
      '@simon/contracts',
      '@simon/distroless',
      '@simon/example' // In gitignore
    ],
    target: 'test',
    outputStyle: 'dynamic',
    parallel: 999,
    nxBail: true,
    nxIgnoreCycles: true,
    skipNxCache: false,
    verbose: undefined,
    __overrides__: []
  },
  allProjects: [
    { name: '@simon/distroless', type: 'lib', data: [Object] },
    { name: '@simon/contracts', type: 'lib', data: [Object] },
    { name: '@simon/apm', type: 'lib', data: [Object] },
    { name: '@simon/cli', type: 'lib', data: [Object] }
  ]
}
```

## Expected Behavior

It should be possible to run lerna commands on folders even if they are in gitignore

## Steps to Reproduce

1. Create a new lerna monorepo
2. Create a package
3. Add it to the root .gitignore
4. Run `lerna run --parallel test`

Expect error:

```
lerna ERR! Error: Invalid projects: @simon/example
lerna ERR!     at checkForInvalidProjects (/Users/simonreilly/work/platform-node/node_modules/nx/src/command-line/run-many.js:48:15)
lerna ERR!     at projectsToRun (/Users/simonreilly/work/platform-node/node_modules/nx/src/command-line/run-many.js:38:5)
lerna ERR!     at /Users/simonreilly/work/platform-node/node_modules/nx/src/command-line/run-many.js:23:26
lerna ERR!     at Generator.next (<anonymous>)
lerna ERR! lerna Invalid projects: @simon/example
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "version": "0.2.0-beta.17",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "conventionalCommits": true,
      "yes": true,
      "registry": "https://npm.pkg.github.com/simon"
    }
  }
}

```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv {
0 silly argv   _: [ 'run' ],
0 silly argv   parallel: true,
0 silly argv   lernaVersion: '6.0.3',
0 silly argv   '$0': '/Users/simonreilly/work/platform-node/node_modules/.bin/lerna',
0 silly argv   script: 'test'
0 silly argv }
1 notice cli v6.0.3
2 verbose rootPath /Users/simonreilly/work/platform-node
3 verbose run nx.json was not found or is missing targetDefaults. Task dependencies will not be automatically included.
4 error Error: Invalid projects: @simon/example
4 error     at checkForInvalidProjects (/Users/simonreilly/work/platform-node/node_modules/nx/src/command-line/run-many.js:45:15)
4 error     at projectsToRun (/Users/simonreilly/work/platform-node/node_modules/nx/src/command-line/run-many.js:38:5)
4 error     at /Users/simonreilly/work/platform-node/node_modules/nx/src/command-line/run-many.js:23:26
4 error     at Generator.next (<anonymous>)

```

</p></details>

### Environment

 - Node v16.14.1
 - Lerna v6.0.3

**Comment by simonireilly** [comment]
There is a workaround to not exclude this in the `.gitignore` but use

```
.git/info/exclude
```

With the folder name.

I believe the root cause is that `createProjectGraphAsync` from nx does not find `.gitignore` folders. 

I am not using nx for caching so this is a side effect.

**Comment by Robloche** [comment]
I've got the same error with all my projects since the 6.0.3 update but none of them are in my `.gitignore`...

**Comment by simonireilly** [comment]
> I've got the same error with all my projects after updating from 6.0.1 to 6.0.2 (same issue with 6.0.3)  but none of them are in my `.gitignore`...
> 

Can you log the results of the all projects from the node_modules?

**Comment by simonireilly** [comment]
> I don't understand what you're asking for...

Fair point - I've assumed a lot of context.

Looking at this in more detail. Lerna passes a list of the projects it wants to run.

There is now a dependency on `nx` inside lerna that runs this code:

https://github.com/nrwl/nx/blob/32bec2a8bdc4b76eddc9c511c91dd17141555557/packages/nx/src/command-line/run-many.ts#L38

That graph does not return projects that are in .gitignore.

**Comment by Robloche** [comment]
In fact, after more tests, it appears that I updated nx from 15.0.10 to 15.0.13 at the same time and it seems it's the culprit. I downgraded nx back to 15.0.10 and now lerna 6.0.3 does not complain about my packages (just as previously).

So, my issue seems linked to nx instead of lerna.

**Comment by Robloche** [comment]
> @Robloche as you noted, your issue has nothing to do with this one.
> 
> @simonireilly This is exclusive an Nx concern, and has been raised to Victor Savkin as a use-case to consider. I'll leave this open in the meantime

Yes, but since the error message is similar, it could draw other people with my problem here. So I linked the issue to the correct repo.

**Comment by FreeFrags** [comment]
I can confirm this is an issue, i have a project in a folder 
/web/packages/myproject

and my git ignore has the following line
**/packages/*

running npx nx graph
wont show myproject

but if i add the following line to my gitignore
!web/packages/*

running npx nx graph
shows myproject as it should
