### ISSUE TITLE
Lerna publish doesn't follow the dependency order

### ISSUE THREAD

**Issue by TheHunterDog** [lerna/lerna#3471]
## Current Behavior
When publishing with ``lerna publish`` the dependancy's found in https://registry.npmjs.org wich is correct because I am uploading to a private registry.

## Expected Behavior

I would expect that `lerna publish` would go in order of the dependancy's

## Steps to Reproduce
1. build a component library in react with atomic pattern.
2. make molecules depend on atoms
3. Prepare private registry
4. Recive error that atom is not found in the [npmregistry](https://registry.npmjs.org)

~~The lerna repo will be added at a later date~~

https://github.com/TheHunterDog/Lerna-Issue-repro

### Failure Logs / Configuration

lerna ERR! lerna Command failed with exit code 1: npm install --package-lock-only --ignore-scripts
lerna ERR! lerna npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
lerna ERR! lerna npm ERR! code E404
lerna ERR! lerna npm ERR! 404 Not Found - GET https://registry.npmjs.org/@XXX%2foverviewlabel - Not found
lerna ERR! lerna npm ERR! 404
lerna ERR! lerna npm ERR! 404  '@XXX/overviewlabel@^1.0.5' is not in this registry.
lerna ERR! lerna npm ERR! 404
lerna ERR! lerna npm ERR! 404 Note that you can also install from a
lerna ERR! lerna npm ERR! 404 tarball, folder, http url, or git url.
lerna ERR! lerna
lerna ERR! lerna npm ERR! A complete log of this run can be found in:
lerna ERR! lerna npm ERR!     C:\Users\XXX\AppData\Local\npm-cache\_logs\2022-12-23T13_54_14_948Z-debug-0.log

<details><summary>lerna.json</summary><p>

```json
{
	"$schema": "node_modules/lerna/schemas/lerna-schema.json",
	"useWorkspaces": true,
	"version": "1.0.5",
	"command": {
		"publish": {
			"registry": "https://gitlab.com/api/v4/projects/XXX/packages/npm/"
		}
	}
}

```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv {
0 silly argv   _: [ 'version' ],
0 silly argv   lernaVersion: '6.1.0',
0 silly argv   '$0': '..\\..\\..\\AppData\\Roaming\\npm\\node_modules\\lerna\\cli.js'
0 silly argv }
1 notice cli v6.1.0
2 verbose rootPath C:\Users\xxx\Desktop\TaskerWebcomponents\xxx
3 info current version 1.0.4
4 silly isAnythingCommitted
5 verbose isAnythingCommitted 1
6 silly getCurrentBranch
7 verbose currentBranch development
8 silly remoteBranchExists
9 silly isBehindUpstream
10 silly isBehindUpstream development is behind origin/development by 0 commit(s) and ahead by 0
11 silly hasTags
12 verbose hasTags true
13 silly git-describe.sync "v1.0.4-2-g0606c6c" => {"lastTagName":"v1.0.4","lastVersion":"v1.0.4","refCount":"2","sha":"0606c6c","isDirty":false}
14 info Looking for changed packages since v1.0.4
15 silly checking diff packages/tasker-atoms/avatar
16 silly no diff found in @xxx/avatar
17 silly checking diff packages/tasker-atoms/badge
18 silly no diff found in @xxx/badge
19 silly checking diff packages/tasker-atoms/box
20 silly no diff found in @xxx/box
21 silly checking diff packages/tasker-atoms/button
22 silly no diff found in @xxx/button
23 silly checking diff packages/tasker-atoms/divider
24 silly no diff found in @xxx/divider
25 silly checking diff packages/tasker-atoms/icon
26 silly no diff found in @xxx/icon
27 silly checking diff packages/tasker-atoms/list
28 silly no diff found in @xxx/list
29 silly checking diff packages/tasker-atoms/logo
30 silly no diff found in @xxx/logo
31 silly checking diff packages/tasker-atoms/modal
32 silly no diff found in @xxx/modal
33 silly checking diff packages/tasker-atoms/overlay
34 silly no diff found in @xxx/overlay
35 silly checking diff packages/tasker-atoms/placeholder
36 silly no diff found in @xxx/placeholder
37 silly checking diff packages/tasker-atoms/typography
38 silly no diff found in @xxx/typography
39 silly checking diff packages/xxx/molecules/commentBody
40 silly found diff in packages/xxx/molecules/commentBody/package.json
41 verbose filtered diff [ 'packages/xxx/molecules/commentBody/package.json' ]
42 silly checking diff packages/xxx/molecules/formBodyInput
43 silly found diff in packages/xxx/molecules/formBodyInput/package.json
44 verbose filtered diff [ 'packages/xxx/molecules/formBodyInput/package.json' ]
45 silly checking diff packages/xxx/molecules/formSelect
46 silly found diff in packages/xxx/molecules/formSelect/package.json
47 verbose filtered diff [ 'packages/xxx/molecules/formSelect/package.json' ]
48 silly checking diff packages/xxx/molecules/formSubmit
49 silly found diff in packages/xxx/molecules/formSubmit/package.json
50 verbose filtered diff [ 'packages/xxx/molecules/formSubmit/package.json' ]
51 silly checking diff packages/xxx/molecules/formTagSelect
52 silly found diff in packages/xxx/molecules/formTagSelect/package.json
53 verbose filtered diff [ 'packages/xxx/molecules/formTagSelect/package.json' ]
54 silly checking diff packages/xxx/molecules/formTextInput
55 silly found diff in packages/xxx/molecules/formTextInput/package.json
56 verbose filtered diff [ 'packages/xxx/molecules/formTextInput/package.json' ]
57 silly checking diff packages/xxx/molecules/models
58 silly found diff in packages/xxx/molecules/models/package.json
59 verbose filtered diff [ 'packages/xxx/molecules/models/package.json' ]
60 silly checking diff packages/xxx/molecules/overviewLabel
61 silly found diff in packages/xxx/molecules/overviewLabel/package.json
62 verbose filtered diff [ 'packages/xxx/molecules/overviewLabel/package.json' ]
63 silly checking diff packages/xxx/molecules/overviewLabels
64 silly found diff in packages/xxx/molecules/overviewLabels/package.json
65 verbose filtered diff [ 'packages/xxx/molecules/overviewLabels/package.json' ]
66 silly checking diff packages/xxx/molecules/overviewLabelsMore
67 silly found diff in packages/xxx/molecules/overviewLabelsMore/package.json
68 verbose filtered diff [ 'packages/xxx/molecules/overviewLabelsMore/package.json' ]
69 silly checking diff packages/xxx/molecules/overviewQuestionBody
70 silly found diff in packages/xxx/molecules/overviewQuestionBody/package.json
71 verbose filtered diff [ 'packages/xxx/molecules/overviewQuestionBody/package.json' ]
72 silly checking diff packages/xxx/molecules/overviewQuestionButton
73 silly found diff in packages/xxx/molecules/overviewQuestionButton/package.json
74 verbose filtered diff [
74 verbose filtered diff   'packages/xxx/molecules/overviewQuestionButton/package.json'
74 verbose filtered diff ]
75 silly checking diff packages/xxx/molecules/overviewQuestionDetails
76 silly found diff in packages/xxx/molecules/overviewQuestionDetails/package.json
77 verbose filtered diff [
77 verbose filtered diff   'packages/xxx/molecules/overviewQuestionDetails/package.json'
77 verbose filtered diff ]
78 silly checking diff packages/xxx/molecules/overviewQuestionHeader
79 silly found diff in packages/xxx/molecules/overviewQuestionHeader/package.json
80 verbose filtered diff [
80 verbose filtered diff   'packages/xxx/molecules/overviewQuestionHeader/package.json'
80 verbose filtered diff ]
81 silly checking diff packages/xxx/molecules/overviewQuestionListEmpty
82 silly found diff in packages/xxx/molecules/overviewQuestionListEmpty/package.json
83 verbose filtered diff [
83 verbose filtered diff   'packages/xxx/molecules/overviewQuestionListEmpty/package.json'
83 verbose filtered diff ]
84 silly checking diff packages/xxx/molecules/overviewQuestionStats
85 silly found diff in packages/xxx/molecules/overviewQuestionStats/package.json
86 verbose filtered diff [
86 verbose filtered diff   'packages/xxx/molecules/overviewQuestionStats/package.json'
86 verbose filtered diff ]
87 silly checking diff packages/xxx/molecules/overviewQuestionTags
88 silly found diff in packages/xxx/molecules/overviewQuestionTags/package.json
89 verbose filtered diff [ 'packages/xxx/molecules/overviewQuestionTags/package.json' ]
90 silly checking diff packages/xxx/molecules/overviewQuestionTaskTitle
91 silly found diff in packages/xxx/molecules/overviewQuestionTaskTitle/package.json
92 verbose filtered diff [
92 verbose filtered diff   'packages/xxx/molecules/overviewQuestionTaskTitle/package.json'
92 verbose filtered diff ]
93 silly checking diff packages/xxx/molecules/overviewQuestionTitle
94 silly found diff in packages/xxx/molecules/overviewQuestionTitle/package.json
95 verbose filtered diff [
95 verbose filtered diff   'packages/xxx/molecules/overviewQuestionTitle/package.json'
95 verbose filtered diff ]
96 silly checking diff packages/xxx/molecules/overviewTitle
97 silly found diff in packages/xxx/molecules/overviewTitle/package.json
98 verbose filtered diff [ 'packages/xxx/molecules/overviewTitle/package.json' ]
99 silly checking diff packages/xxx/molecules/postBody
100 silly found diff in packages/xxx/molecules/postBody/package.json
101 verbose filtered diff [ 'packages/xxx/molecules/postBody/package.json' ]
102 silly checking diff packages/xxx/molecules/questionTitle
103 silly found diff in packages/xxx/molecules/questionTitle/package.json
104 verbose filtered diff [ 'packages/xxx/molecules/questionTitle/package.json' ]
105 silly checking diff packages/xxx/molecules/xxxButton
106 silly found diff in packages/xxx/molecules/xxxButton/package.json
107 verbose filtered diff [ 'packages/xxx/molecules/xxxButton/package.json' ]
108 silly checking diff packages/xxx/molecules/upAndDownVote
109 silly found diff in packages/xxx/molecules/upAndDownVote/package.json
110 verbose filtered diff [ 'packages/xxx/molecules/upAndDownVote/package.json' ]
111 silly checking diff packages/xxx/molecules/userInfo
112 silly found diff in packages/xxx/molecules/userInfo/package.json
113 verbose filtered diff [ 'packages/xxx/molecules/userInfo/package.json' ]
114 silly checking diff packages/xxx/organisms/overviewHeader
115 silly found diff in packages/xxx/organisms/overviewHeader/package.json
116 verbose filtered diff [ 'packages/xxx/organisms/overviewHeader/package.json' ]
117 silly checking diff packages/xxx/organisms/overviewQuestion
118 silly found diff in packages/xxx/organisms/overviewQuestion/package.json
119 verbose filtered diff [ 'packages/xxx/organisms/overviewQuestion/package.json' ]
120 silly checking diff packages/xxx/organisms/overviewQuestionList
121 silly found diff in packages/xxx/organisms/overviewQuestionList/package.json
122 verbose filtered diff [ 'packages/xxx/organisms/overviewQuestionList/package.json' ]
123 silly checking diff packages/xxx/organisms/postContainer
124 silly found diff in packages/xxx/organisms/postContainer/package.json
125 verbose filtered diff [ 'packages/xxx/organisms/postContainer/package.json' ]
126 silly checking diff packages/xxx/organisms/questionForm
127 silly found diff in packages/xxx/organisms/questionForm/package.json
128 verbose filtered diff [ 'packages/xxx/organisms/questionForm/package.json' ]
129 silly checking diff packages/xxx/templates/overview
130 silly found diff in packages/xxx/templates/overview/package.json
131 verbose filtered diff [ 'packages/xxx/templates/overview/package.json' ]
132 silly checking diff packages/xxx/templates/overviewProject
133 silly found diff in packages/xxx/templates/overviewProject/package.json
134 verbose filtered diff [ 'packages/xxx/templates/overviewProject/package.json' ]
135 silly checking diff packages/xxx/templates/overviewTask
136 silly found diff in packages/xxx/templates/overviewTask/package.json
137 verbose filtered diff [ 'packages/xxx/templates/overviewTask/package.json' ]
138 silly checking diff packages/xxx/templates/questionView
139 silly found diff in packages/xxx/templates/questionView/package.json
140 verbose filtered diff [ 'packages/xxx/templates/questionView/package.json' ]
141 verbose updated @xxx/commentbody
142 verbose updated @xxx/formbodyinput
143 verbose updated @xxx/formselect
144 verbose updated @xxx/formsubmit
145 verbose updated @xxx/formtagselect
146 verbose updated @xxx/formtextinput
147 verbose updated @xxx/models
148 verbose updated @xxx/overviewlabel
149 verbose updated @xxx/overviewlabels
150 verbose updated @xxx/overviewlabelsmore
151 verbose updated @xxx/overviewquestionbody
152 verbose updated @xxx/overviewquestionbutton
153 verbose updated @xxx/overviewquestiondetails
154 verbose updated @xxx/overviewquestionheader
155 verbose updated @xxx/overviewquestionlistempty
156 verbose updated @xxx/overviewquestionstats
157 verbose updated @xxx/overviewquestiontags
158 verbose updated @xxx/overviewquestiontasktitle
159 verbose updated @xxx/overviewquestiontitle
160 verbose updated @xxx/overviewtitle
161 verbose updated @xxx/postbody
162 verbose updated @xxx/questiontitle
163 verbose updated @xxx/xxxbutton
164 verbose updated @xxx/upanddownvote
165 verbose updated @xxx/userinfo
166 verbose updated @xxx/overviewheader
167 verbose updated @xxx/overviewquestion
168 verbose updated @xxx/overviewquestionlist
169 verbose updated @xxx/postcontainer
170 verbose updated @xxx/questionform
171 verbose updated @xxx/overview
172 verbose updated @xxx/overviewproject
173 verbose updated @xxx/overviewtask
174 verbose updated @xxx/questionview
175 verbose git-describe undefined => "v1.0.4-2-g0606c6c"
176 silly git-describe parsed => {"lastTagName":"v1.0.4","lastVersion":"v1.0.4","refCount":"2","sha":"0606c6c","isDirty":false}
177 info execute Skipping releases
178 silly lifecycle No script for "preversion" in "@xxx/webcomponents", continuing
179 silly lifecycle No script for "preversion" in "@xxx/commentbody", continuing
180 silly lifecycle No script for "preversion" in "@xxx/formbodyinput", continuing
181 silly lifecycle No script for "preversion" in "@xxx/formselect", continuing
182 silly lifecycle No script for "preversion" in "@xxx/formsubmit", continuing
183 silly lifecycle No script for "preversion" in "@xxx/formtextinput", continuing
184 silly lifecycle No script for "preversion" in "@xxx/models", continuing
185 silly lifecycle No script for "preversion" in "@xxx/overviewlabel", continuing
186 silly lifecycle No script for "preversion" in "@xxx/overviewlabelsmore", continuing
187 verbose version @xxx/formtextinput has no lockfile. Skipping lockfile update.
188 verbose version @xxx/commentbody has no lockfile. Skipping lockfile update.
189 verbose version @xxx/formsubmit has no lockfile. Skipping lockfile update.
190 verbose version @xxx/formbodyinput has no lockfile. Skipping lockfile update.
191 verbose version @xxx/overviewlabelsmore has no lockfile. Skipping lockfile update.
192 verbose version @xxx/models has no lockfile. Skipping lockfile update.
193 verbose version @xxx/overviewlabel has no lockfile. Skipping lockfile update.
194 verbose version @xxx/formselect has no lockfile. Skipping lockfile update.
195 silly lifecycle No script for "version" in "@xxx/formsubmit", continuing
196 silly lifecycle No script for "preversion" in "@xxx/overviewquestionbody", continuing
197 silly lifecycle No script for "version" in "@xxx/formtextinput", continuing
198 silly lifecycle No script for "preversion" in "@xxx/overviewquestionbutton", continuing
199 silly lifecycle No script for "version" in "@xxx/formbodyinput", continuing
200 silly lifecycle No script for "preversion" in "@xxx/overviewquestionlistempty", continuing
201 silly lifecycle No script for "version" in "@xxx/overviewlabelsmore", continuing
202 silly lifecycle No script for "preversion" in "@xxx/overviewquestiontasktitle", continuing
203 silly lifecycle No script for "version" in "@xxx/overviewlabel", continuing
204 silly lifecycle No script for "preversion" in "@xxx/overviewquestiontitle", continuing
205 silly lifecycle No script for "version" in "@xxx/commentbody", continuing
206 silly lifecycle No script for "preversion" in "@xxx/overviewtitle", continuing
207 silly lifecycle No script for "version" in "@xxx/models", continuing
208 silly lifecycle No script for "preversion" in "@xxx/postbody", continuing
209 silly lifecycle No script for "version" in "@xxx/formselect", continuing
210 silly lifecycle No script for "preversion" in "@xxx/xxxbutton", continuing
211 verbose version @xxx/overviewquestionbody has no lockfile. Skipping lockfile update.
212 verbose version @xxx/overviewquestionbutton has no lockfile. Skipping lockfile update.
213 verbose version @xxx/overviewquestionlistempty has no lockfile. Skipping lockfile update.
214 verbose version @xxx/overviewquestiontasktitle has no lockfile. Skipping lockfile update.
215 verbose version @xxx/overviewquestiontitle has no lockfile. Skipping lockfile update.
216 verbose version @xxx/overviewtitle has no lockfile. Skipping lockfile update.
217 verbose version @xxx/postbody has no lockfile. Skipping lockfile update.
218 verbose version @xxx/xxxbutton has no lockfile. Skipping lockfile update.
219 silly lifecycle No script for "version" in "@xxx/overviewquestionbody", continuing
220 silly lifecycle No script for "preversion" in "@xxx/upanddownvote", continuing
221 silly lifecycle No script for "version" in "@xxx/overviewquestiontasktitle", continuing
222 silly lifecycle No script for "preversion" in "@xxx/userinfo", continuing
223 silly lifecycle No script for "version" in "@xxx/overviewquestionbutton", continuing
224 silly lifecycle No script for "preversion" in "@xxx/overviewquestiontags", continuing
225 silly lifecycle No script for "version" in "@xxx/overviewquestionlistempty", continuing
226 silly lifecycle No script for "preversion" in "@xxx/overviewlabels", continuing
227 silly lifecycle No script for "version" in "@xxx/overviewquestiontitle", continuing
228 silly lifecycle No script for "preversion" in "@xxx/overviewquestionstats", continuing
229 verbose version @xxx/upanddownvote has no lockfile. Skipping lockfile update.
230 verbose version @xxx/userinfo has no lockfile. Skipping lockfile update.
231 verbose version @xxx/overviewquestiontags has no lockfile. Skipping lockfile update.
232 verbose version @xxx/overviewlabels has no lockfile. Skipping lockfile update.
233 verbose version @xxx/overviewquestionstats has no lockfile. Skipping lockfile update.
234 silly lifecycle No script for "version" in "@xxx/postbody", continuing
235 silly lifecycle No script for "version" in "@xxx/overviewtitle", continuing
236 silly lifecycle No script for "version" in "@xxx/xxxbutton", continuing
237 silly lifecycle No script for "version" in "@xxx/upanddownvote", continuing
238 silly lifecycle No script for "version" in "@xxx/userinfo", continuing
239 silly lifecycle No script for "preversion" in "@xxx/questiontitle", continuing
240 silly lifecycle No script for "preversion" in "@xxx/postcontainer", continuing
241 silly lifecycle No script for "version" in "@xxx/overviewlabels", continuing
242 silly lifecycle No script for "preversion" in "@xxx/overviewquestionheader", continuing
243 silly lifecycle No script for "preversion" in "@xxx/overviewheader", continuing
244 silly lifecycle No script for "version" in "@xxx/overviewquestiontags", continuing
245 silly lifecycle No script for "preversion" in "@xxx/formtagselect", continuing
246 silly lifecycle No script for "version" in "@xxx/overviewquestionstats", continuing
247 verbose version @xxx/questiontitle has no lockfile. Skipping lockfile update.
248 verbose version @xxx/postcontainer has no lockfile. Skipping lockfile update.
249 verbose version @xxx/overviewquestionheader has no lockfile. Skipping lockfile update.
250 verbose version @xxx/formtagselect has no lockfile. Skipping lockfile update.
251 verbose version @xxx/overviewheader has no lockfile. Skipping lockfile update.
252 silly lifecycle No script for "version" in "@xxx/questiontitle", continuing
253 silly lifecycle No script for "version" in "@xxx/formtagselect", continuing
254 silly lifecycle No script for "preversion" in "@xxx/questionform", continuing
255 silly lifecycle No script for "version" in "@xxx/overviewquestionheader", continuing
256 silly lifecycle No script for "preversion" in "@xxx/overviewquestiondetails", continuing
257 silly lifecycle No script for "version" in "@xxx/postcontainer", continuing
258 silly lifecycle No script for "preversion" in "@xxx/questionview", continuing
259 silly lifecycle No script for "version" in "@xxx/overviewheader", continuing
260 verbose version @xxx/questionform has no lockfile. Skipping lockfile update.
261 verbose version @xxx/overviewquestiondetails has no lockfile. Skipping lockfile update.
262 verbose version @xxx/questionview has no lockfile. Skipping lockfile update.
263 silly lifecycle No script for "version" in "@xxx/questionform", continuing
264 silly lifecycle No script for "version" in "@xxx/questionview", continuing
265 silly lifecycle No script for "version" in "@xxx/overviewquestiondetails", continuing
266 silly lifecycle No script for "preversion" in "@xxx/overviewquestion", continuing
267 verbose version @xxx/overviewquestion has no lockfile. Skipping lockfile update.
268 silly lifecycle No script for "version" in "@xxx/overviewquestion", continuing
269 silly lifecycle No script for "preversion" in "@xxx/overviewquestionlist", continuing
270 verbose version @xxx/overviewquestionlist has no lockfile. Skipping lockfile update.
271 silly lifecycle No script for "version" in "@xxx/overviewquestionlist", continuing
272 silly lifecycle No script for "preversion" in "@xxx/overviewproject", continuing
273 silly lifecycle No script for "preversion" in "@xxx/overviewtask", continuing
274 verbose version @xxx/overviewproject has no lockfile. Skipping lockfile update.
275 verbose version @xxx/overviewtask has no lockfile. Skipping lockfile update.
276 silly lifecycle No script for "version" in "@xxx/overviewproject", continuing
277 silly lifecycle No script for "version" in "@xxx/overviewtask", continuing
278 silly lifecycle No script for "preversion" in "@xxx/overview", continuing
279 verbose version @xxx/overview has no lockfile. Skipping lockfile update.
280 silly lifecycle No script for "version" in "@xxx/overview", continuing
281 verbose version Updating root package-lock.json
282 error Error: Command failed with exit code 1: npm install --package-lock-only --ignore-scripts
282 error npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
282 error npm ERR! code E404
282 error npm ERR! 404 Not Found - GET https://registry.npmjs.org/@xxx%2foverviewlabel - Not found
282 error npm ERR! 404
282 error npm ERR! 404  '@xxx/overviewlabel@^1.0.5' is not in this registry.
282 error npm ERR! 404
282 error npm ERR! 404 Note that you can also install from a
282 error npm ERR! 404 tarball, folder, http url, or git url.
282 error
282 error npm ERR! A complete log of this run can be found in:
282 error npm ERR!     C:\Users\xxx\AppData\Local\npm-cache\_logs\2022-12-23T13_54_14_948Z-debug-0.log
282 error     at makeError (C:\Users\xxx\Desktop\TaskerWebcomponents\xxx\node_modules\execa\lib\error.js:60:11)
282 error     at handlePromise (C:\Users\xxx\Desktop\TaskerWebcomponents\xxx\node_modules\execa\index.js:118:26)
282 error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
282 error     at async Promise.all (index 0)

```

</p></details>

**Comment by TheHunterDog** [comment]
Repo added

**Comment by fahslaj** [comment]
Hi @TheHunterDog , I'm sorry you're experiencing this issue. Thank you for providing a reproduction repo. Unfortunately, I am not able to reproduce the issue on the repo you have provided. I am able to publish it to a local npm repository just fine.

Can you confirm that .npmrc has the private registry configured correctly and that running a plain `npm install` will succeed for you?

**Comment by TheHunterDog** [comment]
@fahslaj The .npmrc contains the following

```
legacy-peer-deps=true
@markheijnekamp:registry=https://gitlab.com/api/v4/packages/npm/
//gitlab.com/api/v4/packages/npm/:_authToken=XX
//gitlab.com/api/v4/projects/41337045/packages/npm/:_authToken=XX
```

``npm install `` does work for me.

**Comment by TheHunterDog** [comment]
I wasn't using ``lerna publish from-package``. I was using ``lerna publish``
