### ISSUE TITLE
Lerna missing nx as a dependency?

### ISSUE THREAD

**Issue by bjorn-einar-bjartnes-4ss** [lerna/lerna#3481]
## Current Behavior

When using lerna, it fails on missing nx as a dependency.
I have one example here https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5517, where nx is not being installed as a depedency through lerna causing the build to fail unless nx is also listed as a dependency. I reported a related issue here https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5519

## Expected Behavior

I would assume nx to be listed as a dependency or peerDependency, not devDependency as suggested here https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5517#issuecomment-1370045330

## Steps to Reproduce

```
git clone https://github.com/AzureAD/microsoft-authentication-library-for-js
cd microsoft-authentication-library-for-js
npm i
npm run build
```
should fail
```
npm install nx
npm run build
```
should work.

### Failure Logs / Configuration
Listed in links above.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.16.4",
  "command": {
    "run": {
      "scope": [
        "msal",
        "@azure/msal-common",
        "@azure/msal-browser",
        "@azure/msal-react",
        "@azure/msal-angular",
        "@azure/msal-node"
      ],
      "stream": true
    },
    "exec": {
      "scope": [
        "msal",
        "@azure/msal-browser",
        "@azure/msal-common",
        "@azure/msal-node",
        "@azure/msal-react",
        "@azure/msal-angular"
      ],
      "stream": true
    },
    "bootstrap": {
      "scope": [
        "msal",
        "@azure/msal-browser",
        "@azure/msal-common",
        "@azure/msal-node",
        "@azure/msal-react",
        "@azure/msal-angular"
      ],
      "stream": true
    }
  },
  "packages": [
    "lib/*",
    "extensions/*"
  ],
  "version": "independent",
  "concurrency": 3
}
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv {
0 silly argv   _: [ 'run' ],
0 silly argv   lernaVersion: '6.0.3',
0 silly argv   '$0': 'node_modules\\lerna\\cli.js',
0 silly argv   script: 'build'
0 silly argv }
1 notice cli v6.0.3
2 verbose rootPath C:\code\fresh-msal
3 info versioning independent
4 notice filter including ["msal","@azure/msal-common","@azure/msal-browser","@azure/msal-react","@azure/msal-angular","@azure/msal-node"]
5 info filter [
5 info filter   'msal',
5 info filter   '@azure/msal-common',
5 info filter   '@azure/msal-browser',
5 info filter   '@azure/msal-react',
5 info filter   '@azure/msal-angular',
5 info filter   '@azure/msal-node'
5 info filter ]
6 error 
 There was a critical error when configuring the task runner, please report this on https://github.com/lerna/lerna
7 error Error: Cannot find module 'nx/src/utils/output'
7 error Require stack:
7 error - C:\code\fresh-msal\node_modules\@lerna\run\index.js
7 error - C:\code\fresh-msal\node_modules\@lerna\run\command.js
7 error - C:\code\fresh-msal\node_modules\lerna\index.js
7 error - C:\code\fresh-msal\node_modules\lerna\cli.js
7 error     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
7 error     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
7 error     at Module.require (node:internal/modules/cjs/loader:1005:19)
7 error     at require (node:internal/modules/cjs/helpers:102:18)
7 error     at RunCommand.configureNxOutput (C:\code\fresh-msal\node_modules\@lerna\run\index.js:350:24)
7 error     at RunCommand.runScriptsUsingNx (C:\code\fresh-msal\node_modules\@lerna\run\index.js:201:10)
<!-- Otherwise, feel free to delete this <details> block -->
```

</p></details>

### Environment

```
lerna notice cli v6.0.3
lerna info versioning independent

 Environment info:

  System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.34.1.
  npmPackages:
    lerna: ^6.0.3 => 6.0.3
```

**Comment by bjorn-einar-bjartnes-4ss** [comment]
Posted here after asking on Slack https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1672848762890099?thread_ts=1672846600.088539&cid=CMFKWPU6Q

**Comment by JamesHenry** [comment]
Hi @bjorn-einar-bjartnes-4ss I'm sorry you've run into an issue here, we will take a look today

**Comment by JamesHenry** [comment]
Just to address some of the immediate confusion upfront though - lerna does specify its dependency upon Nx in its package.json

https://github.com/lerna/lerna/blob/99a2469c51d38dbe51c534487b44703041f36911/core/lerna/package.json#L66

I think the commenter was potentially looking at the root package.json of the project which is not something which is involved in the published packages

**Comment by bjorn-einar-bjartnes-4ss** [comment]
Ah, I see... Then I am slightly more confused on what went wrong.

**Comment by JamesHenry** [comment]
Thanks again @bjorn-einar-bjartnes-4ss I have opened https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5533 which bumps the repo to the latest

**Comment by bjorn-einar-bjartnes-4ss** [comment]
Wow, thanks!
