### ISSUE TITLE
`nx.darwin-x64.node` no suitable image found

### ISSUE THREAD

**Issue by xizon** [lerna/lerna#3572]
Hello, I tried a variety of Node versions and they couldn't run. I don't know why. No matter how I try, I still get the same error.

【when i use nx@15.7.2 it works fine, using the latest version of nx keeps giving the error】

Thanks！

## Current Behavior

appears when running the following command:

```sh
npx nx graph
npx lerna run build
```

## Expected Behavior

can run lerna and nx commands 

### Failure Logs & Configuration

>  NX   dlopen(/<package_name>/node_modules/@nrwl/nx-darwin-x64/nx.darwin-x64.node, 1): no suitable image found.  Did find:

   	/<package_name>/node_modules/@nrwl/nx-darwin-x64/nx.darwin-x64.node: cannot load 'nx.darwin-x64.node' (load command 0x80000034 is unknown)
   	/<package_name>/node_modules/@nrwl/nx-darwin-x64/nx.darwin-x64.node: cannot load 'nx.darwin-x64.node' (load command 0x80000034 is unknown)

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "useWorkspaces": true,
  "version": "0.0.0"
}
```

</p></details>

<details><summary>nx.json</summary><p>

```json
{
    "tasksRunnerOptions": {
      "default": {
        "runner": "nx/tasks-runners/default",
        "options": {
          "cacheableOperations": []
        }
      }
    },
    "targetDefaults": {}
  }
  
```

</p></details>

<details><summary>package.json</summary><p>

```json
{
  "name": "demo",
  "version": "0.0.1",
  "workspaces": [
    "packages/*"
  ],
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "lerna": "^6.5.1"
  }
}
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```json
0 silly argv {
0 silly argv   _: [ 'run' ],
0 silly argv   lernaVersion: '6.5.1',
0 silly argv   '$0': '/Applications/demohere/node_modules/.bin/lerna',
0 silly argv   script: 'build'
0 silly argv }
1 notice cli v6.5.1
2 verbose rootPath /Applications/demohere
3 verbose run Nx target configuration was not found. Task dependencies will not be automatically included.
4 error Error: dlopen(/Applications/demohere/node_modules/@nrwl/nx-darwin-x64/nx.darwin-x64.node, 1): no suitable image found.  Did find:
4 error 	/Applications/demohere/node_modules/@nrwl/nx-darwin-x64/nx.darwin-x64.node: cannot load 'nx.darwin-x64.node' (load command 0x80000034 is unknown)
4 error 	/Applications/demohere/node_modules/@nrwl/nx-darwin-x64/nx.darwin-x64.node: cannot load 'nx.darwin-x64.node' (load command 0x80000034 is unknown)
4 error     at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
4 error     at Module.load (node:internal/modules/cjs/loader:1117:32)
4 error     at Module._load (node:internal/modules/cjs/loader:958:12)
4 error     at Module.require (node:internal/modules/cjs/loader:1141:19)
4 error     at require (node:internal/modules/cjs/helpers:110:18)
4 error     at Object.<anonymous> (/Applications/demohere/node_modules/nx/src/native/index.js:121:29)
4 error     at Module._compile (node:internal/modules/cjs/loader:1254:14)
4 error     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
4 error     at Module.load (node:internal/modules/cjs/loader:1117:32)
4 error     at Module._load (node:internal/modules/cjs/loader:958:12)
4 error     at Module.require (node:internal/modules/cjs/loader:1141:19)
4 error     at require (node:internal/modules/cjs/helpers:110:18)
4 error     at NativeFileHasher.<anonymous> (/Applications/demohere/node_modules/nx/src/hasher/native-file-hasher.js:13:35)
4 error     at Generator.next (<anonymous>)
4 error     at /Applications/demohere/node_modules/tslib/tslib.js:167:75

```

</p></details>

### Environment

macOS 10.14.6
lerna 6.5.1
node 18.15.0 or node 14.x.x or node 16.x.x

**Comment by xizon** [comment]
@JamesHenry Thank you for your detail, understood, I could try it. :)  BEST REGARDS!

**Comment by kjarex** [comment]
Just some feedback for anyone else who ends up here: James' workaround worked fine for me.
