### ISSUE TITLE
Failed to create pakcage under Node18 

### ISSUE THREAD

**Issue by kaikaibenkai** [lerna/lerna#3575]
## Current Behavior

```
Error [ERR_REQUIRE_ESM]: require() of ES Module D:\site\next-oj\node_modules\globby\index.js from D:\site\next-oj\node_modules\@lerna\create\dist\command.js not supported.
Instead change the require of index.js in D:\site\next-oj\node_modules\@lerna\create\dist\command.js to a dynamic import() which is available in all CommonJS modules.
```

## Expected Behavior

Create package successfully.

## Steps to Reproduce

Install Node 18, then run `lerna init && lerna create package`.

### Failure Logs / Configuration

```
$ lerna create web
D:\site\next-oj\node_modules\@lerna\create\dist\command.js:893
    import_globby2 = __toESM(require("globby"));
                             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module D:\site\next-oj\node_modules\globby\index.js from D:\site\next-oj\node_modules\@lerna\create\dist\command.js not supported.
Instead change the require of index.js in D:\site\next-oj\node_modules\@lerna\create\dist\command.js to a dynamic import() which is available in all CommonJS modules.
    at libs/core/src/lib/project/index.ts (D:\site\next-oj\node_modules\@lerna\create\dist\command.js:893:30)
    at __init (D:\site\next-oj\node_modules\@lerna\create\dist\command.js:9:56)
    at libs/core/src/lib/command/index.ts (D:\site\next-oj\node_modules\@lerna\create\dist\command.js:1218:5)
    at __init (D:\site\next-oj\node_modules\@lerna\create\dist\command.js:9:56)
    at libs/core/src/index.ts (D:\site\next-oj\node_modules\@lerna\create\dist\command.js:2926:5)
    at __init (D:\site\next-oj\node_modules\@lerna\create\dist\command.js:9:56)
    at libs/commands/create/src/index.ts (D:\site\next-oj\node_modules\@lerna\create\dist\command.js:2998:5)
    at __require (D:\site\next-oj\node_modules\@lerna\create\dist\command.js:12:50)
    at Object.handler (D:\site\next-oj\node_modules\@lerna\create\dist\command.js:3483:16)
    at Object.runCommand (D:\site\next-oj\node_modules\yargs\build\index.cjs:446:48)
    at Object.parseArgs [as _parseArgs] (D:\site\next-oj\node_modules\yargs\build\index.cjs:2697:57)
    at Object.parse (D:\site\next-oj\node_modules\yargs\build\index.cjs:2278:29)
    at main (D:\site\next-oj\node_modules\lerna\dist\cli.js:9535:357)
    at Object.<anonymous> (D:\site\next-oj\node_modules\lerna\dist\cli.js:9545:18)
    at module.exports (C:\Program Files\nodejs\node_modules\lerna\node_modules\import-local\index.js:23:108)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\lerna\dist\cli.js:9542:5) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.14.0

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "useWorkspaces": true,
  "version": "0.0.0"
}
```

### Environment

lerna 6.5.1
node 18.14.0
npm 9.3.1
yarn 1.22.19

**Comment by kaikaibenkai** [comment]
It's a fatal error😭I can't use it now

**Comment by fahslaj** [comment]
Hi @kaikaibenkai , thank you for reporting this issue. I followed the steps to reproduce with the environment information provided and I was not able to reproduce the error. `lerna init` and `lerna create` were successful for lerna 6.5.1 on node 18.14.0 and npm 9.3.1. 

Could you please provide a repository with a minimal reproduction for this issue?

**Comment by kaikaibenkai** [comment]
@fahslaj Thank you for your attention to this issue. I have been resloved this problem by _running Git Bash with administrator privileges_.

**Comment by linonetwo** [comment]
Same here after install lerna with pnpm

```
% npx lerna create xxx
/Users/linonetwo/Desktop/repo/memeloop/node_modules/.pnpm/@lerna+create@6.6.1/node_modules/@lerna/create/dist/command.js:1135
    import_globby2 = __toESM(require("globby"));
                             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/linonetwo/Desktop/repo/memeloop/node_modules/.pnpm/globby@13.1.4/node_modules/globby/index.js from /Users/linonetwo/Desktop/repo/memeloop/node_modules/.pnpm/@lerna+create@6.6.1/node_modules/@lerna/create/dist/command.js not supported.
Instead change the require of index.js in /Users/linonetwo/Desktop/repo/memeloop/node_modules/.pnpm/@lerna+create@6.6.1/node_modules/@lerna/create/dist/command.js to a dynamic import() which is available in all CommonJS modules.
```
