### ISSUE TITLE
Unable to find nx package.json when checking if nx daemon is outdated when node_module is absent

### ISSUE THREAD

**Issue by garrychnca** [lerna/lerna#3643]
I was playing around with lerna and encountered a strange issue when:

* repo based on the official getting started example https://github.com/lerna/getting-started-example.git
* add a npm lifecycle script `postinstall` to execute `lerna run build,test`
* clean repo (no node_modules installed)
* run `npm install`

Note that such error only happens when node_modules is absent; a subsequent `npm install` completes successfully.

## Current Behavior

The current behaviour is that lerna throws error saying nx's `package.json` cannot be found from the node_modules even if the file does exist.

## Expected Behavior

The command should succeed, no matter if the node_module folder the absent or not.

## Steps to Reproduce

1. git clone https://github.com/lerna/getting-started-example.git
2. git apply the following patch:

```
diff --git a/package.json b/package.json
index 9299927..c4099c7 100644
--- a/package.json
+++ b/package.json
@@ -4,7 +4,10 @@
   "workspaces": [
     "packages/*"
   ],
+  "scripts": {
+    "postinstall": "node --version && npm --version && lerna --version && nx --version && file /Volumes/workplace/repos/getting-started-example/node_modules/nx/package.json && lerna run build,test --verbose"
+  },
   "devDependencies": {
-    "lerna": "^6.0.1"
+    "lerna": "^6.6.1"
   }
 }
```

3. you will have to update the path in the `postinstall` script
4. make sure node_module folder does not exist
5. run `npm install`

Note that when I am writing these steps to reproduce, I found that for some reason the issue cannot be reproduced very reliably. 

Try it several times it should have some 75% chance to reproduce.

### Failure Logs / Configuration

```
➜  getting-started-example git:(main) ✗ npm install
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.

> postinstall
> node --version && npm --version && lerna --version && nx --version && file /Volumes/workplace/repos/getting-started-example/node_modules/nx/package.json && lerna run build,test --verbose

v19.7.0
9.5.0
6.6.1
Nx Version:
- Local: v15.9.2
- Global: vNot found
/Volumes/workplace/repos/getting-started-example/node_modules/nx/package.json: JSON data
lerna notice cli v6.6.1
lerna verb rootPath /Volumes/workplace/repos/getting-started-example
lerna verb run Nx target configuration was found. Task dependencies will be automatically included.

 >  Lerna (powered by Nx)   ENOENT: no such file or directory, open '/Volumes/workplace/repos/getting-started-example/node_modules/nx/package.json'


   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".

{
  stack: "Error: ENOENT: no such file or directory, open '/Volumes/workplace/repos/getting-started-example/node_modules/nx/package.json'\n" +
    '    at Object.openSync (node:fs:585:3)\n' +
    '    at readFileSync (node:fs:453:35)\n' +
    '    at readJsonFile (/Volumes/workplace/repos/getting-started-example/node_modules/nx/src/utils/fileutils.js:18:43)\n' +
    '    at getInstalledNxVersion (/Volumes/workplace/repos/getting-started-example/node_modules/nx/src/daemon/server/server.js:166:54)\n' +
    '    at nxVersionChanged (/Volumes/workplace/repos/getting-started-example/node_modules/nx/src/daemon/server/server.js:162:37)\n' +
    '    at daemonIsOutdated (/Volumes/workplace/repos/getting-started-example/node_modules/nx/src/daemon/server/server.js:159:12)\n' +
    '    at /Volumes/workplace/repos/getting-started-example/node_modules/nx/src/daemon/server/server.js:199:13\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /Volumes/workplace/repos/getting-started-example/node_modules/tslib/tslib.js:118:75\n' +
    '    at new Promise (<anonymous>)',
  message: "ENOENT: no such file or directory, open '/Volumes/workplace/repos/getting-started-example/node_modules/nx/package.json'\n" +
    '\n' +
    'Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.\n' +
    'If the error persists, please run "nx reset".',
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Volumes/workplace/repos/getting-started-example/node_modules/nx/package.json'
}
npm ERR! code 1
npm ERR! path /Volumes/workplace/repos/getting-started-example
npm ERR! command failed
npm ERR! command sh -c node --version && npm --version && lerna --version && nx --version && file /Volumes/workplace/repos/getting-started-example/node_modules/nx/package.json && lerna run build,test --verbose
```

<details><summary>lerna.json</summary><p>

https://github.com/lerna/getting-started-example/blob/main/lerna.json

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```

</p></details>

### Environment

```
lerna notice cli v6.6.1

 Environment info:

  System:
    OS: macOS 12.6.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 19.7.0 - /usr/local/bin/node
    npm: 9.5.0 - /usr/local/bin/npm
  Utilities:
    Git: 2.37.1 - /usr/bin/git
  npmPackages:
    lerna: ^6.6.1 => 6.6.1
```

**Comment by JakeTompkins** [comment]
I've been seeing this behavior in a repo using Lerna recently. It happens consistently for me, any time I remove node_modules and re-run npm install, the next Lerna command fails with this error message and has to be run a second time, at which point it succeeds. 

I haven't been able to find evidence in the code yet, but judging by the few references I've seen to this bug I have a hunch it has something to do with cached dependencies. It would be great if someone more familiar with the code base could take a look at this.
