### ISSUE TITLE
cannot init React Native project inside default lerna monorepo

### ISSUE THREAD

**Issue by howarddo2208** [lerna/lerna#3652]
## Current Behavior

I want to setup a monorepo with lerna, electron and react native. when I init react native app with the cli, I receive this error
```
[!] Invalid `Podfile` file: cannot load such file -- /Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/
node_modules/react-native/scripts/react_native_pods.

 #  from /Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/ios/Podfile:1
 #  -------------------------------------------
 >  require_relative '../node_modules/react-native/scripts/react_native_pods'
 #  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
```
I figure it was reading the current package node_modules which is hoisted to the monorepo folder, so I changed it to 
```
require_relative '../../..//node_modules/react-native/scripts/react_native_pods'
require_relative '../../../node_modules/@react-native-community/cli-platform-ios/native_modules'
```
and run `bundle install & bundle exec pod install` again, it started to install but at the end I received another error from the post-install-hook
```
[!] An error occurred while processing the post-install hook of the Podfile.

No such file or directory @ rb_sysopen - /Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/ios/../node_
modules/react-native/package.json

/Users/tanhopdo/Developments/personal/audiobook-player/node_modules/react-native/scripts/react_native_pods.rb:213:in `read'
/Users/tanhopdo/Developments/personal/audiobook-player/node_modules/react-native/scripts/react_native_pods.rb:213:in `react_nat
ive_post_install'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/ios/Podfile:52:in `block (3 levels) in from_ruby'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.0/l
ib/cocoapods-core/podfile.rb:196:in `post_install!'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/co
coapods/installer.rb:1013:in `run_podfile_post_install_hook'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/co
coapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/co
coapods/user_interface.rb:149:in `message'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/co
coapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/co
coapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/co
coapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/co
coapods/installer.rb:336:in `block in create_and_save_projects'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/co
coapods/user_interface.rb:64:in `section'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/co
coapods/installer.rb:315:in `create_and_save_projects'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/co
coapods/installer.rb:307:in `generate_pods_project'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/co
coapods/installer.rb:183:in `integrate'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/co
coapods/installer.rb:170:in `install!'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/co
coapods/command/install.rb:52:in `run'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/claide-1.1.0/lib/claide
/command.rb:334:in `run'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/co
coapods/command.rb:52:in `run'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/bin/po
d:55:in `<top (required)>'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/bin/pod:23:in `load'
/Users/tanhopdo/Developments/personal/audiobook-player/packages/mobileApp/vendor/bundle/ruby/2.7.0/bin/pod:23:in `<top (require
d)>'
/Users/tanhopdo/.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
/Users/tanhopdo/.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
/Users/tanhopdo/.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
/Users/tanhopdo/.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
/Users/tanhopdo/.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/tanhopdo/.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/tanhopdo/.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Users/tanhopdo/.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
/Users/tanhopdo/.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Users/tanhopdo/.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
/Users/tanhopdo/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
/Users/tanhopdo/.rbenv/versions/2.7.6/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Users/tanhopdo/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
/Users/tanhopdo/.rbenv/versions/2.7.6/bin/bundle:23:in `load'
/Users/tanhopdo/.rbenv/versions/2.7.6/bin/bundle:23:in `<main>'
```
looks like it was trying to access the empty node_modules in the mobileApp package again. Anybody can help me with this please? Do I need to symlink the node_modules or what else am I missing?
## Steps to Reproduce

create a monorepo: `npx lerna init`
create mobileApp react native project in packages folder `npx react-native@latest init mobileApp`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "useWorkspaces": true,
  "version": "0.0.0"
}

```

</p></details>

### Environment

```
 Environment info:

  System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.23.0-20220130.1630 - /usr/local/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Utilities:
    Git: 2.39.1 - /usr/local/bin/git
  npmPackages:
    lerna: ^6.6.1 => 6.6.1 
```

**Comment by djMax** [comment]
I assume the problem is here in the Podfile:

```
  use_react_native!(
    :path => config[:reactNativePath],
```

But I don't know how to either control that or what to replace it with.
