### ISSUE TITLE
[UPDATE] rimraf to v5

### ISSUE THREAD

**Issue by KarafiziArtur** [lerna/lerna#3669]
## Current Behavior

When trying to make `bootstrap` after updating some package dependencies we get the following error in terminal:
```bash
lerna info hoist Pruning hoisted dependencies
lerna ERR! TypeError: (0 , import_rimraf.default) is not a function
lerna ERR!     at rimrafDir (/Users/***/node_modules/@lerna/legacy-package-management/dist/index.js:3575:56)
lerna ERR!     at concurrency (/Users/***/node_modules/@lerna/legacy-package-management/dist/index.js:4371:42)
lerna ERR! lerna (0 , import_rimraf.default) is not a function
```

The problem is due to we are using `rimraf v5` but `lerna v6.6.1` now using `rimraf v4`

## Expected Behavior

Lerna using `rimraf v5` and the problem will be fixed

### Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*", "services/*", "microservices/*"],
  "useNx": true,
  "version": "independent"
}
```

</p></details>

### Environment

```bash
System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  Utilities:
    Git: 2.37.1 - /usr/local/bin/git
  npmPackages:
    lerna: 6.6.1 => 6.6.1
```

**Comment by JamesHenry** [comment]
Closing this one as we have been using later versions of `rimraf` for a while, many thanks
