### ISSUE TITLE
Get error in gitlab ci

### ISSUE THREAD

**Issue by serveyk0-work** [lerna/lerna#3693]
Hi)
I use this command to publish my package,
npx lerna publish prepatch --preid rc --dist-tag rc --yes --force-publish --no-git-reset --loglevel silly --no-progress
however ran into a strange error in gitlab ci. Can you help me with it?
Thank you!

```
$ HUSKY=0 npx lerna publish prepatch --preid rc --dist-tag rc --yes --force-publish --no-git-reset  --loglevel silly --no-progress
lerna sill argv {
lerna sill argv   _: [ 'publish' ],
lerna sill argv   preid: 'rc',
lerna sill argv   'dist-tag': 'rc',
lerna sill argv   distTag: 'rc',
lerna sill argv   yes: true,
lerna sill argv   y: true,
lerna sill argv   'force-publish': true,
lerna sill argv   forcePublish: true,
lerna sill argv   'git-reset': false,
lerna sill argv   gitReset: false,
lerna sill argv   loglevel: 'silly',
lerna sill argv   progress: false,
lerna sill argv   composed: 'publish',
lerna sill argv   lernaVersion: '6.6.2',
lerna sill argv   '$0': 'node_modules/.pnpm/lerna@6.6.2/node_modules/lerna/dist/cli.js',
lerna sill argv   bump: 'prepatch'
lerna sill argv }
lerna notice cli v6.6.2
lerna verb rootPath /builds/serveyk0-work/serveyk0
lerna info versioning independent
lerna info ci enabled
lerna verb packageConfigs Package manager 'pnpm' detected. Resolving packages using 'pnpm-workspace.yaml'.
lerna verb session 7a2d1ba3e4fd13f2
lerna verb user-agent lerna/6.6.2/node@v20.2.0+x64 (linux)
lerna sill argv {
lerna sill argv   _: [ 'publish' ],
lerna sill argv   preid: 'rc',
lerna sill argv   'dist-tag': 'rc',
lerna sill argv   distTag: 'rc',
lerna sill argv   yes: true,
lerna sill argv   y: true,
lerna sill argv   'force-publish': true,
lerna sill argv   forcePublish: true,
lerna sill argv   'git-reset': false,
lerna sill argv   gitReset: false,
lerna sill argv   loglevel: 'silly',
lerna sill argv   progress: false,
lerna sill argv   composed: 'publish',
lerna sill argv   lernaVersion: '6.6.2',
lerna sill argv   bump: 'prepatch'
lerna sill argv }
lerna verb rootPath /builds/serveyk0-work/serveyk0
lerna verb packageConfigs Package manager 'pnpm' detected. Resolving packages using 'pnpm-workspace.yaml'.
lerna sill isAnythingCommitted 
lerna verb isAnythingCommitted 1
lerna sill getCurrentBranch 
lerna verb currentBranch develop
lerna sill remoteBranchExists 
lerna sill isBehindUpstream 
lerna sill isBehindUpstream develop is behind origin/develop by 0 commit(s) and ahead by 0
lerna sill hasTags 
lerna verb hasTags true
lerna sill git-describe.sync "98f42fb" => {"refCount":"45","sha":"98f42fb","isDirty":false}
lerna WARN force-publish all packages
lerna info Assuming all packages changed
lerna verb updated @serveyk0
lerna info auto-confirmed 
Changes:
 - @serveyk0: 1.0.1-rc.0 => 1.0.2-rc.0
lerna info execute Skipping releases
lerna sill lifecycle No script for "preversion" in "before-storybook", continuing
lerna sill lifecycle No script for "preversion" in "@serveyk0", continuing
lerna verb version @serveyk0 has no lockfile. Skipping lockfile update.
lerna sill lifecycle No script for "version" in "@serveyk0", continuing
lerna verb version Updating root pnpm-lock.yaml
node:internal/validators:95
      throw new ERR_INVALID_ARG_TYPE(name, 'number', value);
      ^
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received an instance of Error
    at process.set [as exitCode] (node:internal/bootstrap/node:124:9)
    at ChildProcess.drain (/builds/serveyk0-work/serveyk0-ui/node_modules/.pnpm/@lerna+child-process@6.6.2/node_modules/@lerna/child-process/index.js:138:24)
    at Object.onceWrapper (node:events:626:26)
    at ChildProcess.emit (node:events:523:35)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:[82](https://gitlab.com/serveyk0-work/serveyk0-ui/-/jobs/4320026228#L82):21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v20.2.0
Cleaning up project directory and file based variables

ERROR: Job failed: exit code 1
```

**Comment by theusersimons** [comment]
bump thread

I also encounter this problem on node node:20-alpine

```sh
node:internal/errors:541
      throw error;
      ^
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received an instance of Error
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at setExitCode (/builds/aridle/aridle-workspaces/node_modules/.pnpm/lerna@8.1.5_encoding@0.1.13/node_modules/lerna/dist/index.js:1555:20)
    at ChildProcess.drain (/builds/aridle/aridle-workspaces/node_modules/.pnpm/lerna@8.1.5_encoding@0.1.13/node_modules/lerna/dist/index.js:1630:7)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:531:35)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v20.15.0
```

there is no such problem on node:18-alpine

**Comment by BDelacour** [comment]
Another bump, the issue is since Node 20.0.0 as you noticed : https://nodejs.org/docs/latest-v20.x/api/process.html#processexitcode

Lerna should be fixed accordingly

**Comment by TSwifts** [comment]
Another bump for this issue.

```
lerna verb user-agent lerna/9.0.0/node@v20.19.5+x64 (linux)
node:internal/errors:541
      throw error;
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received an instance of Error
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at setExitCode (/home/ubuntu/workspace/XXXXX/node_modules/lerna/dist/index.js:1782:20)
    at ChildProcess.drain (/home/ubuntu/workspace/XXXXX/node_modules/lerna/dist/index.js:1857:7)
    at Object.onceWrapper (node:events:639:26)
    at ChildProcess.emit (node:events:536:35)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.19.5
```

We encountered this, while attempting to upgrade an internal library from Node major 18 to major 20. In our case the issue popped up while attempting to publish a new library version with `npx lerna publish from-package --yes --loglevel debug`.
The same command executes perfectly fine locally on a Macbook M3 but fails with the error message above on Jenkins, so we must be pretty unlucky to have come across some edge-case.
