### ISSUE TITLE
lerna version fails with "bad revision" if using independent versioning and scopes (slashes) in the package names.

### ISSUE THREAD

**Issue by friday** [lerna/lerna#3728]
When I run `lerna version --conventional-commits` in a monorepo with independent versioning and package names with scopes (and hence also forward slash), lerna produces an invalid git command:

```
lerna notice cli v6.6.2
lerna info versioning independent
lerna info Looking for changed packages since @namespace/package@0.111.0
lerna ERR! Error: Command failed with exit code 128: git diff --name-only @namespace/package@0.111.0 -- packages/other-package
lerna ERR! fatal: bad revision '@namespace/package@0.111.0'
lerna ERR!     at makeError (./node_modules/execa/lib/error.js:60:11)
lerna ERR!     at module.exports.sync (./node_modules/execa/index.js:194:17)
lerna ERR!     at Object.execSync (./node_modules/@lerna/child-process/index.js:39:16)
lerna ERR!     at diffSinceIn (./node_modules/lerna/dist/cli.js:401:24)
lerna ERR!     at hasDiffSinceThatIsntIgnored (./node_modules/lerna/dist/cli.js:374:18)
lerna ERR!     at isCandidate (./node_modules/lerna/dist/cli.js:467:77)
lerna ERR!     at ./node_modules/lerna/dist/cli.js:294:9
lerna ERR!     at PackageGraph.forEach (<anonymous>)
lerna ERR!     at collectPackages (./node_modules/lerna/dist/cli.js:293:12)
lerna ERR! lerna Command failed with exit code 128: git diff --name-only @namespace/package@0.111.0 -- packages/other-package
lerna ERR! lerna fatal: bad revision '@namespace/package@0.111.0'
```
This doesn't happen for my colleagues, but they're not using Linux.

## Expected Behavior

git doesn't support tag names with slashes in them used as refs, although if you add `refs/tags/` before the tag name it does.
```diff
-git diff --name-only @namespace/package@0.111.0 -- packages/package
+git diff --name-only refs/tags/@namespace/package@0.111.0 -- packages/package
```

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "useWorkspaces": true,
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "command": {
    "publish": {
      "registry": "https://npm.pkg.github.com"
    },
    "version": {
      "allowBranch": "master",
      "message": "chore(release): publish"
    }
  }
}
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv {
0 silly argv   _: [ 'version' ],
0 silly argv   'conventional-commits': true,
0 silly argv   conventionalCommits: true,
0 silly argv   changelog: false,
0 silly argv   lernaVersion: '6.6.2',
0 silly argv   '$0': './node_modules/.bin/lerna'
0 silly argv }
1 notice cli v6.6.2
2 verbose rootPath .
3 info versioning independent
4 silly isAnythingCommitted
5 verbose isAnythingCommitted 1
6 silly getCurrentBranch
7 verbose currentBranch master
8 silly remoteBranchExists
9 silly isBehindUpstream
10 silly isBehindUpstream master is behind origin/master by 0 commit(s) and ahead by 0
11 silly hasTags
12 verbose hasTags true
13 silly git-describe.sync "@namespace/package@0.111.0-1-gb243dd1" => {"lastTagName":"@namespace/package@0.111.0","lastVersion":"0.111.0","refCount":"1","sha":"b243dd1","isDirty":false}
14 info Looking for changed packages since @namespace/package@0.111.0
15 silly checking diff packages/conventional-changelog-redbeemedia
16 error Error: Command failed with exit code 128: git diff --name-only @namespace/package@0.111.0 -- packages/conventional-changelog-redbeemedia
16 error fatal: bad revision '@namespace/package@0.111.0'
16 error     at makeError (./node_modules/execa/lib/error.js:60:11)
16 error     at module.exports.sync (./node_modules/execa/index.js:194:17)
16 error     at Object.execSync (./node_modules/@lerna/child-process/index.js:39:16)
16 error     at diffSinceIn (./node_modules/lerna/dist/cli.js:401:24)
16 error     at hasDiffSinceThatIsntIgnored (./node_modules/lerna/dist/cli.js:374:18)
16 error     at isCandidate (./node_modules/lerna/dist/cli.js:467:77)
16 error     at ./node_modules/lerna/dist/cli.js:294:9
16 error     at PackageGraph.forEach (<anonymous>)
16 error     at collectPackages (./node_modules/lerna/dist/cli.js:293:12)
```

</p></details>

### Environment

```
 Environment info:

  System:
    OS: Linux 6.3 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 5800U with Radeon Graphics
  Binaries:
    Node: 18.15.0 - ~/.volta/tools/image/node/18.15.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.5.0 - ~/.volta/tools/image/node/18.15.0/bin/npm
  Utilities:
    Git: 2.41.0 - /usr/bin/git
  npmPackages:
    lerna: ^6.6.2 => 6.6.2 
```

**Comment by friday** [comment]
It turned out that we historically started using `@MyCompanyName` in our tags, but changed the scope name to lowercase for npm later as cased scopes werent supported, but the tag names lerna made for new tags apparently reused the old tag names. All I had to do to break the cycle was to create new tags the same names but lowercased.
