### ISSUE TITLE
Lerna 7.1.3 throws UndefinedParserError exception with Prettier 3.0.0 

### ISSUE THREAD

**Issue by rbirkgit** [lerna/lerna#3773]
## Current Behavior

Publishing a package with Lerna 7.1.3 and Prettier 3.0.0 throws UndefinedParserError exception. This did not happen with Prettier 2.8.8

## Expected Behavior

Expecting to work as before without exception.

## Steps to Reproduce

`yarn run lerna publish --yes`

### Failure Logs / Configuration

```
[2023-07-13T17:20:34.890Z] file:///jenkins/workspace/provisioning-tango-ui-sdk-publish/node_modules/prettier/index.mjs:16967
[2023-07-13T17:20:34.890Z]         throw new UndefinedParserError(
[2023-07-13T17:20:34.890Z]               ^
[2023-07-13T17:20:34.890Z] 
[2023-07-13T17:20:34.890Z] UndefinedParserError: No parser could be inferred for file "/jenkins/workspace/provisioning-tango-ui-sdk-publish/yarn.lock".
[2023-07-13T17:20:34.890Z]     at normalizeFormatOptions (file:///jenkins/workspace/provisioning-tango-ui-sdk-publish/node_modules/prettier/index.mjs:16967:15)
[2023-07-13T17:20:34.890Z]     at formatWithCursor (file:///jenkins/workspace/provisioning-tango-ui-sdk-publish/node_modules/prettier/index.mjs:18588:52)
[2023-07-13T17:20:34.890Z]     at file:///jenkins/workspace/provisioning-tango-ui-sdk-publish/node_modules/prettier/index.mjs:21784:12
[2023-07-13T17:20:34.890Z]     at async Module.format2 (file:///jenkins/workspace/provisioning-tango-ui-sdk-publish/node_modules/prettier/index.mjs:21789:25)

```

### Environment

```
lerna notice cli v7.1.3
lerna info versioning independent

 Environment info:

  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.6.3 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.41.0.
  npmPackages:
    lerna: ^7.1.3 => 7.1.3
```

**Comment by rbirkgit** [comment]
It could possibly be an issue with Prettier 3.0.0 but running prettier by itself all works fine. Downgrading to Prettier 2.8.8 also works fine with latest Lerna.

**Comment by jd-carroll** [comment]
Add a .prettierignore in the root of your workspace

**Comment by rbirkgit** [comment]
Thanks, that is probably my issue! I have local ignore files in each package and only ran prettier on the package folders. I should have a root one. I will try it out!

**Comment by rbirkgit** [comment]
Closing as it works fine with root ignore file.
