### ISSUE TITLE
Error 404 to install Lerna v4.0.0

### ISSUE THREAD

**Issue by rudemex** [lerna/lerna#3783]
Hi, I'm having an error installing lerna v4.0.0, unfortunately in the project I'm working on already came with this version and we can not do an update for the moment.

This error started to happen a few moments ago, since a few hours ago I was able to install everything without any problem.

```sh
npm i -g lerna@4.0.0 > /dev/null
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@lerna%2finfo - Not found
npm ERR! 404 
npm ERR! 404  '@lerna/info@4.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'lerna'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/[202](<repo>)3-07-14T20_57_06_405Z-debug.log
```

**Comment by rudemex** [comment]
when installing Lerna v4.0.0.0 this error returns

```
error Couldn't find package "@lerna/get-npm-exec-opts@4.0.0" required by "@lerna/npm-install@4.0.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@lerna/info@4.0.0" required by "lerna@^4.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:36582:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@lerna/get-npm-exec-opts@4.0.0" required by "@lerna/npm-run-script@4.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:36582:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@lerna/gitlab-client@4.0.0" required by "@lerna/version@4.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:36582:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by rudemex** [comment]
It seems to be fixed... it may have been a problem with npm/yarn registry
