### ISSUE TITLE
Lerna 7 failed to publish with concurrency

### ISSUE THREAD

**Issue by chenmmm111** [lerna/lerna#3803]
## Current Behavior

When running `lerna publish` the following error is thrown:
`lerna ERR! TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))` in https://github.com/lerna/lerna/blob/3123c7668d57b6eb820ba41b507fec10c39e928b/libs/core/src/lib/run-projects-topologically.ts#L75

## Expected Behavior

- There should be no error during publish

## Steps to Reproduce

run `lerna publish`, with default concurrency settings.

The default concurrency is set in https://github.com/lerna/lerna/blob/3123c7668d57b6eb820ba41b507fec10c39e928b/libs/core/src/lib/command/index.ts#L19

In my case, with concurrency > 1, the project has been added to `seen` set but has not been deleted from `depIsNotInCycle` yet. As a result the following filter logic cannot find the next project to process:
```
let batch = Object.keys(dependenciesBySource)
      .filter((p) => dependenciesBySource[p].size === 0)
      .filter((p) => !seen.has(p));
```

This potentially caused by `seen.add` and `dependenciesBySource[dep].delete(p)`  are not consistent with concurrency.

### Workaround
`lerna publish --concurrency=1`

### Failure Logs / Configuration

```
lerna ERR! TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
lerna ERR!     at Function.from (<anonymous>)
lerna ERR!     at /node_modules/lerna/dist/index.js:4730:24
lerna ERR!     at Array.some (<anonymous>)
lerna ERR!     at node_modules/lerna/dist/index.js:4727:53
lerna ERR!     at Array.find (<anonymous>)
```

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "$schema": "node_modules/lerna/schemas/lerna-schema.json"
}
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```

</p></details>

### Environment

lerna notice cli v7.1.4
lerna info versioning independent

 Environment info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (5) arm64 unknown
  Binaries:
    Node: 16.18.1 - /usr/bin/node
    npm: 9.5.1 - /usr/bin/npm
  Utilities:
    Git: 2.25.1 - /usr/bin/git
  npmPackages:
    lerna: ^7.1.4 => 7.1.4

**Comment by chenmmm111** [comment]
Thinking of adding sanity check on https://github.com/lerna/lerna/blob/3123c7668d57b6eb820ba41b507fec10c39e928b/libs/core/src/lib/run-projects-topologically.ts#L75 something like:

`return projectDeps && Array.from(projectDeps).filter(depIsNotInCycle).length > 0;`

**Comment by adam-h** [comment]
Ran into this with our packages too, some of which are quite legacy and sadly _do_ have dependency cycles.

The `--concurrency=1` didn't work, at least alone, but when I made the fix you suggested [1] it published successfully. Thank you 🙂 

---

1: 
```js
return projectDeps && Array.from(projectDeps).filter(depIsNotInCycle).length > 0;
```

**Comment by fahslaj** [comment]
This has been fixed and released with Lerna 7.2.0. Thank you!
