### ISSUE TITLE
Lerna version - make prettier formatting optional (and document it)

### ISSUE THREAD

**Issue by nstuyvesant** [lerna/lerna#3806]
## Description

[This line](https://github.com/lerna/lerna/blob/main/libs/commands/version/src/lib/git-add.ts#L15) suggests that lerna applies prettier to updated files. This is not documented nor desirable behavior.

## Motivation

Almost all repos that use prettier have package.json scripts that explicitly run prettier like this...
```json
    "format": "prettier --plugin-search-dir . --write . --ignore-path ../../.eslintignore"
```

Additionally, those monorepos usually have a setting for editors like .vscode/settings.json...
```json
  "editor.formatOnSave": true
```

It's also common top have husky enforce formatting.

With all the options above, lerna doesn't really need to apply formatting.

## Suggested Implementation

But let's say there is a need that I haven't considered, then...
1. It should be documented somewhere so users know when and why prettier is reformatting files
2. There should be a configuration option to not have prettier format files (preference would be disabled by default and only turned on if configured to do so).

**Comment by cmdcolin** [comment]
might also be desirable to disable because lerna is using prettier v2.0 but i had tried to upgrade to v3.0. after running release of my software it failed at a lerna step with

```

lerna ERR! TypeError: resolvedPrettier.resolveConfig.sync is not a function
lerna ERR!     at maybeFormatFile (/home/ubuntu/jbrowse-components/node_modules/lerna/dist/cli.js:5776:53)
lerna ERR!     at gitAdd (/home/ubuntu/jbrowse-components/node_modules/lerna/dist/cli.js:5799:9)
lerna ERR!     at /home/ubuntu/jbrowse-components/node_modules/lerna/dist/cli.js:6622:36
lerna ERR!     at async Promise.all (index 0)
lerna ERR! TypeError: resolvedPrettier.resolveConfig.sync is not a function
lerna ERR!     at maybeFormatFile (/home/ubuntu/jbrowse-components/node_modules/lerna/dist/cli.js:5776:53)
lerna ERR!     at gitAdd (/home/ubuntu/jbrowse-components/node_modules/lerna/dist/cli.js:5799:9)
lerna ERR!     at /home/ubuntu/jbrowse-components/node_modules/lerna/dist/cli.js:6622:36
lerna ERR!     at async Promise.all (index 0)
lerna ERR! lerna resolvedPrettier.resolveConfig.sync is not a function
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by cmdcolin** [comment]
note that my above comment was maybe due to us using v6...trying to upgrade to v7 since it looks like the prettier v3 compat is mentioned in https://github.com/lerna/lerna/releases/tag/v7.1.2

**Comment by chucksellick** [comment]
> note that my above comment was maybe due to us using lerna v6...trying to upgrade to lerna v7 since it looks like the prettier v3 compat is mentioned in https://github.com/lerna/lerna/releases/tag/v7.1.2

Thanks, was hitting this same error

Definitely agree with OP, it was quite surprising that lerna is invoking Prettier

**Comment by maribethb** [comment]
This seems really problematic. It was a total surprise to us that installing prettier would break versioning, because we used prettier v3 and lerna v6. I was able to update to lerna v7 to resolve it, but this approach means problems may recur in the future if prettier has another breaking change. I don't want my version of prettier to be tied to my version of lerna, especially if that relationship is totally undocumented.

Looking through the implementation, it seems like it would cause problems for anyone who installs prettier and passes in arguments on the command line, because lerna isn't invoking prettier under the same conditions a user normally would for their project.

I don't think lerna should be doing this at all. Instead, users could either have their formatter ignore `lerna.json`, or could write their own post-version script that formats files. Or, lerna could only update the version number and not rewrite the entire contents of `lerna.json`, which makes the format unlikely to change after a version update. But if it will continue to do so, then +1 the behavior should be documented and configurable.

**Comment by novascreen** [comment]
Even more relevant now that folks are starting to use Biome as a prettier replacement. Would be great if we could disable or customize this.
Ideally lerna shouldn't do this at all and remove the prettier dependency if possible.

**Comment by azaxarov** [comment]
This undocumented behaviour is known to cause confusion, as reported in https://github.com/lerna/lerna/issues/3476 and https://github.com/lerna/lerna/issues/3981.

As of https://github.com/lerna/lerna/pull/3482, the only way to prevent files from being formatted is to add a `.prettierignore` configuration.
