### ISSUE TITLE
Error with .modules.yaml not found after having pnpm-lock.yaml and installing via npm

### ISSUE THREAD

**Issue by yordan-kanchelov** [lerna/lerna#3842]
### Current Behavior
After migrating to `pnpm` as the package manager, the build process works fine when modules are installed through `pnpm`. However, if there exists a `pnpm-lock.yaml` file and the modules are installed through `npm`, the build fails with:

```lerna ERR! Error: Could not find ".modules.yaml" at "/Users/test-user/gitlab/****/node_modules/.modules.yaml"```

### Expected Behavior
The build should succeed, irrespective of whether the modules are installed through `npm` or `pnpm`, and even if the `pnpm-lock.yaml` is present. This behavior did not occur before the migration to `pnpm`.

### Steps to Reproduce
1. Migrate to `pnpm` as the package manager.
2. Install modules via `pnpm` – observe that the build process works.
3. Ensure that the `pnpm-lock.yaml` file is present.
4. Install modules via `npm`.
5. Run the build command: `npx lerna run build`. Observe the error regarding the missing `.modules.yaml`.
6. Remove the `pnpm-lock.yaml` file.
7. Re-run the build command and observe that the error is resolved.

### Failure Logs / Configuration
<details>
<summary> lerna.json </summary>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "version": "5.1.0-beta.1",
  "command": {
    "version": {
      "conventionalCommits": true,
      "changelogPreset": "conventional-changelog-conventionalcommits",
      "message": "chore(release): publish %s [skip ci]"
    },
    "publish": {
      "registry": "*censored*"
    }
  }
}
```

</details>

<details>
<summary> lerna-debug.log </summary>

```
0 silly argv {
0 silly argv   _: [ 'run' ],
0 silly argv   lernaVersion: '7.3.0',
0 silly argv   '$0': '/Users/test-user/gitlab-work/test-project/node_modules/.bin/lerna',
0 silly argv   script: 'build'
0 silly argv }
1 notice cli v7.3.0
2 verbose packageConfigs Resolving packages based on package.json "workspaces" configuration.
3 verbose rootPath /Users/test-user/gitlab-work/live-casino
4 error Error: Could not find ".modules.yaml" at "/Users/test-user/gitlab-work/test-project/node_modules/.modules.yaml"
4 error     at loadPnpmHoistedDepsDefinition (/Users/test-user/gitlab-work/test-project/node_modules/nx/src/plugins/js/lock-file/utils/pnpm-normalizer.js:23:15)
4 error     at getNodes (/Users/test-user/gitlab-work/test-project/node_modules/nx/src/plugins/js/lock-file/pnpm-parser.js:69:77)
4 error     at getPnpmLockfileNodes (/Users/test-user/gitlab-work/test-project/node_modules/nx/src/plugins/js/lock-file/pnpm-parser.js:27:12)
4 error     at getLockFileNodes (/Users/test-user/gitlab-work/test-project/node_modules/nx/src/plugins/js/lock-file/lock-file.js:36:59)
4 error     at exports.createNodes (/Users/test-user/gitlab-work/test-project/node_modules/nx/src/plugins/js/index.js:42:64)
4 error     at buildProjectsConfigurationsFromProjectPathsAndPlugins (/Users/test-user/gitlab-work/test-project/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:68:88)
4 error     at createProjectConfigurations (/Users/test-user/gitlab-work/test-project/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:132:129)
4 error     at /Users/test-user/gitlab-work/test-project/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:80:39
4 error     at _retrieveProjectConfigurations (/Users/test-user/gitlab-work/test-project/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:79:12)
```

</details>

**Comment by fahslaj** [comment]
The `.modules.yaml` file is required to properly create a graph of the projects in your repository when using `pnpm`. Lerna picks which package manager to use based on lockfiles that exist in the repository, and it is assuming that the modules were installed via `pnpm` because a `pnpm-lock.yaml` exists.

Though Lerna supports both npm and pnpm individually, it is not recommended to try and use them both at once on the same monorepo. This could cause unwanted side effects with other tools than just Lerna. Could you please give an example that demonstrates the importance of support for two package managers at once in the same monorepo?

**Comment by yordan-kanchelov** [comment]
Thank you for shedding light on the .modules.yaml file and Lerna's behavior regarding package manager selection based on existing lockfiles. In our case, the majority of our team is using pnpm following a recent transition. However, there might be instances where someone might mistakenly install modules through npm. I believe the preferred use of pnpm shouldn't be a restriction from using npm when needed.

Would it be feasible for Lerna to identify the package manager in use based on the trigger command, and accordingly look for the respective lockfile? This way, the build process could accommodate inadvertent use of npm without failing.

**Comment by fahslaj** [comment]
> Would it be feasible for Lerna to identify the package manager in use based on the trigger command, and accordingly look for the respective lockfile? This way, the build process could accommodate inadvertent use of npm without failing.

This would be possible to implement, but then Lerna would then behave differently when run from two different package managers. For example, Lerna uses `pnpm-workspace.yaml` to detect packages when using `pnpm` but uses the `workspaces` property in `package.json` when using yarn or npm. This would cause unexpected behavior when using different execution commands like `npx`, `yarn dlx`, or `pnpx` with Lerna.

> I believe the preferred use of pnpm shouldn't be a restriction from using npm when needed.

While I understand the annoyance of accidentally using the wrong package manager occasionally, I do not think it is worth changing core functionality of Lerna to support mixing package managers in this way.

To smooth the transition to `pnpm`, you could try [this suggestion from `pnpm`](https://pnpm.io/only-allow-pnpm). It creates a much more graceful error message when a developer tries to use `npm install`.
