### ISSUE TITLE
Works fine locally, on GitHub Actions it says "nested alternate groups are not allowed"

### ISSUE THREAD

**Issue by trusktr** [lerna/lerna#3866]
## Current Behavior

On Windows (in GitHub Actions) it fails with this:

```
lerna ERR! Error: GenericFailure, Generic, error parsing glob '{package.json,apps/*/package.json,packages/{glas,docsifyjs+docsify}/package.json,package.json,apps/*/package.json,packages/*/package.json}': nested alternate groups are not allowed
lerna ERR!     at getNxWorkspaceFilesFromContext (C:\npm\prefix\node_modules\lerna\node_modules\nx\src\utils\workspace-context.js:16:29)
lerna ERR!     at retrieveWorkspaceFiles (C:\npm\prefix\node_modules\lerna\node_modules\nx\src\project-graph\utils\retrieve-workspace-files.js:26:138)
lerna ERR!     at async buildProjectGraphWithoutDaemon (C:\npm\prefix\node_modules\lerna\node_modules\nx\src\project-graph\project-graph.js:65:82)
lerna ERR!     at async createProjectGraphAsync (C:\npm\prefix\node_modules\lerna\node_modules\nx\src\project-graph\project-graph.js:116:25)
lerna ERR!     at async detectProjects (C:\npm\prefix\node_modules\lerna\dist\index.js:1449:25)
```

Seen here:

https://github.com/lume/lume/actions/runs/6540191328/job/17759677539

I do not have such a pattern anywhere in my package.json, so Lerna is creating this pattern internally, then failing on it. These are the only Lerna commands I'm running, from my scripts in package.json:

```
		"build:all": "npm run clean:all && lerna run build --ignore '{,glas,classy-solid}'",
		"build:all:noFail": "npm run clean:all && lerna run build --ignore '{,glas,classy-solid}' -- -- --noFail",
		"clean:all": "lerna run clean --ignore '{,glas,classy-solid}' || echo 'clean:all: missing executables, skipping.'",
		"test:all": "lerna run test --scope '{lume,@lume/element,element-behaviors,@lume/variable,@lume/eventful,@lume/autolayout,@lume/kiwi,@lume/three-projected-material,custom-attributes,james-bond,lowclass}'",
```

As seen there, I am not nesting `{}` inside `{}`.

Is this a problem because Lerna is using different code under the hood in Windows than in macOS? (I see `nx` in the stack trace).

## Expected Behavior

Expecting pkg.json scripts to work locally or in CI.

## Steps to Reproduce

TODO

### Failure Logs / Configuration

I only have the GitHub Actions output above, for now. I don't have a local reproduction.

### Environment

Windows latest in GitHub actions.

Lerna 4.0.0 (local)

**Comment by trusktr** [comment]
Aha! I upgraded lerna from 4.0.0 to 7.3.1 in my package.json, and now I can reproduce the issue when I run my scripts locally.

I should be able to make a reproduction...

**Comment by trusktr** [comment]
Ok, I've made a reproduction:

```sh
$ git clone git@github.com:lume/lume.git tmp-lume-lerna-fail-test
$ cd tmp-lume-lerna-fail-test
$ git checkout lerna-issue-3866
$ npm run fresh # this clones git submodules, then runs yarn install
$ npx lerna repair
lerna notice cli v7.3.1
lerna ERR! Error: GenericFailure, Generic, error parsing glob '{package.json,apps/*/package.json,packages/{glas,docsifyjs+docsify}/package.json,package.json,apps/*/package.json,packages/*/package.json}': nested alternate groups are not allowed
lerna ERR!     at getNxWorkspaceFilesFromContext (/Users/trusktr/src/tmp-lume-lerna-fail-test/node_modules/nx/src/utils/workspace-context.js:16:29)
lerna ERR!     at retrieveWorkspaceFiles (/Users/trusktr/src/tmp-lume-lerna-fail-test/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:26:138)
lerna ERR!     at async buildProjectGraphWithoutDaemon (/Users/trusktr/src/tmp-lume-lerna-fail-test/node_modules/nx/src/project-graph/project-graph.js:65:82)
lerna ERR!     at async createProjectGraphAsync (/Users/trusktr/src/tmp-lume-lerna-fail-test/node_modules/nx/src/project-graph/project-graph.js:116:25)
lerna ERR!     at async detectProjects (/Users/trusktr/src/tmp-lume-lerna-fail-test/node_modules/lerna/dist/index.js:1449:25)
lerna ERR! lerna GenericFailure, Generic, error parsing glob '{package.json,apps/*/package.json,packages/{glas,docsifyjs+docsify}/package.json,package.json,apps/*/package.json,packages/*/package.json}': nested alternate groups are not allowed
```

**Comment by trusktr** [comment]
Hmmmm, worth noting that in `package.json` I have

```js
	"workspaces": [
		".",
		"apps/*",
		"packages/!(glas|docsifyjs+docsify)"
	],
```

which is the only place in the project that mentions both `glas|docsifyjs+docsify` at the same time, while in `lerna.json` I have

```js
	"packages": ["./", "apps/*", "packages/*"],
```

Is Lerna reading my workspaces config from package.json?

**Comment by trusktr** [comment]
This is difficult to debug, `WorkspaceContext` is not JavaScript.

**Comment by trusktr** [comment]
I was ignoring `glas` and `docsify` from workspaces for some reason, but after removing `packages` from `lerna.json`, and using `"packages/*"` in pkg.json workspaces to re-include glas/docsify, Lerna is no longer having the error.

**Comment by fahslaj** [comment]
@trusktr can you confirm that this was a configuration issue on your end and not an issue in Lerna? Or is there still an unexpected error on Lerna 7+?

**Comment by oliversalzburg** [comment]
I have the same setup in `package.json`:

```json
"workspaces": ["packages/!(aws-ssm-secrets|keybase-notifications)"],
```

This also gets translated into the faulty result mentioned here. Seems very much like a lerna bug, unless this `workspaces` definition is illegal.

**Comment by trusktr** [comment]
> @trusktr can you confirm that this was a configuration issue on your end and not an issue in Lerna? Or is there still an unexpected error on Lerna 7+?

Yeah, it seems to be an issue in Lerna. The [reproduction above](https://github.com/lerna/lerna/issues/3866#issuecomment-1765441847) should show the issue.

The existence of a combination of packages in `node_modules` seems to be what causes the issue.
