### ISSUE TITLE
lerna version 7.4.2  import_devkit4.createProjectFileMapUsingProjectGraph is not a function

### ISSUE THREAD

**Issue by klh** [lerna/lerna#3899]
version 7.4.2

## Current Behavior

lerna publish prerelease --preid PR2433-8335cc7 --force-publish --yes --no-git-tag-version --no-push

Results in:

info cli using local version of lerna
lerna ERR! TypeError: (0 , import_devkit4.createProjectFileMapUsingProjectGraph) is not a function
lerna ERR!     at detectProjects (/Volumes/Sensitive/git/medtrace/ac2/node_modules/lerna/dist/index.js:1456:89)
lerna ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna ERR! lerna (0 , import_devkit4.createProjectFileMapUsingProjectGraph) is not a function

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

0 silly argv {
0 silly argv   _: [ 'publish' ],
0 silly argv   preid: 'PR2433-8335cc7',
0 silly argv   'force-publish': true,
0 silly argv   forcePublish: true,
0 silly argv   yes: true,
0 silly argv   y: true,
0 silly argv   'git-tag-version': false,
0 silly argv   gitTagVersion: false,
0 silly argv   push: false,
0 silly argv   composed: 'publish',
0 silly argv   lernaVersion: '7.4.2',
0 silly argv   '$0': 'lerna',
0 silly argv   bump: 'prerelease'
0 silly argv }
1 notice cli v7.4.2
2 verbose packageConfigs Explicit "packages" configuration found in lerna.json. Resolving packages using the configured glob(s): ["packages/*","packages/common/*","packages/applications/*","packages/locales/*"]
3 verbose rootPath /Volumes/Sensitive/git/medtrace/ac2
4 error TypeError: (0 , import_devkit4.createProjectFileMapUsingProjectGraph) is not a function
4 error     at detectProjects (/Volumes/Sensitive/git/medtrace/ac2/node_modules/lerna/dist/index.js:1456:89)
4 error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

</p></details>

### Environment

osx, node 20.9.0

**Comment by klh** [comment]
so this is an interdependency issue where lerna version 7.4.x requires NX version 17 to be installed - it would perhaps be a good idea to add a check for versions so that the errors makes sense to a dev.

**Comment by fahslaj** [comment]
@klh, I'm sorry that you are experiencing this issue. I was not able to reproduce this issue on a fresh code repository. The package manager ensures that the correct version of Nx is installed for use by Lerna, even if a different, older version of Nx is used within the workspace. Could you please provide a minimal reproduction of this issue?

**Comment by JamesHenry** [comment]
I'll close this one as there was no response regarding a reproduction, but I also wanted to let you know about the recently released Lerna v9 that modernized all the dependencies and added support for OIDC trusted publishing https://docs.npmjs.com/trusted-publishers, please update to the latest https://github.com/lerna/lerna/releases/tag/v9.0.0

If you experience the issue again on v9 please feel free to reopen and we will work on a reproduction
