### ISSUE TITLE
project-graph.json - no such file or directory (nodejs 21.3.0)

### ISSUE THREAD

**Issue by akornatskyy** [lerna/lerna#3914]
## Current Behavior

```sh
lerna exec --loglevel warn --stream tsc
```

```log
(node:21460) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
ERROR (1) when writing
ENOENT: no such file or directory, open '...\node_modules\.cache\nx\project-graph.json~7ecd1b76'
Error: ENOENT: no such file or directory, open '...\node_modules\.cache\nx\project-graph.json~7ecd1b76'
    at writeFileSync (node:fs:2352:20)
    at writeJsonFile (...\node_modules\nx\src\utils\fileutils.js:55:28)
    at writeCache (...\node_modules\nx\src\project-graph\nx-deps-cache.js:101:43)
    at buildProjectGraphUsingProjectFileMap (...\node_modules\nx\src\project-graph\build-project-graph.js:65:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildProjectGraphWithoutDaemon (...\node_modules\nx\src\project-graph\project-graph.js:72:27)
    at async createProjectGraphAsync (...\node_modules\nx\src\project-graph\project-graph.js:121:25)
    at async detectProjects (...\node_modules\lerna\dist\index.js:1553:25)
    at async ExecCommand.detectProjects (...\node_modules\lerna\dist\index.js:1772:50)
ERROR (2) when writing
ENOENT: no such file or directory, ...
```

## Steps to Reproduce

use nodejs 21.3.0. it works as expected with 21.2.0.

### Environment

lerna 8.0.0

**Comment by akornatskyy** [comment]
fixed with 21.4.0 release.
