### ISSUE TITLE
[Feature] See output from npm scripts with lerna run

### ISSUE THREAD

**Issue by liamcurry** [lerna/lerna#394]
Is there a way to see all output from the npm scripts that are run by `lerna run`? I'm not seeing this documented on the homepage or in the readme.

**Comment by liamcurry** [comment]
It does look like this is a feature in the master branch with the `--loglevel` args, but trying to install from github gives an error:

```
$ npm install --save-dev git://github.com/lerna/lerna.git
$ `npm bin`/lerna
module.js:471
    throw err;
    ^

Error: Cannot find module '../lib/index'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sagan/Dropbox/Projects/radio-dev/node_modules/lerna/bin/lerna.js:3:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Because the `lib` folder is missing from the repo I guess?

**Comment by seb0zz** [comment]
The `lib` folder is generated during `npm run build` which will be executed before every npm publish. I also wanted to checkout the master so my guess was to trigger an `npm run build` in the lerna directory during my `postinstall` hook. The problem is that the `src` directory does not come with npm install (see `.npmignore`). Could we remove the `src` directory from this file? Would make working on the master much easier.

**Comment by thejameskyle** [comment]
We should publish master

**Comment by hzoo** [comment]
Looks like this was done in https://github.com/lerna/lerna/pull/367, need to make a release
