### ISSUE TITLE
`TypeError: (0 , minimatch_1.minimatch) is not a function` when running `lerna run webpack --stream`

### ISSUE THREAD

**Issue by titanve** [lerna/lerna#3952]
## Current Behavior

When running `lerna run webpack --stream` I get the error:
```
yarn run v1.22.19
$ lerna run webpack --stream
lerna notice cli v8.1.2
lerna ERR! TypeError: (0 , minimatch_1.minimatch) is not a function
lerna ERR!     at buildProjectsConfigurationsFromProjectPathsAndPlugins (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:146:43)
lerna ERR!     at createProjectConfigurations (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
lerna ERR!     at _retrieveProjectConfigurations (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
lerna ERR!     at retrieveProjectConfigurations (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
lerna ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna ERR!     at async processFilesAndCreateAndSerializeProjectGraph (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:140:28)
lerna ERR!     at async getCachedSerializedProjectGraphPromise (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:43:16)
lerna ERR!     at async handleRequestProjectGraph (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/daemon/server/handle-request-project-graph.js:12:24)
lerna ERR!     at async handleResult (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/daemon/server/server.js:110:16)
lerna ERR! lerna (0 , minimatch_1.minimatch) is not a function
lerna ERR! lerna
lerna ERR! lerna Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
lerna ERR! lerna If the error persists, please run "nx reset".
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected Behavior

Lerna to compile and run my yarn workspaces

## Steps to Reproduce

install Lerna version `8.1.2` and run `lerna run webpack --stream`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "yarn",
  "packages": ["frontend/*"],
  "version": "0.0.0",
  "$schema": "node_modules/lerna/schemas/lerna-schema.json"
}
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv {
0 silly argv   _: [ 'run' ],
0 silly argv   stream: true,
0 silly argv   lernaVersion: '8.1.2',
0 silly argv   '$0': '/Users/rafael.mora/Sites/auth_manager/node_modules/.bin/lerna',
0 silly argv   script: 'webpack'
0 silly argv }
1 notice cli v8.1.2
2 verbose packageConfigs Explicit "packages" configuration found in lerna.json. Resolving packages using the configured glob(s): ["frontend/*"]
3 verbose rootPath /Users/rafael.mora/Sites/auth_manager
4 error TypeError: (0 , minimatch_1.minimatch) is not a function
4 error     at buildProjectsConfigurationsFromProjectPathsAndPlugins (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:146:43)
4 error     at createProjectConfigurations (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
4 error     at _retrieveProjectConfigurations (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
4 error     at retrieveProjectConfigurations (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
4 error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
4 error     at async processFilesAndCreateAndSerializeProjectGraph (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:140:28)
4 error     at async getCachedSerializedProjectGraphPromise (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:43:16)
4 error     at async handleRequestProjectGraph (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/daemon/server/handle-request-project-graph.js:12:24)
4 error     at async handleResult (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/daemon/server/server.js:110:16)
```

</p></details>

### Environment

```txt
npx lerna info                   1 ✘  54s  3.2.2   09:00:54
lerna notice cli v8.1.2
lerna ERR! TypeError: (0 , minimatch_1.minimatch) is not a function
lerna ERR!     at buildProjectsConfigurationsFromProjectPathsAndPlugins (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:146:43)
lerna ERR!     at createProjectConfigurations (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
lerna ERR!     at _retrieveProjectConfigurations (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
lerna ERR!     at retrieveProjectConfigurations (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
lerna ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna ERR!     at async processFilesAndCreateAndSerializeProjectGraph (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:140:28)
lerna ERR!     at async getCachedSerializedProjectGraphPromise (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:43:16)
lerna ERR!     at async handleRequestProjectGraph (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/daemon/server/handle-request-project-graph.js:12:24)
lerna ERR!     at async handleResult (/Users/rafael.mora/Sites/auth_manager/node_modules/nx/src/daemon/server/server.js:110:16)
lerna ERR! lerna (0 , minimatch_1.minimatch) is not a function
lerna ERR! lerna
lerna ERR! lerna Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
lerna ERR! lerna If the error persists, please run "nx reset".
```

**Comment by titanve** [comment]
I had an entry for `resolutions` in my `package.json` file and by removing it the issue got fixed ✅
