### ISSUE TITLE
tar dependency is broken after `npm audit fix`

### ISSUE THREAD

**Issue by codebam** [lerna/lerna#4005]
### Failure Logs / Configuration
```shell
❯ npm run build

> build
> lerna run build

/home/codebam/git/cf-workers-telegram-bot/node_modules/tar/lib/read-entry.js:97
  [SLURP] (ex, global) {
   ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/codebam/git/cf-workers-telegram-bot/node_modules/tar/lib/read-entry.js:97:4)
    at Module._compile (node:internal/modules/cjs/loader:1455:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1534:10)
    at Module.load (node:internal/modules/cjs/loader:1265:32)
    at Module._load (node:internal/modules/cjs/loader:1081:12)
    at Module.require (node:internal/modules/cjs/loader:1290:19)
    at require (node:internal/modules/helpers:188:18)
    at Object.<anonymous> (/home/codebam/git/cf-workers-telegram-bot/node_modules/tar/lib/pack.js:27:19)
    at Module._compile (node:internal/modules/cjs/loader:1455:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1534:10)

Node.js v22.0.0
```

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "version": "7.7.0"
}
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```

</p></details>

**Comment by bezoerb** [comment]
installing tar using `npm install tar` solved the issue for me

**Comment by gunzy83** [comment]
> installing tar using `npm install tar` solved the issue for me

This worked for me also (saved as a dev dependency). Utterly ridiculous that this is a solution though.

**Comment by JamesHenry** [comment]
Hi Folks, please could you retry with the latest lerna `8.1.5` and report back?

**Comment by fcano-ut** [comment]
Using the latest Lerna, the dependency alert seems to be fixed  🎉

**Comment by gunzy83** [comment]
I installed the `8.1.5` and removed the manual install of `tar` workaround and this is working. Thanks.

**Comment by NSeydoux** [comment]
This fixed the issue on my repository too.
