### ISSUE TITLE
Latest version with NX 19 is breaking yarn install/add for dependencies

### ISSUE THREAD

**Issue by DanOfir** [lerna/lerna#4011]
## Current Behavior

After upgrading to the latest lerna version 8.1.3, it also upgraded NX to v19.
in one of my apps, i tried to install react flow: `yarn add reactflow`
and get this error:
```
error Invariant Violation: expected workspace package to exist for "ora"
    at invariant (/Users/danofir/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:2318:15)
    at _loop2 (/Users/danofir/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:91560:9)
    at PackageHoister.init (/Users/danofir/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:91619:19)
    at PackageLinker.getFlatHoistedTree (/Users/danofir/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:48551:20)
    at PackageLinker.<anonymous> (/Users/danofir/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:48562:27)
    at Generator.next (<anonymous>)
    at step (/Users/danofir/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/danofir/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:328:14
    at new Promise (<anonymous>)
    at new F (/Users/danofir/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:5539:28)
```
I see that in NX version 19 "ora" is one of the dependencies.
reverting to 18.1.2 with older NX(18.3.5) everything seems to work

## Expected Behavior

install should work and dependencies should be OK.

## Steps to Reproduce

Upgrade Lerna to latest (8.1.3)
in one of the sub projects/apps: `yarn add reactflow`
followed by: `yarn install`

redacted package.json in root folder
```json
{
"devDependencies": {
    "lerna": "8.1.3",
    "nx": "18.3.5",
  }
}
```

package.json inside one of the app
```json
{
"dependencies": {
    "reactflow": "^11.11.3",
}
}
```

**Comment by JamesHenry** [comment]
@DanOfir please kindly provide a minimal reproduction, I cannot reproduce

<img width="1512" alt="image" src="https://github.com/lerna/lerna/assets/900523/15a31cad-b9b3-4c15-bd12-67473cac7210">
