### ISSUE TITLE
Regression: cannot run lerna since 8.1.5 with MODULE packages

### ISSUE THREAD

**Issue by 92dev** [lerna/lerna#4040]
#4033 seems to break dependancies when running lerna using `npm run`
This happened when migrating the `gauge` pacakge 
See https://github.com/lerna/lerna/blob/9e822ca9b27f6e798290058386f8c5e58b120c5b/libs/core/src/lib/npmlog/gauge/wide-truncate.ts

This probably used to work since it was a `.js` file and not a `.ts` like now with the migration
For now I workaround the issue by just specifying that `lerna` has to be under `8.1.5` - but I really prefer to work with latest

## Current Behavior

```
> dev
> lerna run --stream --parallel dev,storybook

..../node_modules/lerna/dist/index.js:319
    var stripAnsi = require("strip-ansi");
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module ..../node_modules/strip-ansi/index.js from ..../node_modules/lerna/dist/index.js not supported.
Instead change the require of ..../node_modules/strip-ansi/index.js in ..../node_modules/lerna/dist/index.js to a dynamic import() which is available in all CommonJS modules.
    at libs/core/src/lib/npmlog/gauge/wide-truncate.ts (/..../node_modules/lerna/dist/index.js:319:21)
    at __require (..../node_modules/lerna/dist/index.js:12:50)
    at libs/core/src/lib/npmlog/gauge/render-template.ts (..../node_modules/lerna/dist/index.js:453:24)
    at __require (..../node_modules/lerna/dist/index.js:12:50)
    at libs/core/src/lib/npmlog/gauge/plumbing.ts (..../node_modules/lerna/dist/index.js:660:26) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.14.0
```

## Expected Behavior

For it to work like the past

## Steps to Reproduce

Use a package scheme such as:
```
{
  "name": "lerna-regression",
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "scripts": {
    "dev": "lerna run --stream --parallel dev,storybook",
    "build": "lerna run --stream build",
    "type-check": "lerna run type-check"
  },
  "devDependencies": {
    "lerna": "^8.1.3",
    "prettier": "^3.2.5",
    "prettier-plugin-tailwindcss": "^0.6.1"
  }
}
```

with some module package:
```
{
  "name": "@lerna-regression/core",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "build-storybook": "storybook build",
    "build": "tsc && vite build",
    "coverage": "vitest run --coverage",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview",
    "storybook": "storybook dev -p 6006 --no-open",
    "test:watch": "vitest --watch",
    "test": "vitest",
    "type-check": "tsc --noEmit"
  },
  "devDependencies": {
    "@chromatic-com/storybook": "^1.5.0",
    "@storybook/addon-essentials": "^8.1.9",
    "@storybook/addon-interactions": "^8.1.9",
    "@storybook/addon-links": "^8.1.9",
    "@storybook/blocks": "^8.1.9",
    "@storybook/react": "^8.1.9",
    "@storybook/react-vite": "^8.1.9",
    "@storybook/test": "^8.1.9",
    "@tailwindcss/forms": "^0.5.7",
    "@tailwindcss/typography": "^0.5.13",
    "@testing-library/dom": "^10.1.0",
    "@testing-library/jest-dom": "^6.4.6",
    "@testing-library/react": "^16.0.0",
    "@testing-library/user-event": "^14.5.2",
    "@types/react": "^18.2.66",
    "@types/react-dom": "^18.2.22",
    "@typescript-eslint/eslint-plugin": "^7.2.0",
    "@typescript-eslint/parser": "^7.2.0",
    "@vitejs/plugin-react-swc": "^3.5.0",
    "eslint": "^8.57.0",
    "eslint-import-resolver-typescript": "^3.6.1",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.6",
    "eslint-plugin-storybook": "^0.8.0",
    "storybook": "^8.1.9",
    "tailwindcss": "^3.4.4",
    "tailwindcss-react-aria-components": "^1.1.3",
    "typescript": "^5.2.2",
    "vite": "^5.2.0",
    "vite-plugin-svgr": "^4.2.0",
    "vitest": "^1.6.0",
    "vitest-canvas-mock": "^0.3.3"
  },
  "peerDependencies": {
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "react": "^18.3.1",
    "tailwind-merge": "^2.3.0",
    "typewriter-effect": "^2.21.0",
    "unist-util-visit": "^5.0.0",
    "zod": "^3.23.8",
    "zustand": "^4.5.2"
  }
}
```

**Comment by serialito74** [comment]
Same error with 8.1.5 and 8.1.6

Workaround use lerna 8.1.4
