### ISSUE TITLE
Support for the PNPM (9.5) `catalog:` package.json dependency resolution

### ISSUE THREAD

**Issue by JulianCataldo** [lerna/lerna#4055]
Hello!

Not sure if it's a feat. or a fix.

## Current Behavior

```sh
Run pnpm lerna publish --conventional-commits --exact --conventional-prerelease --canary --dist-tag=next --preid=next --yes
lerna-lite notice cli v3.5.1
lerna-lite info versioning independent
lerna-lite info ci enabled
lerna-lite ERR! Error: Unsupported URL Type "catalog:": catalog:
lerna-lite ERR!     at unsupportedURLType (/home/runner/work/gracile/gracile/node_modules/.pnpm/npm-package-arg@[11](https://github.com/gracile-web/gracile/actions/runs/10124756135/job/27999461862#step:19:12).0.2/node_modules/npm-package-arg/lib/npa.js:310:15)
lerna-lite ERR!     at fromURL (/home/runner/work/gracile/gracile/node_modules/.pnpm/npm-package-arg@11.0.2/node_modules/npm-package-arg/lib/npa.js:367:13)
lerna-lite ERR!     at Function.resolve (/home/runner/work/gracile/gracile/node_modules/.pnpm/npm-package-arg@11.0.2/node_modules/npm-package-arg/lib/npa.js:83:[12](https://github.com/gracile-web/gracile/actions/runs/10124756135/job/27999461862#step:19:13))
lerna-lite ERR!     at file:///home/runner/work/gracile/gracile/node_modules/.pnpm/@lerna-lite+core@3.5.1_typescript@5.5.4/node_modules/@lerna-lite/core/dist/package-graph/package-graph.js:45:38
lerna-lite ERR!     at Array.forEach (<anonymous>)
lerna-lite ERR!     at file:///home/runner/work/gracile/gracile/node_modules/.pnpm/@lerna-lite+core@3.5.1_typescript@5.5.4/node_modules/@lerna-lite/core/dist/package-graph/package-graph.js:30:44
lerna-lite ERR!     at PackageGraph.forEach (<anonymous>)
lerna-lite ERR!     at new PackageGraph (file:///home/runner/work/gracile/gracile/node_modules/.pnpm/@lerna-lite+core@3.5.1_typescript@5.5.4/node_modules/@lerna-lite/core/dist/package-graph/package-graph.js:26:14)
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: Unsupported URL Type "catalog:": catalog:
    at unsupportedURLType (/home/runner/work/gracile/gracile/node_modules/.pnpm/npm-package-arg@11.0.2/node_modules/npm-package-arg/lib/npa.js:310:15)
    at fromURL (/home/runner/work/gracile/gracile/node_modules/.pnpm/npm-package-arg@11.0.2/node_modules/npm-package-arg/lib/npa.js:367:[13](https://github.com/gracile-web/gracile/actions/runs/10124756135/job/27999461862#step:19:14))
    at Function.resolve (/home/runner/work/gracile/gracile/node_modules/.pnpm/npm-package-arg@11.0.2/node_modules/npm-package-arg/lib/npa.js:83:12)
    at file:///home/runner/work/gracile/gracile/node_modules/.pnpm/@lerna-lite+core@3.5.1_typescript@5.5.4/node_modules/@lerna-lite/core/dist/package-graph/package-graph.js:45:38
    at Array.forEach (<anonymous>)
    at file:///home/runner/work/gracile/gracile/node_modules/.pnpm/@lerna-lite+core@3.5.1_typescript@5.5.4/node_modules/@lerna-lite/core/dist/package-graph/package-graph.js:30:44
    at PackageGraph.forEach (<anonymous>)
    at new PackageGraph (file:///home/runner/work/gracile/gracile/node_modules/.pnpm/@lerna-lite+core@3.5.1_typescript@5.5.4/node_modules/@lerna-lite/core/dist/package-graph/package-graph.js:26:[14](https://github.com/gracile-web/gracile/actions/runs/10124756135/job/27999461862#step:19:15))
    at file:///home/runner/work/gracile/gracile/node_modules/.pnpm/@lerna-lite+core@3.5.1_typescript@5.5.4/node_modules/@lerna-lite/core/dist/command.js:187:37 {
  code: 'EUNSUPPORTEDPROTOCOL'
}

Node.js v22.2.0
Error: Process completed with exit code 1.
```

## Expected Behavior

Should handle `catalog:` in a similar fashion as `workspace:`.

### Environment

[PNPM Catalogs](https://pnpm.io/catalogs) (added in v9.5)

**Comment by JulianCataldo** [comment]
For anyone in the same situation, I think using an agnostic solution that play nice with Lerna could be something like this: https://www.npmjs.com/package/syncpack

**Comment by eyolas** [comment]
As a workaround for the issue, a pnpm patch can be used.

In the root of the monorepo, create a folder called `patches` and create a file called `lerna@8.1.8.patch`

In the root package.json file, add the following line:
```json
"patchedDependencies": {
    "lerna@8.1.8": "patches/lerna@8.1.8.patch"
}
```

In the `patches/lerna@8.1.8.patch` file, add the following content:
```diff
diff --git a/dist/index.js b/dist/index.js
index 033f2f5861d744959ee67740f9f625ab3b8455d1..cefd8872b7ef91725957296e708809791ec0ff3c 100644
--- a/dist/index.js
+++ b/dist/index.js
@@ -7071,6 +7071,7 @@ var init_package_graph = __esm({
             const depNode = this.get(depName);
             let spec = graphDependencies[depName].replace(/^link:/, "file:");
             const isWorkspaceSpec = /^workspace:/.test(spec);
+            const isCatalog = /^catalog:/.test(spec);
             let fullWorkspaceSpec;
             let workspaceAlias;
             if (isWorkspaceSpec) {
@@ -7087,6 +7088,9 @@ var init_package_graph = __esm({
                 }
               }
             }
+            if (isCatalog) {
+              spec = spec.replace(/^catalog:/, "");
+            }
             const resolved = import_npm_package_arg7.default.resolve(depName, spec, currentNode.location);
             resolved.workspaceSpec = fullWorkspaceSpec;
             resolved.workspaceAlias = workspaceAlias;
```

Then run `pnpm install` to apply the patch.

This patch will remove the `catalog:` prefix from the dependency spec before resolving it.

**Comment by wassim-ben-amor** [comment]
[eyolas](https://github.com/eyolas), here doing `spec = spec.replace(/^catalog:/, "");` will just remove the `catalog:`, but I think you are missing replacing it with the version pulled from the original catalog 🤔

**Comment by JamesHenry** [comment]
Hi Folks, please can you open a PR with the necessary changes?

**Comment by grant-progress** [comment]
I'm interested in making a PR for this. There's something I'd like to clarify first: Lerna docs state that `npm publish` will be used regardless of package manager configuration. Is there a strict internal requirement which necessitates this?

It would be easier, rather than reimplementing `catalog:` resolution in Lerna, to rely on `pnpm publish` to perform the correct behavior at publish invocation. In my mind this is the simplest fix both for `catalog` and `workspace` protocol support, but if it's out of the question for reasons unknown to me, I can look at reimplementing PNPM's lookup (which is, of course, not particularly difficult).

Edit: it occurs to me that either way this will require at least some catalog resolution logic for package change detection; if the user updates catalog dependency versions I assume dependent packages should be versioned.

**Comment by mathieustan** [comment]
Hi, just for info — I ran into the same issue on a personal project. Switching to lerna-lite solved it, since it handles the case properly.

**Comment by bradleat** [comment]
@grant-progress or `bun publish`, etc

**Comment by literat** [comment]
Hi, the same goes for the `yarn` too (https://yarnpkg.com/features/catalogs). It supports catalogs as well.

**Comment by grant-progress** [comment]
For my part, I just moved us on to Nx proper. Wasn't too complicated and the PNPM support is better (though not perfect).
