### ISSUE TITLE
lerna publish from-package error in lerna@8.1.5-8.1.7, but lerna@8.1.4 is ok

### ISSUE THREAD

**Issue by liangskyli** [lerna/lerna#4057]
## Current Behavior
 run lerna publish from-package

```
lerna ERR! TypeError: Cannot set properties of null (setting 'peer')
lerna ERR!     at visit (/xxxx/mock/node_modules/.pnpm/@npmcli+arborist@7.5.3/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:101:54)
lerna ERR!     at visitNode (/xxxxmock/node_modules/.pnpm/treeverse@3.0.0/node_modules/treeverse/lib/depth-descent.js:58:25)
lerna ERR!     at next (/xxxx/mock/node_modules/.pnpm/treeverse@3.0.0/node_modules/treeverse/lib/depth-descent.js:44:19)
lerna ERR!     at depth (/xxxx/mock/node_modules/.pnpm/treeverse@3.0.0/node_modules/treeverse/lib/depth-descent.js:83:10)
lerna ERR!     at depth (/xxxx/mock/node_modules/.pnpm/treeverse@3.0.0/node_modules/treeverse/lib/depth.js:27:12)
lerna ERR!     at unsetFlag (/xxxx/mock/node_modules/.pnpm/@npmcli+arborist@7.5.3/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:96:5)
lerna ERR!     at /xxxx/mock/node_modules/.pnpm/@npmcli+arborist@7.5.3/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:63:7
lerna ERR!     at Map.forEach (<anonymous>)
lerna ERR!     at calcDepFlagsStep (/xxxx/mock/node_modules/.pnpm/@npmcli+arborist@7.5.3/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:41:17)
lerna ERR! lerna Cannot set properties of null (setting 'peer')

```

## Expected Behavior
 run lerna publish from-package
expected no error

## Steps to Reproduce

run:  lerna publish from-package
when use lerna@8.1.4 is ok
when use lerna@8.1.5-8.1.7 is error

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "npmClient": "pnpm",
  "version": "4.0.1",
  "command": {
    "version": {
      "conventionalCommits": true,
      "changelogPreset": {
        "name": "conventional-changelog-conventionalcommits",
        "issuePrefixes": ["#"],
        "types": [
          {
            "type": "feat",
            "section": "Features"
          },
          {
            "type": "feature",
            "section": "Features"
          },
          {
            "type": "fix",
            "section": "Bug Fixes"
          },
          {
            "type": "perf",
            "section": "Performance Improvements"
          },
          {
            "type": "revert",
            "section": "Reverts"
          },
          {
            "type": "docs",
            "section": "Documentation",
            "hidden": true
          },
          {
            "type": "style",
            "section": "Styles",
            "hidden": true
          },
          {
            "type": "chore",
            "section": "Miscellaneous Chores",
            "hidden": true
          },
          {
            "type": "refactor",
            "section": "Code Refactoring",
            "hidden": true
          },
          {
            "type": "test",
            "section": "Tests",
            "hidden": true
          },
          {
            "type": "build",
            "section": "Build System",
            "hidden": true
          },
          {
            "type": "ci",
            "section": "Continuous Integration",
            "hidden": true
          }
        ],
        "issueUrlFormat": "{{host}}/{{owner}}/{{repository}}/issues/{{id}}",
        "commitUrlFormat": "{{host}}/{{owner}}/{{repository}}/commit/{{hash}}",
        "compareUrlFormat": "{{host}}/{{owner}}/{{repository}}/compare/{{previousTag}}...{{currentTag}}",
        "userUrlFormat": "{{host}}/{{user}}"
      },
      "message": "chore: update version %s",
      "push": false
    },
    "publish": {
      "ignoreChanges": ["ignored-file", "*.md"],
      "registry": "https://registry.npmjs.org/",
      "message": "chore: publish release %s"
    }
  }
}

```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
0 silly argv {
0 silly argv   _: [ 'publish' ],
0 silly argv   composed: 'publish',
0 silly argv   lernaVersion: '8.1.5',
0 silly argv   '$0': 'node_modules/lerna/dist/cli.js',
0 silly argv   bump: 'from-package'
0 silly argv }
1 notice cli v8.1.5
2 verbose packageConfigs Package manager "pnpm" detected. Resolving packages using `pnpm-workspace.yaml`.
3 verbose rootPath /xxxx/mock
4 verbose session 39e25e9268841368
5 verbose user-agent lerna/8.1.5/node@v16.14.0+x64 (darwin)
6 verbose git-describe undefined => "v4.0.1-0-g1af883b"
7 silly git-describe parsed => {"lastTagName":"v4.0.1","lastVersion":"v4.0.1","refCount":"0","sha":"1af883b","isDirty":false}
8 silly getProjectsWithUnpublishedPackages
9 info publish Publishing packages to npm...
10 silly getCurrentSHA
11 verbose getCurrentSHA 1af883bf42a82853e3325a684b92bc69a50c0a41
12 silly lifecycle No script for "prepublish" in "root", continuing
13 silly lifecycle "prepare" starting in "root"
14 info lifecycle root@undefined~prepare: root@undefined
15 silly lifecycle "prepare" finished in "root"
16 silly lifecycle No script for "prepublishOnly" in "root", continuing
17 silly lifecycle No script for "prepack" in "root", continuing
18 verbose pack-directory packages/utils
19 silly lifecycle No script for "prepublish" in "@liangskyli/utils", continuing
20 silly lifecycle No script for "prepare" in "@liangskyli/utils", continuing
21 silly lifecycle No script for "prepublishOnly" in "@liangskyli/utils", continuing
22 silly lifecycle No script for "prepack" in "@liangskyli/utils", continuing
23 silly lifecycle No script for "postpack" in "@liangskyli/utils", continuing
24 verbose packed packages/utils
25 verbose pack-directory packages/grpc-mock
26 silly lifecycle No script for "prepublish" in "@liangskyli/grpc-mock", continuing
27 verbose pack-directory packages/http-mock-gen
28 silly lifecycle No script for "prepublish" in "@liangskyli/http-mock-gen", continuing
29 verbose pack-directory packages/mock
30 silly lifecycle No script for "prepublish" in "@liangskyli/mock", continuing
31 silly lifecycle No script for "prepare" in "@liangskyli/grpc-mock", continuing
32 silly lifecycle No script for "prepare" in "@liangskyli/http-mock-gen", continuing
33 silly lifecycle No script for "prepare" in "@liangskyli/mock", continuing
34 silly lifecycle No script for "prepublishOnly" in "@liangskyli/grpc-mock", continuing
35 silly lifecycle No script for "prepublishOnly" in "@liangskyli/mock", continuing
36 silly lifecycle No script for "prepublishOnly" in "@liangskyli/http-mock-gen", continuing
37 silly lifecycle No script for "prepack" in "@liangskyli/grpc-mock", continuing
38 silly lifecycle No script for "prepack" in "@liangskyli/mock", continuing
39 silly lifecycle No script for "prepack" in "@liangskyli/http-mock-gen", continuing
40 error TypeError: Cannot set properties of null (setting 'peer')
40 error     at visit (/xxxx/mock/node_modules/.pnpm/@npmcli+arborist@7.5.3/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:101:54)
40 error     at visitNode (/xxxx/mock/node_modules/.pnpm/treeverse@3.0.0/node_modules/treeverse/lib/depth-descent.js:58:25)
40 error     at next (/xxxx/mock/node_modules/.pnpm/treeverse@3.0.0/node_modules/treeverse/lib/depth-descent.js:44:19)
40 error     at depth (/xxxx/mock/node_modules/.pnpm/treeverse@3.0.0/node_modules/treeverse/lib/depth-descent.js:83:10)
40 error     at depth (/xxxx/mock/node_modules/.pnpm/treeverse@3.0.0/node_modules/treeverse/lib/depth.js:27:12)
40 error     at unsetFlag (/xxxx/mock/node_modules/.pnpm/@npmcli+arborist@7.5.3/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:96:5)
40 error     at /xxxx/mock/node_modules/.pnpm/@npmcli+arborist@7.5.3/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:63:7
40 error     at Map.forEach (<anonymous>)
40 error     at calcDepFlagsStep (/xxxx/mock/node_modules/.pnpm/@npmcli+arborist@7.5.3/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:41:17)

```

</p></details>

**Comment by liangskyli** [comment]
this is the submission records that affect errors: #4033

**Comment by liangskyli** [comment]
need upgrade @npmcli/arborist@7.5.3 to @npmcli/arborist@7.5.4 fix, see:  https://github.com/npm/cli/pull/7579
<img width="837" alt="image" src="https://github.com/user-attachments/assets/1fd67853-0741-46cc-b075-5c828f8e9a94">
