### ISSUE TITLE
[Bug] lerna publish fails immediately with "This socket is closed" on node v7

### ISSUE THREAD

**Issue by cchamberlain** [lerna/lerna#409]
Seeing this happening consistently across 2 lerna repos when using node `v7.1.0`. Downgrading to `v6.9.1` resolves the issue.

When I run `lerna publish` I see the following output:

```bash
Lerna v2.0.0-beta.30
Current version: 0.16.1
Checking for updated packages...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at Console.log (console.js:43:16)
    at Logger._log (C:\Users\ColeChamberlain\local\npm\node_modules\lerna\lib\logger.js:57:17)
    at Logger.error (C:\Users\ColeChamberlain\local\npm\node_modules\lerna\lib\logger.js:94:12)
    at PublishCommand._attempt (C:\Users\ColeChamberlain\local\npm\node_modules\lerna\lib\Command.js:174:21)
```

**Comment by gigabo** [comment]
Yikes!  @cchamberlain Do you know if this is windows specific?

**Comment by doug-wade** [comment]
we never received a response; closing.
