### ISSUE TITLE
CircleCI error when running yarn test script

### ISSUE THREAD

**Issue by titanve** [lerna/lerna#4109]
## Current Behavior

Locally the yarn test script is running fine but in CircleCI we are seeing this error:
```
/bin/sh: 1: bun: not found
lerna ERR! Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
lerna ERR!       An error occurred while processing files for the nx/js/dependencies-and-lockfile plugin.
lerna ERR!     - bun.lockb: Command failed: bun /home/circleci/auth_manager/bun.lockb
lerna ERR!   /bin/sh: 1: bun: not found
lerna ERR!   
lerna ERR!       Error: Command failed: bun /home/circleci/auth_manager/bun.lockb
lerna ERR!       /bin/sh: 1: bun: not found
lerna ERR!       
lerna ERR!           at genericNodeError (node:internal/errors:984:15)
lerna ERR!           at wrappedFn (node:internal/errors:538:14)
lerna ERR!           at checkExecSyncError (node:child_process:890:11)
lerna ERR!           at execSync (node:child_process:962:15)
lerna ERR!           at exports.createNodes (/home/circleci/auth_manager/node_modules/nx/src/plugins/js/index.js:35:44)
lerna ERR!           at /home/circleci/auth_manager/node_modules/nx/src/project-graph/plugins/utils.js:10:33
lerna ERR!           at Array.map (<anonymous>)
lerna ERR!           at createNodesFromFiles (/home/circleci/auth_manager/node_modules/nx/src/project-graph/plugins/utils.js:8:35)
lerna ERR!           at LoadedNxPlugin.createNodes (/home/circleci/auth_manager/node_modules/nx/src/project-graph/plugins/internal-api.js:27:76)
lerna ERR! lerna Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
```

## Expected Behavior

The test to run without errors

## Steps to Reproduce

My yarn test script runs:
```
lerna run build:test --concurrency 2
```

### Failure Logs / Configuration
![image](https://github.com/user-attachments/assets/8ec462fd-42e1-41a3-b510-51e28a685544)

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "yarn",
  "packages": ["frontend/*"],
  "version": "0.0.0",
  "$schema": "node_modules/lerna/schemas/lerna-schema.json"
}
```

</p></details>

### Environment

```
lerna notice cli v8.1.9

 Environment info:

  System:
    OS: macOS 15.0.1
    CPU: (12) arm64 Apple M2 Max
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v20.11.1/bin/npm
  Utilities:
    Git: 2.42.0 - /opt/homebrew/bin/git
  npmPackages:
    lerna: 8.1.9 => 8.1.9
```

**Comment by JamesHenry** [comment]
Is this a new repo? Lerna has never claimed to have `bun` support and it doesn't have any explicit handling for it, if it were to happen to work that's fine, but you would be off the supported path.

The most obvious question (and I have to ask it because you haven't explicitly addressed it) is have you installed bun explicitly in your CI environment (circle in this case)?

You do appear to have the bun specific lock file in there (which again lerna has no handling for), so it was suggest you are expecting `bun` to be present, but have you explicitly installed it on Circle?

**Comment by titanve** [comment]
Hi @JamesHenry 

I do have `bun` installed but I haven't installed it in my CI env; I've been able to upgrade `lerna` without troubles until now. We have had `bun` installed since a long time ago.

Thanks.

**Comment by JamesHenry** [comment]
Again, just to set expectations, lerna has never claimed to have bun support. 

Out of interest, at what version of lerna did this behaviour change for you?

My guess is that you have gone from internally leveraging an nx version that ignored bun lockfiles altogether, to one that now supports them (again, though, lerna does not). Therefore the internals are trying to evaluate your bun lock file during project graph construction.

How are you running bun in CI if you haven't installed it there? Why are you running `yarn` commands if `bun` is your package manager? Your setup is very unclear to me right now, please provide more information.

**Comment by titanve** [comment]
Hi @JamesHenry 

We are not using `bun` locally or in the CI and this issue just happened in this latest upgrade for `lerna`
![image](https://github.com/user-attachments/assets/8b53b6bc-733a-4953-8a83-421934cc1093)

Thanks 🙏

**Comment by JamesHenry** [comment]
Hi @titanve do you definitely not have a `bun.lockb` file in the repo? Our logic all seems to check for that file's existence.

If you don't have that file in your repo please can you confirm what version of nx is in your node_modules tree, e.g. by running:

```sh
npm ls nx
```

Or equivalent

**Comment by JamesHenry** [comment]
I'll close this one for now as I've not heard back, but I wanted to let you know about the recently released Lerna v9 that modernized all the dependencies, including Nx for the task runner, and so you should no longer experience this issue, please update to the latest https://github.com/lerna/lerna/releases/tag/v9.0.0

If you experience the issue again on v9 please feel free to reopen and we will work on a reproduction
