### ISSUE TITLE
Lerna version/publish commands are failing when using PNPM as package manager

### ISSUE THREAD

**Issue by DanOfir** [lerna/lerna#4114]
## Current Behavior

When using PNPM, version and publish command won't work

## Expected Behavior

version and publish command should work as normal

## Steps to Reproduce

When using pnpm as package manager, I am using this command for version the packages in a CI `lerna version --conventional-commits --conventional-graduate --yes --loglevel verbose --force-git-tag`.
We can see versions are being upgraded and changes are being made to the relevant package.json files.
inside the version command source code in line 780 https://github.dev/lerna/lerna/blob/e81831fff4682b09865ad57e7332e3721ebef697/libs/commands/version/src/index.ts, we can see that if running with pnpm it will run: `pnpm install ...` but now it's a chicken and egg issue, cause this command will fail with `ERR_PNPM_NO_MATCHING_VERSION  No matching version found for` obviously, cause the versions and packages are not yet published. same for the publish command.
is there a workaround somewhere? 

lerna verb version Updating root pnpm-lock.yaml
lerna ERR! Error: Command failed with exit code 1: pnpm install --lockfile-only --ignore-scripts
lerna ERR! Scope: all 7 workspace projects
lerna ERR!  WARN  `node_modules` is present. Lockfile only installation will make it out-of-date
lerna ERR! Progress: resolved 1, reused 0, downloaded 0, added 0
lerna ERR!  ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @MyRepository/app@^1.5.1
lerna ERR! 
lerna ERR! 
lerna ERR! The latest release of @MyRepository/app is "1.5.0".
lerna ERR! 
lerna ERR! If you need the full list of all 12 published versions run "$ pnpm view @MyRepository/app versions".

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "version": "independent",
  "private": true,
  "npmClient": "pnpm",
  "ignoreChanges": [
    "**/__fixtures__/**",
    "**/__tests__/**",
    "**/*.md",
    "**/*.test.ts",
    ".npmrc",
    "**/dist/**",
    "**/build/**",
    "**/.cache/**",
    "**/node_modules/**",
    "**/*.js",
    "**/*.d.ts"
  ],
  "command": {
    "version": {
      "conventionalCommits": true,
      "message": "chore(release): publish"
    }
  }
}

```

```txt
107 error Error: Command failed with exit code 1: pnpm install --lockfile-only --ignore-scripts
107 error Scope: all 7 workspace projects
107 error  WARN  `node_modules` is present. Lockfile only installation will make it out-of-date
107 error Progress: resolved 1, reused 0, downloaded 0, added 0
107 error /myfolder/app:
107 error  ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @MyRepository/app@^1.5.1
107 error
107 error This error happened while installing a direct dependency of /myfolder/app
107 error
107 error The latest release of @MyRepository/app is "1.5.0".
107 error
107 error If you need the full list of all 12 published versions run "$ pnpm view @MyRepository/app versions".
107 error     at makeError (/myfolder/node_modules/.pnpm/execa@5.0.0/node_modules/execa/lib/error.js:59:11)
107 error     at handlePromise (/myfolder/node_modules/.pnpm/execa@5.0.0/node_modules/execa/index.js:114:26)
107 error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
107 error     at async VersionCommand.updatePackageVersions (/myfolder/node_modules/.pnpm/lerna@8.1.2_encoding@0.1.13/node_modules/lerna/dist/index.js:8436:11)
107 error     at async Promise.all (index 0)

```

</p></details>

### Environment
lerna notice cli v8.1.2
lerna info versioning independent

 Environment info:

  System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.13.1/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
  Utilities:
    Git: 2.39.5 - /usr/bin/git
  npmPackages:
    lerna: 8.1.2 => 8.1.2 
    
    nx@18.3.5
    pnpm@9.12.3

**Comment by JamesHenry** [comment]
I think you might be running into the fact that pnpm v9 no longer links local packages by default if they use version numbers, only if they use local protocols like `workspace:`. In v8 it linked all local packages by default.

You can control it via this option:

https://pnpm.io/npmrc#link-workspace-packages

**Comment by JamesHenry** [comment]
I will assume this one was resolved by my previous comment and close, many thanks
