### ISSUE TITLE
lerna ERR! lerna WorkspaceContext is not a constructor

### ISSUE THREAD

**Issue by LiuLingyang** [lerna/lerna#4135]
## Current Behavior
Current Behavior
after upgrading lerna 8.1.8，get an error when i run lerna command:

lerna ERR! TypeError: WorkspaceContext is not a constructor
lerna ERR! at setupWorkspaceContext (/Users/lanberts/Documents/create-next-app/node_modules/nx/src/utils/workspace-context.js:10:24)
lerna ERR! at ensureContextAvailable (/Users/lanberts/Documents/create-next-app/node_modules/nx/src/utils/workspace-context.js:50:9)
lerna ERR! at globWithWorkspaceContext (/Users/lanberts/Documents/create-next-app/node_modules/nx/src/utils/workspace-context.js:21:5)
lerna ERR! at retrieveProjectConfigurations (/Users/lanberts/Documents/create-next-app/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:41:77)
lerna ERR! at buildProjectGraphAndSourceMapsWithoutDaemon (/Users/lanberts/Documents/create-next-app/node_modules/nx/src/project-graph/project-graph.js:77:98)
lerna ERR! at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna ERR! at async createProjectGraphAndSourceMapsAsync (/Users/lanberts/Documents/create-next-app/node_modules/nx/src/project-graph/project-graph.js:201:25)
lerna ERR! at async createProjectGraphAsync (/Users/lanberts/Documents/create-next-app/node_modules/nx/src/project-graph/project-graph.js:190:39)
lerna ERR! at async detectProjects (/Users/lanberts/Documents/create-next-app/node_modules/lerna/dist/index.js:1563:25)
lerna ERR! lerna WorkspaceContext is not a constructor
![image](https://github.com/user-attachments/assets/2d54db54-bb1a-491b-adf6-d167c38bb23e)

## Expected Behavior
run lerna command without error

### Environment

yarn:1.22.22 
node: 18.20.3
macOS: 10.14.3

**Comment by JamesHenry** [comment]
Hi again @LiuLingyang, I believe this should have been resolved already in `8.2.1`, but the recently released Lerna v9 modernized all the dependencies, including Nx for the task runner, and so you should no longer experience this issue, please update to the latest https://github.com/lerna/lerna/releases/tag/v9.0.0

If you experience the issue again on v9 please feel free to reopen and we will work on a reproduction
