### ISSUE TITLE
Fetching packages... error Error: https://registry.yarnpkg.com/fs-constants/-/fs-constants-1.0.0.tgz: Request failed "304 Not Modified"

### ISSUE THREAD

**Issue by harsh-jha-qapita** [lerna/lerna#4137]
When Doing **yarn install** -

yarn install
yarn install v1.22.22
[1/4] 🔍  Resolving packages...
warning Resolution field "@types/react@17.0.11" is incompatible with requested version "@types/react@18.3.3"
warning Resolution field "@types/react@17.0.11" is incompatible with requested version "@types/react@18.3.3"
warning Resolution field "@types/react@17.0.11" is incompatible with requested version "@types/react@18.3.3"
warning Resolution field "@types/react@17.0.11" is incompatible with requested version "@types/react@18.3.3"
warning Resolution field "@types/react@17.0.11" is incompatible with requested version "@types/react@18.3.3"
warning Resolution field "@types/react@17.0.11" is incompatible with requested version "@types/react@18.3.3"
warning Resolution field "@types/react@17.0.11" is incompatible with requested version "@types/react@18.3.3"
[2/4] 🚚  Fetching packages...
error Error: https://registry.yarnpkg.com/fs-constants/-/fs-constants-1.0.0.tgz: Request failed "304 Not Modified"
    at Request.<anonymous> (/Users/harshjha/workspace/qmap-ui-4/qmap-ui-app/.yarn/releases/yarn-1.22.22.cjs:78280:16)
    at Request.emit (node:events:519:28)
    at module.exports.Request.onRequestResponse (/Users/harshjha/workspace/qmap-ui-4/qmap-ui-app/.yarn/releases/yarn-1.22.22.cjs:136694:10)
    at ClientRequest.emit (node:events:519:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:698:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:540:22)
    at TLSSocket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

dependency of fs-constant -

@nx/devkit@19.8.4 extraneous
  └─┬ nx@15.9.2 invalid: ">= 17 <= 20" from node_modules/@nx/devkit
    └─┬ tar-stream@2.2.0
      └── fs-constants@1.0.0

lerna@6.0.1 invalid: "8.1.8" from the root project
  └── nx@15.9.2 deduped invalid: ">= 17 <= 20" from node_modules/@nx/devkit

**Comment by singaravelanaws** [comment]
yarn install
yarn install v1.22.22
info No lockfile found.
[1/4] Resolving packages...
⠁ 
warning @google-cloud/storage > google-auth-library > gtoken > google-p12-pem@4.0.1: Package is no longer maintained
warning @types/nanoid@3.0.0: This is a stub types definition. nanoid provides its own type definitions, so you do not need this installed.
warning archiver > archiver-utils > glob@8.1.0: Glob versions prior to v9 are no longer supported
warning archiver > archiver-utils > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning firebase-admin > @google-cloud/firestore > google-gax > protobufjs-cli > glob@8.1.0: Glob versions prior to v9 are no longer supported
warning querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning unzipper > fstream@1.0.12: This package is no longer supported.
warning unzipper > fstream > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
warning unzipper > fstream > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning unzipper > fstream > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning yamljs > glob@7.2.3: Glob versions prior to v9 are no longer supported
[2/4] Fetching packages...
error Error: https://registry.yarnpkg.com/fs-constants/-/fs-constants-1.0.0.tgz: Request failed "304 Not Modified"
    at ResponseError.ExtendableBuiltin (/opt/yarn-v1.22.22/lib/cli.js:696:66)
    at new ResponseError (/opt/yarn-v1.22.22/lib/cli.js:802:124)
    at Request.<anonymous> (/opt/yarn-v1.22.22/lib/cli.js:66750:16)
    at Request.emit (node:events:518:28)
    at module.exports.Request.onRequestResponse (/opt/yarn-v1.22.22/lib/cli.js:142287:10)
    at ClientRequest.emit (node:events:518:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:702:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:118:17)
    at TLSSocket.socketOnData (node:_http_client:544:22)
    at TLSSocket.emit (node:events:518:28)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.                   => Same kind of issue

**Comment by singaravelanaws** [comment]
I used below cmd for temp solution: 

docker run -itd node:20.18.1
docker run -itd node:20.18.1

+ node -v
v20.18.1
+ npm -v
10.8.2

---------- below cmd inside the container----------
yarn add glob@7.1.6 minimatch@3.0.4 @types/glob@7.1.3
rm -rf dist node_modules yarn.lock package-lock.json
yarn add typescript@latest
yarn build
-----------------
i got dist folder
