### ISSUE TITLE
Bootstrap Failure

### ISSUE THREAD

**Issue by casesandberg** [lerna/lerna#451]
When running `lerna bootstrap`

`_this6.logger.warning("Symlink already exists for " + dependency + " dependency of " + filteredPackage.name + ", " + "but links to different location. Replacing with updated symlink...");`

```
TypeError: _this6.logger.warning is not a function
    at /Users/case/.nvm/versions/node/v7.1.0/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:298:33
    at /Users/case/.nvm/versions/node/v7.1.0/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:325:15
    at Array.forEach (native)
    at /Users/case/.nvm/versions/node/v7.1.0/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:279:12
    at Array.forEach (native)
    at BootstrapCommand.symlinkPackages (/Users/case/.nvm/versions/node/v7.1.0/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:271:29)
    at /Users/case/.nvm/versions/node/v7.1.0/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:101:23
    at /Users/case/.nvm/versions/node/v7.1.0/lib/node_modules/lerna/node_modules/async/lib/async.js:718:13
    at Immediate.iterate (/Users/case/.nvm/versions/node/v7.1.0/lib/node_modules/lerna/node_modules/async/lib/async.js:262:13)
    at runCallback (timers.js:637:20)
```

**Comment by posva** [comment]
As a workaround do `rm -r node_modules` on the packages directories

**Comment by gigabo** [comment]
Hi @casesandberg sorry you ran into trouble!
 
This looks like https://github.com/lerna/lerna/pull/444, which should be fixed with the _next_ version of Lerna when it's published.

Meanwhile I hope the workaround suggested by @posva will get you un-blocked.

If that doesn't work you could try this, which was suggested by @evocateur in #444:

```bash
git clean -fdx && npm i --cache-min=Infinity && lerna bootstrap
```

**Comment by casesandberg** [comment]
Worked, Thanks!
