### ISSUE TITLE
JS error when running boostrap

### ISSUE THREAD

**Issue by SamyPesse** [lerna/lerna#462]
With version v2.0.0-beta.31:

```
Lerna v2.0.0-beta.31
Bootstrapping 14 packages
Preinstalling packages
Installing external dependencies
Symlinking packages and binaries
/Users/samypesse/Projects/GitBook/gitbook/node_modules/lerna/lib/commands/BootstrapCommand.js:301
                  _this6.logger.warning(dependency + " is already installed for " + filteredPackage.name + ". " + "Replacing with symlink...");
                                ^

TypeError: _this6.logger.warning is not a function
    at /Users/samypesse/Projects/GitBook/gitbook/node_modules/lerna/lib/commands/BootstrapCommand.js:301:33
    at /Users/samypesse/Projects/GitBook/gitbook/node_modules/lerna/lib/commands/BootstrapCommand.js:325:15
    at Array.forEach (native)
    at /Users/samypesse/Projects/GitBook/gitbook/node_modules/lerna/lib/commands/BootstrapCommand.js:279:12
    at Array.forEach (native)
    at BootstrapCommand.symlinkPackages (/Users/samypesse/Projects/GitBook/gitbook/node_modules/lerna/lib/commands/BootstrapCommand.js:271:29)
    at /Users/samypesse/Projects/GitBook/gitbook/node_modules/lerna/lib/commands/BootstrapCommand.js:101:23
    at /Users/samypesse/Projects/GitBook/gitbook/node_modules/async/lib/async.js:718:13
    at iterate (/Users/samypesse/Projects/GitBook/gitbook/node_modules/async/lib/async.js:262:13)
    at /Users/samypesse/Projects/GitBook/gitbook/node_modules/async/lib/async.js:274:29
```

**Comment by SamyPesse** [comment]
Already fixed by https://github.com/lerna/lerna/pull/444
