### ISSUE TITLE
Lerna bootstrap fails with TypeError

### ISSUE THREAD

**Issue by rogierschouten** [lerna/lerna#467]
Lerna version 2.0.0-beta.31, Windows 10, NodeJS 6.7.0

```
mkdir temp
cd temp
git init
lerna init --independent
lerna bootstrap
```

yields

```
Lerna v2.0.0-beta.31
Bootstrapping 0 packages
Preinstalling packages
Errored while running BootstrapCommand.execute
TypeError: Cannot read property 'map' of undefined
    at bootstrapBatch (C:\Users\me\AppData\Local\Yarn\config\global\node_modules\lerna\lib\commands\BootstrapCommand.js:125:44)
    at BootstrapCommand.runScriptInPackages (C:\Users\me\AppData\Local\Yarn\config\global\node_modules\lerna\lib\commands\BootstrapCommand.js:143:7)
    at BootstrapCommand.preinstallPackages (C:\Users\me\AppData\Local\Yarn\config\global\node_modules\lerna\lib\commands\BootstrapCommand.js:155:12)
    at C:\Users\me\AppData\Local\Yarn\config\global\node_modules\lerna\lib\commands\BootstrapCommand.js:93:23
    at C:\Users\me\AppData\Local\Yarn\config\global\node_modules\async\lib\async.js:718:13
    at iterate (C:\Users\me\AppData\Local\Yarn\config\global\node_modules\async\lib\async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (C:\Users\me\AppData\Local\Yarn\config\global\node_modules\async\lib\async.js:281:9)
    at _parallel (C:\Users\me\AppData\Local\Yarn\config\global\node_modules\async\lib\async.js:717:9)
    at Object.async.series (C:\Users\me\AppData\Local\Yarn\config\global\node_modules\async\lib\async.js:739:9)
    at BootstrapCommand.bootstrapPackages (C:\Users\me\AppData\Local\Yarn\config\global\node_modules\lerna\lib\commands\BootstrapCommand.js:90:23)
```

**Comment by rogierschouten** [comment]
I just tried version 2.0.0-beta.30 and there it still works.

**Comment by lewisdawson** [comment]
I'm seeing the same issue with `v2.0.0-beta.31`.

**Comment by zxqfox** [comment]
Is this still actual?
