### ISSUE TITLE
Error: spawnSync /bin/sh ENOBUFS during ImportCommand.execute

### ISSUE THREAD

**Issue by garthk** [lerna/lerna#479]
```
lerna(info)    About to import 2 commits into from /tmp/xxx into packages/xxx
lerna(verbose) Successfully ran ImportCommand.initialize
lerna(verbose) Attempting running ImportCommand.execute
lerna(error)   Errored while running ImportCommand.execute
    Error: spawnSync /bin/sh ENOBUFS
        at exports._errnoException (util.js:1026:11)
        at spawnSync (child_process.js:461:20)
        at Object.execSync (child_process.js:517:13)
        at execSync (/usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js:76:40)
        at ImportCommand.externalExecSync (/usr/local/lib/node_modules/lerna/lib/commands/ImportCommand.js:128:50)
        at /usr/local/lib/node_modules/lerna/lib/commands/ImportCommand.js:146:30
        at /usr/local/lib/node_modules/lerna/node_modules/async/lib/async.js:718:13
        at iterate (/usr/local/lib/node_modules/lerna/node_modules/async/lib/async.js:262:13)
        at async.forEachOfSeries.async.eachOfSeries (/usr/local/lib/node_modules/lerna/node_modules/async/lib/async.js:281:9)
        at _parallel (/usr/local/lib/node_modules/lerna/node_modules/async/lib/async.js:717:9)
```

Node v9.6.1 on macOS 10.12.2.

**Comment by sstone1** [comment]
I hit this problem, I worked around it by modifying a value in this file:
`/usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js`

```javascript
// maxBuffer value for running exec
var MAX_BUFFER = 500 * 1024;
```

I changed MAX_BUFFER to `500 * 1024 * 1024`.

**Comment by toddself** [comment]
Also happening on Arch Linux (kernel 4.8.13-1) using node 6.9.2 but only when trying to import large (200+ commits) repos

**Comment by garthk** [comment]
272 commits in this repo.

**Comment by jvivs** [comment]
Seeing the same error w/ importing a package with 173 commits into a fresh lerna repo. Relevant node, npm, and git versions:
```
$ npm version
{ npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '56.1',
  modules: '46',
  node: '4.6.2',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '4.5.103.42',
  zlib: '1.2.8' }
```
```
$ git --version
git version 2.5.0
```

Change to `MAX_BUFFER` mentioned by @sstone1 allowed me to import successfully.

**Comment by mjackson** [comment]
I also ran into this issue when trying to import a repo with 3416 commits.

**Comment by nicojs** [comment]
I'm running into *kind of* the same issue:

```
vagrant@debian:~/stryker-mutator/stryker$ ./node_modules/.bin/lerna --logLevel silly import /home/vagrant/stryker-mutator/stryker-html-reporter/
Lerna v2.0.0-rc.3
Independent Versioning Mode
About to import 53 commits from /home/vagrant/stryker-mutator/stryker-html-reporter/ into packages/stryker-html-reporter
? Are you sure you want to import these commits onto the current branch? Yes
332620f                                            ╢█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░(node:6241) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: spawnSync git ENOBUFS
(node:6241) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
8120977                                            ╢██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
```

So i get an unhandled promise rejection. However:

> I hit this problem, I worked around it by modifying a value in this file: /usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js

This line isn't there anymore:

```javascript
// maxBuffer value for running exec
var MAX_BUFFER = 500 * 1024;
```

**Comment by evocateur** [comment]
@nicojs That's definitely a configurable value, should the urge to create a PR for `--max-buffer=<numBytes>` strike...

**Comment by nicojs** [comment]
@evocateur that should be done in `execa` before we can create a PR here, correct?

**Comment by evocateur** [comment]
I'm fairly certain execa already accepts a maxBuffer option, we just need to feed it into our calls.

**Comment by nicojs** [comment]
Awesome! Didn't even get around to do it and its fixed already
