### ISSUE TITLE
force-publish should publish the packages despite lack of changes

### ISSUE THREAD

**Issue by wookieb** [lerna/lerna#494]
Hi,

I'm running
```
lerna publish --force-publish *
```
I expect that all packages will be published even though they haven't been changed.
Unfortunatelly I got an error.
```
Lerna v2.0.0-beta.32
Current version: 2.0.0-rc3
Checking for updated packages...
Errored while running PublishCommand.initialize
Error: No updated packages to publish.
    at PublishCommand.initialize (/Users/wookieb/.nvm/versions/node/v5.10.1/lib/node_modules/lerna/lib/commands/PublishCommand.js:98:18)
    at PublishCommand._attempt (/Users/wookieb/.nvm/versions/node/v5.10.1/lib/node_modules/lerna/lib/Command.js:166:21)
    at PublishCommand.runCommand (/Users/wookieb/.nvm/versions/node/v5.10.1/lib/node_modules/lerna/lib/Command.js:150:12)
    at PublishCommand.run (/Users/wookieb/.nvm/versions/node/v5.10.1/lib/node_modules/lerna/lib/Command.js:69:12)
    at Object.<anonymous> (/Users/wookieb/.nvm/versions/node/v5.10.1/lib/node_modules/lerna/bin/lerna.js:62:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```
Is my expectation correct? If so I can deliver a fix.

**Comment by emmenko** [comment]
It should be `=*`

```
lerna publish --force-publish=*
```

**Comment by wookieb** [comment]
You're obviously right. I'm sorry for my mistake. Closing the issue.

**Comment by tusharmath** [comment]
BTW `lerna publish --help` doesn't document `--force-publish`

**Comment by tusharmath** [comment]
@evocateur why? Also if not `--force-publish` how does one solve this genuine use case?

**Comment by evocateur** [comment]
Lerna doesn’t stop you from running `npm publish`, it just coordinates multiple packages in the same repository.
