### ISSUE TITLE
`lerna run --scope my-package fail` prints same error three times

### ISSUE THREAD

**Issue by nfcampos** [lerna/lerna#592]
With this in `packages/my-package/package.json`
```
{
  "scripts": {
    "fail": "exit 1"
  }
}
```
running `lerna run --scope my-package fail` outputs
```
Lerna v2.0.0-beta.36
Scoping to packages that match 'trainline-desktop'
NpmUtilities.execInDir        ("run fail", [], "./packages/trainline-desktop")
Error: Command failed: npm run fail 

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/nunoc/.nvm/versions/node/v6.9.1/bin/node" "/Users/nunoc/.nvm/versions/node/v6.9.1/bin/npm" "run" "fail"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! trainline-desktop@0.0.0 fail: `exit 1`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trainline-desktop@0.0.0 fail script 'exit 1'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the trainline-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     exit 1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs trainline-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls trainline-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nunoc/dev/trainline-desktop/packages/trainline-desktop/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

> trainline-desktop@0.0.0 fail /Users/nunoc/dev/trainline-desktop/packages/trainline-desktop
> exit 1


NpmUtilities.runScriptInDir   ("fail", [], "./packages/trainline-desktop")
Error: Command failed: npm run fail 

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/nunoc/.nvm/versions/node/v6.9.1/bin/node" "/Users/nunoc/.nvm/versions/node/v6.9.1/bin/npm" "run" "fail"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! trainline-desktop@0.0.0 fail: `exit 1`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trainline-desktop@0.0.0 fail script 'exit 1'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the trainline-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     exit 1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs trainline-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls trainline-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nunoc/dev/trainline-desktop/packages/trainline-desktop/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

> trainline-desktop@0.0.0 fail /Users/nunoc/dev/trainline-desktop/packages/trainline-desktop
> exit 1



> trainline-desktop@0.0.0 fail /Users/nunoc/dev/trainline-desktop/packages/trainline-desktop
> exit 1


Errored while running npm script 'fail' in 'trainline-desktop'
Error: Command failed: npm run fail 

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/nunoc/.nvm/versions/node/v6.9.1/bin/node" "/Users/nunoc/.nvm/versions/node/v6.9.1/bin/npm" "run" "fail"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! trainline-desktop@0.0.0 fail: `exit 1`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trainline-desktop@0.0.0 fail script 'exit 1'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the trainline-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     exit 1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs trainline-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls trainline-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nunoc/dev/trainline-desktop/packages/trainline-desktop/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
Errored while running RunCommand.execute
Error: Command failed: npm run fail 

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/nunoc/.nvm/versions/node/v6.9.1/bin/node" "/Users/nunoc/.nvm/versions/node/v6.9.1/bin/npm" "run" "fail"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! trainline-desktop@0.0.0 fail: `exit 1`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trainline-desktop@0.0.0 fail script 'exit 1'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the trainline-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     exit 1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs trainline-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls trainline-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nunoc/dev/trainline-desktop/packages/trainline-desktop/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```
It gets really difficult to see the actual output of the falling command with this much padding. I understand that the `npm ERR!` output is created by `npm` but surely `lerna` doesn't need to print it three times? 

From a cursory look at the `lerna` code it seems that part of the issue comes from
1. having both https://github.com/lerna/lerna/blob/master/src/Command.js#L189 and https://github.com/lerna/lerna/blob/master/src/commands/RunCommand.js#L52 logging the same error object
2. and having both `runScriptInDir` and `execInDir` be wrapped in  `@logger.logifyAsync()` https://github.com/lerna/lerna/blob/master/src/NpmUtilities.js#L94

What do you guys think?

**Comment by evocateur** [comment]
This is certainly problematic.

#### Does `RunCommand.runScriptInPackage` _really_ need to re-log the error?

My thought is no, clearly the `NpmUtilities` are handling the logging of the error object itself. Removing the `err` argument to the error log here is pretty self-evidently a good thing.

#### Do both `NpmUtilities` methods need to log?

Again, no. I'd go so far as to merge `NpmUtilities.execInDir` into `NpmUtilities.runScriptInDir`, as it is literally the only consumer of `execInDir`. If merging the methods is a bridge too far, remove the `logifyAsync` decorator from `execInDir`.

#### Does `Command` need to log the execution callback error every time?

This is the tricky bit. We'd have to do a lot of digging in the current commands to ensure that removing the error object here (or moving it to a different log level?) doesn't negatively impact the developer experience.

PRs welcome for the first two questions above. We'll need to dig deeper into the Command changes, if any.

**Comment by nfcampos** [comment]
Alright, I've opened a PR with the two first changes. #614
These 2 changes remove 2 of the 4 times the error is printed.

Another possible change would be to change this line https://github.com/lerna/lerna/blob/master/src/logger.js#L44 in `src/logger.js` to read `message += "\n" + error.message;`. What's the point of printing what will always be a stack internal to lerna?

**Comment by evocateur** [comment]
The logger appending the error regardless of level certainly is troubling.
