### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by iTonyYo** [lerna/lerna#617]
![image](https://cloud.githubusercontent.com/assets/5499703/23241019/c7442442-f9ab-11e6-984d-f40145dfd60c.png)

My lerna.json file,

```json
{
  "lerna": "2.0.0-beta.37",
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```

#### Context
- _node version_: v7.3.0+
- _lerna version_: v2.0.0-beta.37
- _os_: macOS Sierra 10.12.1

**Comment by iTonyYo** [comment]
Don't delete `package.json.lerna_backup` file!!!!! Or, this error will kick your ass! 😭

**Comment by fengzilong** [comment]
I have the same issue, but in my case it's because of missing name field in package.json in certain package.

**Comment by gpltaylor** [comment]
Sorry to re-awaken this issue.
I'm having the same problem. I added a new package.json dependency. Ran "lerna bootstrap" 

```
GTaylor@sn000711301 MINGW64 /d/Desktop/Development Area/Fluent.FluentLoans.Online/uiv2/packages/components (master)
$ lerna bootstrap
Lerna v2.0.0-beta.38
Independent Versioning Mode
Bootstrapping 6 packages
Preinstalling packages
fl-components                                      ╢███████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
fl-server                                          ╢██████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
fluent-utilities                                   ╢██████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
fl-redux                                           ╢█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
fluentloans.online.ui                              ╢████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
fl-ui                                              ╢███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████╟
Installing external dependencies
FileSystemUtilities.renameSync("D:\\Desktop\\Development Area\\Fluent.FluentLoans.Online\\uiv2\\packages\\components\\package.json....)
Error: EPERM: operation not permitted, rename 'D:\Desktop\Development Area\Fluent.FluentLoans.Online\uiv2\packages\components\package.json.lerna_backup' -> 'D:\Desktop\Development Area\Fluent.FluentLoans.Online\uiv2\packages\components\package.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:803:18)
    at renameSync (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\FileSystemUtilities.js:119:20)
    at Function.descriptor.value (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\logger.js:146:33)
    at cleanup (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\NpmUtilities.js:112:41)
    at done (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\NpmUtilities.js:136:13)
    at C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\ChildProcessUtilities.js:75:16
    at ChildProcess.<anonymous> (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\ChildProcessUtilities.js:162:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
FileSystemUtilities.renameSync("D:\\Desktop\\Development Area\\Fluent.FluentLoans.Online\\uiv2\\packages\\components\\package.json....)
Error: EPERM: operation not permitted, rename 'D:\Desktop\Development Area\Fluent.FluentLoans.Online\uiv2\packages\components\package.json.lerna_backup' -> 'D:\Desktop\Development Area\Fluent.FluentLoans.Online\uiv2\packages\components\package.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:803:18)
    at renameSync (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\FileSystemUtilities.js:119:20)
    at Function.descriptor.value (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\logger.js:146:33)
    at EventEmitter.cleanup (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\NpmUtilities.js:112:41)
    at emitTwo (events.js:111:20)
    at EventEmitter.emit (events.js:191:7)
    at emit (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\node_modules\signal-exit\index.js:77:11)
    at processEmit [as emit] (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\node_modules\signal-exit\index.js:150:5)
    at process._fatalException (node.js:276:21)
C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\logger.js:151
            throw error;
            ^

Error: EPERM: operation not permitted, rename 'D:\Desktop\Development Area\Fluent.FluentLoans.Online\uiv2\packages\components\package.json.lerna_backup' -> 'D:\Desktop\Development Area\Fluent.FluentLoans.Online\uiv2\packages\components\package.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:803:18)
    at renameSync (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\FileSystemUtilities.js:119:20)
    at Function.descriptor.value (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\logger.js:146:33)
    at cleanup (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\NpmUtilities.js:112:41)
    at done (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\NpmUtilities.js:136:13)
    at C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\ChildProcessUtilities.js:75:16
    at ChildProcess.<anonymous> (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\ChildProcessUtilities.js:162:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
```

I did delete the package.json.lerna_backup file (upps)
Now I am getting
```
$ lerna bootstrap
Lerna v2.0.0-beta.38
Independent Versioning Mode
Bootstrapping 6 packages
Preinstalling packages
Errored while running BootstrapCommand.execute
TypeError: Cannot read property 'slice' of undefined
    at ProgressBarController.tick (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\progressBar.js:61:50)
    at C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\commands\BootstrapCommand.js:134:32
    at Package.runScript (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\Package.js:61:9)
    at C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\commands\BootstrapCommand.js:133:15
    at C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\node_modules\async\lib\async.js:718:13
    at replenish (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\node_modules\async\lib\async.js:319:21)
    at C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\node_modules\async\lib\async.js:330:15
    at _parallel (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\node_modules\async\lib\async.js:717:9)
    at Object.async.parallelLimit (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\node_modules\async\lib\async.js:735:9)
    at C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\PackageUtilities.js:298:27
```

I can't get rid of this error. I have tried:
Pulling the package.json.lerna_backup back
deleting the lerna.json file and running lerna init

nothing is working.

any ideas how to fix this?
