### ISSUE TITLE
error when using flag --conventional-commits

### ISSUE THREAD

**Issue by gitawego** [lerna/lerna#756]
## Expected Behavior

changelog.md to be generated in packages
## Current Behavior

failed when calling conventional-changelog/cli.js
![error](https://cloud.githubusercontent.com/assets/438120/24961854/6b04f53e-1f9a-11e7-8f44-c8ae429bc8a4.png)

## Steps to Reproduce (for bugs)

Call ``  lerna -- publish --skip-npm --conventional-commits`` in windows

I don't have such problem when calling directly conventional-changelog-cli, 
```shell
conventional-changelog -p angular -l portal-app --commit-path=./packages/portal-app -i ./packages/portal-app/CHANGELOG.md -s -r 0
```
<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.1",
  "packages": [
    "packages/*"
  ],
  "version": "1.1.2"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
...
lerna(error)   ConventionalCommitUtilities.updateChangelog({"name":"portal-app","location":"D:\\hlu022417\\workspace\\portal\\packages\\portal-app"}, {"cwd":"D...)
    Error: Command failed: D:\hlu022417\workspace\portal\node_modules\conventional-changelog-cli\cli.js -l portal-app --commit-path=D:\hlu022417\workspace\portal\packages\portal-app --pkg=D:\hlu022417\workspace\portal\packages\portal-app\package.json -p angular
        at checkExecSyncError (child_process.js:483:13)
        at Object.execSync (child_process.js:523:13)
        at Function.execSync (D:\hlu022417\workspace\portal\node_modules\lerna\lib\ChildProcessUtilities.js:68:44)
        at updateChangelog (D:\hlu022417\workspace\portal\node_modules\lerna\lib\ConventionalCommitUtilities.js:109:54)
        at Function.descriptor.value (D:\hlu022417\workspace\portal\node_modules\lerna\lib\logger.js:146:33)
        at D:\hlu022417\workspace\portal\node_modules\lerna\lib\commands\PublishCommand.js:452:49
        at Array.forEach (native)
        at PublishCommand.updateUpdatedPackages (D:\hlu022417\workspace\portal\node_modules\lerna\lib\commands\PublishCommand.js:430:20)
        at PublishCommand.execute (D:\hlu022417\workspace\portal\node_modules\lerna\lib\commands\PublishCommand.js:175:14)
        at PublishCommand._attempt (D:\hlu022417\workspace\portal\node_modules\lerna\lib\Command.js:219:21)
lerna(error)   Errored while running PublishCommand.execute

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.1|
| `npm --version`  | 3.10.8|
| `node --version` | v6.10.0|

| OS | Version |
| ---: | :--- |
| Windows 7 Enterprise| 7.8.1|

**Comment by evocateur** [comment]
@gitawego I appreciate the detailed bug report! We've already got an issue open on this bug, #708, so I'll close this and invite you to follow along there.
