### ISSUE TITLE
[2.0.0-rc.2] lerna clean results in error: "Error: spawn rimraf ENOENT"

### ISSUE THREAD

**Issue by Scarysize** [lerna/lerna#772]
## Expected Behavior
`lerna clean` removes the `node_modules` directories of the packages.

## Current Behavior
`lerna clean` throws an error

```
FileSystemUtilities.rimraf    ("./packages/<some-package>/node_modules")
Error: spawn rimraf ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Errored while running CleanCommand.execute
Error: spawn rimraf ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

## Possible Solution
Use `lerna@2.0.0-beta.37`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-beta.37",
  "version": "1.9.2"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` |2.0.0-rc.2 |
| `npm --version`  | 4.2.0 |
| `yarn --version` | 0.23.2 |
| `node --version` | 7.9.0 |

| OS | Version |
| --- | --- |
| macOS | 10.12.3 |

If I find the time I will try to setup a example to reproduce the bug.

**Comment by evocateur** [comment]
Thanks for the bug report! This has been fixed by #771, and will be released shortly.

**Comment by evocateur** [comment]
Released in https://github.com/lerna/lerna/releases/tag/v2.0.0-rc.3

**Comment by Scarysize** [comment]
Nice, thanks for the fast update.
