### ISSUE TITLE
lerna publish: git unable to retrieve current branch on Windows

### ISSUE THREAD

**Issue by Vincent2015** [lerna/lerna#773]
**env**
git version 2.11.1.windows.1

```
D:\ui\lernademo>lerna -v
2.0.0-rc.3

D:\ui\lernademo>node -v
v6.9.5
```

**code and dirs**
```
lernademo
   -lerna.json
   -package.json
   -packages
      --aa
         -- package.json
         -- index.js
```

lerna.json content
```json
{
  "lerna": "2.0.0-rc.3",
  "packages": [
    "packages/aa"
  ],
  "version": "0.0.0"
}
```

-aa package.json
```json
{
  "name": "aa",
  "version": "1.0.0",
  "description": "",
  "main": "aa.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

**Operations**

Common error:
```
GitUtilities.getCurrentBranch ({"cwd":"D:\\ui\\lernademo"})
Error: fatal: ambiguous argument 'HEAD': unknown revision or path not in the wor
king tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at Function.module.exports.sync (C:\Users\qiupc\AppData\Roaming\npm\node_mod
ules\lerna\node_modules\execa\index.js:277:26)
    at Function.execSync (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\
lib\ChildProcessUtilities.js:50:30)
    at getCurrentBranch (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\l
ib\GitUtilities.js:158:46)
    at Function.descriptor.value (C:\Users\qiupc\AppData\Roaming\npm\node_module
s\lerna\lib\logger.js:146:33)
    at isDetachedHead (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib
\GitUtilities.js:67:37)
    at Function.descriptor.value (C:\Users\qiupc\AppData\Roaming\npm\node_module
s\lerna\lib\logger.js:146:33)
    at PublishCommand.execute (C:\Users\qiupc\AppData\Roaming\npm\node_modules\l
erna\lib\commands\PublishCommand.js:238:55)
    at PublishCommand._attempt (C:\Users\qiupc\AppData\Roaming\npm\node_modules\
lerna\lib\Command.js:249:21)
    at C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib\Command.js:234:
15
    at C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib\Command.js:258:
13
GitUtilities.isDetachedHead   ({"cwd":"D:\\ui\\lernademo"})
Error: fatal: ambiguous argument 'HEAD': unknown revision or path not in the wor
king tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

```

<details><summary>full record</summary><p>

```

D:\>cd ui
D:\ui>lerna init
Lerna v2.0.0-rc.3
Initializing Git repository.
Creating package.json.
Creating lerna.json.
Successfully initialized Lerna files

D:\ui>ls
ifbp-service  lerna.json    package.json

D:\ui>rm lerna.json

D:\ui>rm package.json

D:\ui>md lernademo

D:\ui>cd lernademo

D:\ui\lernademo>lerna init
Lerna v2.0.0-rc.3
Creating package.json.
Creating lerna.json.
Successfully initialized Lerna files

D:\ui\lernademo>lerna publish
Lerna v2.0.0-rc.3
Current version: 0.0.0
Checking for updated packages...
No tags found! Comparing with initial commit.
Errored while running PublishCommand.initialize
Error: No updated packages to publish.
    at PublishCommand.initialize (C:\Users\qiupc\AppData\Roaming\npm\node_module
s\lerna\lib\commands\PublishCommand.js:195:18)
    at PublishCommand._attempt (C:\Users\qiupc\AppData\Roaming\npm\node_modules\
lerna\lib\Command.js:249:21)
    at PublishCommand.runCommand (C:\Users\qiupc\AppData\Roaming\npm\node_module
s\lerna\lib\Command.js:233:12)
    at PublishCommand.run (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna
\lib\Command.js:130:12)
    at Object.handler (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib
\commands\PublishCommand.js:79:43)
    at Object.self.runCommand (C:\Users\qiupc\AppData\Roaming\npm\node_modules\l
erna\node_modules\yargs\lib\command.js:231:22)
    at Object.Yargs.self._parseArgs (C:\Users\qiupc\AppData\Roaming\npm\node_mod
ules\lerna\node_modules\yargs\yargs.js:990:30)
    at Object.get [as argv] (C:\Users\qiupc\AppData\Roaming\npm\node_modules\ler
na\node_modules\yargs\yargs.js:930:19)
    at Object.<anonymous> (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna
\bin\lerna.js:33:3)
    at Module._compile (module.js:570:32)

D:\ui\lernademo>md packages

D:\ui\lernademo>cd packages

D:\ui\lernademo\packages>mkdir aa

D:\ui\lernademo\packages>cd aa

D:\ui\lernademo\packages\aa>vi aa.js
'vi' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\ui\lernademo\packages\aa>vim aa.js

D:\ui\lernademo\packages\aa>ls
aa.js

D:\ui\lernademo\packages\aa>cd ..

D:\ui\lernademo\packages>ls
aa

D:\ui\lernademo\packages>cd ..

D:\ui\lernademo>ls
lerna-debug.log  lerna.json       package.json     packages

D:\ui\lernademo>lerna publish
Lerna v2.0.0-rc.3
Current version: 0.0.0
Checking for updated packages...
No tags found! Comparing with initial commit.
Errored while running PublishCommand.initialize
Error: No updated packages to publish.
    at PublishCommand.initialize (C:\Users\qiupc\AppData\Roaming\npm\node_module
s\lerna\lib\commands\PublishCommand.js:195:18)
    at PublishCommand._attempt (C:\Users\qiupc\AppData\Roaming\npm\node_modules\
lerna\lib\Command.js:249:21)
    at PublishCommand.runCommand (C:\Users\qiupc\AppData\Roaming\npm\node_module
s\lerna\lib\Command.js:233:12)
    at PublishCommand.run (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna
\lib\Command.js:130:12)
    at Object.handler (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib
\commands\PublishCommand.js:79:43)
    at Object.self.runCommand (C:\Users\qiupc\AppData\Roaming\npm\node_modules\l
erna\node_modules\yargs\lib\command.js:231:22)
    at Object.Yargs.self._parseArgs (C:\Users\qiupc\AppData\Roaming\npm\node_mod
ules\lerna\node_modules\yargs\yargs.js:990:30)
    at Object.get [as argv] (C:\Users\qiupc\AppData\Roaming\npm\node_modules\ler
na\node_modules\yargs\yargs.js:930:19)
    at Object.<anonymous> (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna
\bin\lerna.js:33:3)
    at Module._compile (module.js:570:32)

D:\ui\lernademo>vim lerna.json

D:\ui\lernademo>vim lerna.json

D:\ui\lernademo>lerna publish
Lerna v2.0.0-rc.3
Current version: 0.0.0
Checking for updated packages...
No tags found! Comparing with initial commit.
Errored while running PublishCommand.initialize
Error: No updated packages to publish.
    at PublishCommand.initialize (C:\Users\qiupc\AppData\Roaming\npm\node_module
s\lerna\lib\commands\PublishCommand.js:195:18)
    at PublishCommand._attempt (C:\Users\qiupc\AppData\Roaming\npm\node_modules\
lerna\lib\Command.js:249:21)
    at PublishCommand.runCommand (C:\Users\qiupc\AppData\Roaming\npm\node_module
s\lerna\lib\Command.js:233:12)
    at PublishCommand.run (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna
\lib\Command.js:130:12)
    at Object.handler (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib
\commands\PublishCommand.js:79:43)
    at Object.self.runCommand (C:\Users\qiupc\AppData\Roaming\npm\node_modules\l
erna\node_modules\yargs\lib\command.js:231:22)
    at Object.Yargs.self._parseArgs (C:\Users\qiupc\AppData\Roaming\npm\node_mod
ules\lerna\node_modules\yargs\yargs.js:990:30)
    at Object.get [as argv] (C:\Users\qiupc\AppData\Roaming\npm\node_modules\ler
na\node_modules\yargs\yargs.js:930:19)
    at Object.<anonymous> (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna
\bin\lerna.js:33:3)
    at Module._compile (module.js:570:32)

D:\ui\lernademo>vim aa.js

D:\ui\lernademo>vim lerna.json

D:\ui\lernademo>ls packages
aa

D:\ui\lernademo>ls /aa
ls: /aa: No such file or directory

D:\ui\lernademo>ls packages/aa
aa.js

D:\ui\lernademo>cd packages/aa

D:\ui\lernademo\packages\aa>npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (aa)
version: (1.0.0)
description:
entry point: (aa.js)
test command:
git repository:
keywords:
author:
license: (ISC)
About to write to D:\ui\lernademo\packages\aa\package.json:

{
  "name": "aa",
  "version": "1.0.0",
  "description": "",
  "main": "aa.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this ok? (yes) yes

D:\ui\lernademo\packages\aa>cd ..

D:\ui\lernademo\packages>cd ..

D:\ui\lernademo>lerna publish
Lerna v2.0.0-rc.3
Current version: 0.0.0
Checking for updated packages...
No tags found! Comparing with initial commit.
aa                                                 ╢█████████████
? Select a new version (currently 0.0.0) Minor (0.1.0)

Changes:
- aa: 1.0.0 => 0.1.0

? Are you sure you want to publish the above changes? Yes
GitUtilities.getCurrentBranch ({"cwd":"D:\\ui\\lernademo"})
Error: fatal: ambiguous argument 'HEAD': unknown revision or path not in the wor
king tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at Function.module.exports.sync (C:\Users\qiupc\AppData\Roaming\npm\node_mod
ules\lerna\node_modules\execa\index.js:277:26)
    at Function.execSync (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\
lib\ChildProcessUtilities.js:50:30)
    at getCurrentBranch (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\l
ib\GitUtilities.js:158:46)
    at Function.descriptor.value (C:\Users\qiupc\AppData\Roaming\npm\node_module
s\lerna\lib\logger.js:146:33)
    at isDetachedHead (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib
\GitUtilities.js:67:37)
    at Function.descriptor.value (C:\Users\qiupc\AppData\Roaming\npm\node_module
s\lerna\lib\logger.js:146:33)
    at PublishCommand.execute (C:\Users\qiupc\AppData\Roaming\npm\node_modules\l
erna\lib\commands\PublishCommand.js:238:55)
    at PublishCommand._attempt (C:\Users\qiupc\AppData\Roaming\npm\node_modules\
lerna\lib\Command.js:249:21)
    at C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib\Command.js:234:
15
    at C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib\Command.js:258:
13
GitUtilities.isDetachedHead   ({"cwd":"D:\\ui\\lernademo"})
Error: fatal: ambiguous argument 'HEAD': unknown revision or path not in the wor
king tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at Function.module.exports.sync (C:\Users\qiupc\AppData\Roaming\npm\node_mod
ules\lerna\node_modules\execa\index.js:277:26)
    at Function.execSync (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\
lib\ChildProcessUtilities.js:50:30)
    at getCurrentBranch (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\l
ib\GitUtilities.js:158:46)
    at Function.descriptor.value (C:\Users\qiupc\AppData\Roaming\npm\node_module
s\lerna\lib\logger.js:146:33)
    at isDetachedHead (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib
\GitUtilities.js:67:37)
    at Function.descriptor.value (C:\Users\qiupc\AppData\Roaming\npm\node_module
s\lerna\lib\logger.js:146:33)
    at PublishCommand.execute (C:\Users\qiupc\AppData\Roaming\npm\node_modules\l
erna\lib\commands\PublishCommand.js:238:55)
    at PublishCommand._attempt (C:\Users\qiupc\AppData\Roaming\npm\node_modules\
lerna\lib\Command.js:249:21)
    at C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib\Command.js:234:
15
    at C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib\Command.js:258:
13
Errored while running PublishCommand.execute
Error: fatal: ambiguous argument 'HEAD': unknown revision or path not in the wor
king tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at Function.module.exports.sync (C:\Users\qiupc\AppData\Roaming\npm\node_mod
ules\lerna\node_modules\execa\index.js:277:26)
    at Function.execSync (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\
lib\ChildProcessUtilities.js:50:30)
    at getCurrentBranch (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\l
ib\GitUtilities.js:158:46)
    at Function.descriptor.value (C:\Users\qiupc\AppData\Roaming\npm\node_module
s\lerna\lib\logger.js:146:33)
    at isDetachedHead (C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib
\GitUtilities.js:67:37)
    at Function.descriptor.value (C:\Users\qiupc\AppData\Roaming\npm\node_module
s\lerna\lib\logger.js:146:33)
    at PublishCommand.execute (C:\Users\qiupc\AppData\Roaming\npm\node_modules\l
erna\lib\commands\PublishCommand.js:238:55)
    at PublishCommand._attempt (C:\Users\qiupc\AppData\Roaming\npm\node_modules\
lerna\lib\Command.js:249:21)
    at C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib\Command.js:234:
15
    at C:\Users\qiupc\AppData\Roaming\npm\node_modules\lerna\lib\Command.js:258:
13

D:\ui\lernademo>

```
</p></details>

**Comment by evocateur** [comment]
@Vincent2015 thanks for the detail!

I believe we may have a problem with executing `git rev-parse --abbrev-ref HEAD` on Windows?

(calling code is [here](https://github.com/lerna/lerna/blob/a201362cc29f6be2244979098a41b0494d0dd166/src/GitUtilities.js#L100))

**Comment by arndissler** [comment]
Hi there, basically it's not a Windows problem. The problem is the repo itself which doesn't have any commits and therefore nothing to publish.
