### ISSUE TITLE
skip, tag, and diff commands for `lerna publish`

### ISSUE THREAD

**Issue by krainboltgreene** [lerna/lerna#817]
When doing `lerna publish` sometimes I get situations where I don't want to publish (`skip`), I only want to tag (`tag`), and I want to see what's changed (`diff`). These options should be present in the menu:

```
? Select a new version for @unction/mergewith (currently 2.0.0) (Use arrow keys)
❯ Patch (2.0.1) 
  Minor (2.1.0) 
  Major (3.0.0) 
  Prepatch (2.0.1-0) 
  Preminor (2.1.0-0) 
  Premajor (3.0.0-0) 
  Prerelease 
  Custom 
```

**Comment by GeorgeTaveras1231** [comment]
Plus one on the skip feature.

**Comment by evocateur** [comment]
Presumably you're using "independent" versioning? (the "skip" for the default unified version is just `Ctrl+C`)

This is probably going to open up another can of worms, but `skip` and `tag` options don't feel appropriate for `lerna publish`, and `diff` is sufficiently covered by `lerna diff [pkg]`, imo. Reasoning:

* `skip`: If changes have been detected in a non-`private` package _or its dependencies_, it should be published. `skip` is just another backdoor into #707, which we've already established is not supported by lerna.
* `tag`: If you're using lerna, you've implicitly agreed to let lerna manage the tags for you. You can always `git tag` yourself, but tags are significant in lerna and by doing that, you're kinda in uncharted territory in terms of lerna support. I mean, it'll _work_ after a manual `v2.0.1` (or `my-package@2.0.1` with `--independent`) tag, for example, but it will no longer recognize changes before that tag as qualifying various packages for the next `lerna publish`.
* `diff`: Piping a subshell into a prompt and then handling exit etc is ...not appealing. Moreover, I'm not certain it's possible, given our current infrastructure. I might be wrong, but that's my gut.

**Comment by krainboltgreene** [comment]
1. I don't always want to publish something and lerna isn't always correct about the difference between published and local.
2. Sometimes I want to publish X before Y.
3. Not all projects start using lerna, so lerna being trusted with tags wont always work.
4. If lerna is going to *force* me to publish all packages, I absolutely need to know the diff so that I can accurately determine if one of my 50 packages needs to be patch, minor, or major.

**Comment by krainboltgreene** [comment]
So because I accidentally already had a tag at a version I just lost 15 minutes of work D:

```
| lerna publish
lerna info version 2.0.0-rc.5
lerna info versioning independent
lerna info Checking for updated packages...
lerna info Comparing with tag @unction/allobjectp@1.0.4
? Select a new version for @unction/allobjectp (currently 1.0.3) Patch (1.0.4)
? Select a new version for @unction/allp (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/append (currently 0.0.0) Major (1.0.0)
? Select a new version for @unction/appendm (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/aside (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/attach (currently 0.0.0) Major (1.0.0)
? Select a new version for @unction/catchp (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/compact (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/computedprop (currently 1.0.3) Patch (1.0.4)
? Select a new version for @unction/couple (currently 1.0.1) Patch (1.0.2)
? Select a new version for @unction/endswith (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/everyp (currently 0.0.0) Major (1.0.0)
? Select a new version for @unction/flattentree (currently 0.0.0) Major (1.0.0)
? Select a new version for @unction/foreach (currently 1.0.1) Patch (1.0.2)
? Select a new version for @unction/hammer (currently 2.0.1) Minor (2.1.0)
? Select a new version for @unction/isarray (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/isiterable (currently 1.0.1) Patch (1.0.2)
? Select a new version for @unction/isobject (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/ispopulated (currently 2.0.0) Patch (2.0.1)
? Select a new version for @unction/ispresent (currently 1.0.0) Minor (1.1.0)
? Select a new version for @unction/istype (currently 1.0.1) Patch (1.0.2)
? Select a new version for @unction/lackstext (currently 1.0.0) Minor (1.1.0)
? Select a new version for @unction/mapkeys (currently 1.0.3) Major (2.0.0)
? Select a new version for @unction/mapkeyswithvaluekey (currently 0.0.0) Major (1.0.0)
? Select a new version for @unction/mapvalues (currently 1.0.4) Major (2.0.0)
? Select a new version for @unction/mapvalueswithvaluekey (currently 0.0.0) Major (1.0.0)
? Select a new version for @unction/mergedeepleft (currently 2.0.1) Minor (2.1.0)
? Select a new version for @unction/mergedeepright (currently 1.0.4) Minor (1.1.0)
? Select a new version for @unction/mergeleft (currently 0.0.0) Major (1.0.0)
? Select a new version for @unction/mergeright (currently 0.0.0) Major (1.0.0)
? Select a new version for @unction/mergewith (currently 2.0.1) Major (3.0.0)
? Select a new version for @unction/mergewithkey (currently 1.0.1) Major (2.0.0)
? Select a new version for @unction/nestedapply (currently 2.1.1) Patch (2.1.2)
? Select a new version for @unction/nestedobjof (currently 1.0.0) Minor (1.1.0)
? Select a new version for @unction/optimisticp (currently 1.0.1) Patch (1.0.2)
? Select a new version for @unction/pairskeys (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/pairsvalues (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/pluck (currently 0.0.0) Major (1.0.0)
? Select a new version for @unction/plucks (currently 0.0.0) Major (1.0.0)
? Select a new version for @unction/prepend (currently 0.0.0) Major (1.0.0)
? Select a new version for @unction/reducevalues (currently 1.0.4) Minor (1.1.0)
? Select a new version for @unction/reducewithvaluekey (currently 1.0.3) Major (2.0.0)
? Select a new version for @unction/rejectp (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/resolvep (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/sample (currently 1.0.1) Patch (1.0.2)
? Select a new version for @unction/samplesize (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/shuffle (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/startswith (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/thencatchp (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/thenp (currently 1.0.0) Patch (1.0.1)
? Select a new version for @unction/thrush (currently 1.0.1) Patch (1.0.2)
? Select a new version for @unction/treeify (currently 1.0.9) Minor (1.1.0)
? Select a new version for @unction/upto (currently 2.0.0) Patch (2.0.1)
? Select a new version for @unction/withoutkeyrecursive (currently 1.1.1) Patch (1.1.2)

Changes:
 - @unction/allobjectp: 1.0.3 => 1.0.4
 - @unction/allp: 1.0.0 => 1.0.1
 - @unction/append: 0.0.0 => 1.0.0
 - @unction/appendm: 1.0.0 => 1.0.1
 - @unction/aside: 1.0.0 => 1.0.1
 - @unction/attach: 0.0.0 => 1.0.0
 - @unction/catchp: 1.0.0 => 1.0.1
 - @unction/compact: 1.0.0 => 1.0.1
 - @unction/computedprop: 1.0.3 => 1.0.4
 - @unction/couple: 1.0.1 => 1.0.2
 - @unction/endswith: 1.0.0 => 1.0.1
 - @unction/everyp: 0.0.0 => 1.0.0
 - @unction/flattentree: 0.0.0 => 1.0.0
 - @unction/foreach: 1.0.1 => 1.0.2
 - @unction/hammer: 2.0.1 => 2.1.0
 - @unction/isarray: 1.0.0 => 1.0.1
 - @unction/isiterable: 1.0.1 => 1.0.2
 - @unction/isobject: 1.0.0 => 1.0.1
 - @unction/ispopulated: 2.0.0 => 2.0.1
 - @unction/ispresent: 1.0.0 => 1.1.0
 - @unction/istype: 1.0.1 => 1.0.2
 - @unction/lackstext: 1.0.0 => 1.1.0
 - @unction/mapkeys: 1.0.3 => 2.0.0
 - @unction/mapkeyswithvaluekey: 0.0.0 => 1.0.0
 - @unction/mapvalues: 1.0.4 => 2.0.0
 - @unction/mapvalueswithvaluekey: 0.0.0 => 1.0.0
 - @unction/mergedeepleft: 2.0.1 => 2.1.0
 - @unction/mergedeepright: 1.0.4 => 1.1.0
 - @unction/mergeleft: 0.0.0 => 1.0.0
 - @unction/mergeright: 0.0.0 => 1.0.0
 - @unction/mergewith: 2.0.1 => 3.0.0
 - @unction/mergewithkey: 1.0.1 => 2.0.0
 - @unction/nestedapply: 2.1.1 => 2.1.2
 - @unction/nestedobjof: 1.0.0 => 1.1.0
 - @unction/optimisticp: 1.0.1 => 1.0.2
 - @unction/pairskeys: 1.0.0 => 1.0.1
 - @unction/pairsvalues: 1.0.0 => 1.0.1
 - @unction/pluck: 0.0.0 => 1.0.0
 - @unction/plucks: 0.0.0 => 1.0.0
 - @unction/prepend: 0.0.0 => 1.0.0
 - @unction/reducevalues: 1.0.4 => 1.1.0
 - @unction/reducewithvaluekey: 1.0.3 => 2.0.0
 - @unction/rejectp: 1.0.0 => 1.0.1
 - @unction/resolvep: 1.0.0 => 1.0.1
 - @unction/sample: 1.0.1 => 1.0.2
 - @unction/samplesize: 1.0.0 => 1.0.1
 - @unction/shuffle: 1.0.0 => 1.0.1
 - @unction/startswith: 1.0.0 => 1.0.1
 - @unction/thencatchp: 1.0.0 => 1.0.1
 - @unction/thenp: 1.0.0 => 1.0.1
 - @unction/thrush: 1.0.1 => 1.0.2
 - @unction/treeify: 1.0.9 => 1.1.0
 - @unction/upto: 2.0.0 => 2.0.1
 - @unction/withoutkeyrecursive: 1.1.1 => 1.1.2

? Are you sure you want to publish the above changes? Yes
lerna ERR! execute Error: fatal: tag '@unction/allobjectp@1.0.4' already exists
lerna ERR! execute
lerna ERR! execute     at Function.module.exports.sync (/Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/node_modules/execa/index.js:277:26)
lerna ERR! execute     at Function.execSync (/Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
lerna ERR! execute     at Function.addTag (/Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/GitUtilities.js:90:39)
lerna ERR! execute     at /Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/commands/PublishCommand.js:580:39
lerna ERR! execute     at Array.forEach (native)
lerna ERR! execute     at PublishCommand.gitCommitAndTagVersionForUpdates (/Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/commands/PublishCommand.js:579:12)
lerna ERR! execute     at PublishCommand.commitAndTagUpdates (/Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/commands/PublishCommand.js:560:26)
lerna ERR! execute     at PublishCommand.execute (/Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/commands/PublishCommand.js:246:16)
lerna ERR! execute     at PublishCommand._attempt (/Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/Command.js:265:21)
lerna ERR! execute     at /Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/Command.js:252:15
lerna ERR! execute  callback with error
lerna ERR! execute  Error: fatal: tag '@unction/allobjectp@1.0.4' already exists
lerna ERR! execute
lerna ERR! execute     at Function.module.exports.sync (/Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/node_modules/execa/index.js:277:26)
lerna ERR! execute     at Function.execSync (/Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
lerna ERR! execute     at Function.addTag (/Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/GitUtilities.js:90:39)
lerna ERR! execute     at /Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/commands/PublishCommand.js:580:39
lerna ERR! execute     at Array.forEach (native)
lerna ERR! execute     at PublishCommand.gitCommitAndTagVersionForUpdates (/Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/commands/PublishCommand.js:579:12)
lerna ERR! execute     at PublishCommand.commitAndTagUpdates (/Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/commands/PublishCommand.js:560:26)
lerna ERR! execute     at PublishCommand.execute (/Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/commands/PublishCommand.js:246:16)
lerna ERR! execute     at PublishCommand._attempt (/Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/Command.js:265:21)
lerna ERR! execute     at /Users/krainboltgreene/.nvm/versions/node/v7.7.2/lib/node_modules/lerna/lib/Command.js:252:15
```

**Comment by krainboltgreene** [comment]
Also, in the middle of publishing I accidentally selected "minor" when it should be major. 25 packages in I have to start over :/
