### ISSUE TITLE
Problems using dependencies with npm organisation - not well documented!!

### ISSUE THREAD

**Issue by kristianmandrup** [lerna/lerna#821]
`lerna bootstrap` doesn't resolves dependencies correctly. Using same structure I see in other lerna projects such as `turf`.

## Expected Behavior

Resolve each dependency, ignoring the npm organisation name, such as `@tecla5` and relative to root folder: `/packages` 

Note: None of the dependency packages have been published to npm. I wonder if this is a pre-requisite or not. Docs don't make this clear. I thought lerna would try to `nmp link` to sister package before trying to install from npm?

## Current Behaviour

Tries to resolve relative to own folder instead of relative to `/packages`

ie. `/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/@tecla5/gitlab` instead of /Users/kristianmandrup/repos/tecla5/docker-gen/packages/@tecla5/gitlab

```bash
$ lerna bootstrap --scope @tecla5/ploppy
lerna info version 2.0.0-rc.4
lerna info versioning independent
lerna info scope @tecla5/ploppy
lerna info Bootstrapping 1 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute Error: Command failed: npm install
lerna ERR! execute npm ERR! addLocal Could not install /Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/@tecla5/gitlab
```

My project in `packages/ploppy`

```js
{
  "name": "@tecla5/ploppy",
  // ...
"dependencies": {
    "fs-extra-promise": "^1.0.1",
    "gitlab": "@tecla5/gitlab"
  }
}
```

## Possible Solution

Must be doing something wrong. Better docs and error messages please.

## Steps to Reproduce (for bugs)

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.4",
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'bootstrap' ]
1 silly flags { _: [ 'bootstrap' ],
1 silly flags   sort: true,
1 silly flags   scope: '@tecla5/ploppy',
1 silly flags   concurrency: 4 }
2 verbose rootPath /Users/kristianmandrup/repos/tecla5/docker-gen
3 info version 2.0.0-rc.4
4 info versioning independent
5 silly isInitialized
6 silly isInitialized true
7 silly existsSync /Users/kristianmandrup/repos/tecla5/docker-gen/VERSION
8 info scope @tecla5/ploppy
9 silly initialize attempt
10 silly initialize success
11 silly execute attempt
12 info Bootstrapping 1 packages
13 info lifecycle preinstall
14 silly runScript preinstall @tecla5/ploppy
15 silly @tecla5/ploppy
16 silly hasDependencyInstalled @tecla5/ploppy ava
17 silly dependencyIsSatisfied [ 'ava',
17 silly dependencyIsSatisfied   '^0.19.1',
17 silly dependencyIsSatisfied   '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/node_modules' ]
18 verbose dependencyIsSatisfied ava false
19 silly hasDependencyInstalled @tecla5/ploppy babel-cli
20 silly dependencyIsSatisfied [ 'babel-cli',
20 silly dependencyIsSatisfied   '^6.24.0',
20 silly dependencyIsSatisfied   '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/node_modules' ]
21 verbose dependencyIsSatisfied babel-cli false
22 silly hasDependencyInstalled @tecla5/ploppy babel-core
23 silly dependencyIsSatisfied [ 'babel-core',
23 silly dependencyIsSatisfied   '^6.24.1',
23 silly dependencyIsSatisfied   '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/node_modules' ]
24 verbose dependencyIsSatisfied babel-core false
25 silly hasDependencyInstalled @tecla5/ploppy babel-plugin-transform-runtime
26 silly dependencyIsSatisfied [ 'babel-plugin-transform-runtime',
26 silly dependencyIsSatisfied   '^6.23.0',
26 silly dependencyIsSatisfied   '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/node_modules' ]
27 verbose dependencyIsSatisfied babel-plugin-transform-runtime false
28 silly hasDependencyInstalled @tecla5/ploppy babel-polyfill
29 silly dependencyIsSatisfied [ 'babel-polyfill',
29 silly dependencyIsSatisfied   '^6.23.0',
29 silly dependencyIsSatisfied   '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/node_modules' ]
30 verbose dependencyIsSatisfied babel-polyfill false
31 silly hasDependencyInstalled @tecla5/ploppy babel-preset-env
32 silly dependencyIsSatisfied [ 'babel-preset-env',
32 silly dependencyIsSatisfied   '^1.3.1',
32 silly dependencyIsSatisfied   '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/node_modules' ]
33 verbose dependencyIsSatisfied babel-preset-env false
34 silly hasDependencyInstalled @tecla5/ploppy fs-extra-promise
35 silly dependencyIsSatisfied [ 'fs-extra-promise',
35 silly dependencyIsSatisfied   '^1.0.1',
35 silly dependencyIsSatisfied   '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/node_modules' ]
36 verbose dependencyIsSatisfied fs-extra-promise false
37 silly hasDependencyInstalled @tecla5/ploppy gitlab
38 silly dependencyIsSatisfied [ 'gitlab',
38 silly dependencyIsSatisfied   '@tecla5/gitlab',
38 silly dependencyIsSatisfied   '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/node_modules' ]
39 verbose dependencyIsSatisfied gitlab false
40 silly root dependencies []
41 silly leaf dependencies {
41 silly leaf dependencies   "@tecla5/ploppy": [
41 silly leaf dependencies     {
41 silly leaf dependencies       "dependency": "ava@^0.19.1",
41 silly leaf dependencies       "isSatisfied": false
41 silly leaf dependencies     },
41 silly leaf dependencies     {
41 silly leaf dependencies       "dependency": "babel-cli@^6.24.0",
41 silly leaf dependencies       "isSatisfied": false
41 silly leaf dependencies     },
41 silly leaf dependencies     {
41 silly leaf dependencies       "dependency": "babel-core@^6.24.1",
41 silly leaf dependencies       "isSatisfied": false
41 silly leaf dependencies     },
41 silly leaf dependencies     {
41 silly leaf dependencies       "dependency": "babel-plugin-transform-runtime@^6.23.0",
41 silly leaf dependencies       "isSatisfied": false
41 silly leaf dependencies     },
41 silly leaf dependencies     {
41 silly leaf dependencies       "dependency": "babel-polyfill@^6.23.0",
41 silly leaf dependencies       "isSatisfied": false
41 silly leaf dependencies     },
41 silly leaf dependencies     {
41 silly leaf dependencies       "dependency": "babel-preset-env@^1.3.1",
41 silly leaf dependencies       "isSatisfied": false
41 silly leaf dependencies     },
41 silly leaf dependencies     {
41 silly leaf dependencies       "dependency": "fs-extra-promise@^1.0.1",
41 silly leaf dependencies       "isSatisfied": false
41 silly leaf dependencies     },
41 silly leaf dependencies     {
41 silly leaf dependencies       "dependency": "gitlab@@tecla5/gitlab",
41 silly leaf dependencies       "isSatisfied": false
41 silly leaf dependencies     }
41 silly leaf dependencies   ]
41 silly leaf dependencies }
42 info Installing external dependencies
43 verbose actions 1 actions, concurrency 4
44 silly installInDir ploppy [ 'ava@^0.19.1',
44 silly installInDir   'babel-cli@^6.24.0',
44 silly installInDir   'babel-core@^6.24.1',
44 silly installInDir   'babel-plugin-transform-runtime@^6.23.0',
44 silly installInDir   'babel-polyfill@^6.23.0',
44 silly installInDir   'babel-preset-env@^1.3.1',
44 silly installInDir   'fs-extra-promise@^1.0.1',
44 silly installInDir   'gitlab@@tecla5/gitlab' ]
45 silly installInDir backup /Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/package.json
46 silly rename [ '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/package.json',
46 silly rename   '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/package.json.lerna_backup' ]
47 silly installInDir writing tempJson { dependencies:
47 silly installInDir    { ava: '^0.19.1',
47 silly installInDir      'babel-cli': '^6.24.0',
47 silly installInDir      'babel-core': '^6.24.1',
47 silly installInDir      'babel-plugin-transform-runtime': '^6.23.0',
47 silly installInDir      'babel-polyfill': '^6.23.0',
47 silly installInDir      'babel-preset-env': '^1.3.1',
47 silly installInDir      'fs-extra-promise': '^1.0.1',
47 silly installInDir      gitlab: '@tecla5/gitlab' } }
48 silly getExecOpts { cwd: '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy' }
49 silly installInDir [ 'npm', [ 'install' ] ]
50 silly installInDir cleanup /Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/package.json
51 silly renameSync [ '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/package.json.lerna_backup',
51 silly renameSync   '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/package.json' ]
52 verbose installed leaf @tecla5/ploppy
53 error execute Error: Command failed: npm install
53 error execute npm ERR! addLocal Could not install /Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/@tecla5/gitlab
53 error execute npm ERR! Darwin 16.5.0
53 error execute npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
53 error execute npm ERR! node v7.10.0
53 error execute npm ERR! npm  v4.2.0
53 error execute npm ERR! path /Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/@tecla5/gitlab
53 error execute npm ERR! code ENOENT
53 error execute npm ERR! errno -2
53 error execute npm ERR! syscall open
53 error execute
53 error execute npm ERR! enoent ENOENT: no such file or directory, open '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/@tecla5/gitlab'
53 error execute npm ERR! enoent ENOENT: no such file or directory, open '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/@tecla5/gitlab'
53 error execute npm ERR! enoent This is most likely not a problem with npm itself
53 error execute npm ERR! enoent and is related to npm not being able to find a file.
53 error execute npm ERR! enoent
53 error execute
53 error execute npm ERR! Please include the following file with any support request:
53 error execute npm ERR!     /Users/kristianmandrup/.npm/_logs/2017-05-18T15_40_47_856Z-debug.log
53 error execute
53 error execute     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:210:11)
53 error execute     at process._tickCallback (internal/process/next_tick.js:109:7)
53 error execute  callback with error
53 error execute  { Error: Command failed: npm install
53 error execute npm ERR! addLocal Could not install /Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/@tecla5/gitlab
53 error execute npm ERR! Darwin 16.5.0
53 error execute npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
53 error execute npm ERR! node v7.10.0
53 error execute npm ERR! npm  v4.2.0
53 error execute npm ERR! path /Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/@tecla5/gitlab
53 error execute npm ERR! code ENOENT
53 error execute npm ERR! errno -2
53 error execute npm ERR! syscall open
53 error execute
53 error execute npm ERR! enoent ENOENT: no such file or directory, open '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/@tecla5/gitlab'
53 error execute npm ERR! enoent ENOENT: no such file or directory, open '/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/@tecla5/gitlab'
53 error execute npm ERR! enoent This is most likely not a problem with npm itself
53 error execute npm ERR! enoent and is related to npm not being able to find a file.
53 error execute npm ERR! enoent
53 error execute
53 error execute npm ERR! Please include the following file with any support request:
53 error execute npm ERR!     /Users/kristianmandrup/.npm/_logs/2017-05-18T15_40_47_856Z-debug.log
53 error execute
53 error execute     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:210:11)
53 error execute     at process._tickCallback (internal/process/next_tick.js:109:7)
53 error execute   code: 254,
53 error execute   killed: false,
53 error execute   stdout: '',
53 error execute   stderr: 'npm ERR! addLocal Could not install /Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/@tecla5/gitlab\nnpm ERR! Darwin 16.5.0\nnpm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"\nnpm ERR! node v7.10.0\nnpm ERR! npm  v4.2.0\nnpm ERR! path /Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/@tecla5/gitlab\nnpm ERR! code ENOENT\nnpm ERR! errno -2\nnpm ERR! syscall open\n\nnpm ERR! enoent ENOENT: no such file or directory, open \'/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/@tecla5/gitlab\'\nnpm ERR! enoent ENOENT: no such file or directory, open \'/Users/kristianmandrup/repos/tecla5/docker-gen/packages/ploppy/@tecla5/gitlab\'\nnpm ERR! enoent This is most likely not a problem with npm itself\nnpm ERR! enoent and is related to npm not being able to find a file.\nnpm ERR! enoent \n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /Users/kristianmandrup/.npm/_logs/2017-05-18T15_40_47_856Z-debug.log\n',
53 error execute   failed: true,
53 error execute   signal: null,
53 error execute   cmd: 'npm install',
53 error execute   timedOut: false }
```
</p></details>

## Context

I can't use my project with lerna, so have to hook up projects manually...

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.4 |
| `npm --version`  | 4.2.0 |
| `node --version` | 7.10.0 |

| OS | Version |
| macOS Sierra | 10.12.3 |

**Comment by kristianmandrup** [comment]
OMG! Too tired... never program on too little sleep. Put dependencies in reverse order!
