### ISSUE TITLE
Detached HEAD in Continuous Integration Publish

### ISSUE THREAD

**Issue by dtothefp** [lerna/lerna#839]
## Expected Behavior
Using a few flags with `lerna publish` in order to brute force publishing of all packages in CI without confirmation prompts.

```sh
lerna publish --cd-version $VERSION --yes --force-publish=*
```

## Current Behavior
I'm pretty sure this isn't a bug, but most likely something to do with how Travis CI works with git. I've added a new remote with GitHub auth token, but am unsure where/what in the Lerna code is failing

```sh
0.78s$ if [ $TRAVIS_BRANCH = "master" ]; then yarn publish-ci; else gulp build; fi
yarn publish-ci v0.24.6
$ VERSION=${MODULE_VERSION:-patch}; echo "publishing $VERSION"; lerna publish --cd-version $VERSION --yes --force-publish=* 
publishing minor
lerna info version 2.0.0-rc.4
lerna info current version 1.0.4
lerna info Checking for updated packages...
lerna info Comparing with tag v1.0.2
Changes:
 - @h1/boiler-config-eslint: 1.0.4 => 1.1.0
 - @h1/boiler-config: 1.0.4 => 1.1.0
 - @h1/boiler-core: 1.0.4 => 1.1.0
 - @h1/boiler-task-eslint: 1.0.4 => 1.1.0
 - @h1/boiler-utils: 1.0.4 => 1.1.0
lerna info auto-confirmed 
lerna ERR! execute Error: Detached git HEAD, please checkout a branch to publish changes.
lerna ERR! execute     at PublishCommand.execute (/home/travis/build/SystemsSoftware/build-boiler/node_modules/lerna/lib/commands/PublishCommand.js:235:17)
lerna ERR! execute     at PublishCommand._attempt (/home/travis/build/SystemsSoftware/build-boiler/node_modules/lerna/lib/Command.js:265:21)
lerna ERR! execute     at /home/travis/build/SystemsSoftware/build-boiler/node_modules/lerna/lib/Command.js:252:15
lerna ERR! execute     at /home/travis/build/SystemsSoftware/build-boiler/node_modules/lerna/lib/Command.js:274:13
lerna ERR! execute     at PublishCommand.confirmVersions (/home/travis/build/SystemsSoftware/build-boiler/node_modules/lerna/lib/commands/PublishCommand.js:471:9)
lerna ERR! execute     at /home/travis/build/SystemsSoftware/build-boiler/node_modules/lerna/lib/commands/PublishCommand.js:227:16
lerna ERR! execute     at PublishCommand.getVersionsForUpdates (/home/travis/build/SystemsSoftware/build-boiler/node_modules/lerna/lib/commands/PublishCommand.js:319:16)
lerna ERR! execute     at PublishCommand.initialize (/home/travis/build/SystemsSoftware/build-boiler/node_modules/lerna/lib/commands/PublishCommand.js:208:12)
lerna ERR! execute     at PublishCommand._attempt (/home/travis/build/SystemsSoftware/build-boiler/node_modules/lerna/lib/Command.js:265:21)
lerna ERR! execute     at PublishCommand.runCommand (/home/travis/build/SystemsSoftware/build-boiler/node_modules/lerna/lib/Command.js:251:12)
```

## Possible Solution
For now I'm passing the additional flag of `--skip-git` which obviously fixes the issue 

## Steps to Reproduce (for bugs)
Right now this is in GitHub Enterprise and Running on Travis Enterprise but I can create a small open source example if necessary.

// lerna.json
```json
{
  "lerna": "2.0.0-rc.4",
  "version": "1.0.4",
  "npmClient": "yarn"
}
```

| `yarn --version` | 0.23.4 |
| `node --version` | 7.10.0 |

**Comment by palmerabollo** [comment]
@dtothefp Same here. Any luck?

**Comment by evocateur** [comment]
Wouldn't `git checkout master` before `yarn publish-ci` be sufficient?

**Comment by evocateur** [comment]
(assuming you _want_ your CI to make commits and push them, with appropriate auth and whatnot)

**Comment by LucaT1** [comment]
Same here. Have you found a fix?

**Comment by evocateur** [comment]
`lerna publish` makes a commit and pushes it to remote, by default. That’s not ideal for a CI build. I would recommend passing `--canary` for that purpose.

**Comment by danielo515** [comment]
Sorry, but I just don't understand. How the canary flag can help here ? I just want to automate the publish process and allow Lerna to push tags back to the repository.

**Comment by evocateur** [comment]
Unlike semantic-release, lerna currently pushes a commit to the remote, not just tags. There’s also currently no way to split the tagging and committing operations from CLI flags.

There are ways to “re-attach” the HEAD in CI, but they are largely dependent on CI environment variables, and thus complicated, arguably outside lerna’s scope.

**Comment by danielo515** [comment]
In my case I fixed it by previously making a checkout on the CI system

**Comment by light24bulbs** [comment]
If you are on jenkins and have this problem you can add the local branch plugin to your checkout SCM:
` extensions: [[$class: 'LocalBranch', localBranch: '**']]`
This will tell jenkins git to use a local branch, avoiding the detached head state.
