### ISSUE TITLE
lerna publish ignores lerna.json args

### ISSUE THREAD

**Issue by tivac** [lerna/lerna#841]
## Expected Behavior

When configuring `lerna.json` with a `publish` section under `command` those flags should be respected by lerna.

## Current Behavior

Flags in `lerna.json` are ignored when running `lerna publish`

## Possible Solution

@evocateur suggested [in slack](https://lernajs.slack.com/archives/C190VQD40/p1495659732334611) that `PublishCommand.js` should use `this.options.*` instead of `this.flags.*` to support durable args.

## Steps to Reproduce
1. Configure `lerna.json` with flags for `publish`.
2. Run `lerna publish`
3. Note that the commit message does not use the defined value

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-beta.38",
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "command": {
    "publish": {
      "message": "chore: Publish"
    },
    "bootstrap": {
      "hoist": true
    }
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'publish' ]
1 silly flags { _: [ 'publish' ], sort: true, concurrency: 4 }
2 verbose rootPath D:\git\modular-css
3 info version 2.0.0-rc.4
4 info versioning independent
5 silly isInitialized
6 silly isInitialized true
7 silly existsSync D:\git\modular-css\VERSION
8 silly initialize attempt
9 silly getUpdates
10 info Checking for updated packages...
11 silly hasTags
12 verbose hasTags true
13 silly getLastTag
14 verbose getLastTag modular-css-webpack@5.2.3
15 info Comparing with tag modular-css-webpack@5.2.3
16 silly getLastTaggedCommitInBranch
17 silly getLastTag
18 verbose getLastTag modular-css-webpack@5.2.3
19 verbose getLastTaggedCommitInBranch 4ac74b7e676219c9d8135d1db45ac8b74151162a
20 silly describeTag 4ac74b7e676219c9d8135d1db45ac8b74151162a
21 silly describeTag modular-css-webpack@5.2.3
22 silly diffSinceIn modular-css-webpack@5.2.3 D:\git\modular-css\packages\aliases
23 silly diff packages/aliases/.npmignore
23 silly diff packages/aliases/LICENSE
23 silly diff packages/aliases/README.md
23 silly diff packages/aliases/aliases.js
23 silly diff packages/aliases/package.json
23 silly diff packages/aliases/test/__snapshots__/aliases.test.js.snap
23 silly diff packages/aliases/test/aliases.test.js
23 silly diff packages/aliases/test/specimens/one/one.css
23 silly diff packages/aliases/test/specimens/one/sub/sub.css
23 silly diff packages/aliases/test/specimens/two/two.css
24 silly diffSinceIn modular-css-webpack@5.2.3 D:\git\modular-css\packages\browserify
25 silly diff
26 silly diffSinceIn modular-css-webpack@5.2.3 D:\git\modular-css\packages\bundle
27 silly diff
28 silly diffSinceIn modular-css-webpack@5.2.3 D:\git\modular-css\packages\cli
29 silly diff
30 silly diffSinceIn modular-css-webpack@5.2.3 D:\git\modular-css\packages\core
31 silly diff
32 silly diffSinceIn modular-css-webpack@5.2.3 D:\git\modular-css\packages\glob
33 silly diff
34 silly diffSinceIn modular-css-webpack@5.2.3 D:\git\modular-css\packages\namer
35 silly diff
36 silly diffSinceIn modular-css-webpack@5.2.3 D:\git\modular-css\packages\paths
37 silly diff packages/paths/README.md
37 silly diff packages/paths/package.json
37 silly diff packages/paths/paths.js
38 silly diffSinceIn modular-css-webpack@5.2.3 D:\git\modular-css\packages\postcss
39 silly diff
40 silly diffSinceIn modular-css-webpack@5.2.3 D:\git\modular-css\packages\rollup
41 silly diff
42 silly diffSinceIn modular-css-webpack@5.2.3 D:\git\modular-css\packages\test-utils
43 silly diff
44 silly diffSinceIn modular-css-webpack@5.2.3 D:\git\modular-css\packages\webpack
45 silly diff
46 silly diffSinceIn modular-css-webpack@5.2.3 D:\git\modular-css\packages\www
47 silly diff
48 verbose has update modular-css-aliases
49 verbose has update modular-css-paths
50 silly collectDependents
51 silly isPackageDependentOf modular-css-aliases modular-css-aliases
52 silly isPackageDependentOf modular-css-core modular-css-aliases
53 silly isPackageDependentOf test-utils modular-css-aliases
54 silly isPackageDependentOf test-utils modular-css-aliases
55 silly isPackageDependentOf modular-css-aliases modular-css-paths
56 silly isPackageDependentOf modular-css-core modular-css-paths
57 silly isPackageDependentOf test-utils modular-css-paths
58 silly isPackageDependentOf test-utils modular-css-paths
59 silly isPackageDependentOf modular-cssify modular-css-aliases
60 silly isPackageDependentOf test-utils modular-css-aliases
61 silly isPackageDependentOf modular-css-core modular-css-aliases
62 silly isPackageDependentOf modular-cssify modular-css-paths
63 silly isPackageDependentOf test-utils modular-css-paths
64 silly isPackageDependentOf modular-css-core modular-css-paths
65 silly isPackageDependentOf modular-css modular-css-aliases
66 silly isPackageDependentOf modular-css-cli modular-css-aliases
67 silly isPackageDependentOf test-utils modular-css-aliases
68 silly isPackageDependentOf modular-css-core modular-css-aliases
69 silly isPackageDependentOf modular-css-glob modular-css-aliases
70 silly isPackageDependentOf test-utils modular-css-aliases
71 silly isPackageDependentOf modular-css-core modular-css-aliases
72 silly isPackageDependentOf modular-css-core modular-css-aliases
73 silly isPackageDependentOf modular-css-glob modular-css-aliases
74 silly isPackageDependentOf modular-css-rollup modular-css-aliases
75 silly isPackageDependentOf test-utils modular-css-aliases
76 silly isPackageDependentOf modular-css-core modular-css-aliases
77 silly isPackageDependentOf modular-css-webpack modular-css-aliases
78 silly isPackageDependentOf test-utils modular-css-aliases
79 silly isPackageDependentOf modular-css-core modular-css-aliases
80 silly isPackageDependentOf modular-cssify modular-css-aliases
81 silly isPackageDependentOf postcss-modular-css modular-css-aliases
82 silly isPackageDependentOf test-utils modular-css-aliases
83 silly isPackageDependentOf modular-css-core modular-css-aliases
84 silly isPackageDependentOf modular-css modular-css-paths
85 silly isPackageDependentOf modular-css-cli modular-css-paths
86 silly isPackageDependentOf test-utils modular-css-paths
87 silly isPackageDependentOf modular-css-core modular-css-paths
88 silly isPackageDependentOf modular-css-glob modular-css-paths
89 silly isPackageDependentOf test-utils modular-css-paths
90 silly isPackageDependentOf modular-css-core modular-css-paths
91 silly isPackageDependentOf modular-css-core modular-css-paths
92 silly isPackageDependentOf modular-css-glob modular-css-paths
93 silly isPackageDependentOf modular-css-rollup modular-css-paths
94 silly isPackageDependentOf test-utils modular-css-paths
95 silly isPackageDependentOf modular-css-core modular-css-paths
96 silly isPackageDependentOf modular-css-webpack modular-css-paths
97 silly isPackageDependentOf test-utils modular-css-paths
98 silly isPackageDependentOf modular-css-core modular-css-paths
99 silly isPackageDependentOf modular-cssify modular-css-paths
100 silly isPackageDependentOf postcss-modular-css modular-css-paths
101 silly isPackageDependentOf test-utils modular-css-paths
102 silly isPackageDependentOf modular-css-core modular-css-paths
103 silly isPackageDependentOf modular-css-cli modular-css-aliases
104 silly isPackageDependentOf modular-css-cli modular-css-paths
105 silly isPackageDependentOf modular-css-core modular-css-aliases
106 silly isPackageDependentOf modular-css-core modular-css-paths
107 silly isPackageDependentOf modular-css-glob modular-css-aliases
108 silly isPackageDependentOf modular-css-glob modular-css-paths
109 silly isPackageDependentOf modular-css-namer modular-css-aliases
110 silly isPackageDependentOf modular-css-namer modular-css-paths
111 silly isPackageDependentOf modular-css-paths modular-css-aliases
112 silly isPackageDependentOf modular-css-core modular-css-aliases
113 silly isPackageDependentOf test-utils modular-css-aliases
114 silly isPackageDependentOf modular-css-paths modular-css-paths
115 silly isPackageDependentOf modular-css-core modular-css-paths
116 silly isPackageDependentOf test-utils modular-css-paths
117 silly isPackageDependentOf postcss-modular-css modular-css-aliases
118 silly isPackageDependentOf postcss-modular-css modular-css-paths
119 silly isPackageDependentOf modular-css-rollup modular-css-aliases
120 silly isPackageDependentOf modular-css-rollup modular-css-paths
121 silly isPackageDependentOf test-utils modular-css-aliases
122 silly isPackageDependentOf test-utils modular-css-paths
123 silly isPackageDependentOf modular-css-webpack modular-css-aliases
124 silly isPackageDependentOf modular-css-webpack modular-css-paths
125 silly isPackageDependentOf www modular-css-aliases
126 silly isPackageDependentOf modular-css-namer modular-css-aliases
127 silly isPackageDependentOf modular-cssify modular-css-aliases
128 silly isPackageDependentOf modular-css-core modular-css-aliases
129 silly isPackageDependentOf www modular-css-paths
130 silly isPackageDependentOf modular-css-namer modular-css-paths
131 silly isPackageDependentOf modular-cssify modular-css-paths
132 silly isPackageDependentOf modular-css-core modular-css-paths
133 silly collectUpdates
134 verbose has filtered update modular-css-aliases
135 verbose has filtered update modular-css-paths
136 silly initialize success
137 silly execute attempt
138 silly isDetachedHead
139 silly getCurrentBranch
140 verbose getCurrentBranch master
141 verbose isDetachedHead false
142 silly addFile D:\git\modular-css\packages\aliases\package.json
143 silly addFile D:\git\modular-css\packages\paths\package.json
144 silly commit Publish
144 silly commit
144 silly commit  - modular-css-aliases@5.1.5
144 silly commit  - modular-css-paths@5.1.6
145 verbose commit [ 'commit',
145 verbose commit   '-F',
145 verbose commit   'C:\\Users\\pcavit\\AppData\\Local\\Temp\\f237d304-a6c1-4f40-af8a-0606faa342f6\\lerna-commit.txt' ]
146 error execute Error:
146 error execute > husky - npm run -s precommit
146 error execute
146 error execute [?25l[13:58:46] Running tasks for *.js [started]
146 error execute [13:58:46] Running tasks for *.js [skipped]
146 error execute [13:58:46] → No staged files match *.js
146 error execute [?25h[?25h
146 error execute > husky - npm run -s commitmsg
146 error execute
146 error execute INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" !
146 error execute Publish
146 error execute
146 error execute > husky - commit-msg hook failed (add --no-verify to bypass)
146 error execute > husky - to debug, use 'npm run commitmsg'
146 error execute
146 error execute     at Function.module.exports.sync (C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\node_modules\execa\index.js:277:26)
146 error execute     at Function.execSync (C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\ChildProcessUtilities.js:51:30)
146 error execute     at Function.commit (C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\GitUtilities.js:84:39)
146 error execute     at PublishCommand.gitCommitAndTagVersionForUpdates (C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\commands\PublishCommand.js:577:30)
146 error execute     at PublishCommand.commitAndTagUpdates (C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\commands\PublishCommand.js:559:26)
146 error execute     at PublishCommand.execute (C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\commands\PublishCommand.js:245:16)
146 error execute     at PublishCommand._attempt (C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\Command.js:265:21)
146 error execute     at C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\Command.js:252:15
146 error execute     at C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\Command.js:274:13
146 error execute     at C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\commands\PublishCommand.js:474:11
146 error execute  callback with error
146 error execute  Error:
146 error execute > husky - npm run -s precommit
146 error execute
146 error execute [?25l[13:58:46] Running tasks for *.js [started]
146 error execute [13:58:46] Running tasks for *.js [skipped]
146 error execute [13:58:46] → No staged files match *.js
146 error execute [?25h[?25h
146 error execute > husky - npm run -s commitmsg
146 error execute
146 error execute INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" !
146 error execute Publish
146 error execute
146 error execute > husky - commit-msg hook failed (add --no-verify to bypass)
146 error execute > husky - to debug, use 'npm run commitmsg'
146 error execute
146 error execute     at Function.module.exports.sync (C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\node_modules\execa\index.js:277:26)
146 error execute     at Function.execSync (C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\ChildProcessUtilities.js:51:30)
146 error execute     at Function.commit (C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\GitUtilities.js:84:39)
146 error execute     at PublishCommand.gitCommitAndTagVersionForUpdates (C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\commands\PublishCommand.js:577:30)
146 error execute     at PublishCommand.commitAndTagUpdates (C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\commands\PublishCommand.js:559:26)
146 error execute     at PublishCommand.execute (C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\commands\PublishCommand.js:245:16)
146 error execute     at PublishCommand._attempt (C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\Command.js:265:21)
146 error execute     at C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\Command.js:252:15
146 error execute     at C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\Command.js:274:13
146 error execute     at C:\Users\pcavit\AppData\Roaming\npm\node_modules\lerna\lib\commands\PublishCommand.js:474:11

```
</p></details>

## Context

I'd like to configure as much as possible via `lerna.json` because having to remember CLI args is always a bad plan.

## Your Environment

- Windows 10
- Node v7.9.0
- NPM v4.6.1
- Lerna

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.5 |
| `npm --version`  | 4.6.1 |
| `node --version` | 7.9.0 |

| OS | Version |
| --- | --- |
| Windows 10 | 14393 |

**Comment by evocateur** [comment]
I forgot my automagical "fixes" comment :shipit:
