### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by gpltaylor** [lerna/lerna#894]
I'm having the same problem. I added a new package.json dependency. Ran "lerna bootstrap" 

```
$ lerna bootstrap
Lerna v2.0.0-beta.38
Independent Versioning Mode
Bootstrapping 6 packages
Preinstalling packages
fl-components                                      ╢███████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
fl-server                                          ╢██████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
fluent-utilities                                   ╢██████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
fl-redux                                           ╢█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
fluentloans.online.ui                              ╢████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
fl-ui                                              ╢███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████╟
Installing external dependencies
FileSystemUtilities.renameSync("D:\\Desktop\\Development Area\\Fluent.FluentLoans.Online\\uiv2\\packages\\components\\package.json....)
Error: EPERM: operation not permitted, rename 'D:\Desktop\Development Area\Fluent.FluentLoans.Online\uiv2\packages\components\package.json.lerna_backup' -> 'D:\Desktop\Development Area\Fluent.FluentLoans.Online\uiv2\packages\components\package.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:803:18)
    at renameSync (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\FileSystemUtilities.js:119:20)
    at Function.descriptor.value (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\logger.js:146:33)
    at cleanup (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\NpmUtilities.js:112:41)
    at done (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\NpmUtilities.js:136:13)
    at C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\ChildProcessUtilities.js:75:16
    at ChildProcess.<anonymous> (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\ChildProcessUtilities.js:162:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
FileSystemUtilities.renameSync("D:\\Desktop\\Development Area\\Fluent.FluentLoans.Online\\uiv2\\packages\\components\\package.json....)
Error: EPERM: operation not permitted, rename 'D:\Desktop\Development Area\Fluent.FluentLoans.Online\uiv2\packages\components\package.json.lerna_backup' -> 'D:\Desktop\Development Area\Fluent.FluentLoans.Online\uiv2\packages\components\package.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:803:18)
    at renameSync (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\FileSystemUtilities.js:119:20)
    at Function.descriptor.value (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\logger.js:146:33)
    at EventEmitter.cleanup (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\NpmUtilities.js:112:41)
    at emitTwo (events.js:111:20)
    at EventEmitter.emit (events.js:191:7)
    at emit (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\node_modules\signal-exit\index.js:77:11)
    at processEmit [as emit] (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\node_modules\signal-exit\index.js:150:5)
    at process._fatalException (node.js:276:21)
C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\logger.js:151
            throw error;
            ^

Error: EPERM: operation not permitted, rename 'D:\Desktop\Development Area\Fluent.FluentLoans.Online\uiv2\packages\components\package.json.lerna_backup' -> 'D:\Desktop\Development Area\Fluent.FluentLoans.Online\uiv2\packages\components\package.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:803:18)
    at renameSync (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\FileSystemUtilities.js:119:20)
    at Function.descriptor.value (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\logger.js:146:33)
    at cleanup (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\NpmUtilities.js:112:41)
    at done (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\NpmUtilities.js:136:13)
    at C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\ChildProcessUtilities.js:75:16
    at ChildProcess.<anonymous> (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\ChildProcessUtilities.js:162:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
```

I did delete the package.json.lerna_backup file (upps)
Now I am getting
```
$ lerna bootstrap
Lerna v2.0.0-beta.38
Independent Versioning Mode
Bootstrapping 6 packages
Preinstalling packages
Errored while running BootstrapCommand.execute
TypeError: Cannot read property 'slice' of undefined
    at ProgressBarController.tick (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\progressBar.js:61:50)
    at C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\commands\BootstrapCommand.js:134:32
    at Package.runScript (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\Package.js:61:9)
    at C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\commands\BootstrapCommand.js:133:15
    at C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\node_modules\async\lib\async.js:718:13
    at replenish (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\node_modules\async\lib\async.js:319:21)
    at C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\node_modules\async\lib\async.js:330:15
    at _parallel (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\node_modules\async\lib\async.js:717:9)
    at Object.async.parallelLimit (C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\node_modules\async\lib\async.js:735:9)
    at C:\Users\gtaylor\AppData\Roaming\nvm\v6.1.0\node_modules\lerna\lib\PackageUtilities.js:298:27
```

I can't get rid of this error. I have tried:
Pulling the package.json.lerna_backup back
deleting the lerna.json file and running lerna init

nothing is working.

any ideas how to fix this?

**Comment by gpltaylor** [comment]
I have been able to fix this by editing the progressBar.js
In some cases the package name is undefined. This causes the error when trying to run slice on it.

I placed a null check and this worked.
https://github.com/lerna/lerna/blob/v2.0.0-beta.38/src/progressBar.js#L37

```
  tick(name) {
    if (this.bar && name) {
      this.bar.tick({
        packagename: padEnd(name.slice(0, 50), 50)
      });
    }
  }
```

NOTE: The real issue is working out why the pkg name is undefined but I don't have the time to dig into this at the moment. Quick hack/fix

**Comment by gpltaylor** [comment]
Just noticed that one of the package.json files has become corrupted. This explains the bad package name, as the code can't read the project name from the json.

It looks like Lerna did not restore the file after running bootstrap. It's only got the dependency lines in there now.
