### ISSUE TITLE
`NPM need auth auth required for publishing` error (`npm whoami` shows logged in as correct user)

### ISSUE THREAD

**Issue by flipactual** [lerna/lerna#896]
## Expected Behavior
`lerna publish` should publish my packages

## Current Behavior
`lerna publish` does not publish my packages

no `lerna-debug.log` or `npm-debug.log` is created
`package.json`s are updated correctly
`lerna.json` is updated correctly

following error is received

<details><summary>log</summary><p>

```sh
? Are you sure you want to publish the above changes? Yes
lerna info publish Publishing packages to npm...
lerna ERR! publish Retrying failed publish: emdaer-plugin-heading
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_37_157Z-debug.log

(node:44146) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
lerna ERR! publish Retrying failed publish: emdaer-core
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_37_171Z-debug.log

lerna ERR! publish Retrying failed publish: emdaer-cli
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_37_276Z-debug.log

lerna ERR! publish Retrying failed publish: emdaer-plugin-linebreak
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_37_352Z-debug.log

lerna ERR! publish Retrying failed publish: emdaer-core
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_39_870Z-debug.log

lerna ERR! publish Retrying failed publish: emdaer-plugin-heading
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_39_901Z-debug.log

lerna ERR! publish Retrying failed publish: emdaer-plugin-linebreak
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 21): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_40_327Z-debug.log

lerna ERR! publish Retrying failed publish: emdaer-cli
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 24): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_40_378Z-debug.log

lerna ERR! publish Retrying failed publish: emdaer-core
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 27): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_42_698Z-debug.log

lerna ERR! publish Retrying failed publish: emdaer-plugin-heading
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 30): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_42_840Z-debug.log

lerna ERR! publish Retrying failed publish: emdaer-plugin-linebreak
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 33): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_43_400Z-debug.log

lerna ERR! publish Retrying failed publish: emdaer-cli
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 36): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_43_419Z-debug.log

lerna ERR! publish Retrying failed publish: emdaer-core
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 39): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_45_576Z-debug.log

lerna ERR! publish Retrying failed publish: emdaer-plugin-heading
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 42): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_45_868Z-debug.log

lerna ERR! publish Retrying failed publish: emdaer-plugin-linebreak
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 45): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_46_371Z-debug.log

lerna ERR! publish Retrying failed publish: emdaer-cli
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 48): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_46_603Z-debug.log

lerna ERR! publish Ran out of retries while publishing emdaer-core Error: Command failed: npm publish --tag latest
lerna ERR! publish npm ERR! Darwin 17.0.0
lerna ERR! publish npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
lerna ERR! publish npm ERR! node v7.10.0
lerna ERR! publish npm ERR! npm  v4.2.0
lerna ERR! publish npm ERR! code ENEEDAUTH
lerna ERR! publish 
lerna ERR! publish npm ERR! need auth auth required for publishing
lerna ERR! publish npm ERR! need auth You need to authorize this machine using `npm adduser`
lerna ERR! publish 
lerna ERR! publish npm ERR! Please include the following file with any support request:
lerna ERR! publish npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_49_004Z-debug.log
lerna ERR! publish 
lerna ERR! publish     at Promise.all.then.arr (/Users/flipactual/Dev/emdaer/node_modules/execa/index.js:210:11)
lerna ERR! publish     at process._tickCallback (internal/process/next_tick.js:109:7)
lerna ERR! execute callback with error
lerna ERR! execute  Error: Command failed: npm publish --tag latest
lerna ERR! execute npm ERR! Darwin 17.0.0
lerna ERR! execute npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
lerna ERR! execute npm ERR! node v7.10.0
lerna ERR! execute npm ERR! npm  v4.2.0
lerna ERR! execute npm ERR! code ENEEDAUTH
lerna ERR! execute 
lerna ERR! execute npm ERR! need auth auth required for publishing
lerna ERR! execute npm ERR! need auth You need to authorize this machine using `npm adduser`
lerna ERR! execute 
lerna ERR! execute npm ERR! Please include the following file with any support request:
lerna ERR! execute npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_49_004Z-debug.log
lerna ERR! execute 
lerna ERR! execute     at Promise.all.then.arr (/Users/flipactual/Dev/emdaer/node_modules/execa/index.js:210:11)
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:109:7)
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 51): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_49_004Z-debug.log

lerna ERR! publish Ran out of retries while publishing emdaer-plugin-heading Error: Command failed: npm publish --tag latest
lerna ERR! publish npm ERR! Darwin 17.0.0
lerna ERR! publish npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
lerna ERR! publish npm ERR! node v7.10.0
lerna ERR! publish npm ERR! npm  v4.2.0
lerna ERR! publish npm ERR! code ENEEDAUTH
lerna ERR! publish 
lerna ERR! publish npm ERR! need auth auth required for publishing
lerna ERR! publish npm ERR! need auth You need to authorize this machine using `npm adduser`
lerna ERR! publish 
lerna ERR! publish npm ERR! Please include the following file with any support request:
lerna ERR! publish npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_49_510Z-debug.log
lerna ERR! publish 
lerna ERR! publish     at Promise.all.then.arr (/Users/flipactual/Dev/emdaer/node_modules/execa/index.js:210:11)
lerna ERR! publish     at process._tickCallback (internal/process/next_tick.js:109:7)
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 54): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_49_510Z-debug.log

lerna ERR! publish Ran out of retries while publishing emdaer-plugin-linebreak Error: Command failed: npm publish --tag latest
lerna ERR! publish npm ERR! Darwin 17.0.0
lerna ERR! publish npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
lerna ERR! publish npm ERR! node v7.10.0
lerna ERR! publish npm ERR! npm  v4.2.0
lerna ERR! publish npm ERR! code ENEEDAUTH
lerna ERR! publish 
lerna ERR! publish npm ERR! need auth auth required for publishing
lerna ERR! publish npm ERR! need auth You need to authorize this machine using `npm adduser`
lerna ERR! publish 
lerna ERR! publish npm ERR! Please include the following file with any support request:
lerna ERR! publish npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_49_931Z-debug.log
lerna ERR! publish 
lerna ERR! publish     at Promise.all.then.arr (/Users/flipactual/Dev/emdaer/node_modules/execa/index.js:210:11)
lerna ERR! publish     at process._tickCallback (internal/process/next_tick.js:109:7)
(node:44146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 57): Error: Command failed: npm publish --tag latest
npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/node" "/Users/flipactual/.nvm/versions/node/v7.10.0/bin/npm" "publish" "--tag" "latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flipactual/.npm/_logs/2017-06-24T21_43_49_931Z-debug.log

error Command failed with exit code 1.

```
</p></details>

## Possible Solution
No clue, sorry

## Steps to Reproduce (for bugs)

https://github.com/emdaer/emdaer

had https://github.com/emdaer/emdaer/commit/fcd0919623253064a7c0d49346e3e6af31d772c5 ready, ran `yarn lerna` (I've got weird build steps due to babel/flow/etc), received error in terminal

https://github.com/emdaer/emdaer/commit/dd4c8c0ecbbe2335650998ea6f637ef74bdec007 was created along with a git tag

nothing was published

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.5",
  "packages": [
    "packages/emdaer-cli",
    "packages/emdaer-core",
    "packages/emdaer-plugin-heading",
    "packages/emdaer-plugin-linebreak",
    "packages/emdaer-transform-smartypants"
  ],
  "version": "1.0.0-bluerose.5"
}

```
</p></details>

## Context

Trying to publish packages

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.5 |
| `npm --version`  | 4.2.0 |
| `yarn --version` | 0.24.6 |
| `node --version` | v7.10.0  |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by michalkvasnicak** [comment]
Same error for me:

|  Executable  | Version  |
| -- | -- |
| `lerna --version` | 2.0.0-rc.5 |
| `npm --version` | 5.0.3 | 
| `yarn --version` | 0.24.5 |
| `node --version` | 8.1.2 |

| OS | Version |
| --  | -- |
| macOS Sierra | 10.12.5 (16F73) |

**Comment by michalkvasnicak** [comment]
I found that the problem is somehow connected with `yarn`. When you run `publish`, then `npm-run-path` assigns yarn registry url to env variable `npm_config_registry`. So  when `lerna` spawns `npm publish`, `npm` is using yarn's registry url and this causes error `ENEEDAUTH `. 

As a workaround for now, we have to use `lerna publish --registry=https://registry.npmjs.org/` or specify the `registry` in `lerna.json`. It forced given registry URL.

**Comment by evocateur** [comment]
Oy, that's a subtle bug. Maybe we should always pass `npm_config_registry`, defaulting the option to `https://registry.npmjs.org/` so it always "just works" with custom `--registry` config?

**Comment by flipactual** [comment]
@michalkvasnicak Thank you _so much_ for identify the issue

@evocateur that sounds like a solid solution to me

**Comment by evocateur** [comment]
#1145 may have fixed this, if we can trust that `yarn publish` to do the right thing, auth-wise?

**Comment by ahuth** [comment]
2.7.0 did not end up fixing this for me, @evocateur, although manually setting the registry through CLI options did work.

My setup is probably weird, though:

- Using lerna 2.7.0
- Using yarn 1.1.0
- Using yarn workspaces
- `yarn publish` [doesn't seem to play nicely](https://github.com/yarnpkg/yarn/issues/2445) with `lerna publish`, as it breaks when ran from a script.
- Because of the point above, I'm configuring lerna to use npm when publishing

**Comment by evocateur** [comment]
2.7.1 should have fixed the yarn publish issue, turns out it tries to prompt for “new version” be default. Dunno if that solves the issue for you, though.

**Comment by ahuth** [comment]
Works perfectly for me as of 2.7.1. Thanks!
