### ISSUE TITLE
Unpredictable npm module missing after bootstrap

### ISSUE THREAD

**Issue by antonmedv** [lerna/lerna#903]
## Expected Behavior
Install all required npm packages.

## Current Behavior
Unpredictable behavior. Example: https://github.com/aviasales/mx
I need to run `lerna bootstrap` 3 times to get everything working.

## Possible Solution
No have.

## Steps to Reproduce (for bugs)
0. git clone git@github.com:aviasales/mx.git && cd mx
1. npm install
2. lerna bootstrap
3. lerna bootstrap
4. lerna bootstrap

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.5",
  "packages": [
    "packages/*",
    "examples/*"
  ],
  "version": "0.0.0"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'bootstrap' ]
1 silly flags { _: [ 'bootstrap' ], sort: true, concurrency: 4 }
2 verbose rootPath /Users/anton/Projects/mx
3 info version 2.0.0-rc.5
4 silly existsSync /Users/anton/Projects/mx/VERSION
5 silly initialize attempt
6 silly initialize success
7 silly execute attempt
8 info Bootstrapping 6 packages
9 info lifecycle preinstall
10 silly runScript preinstall mx
11 silly mx
12 silly runScript preinstall babel-plugin-mx
13 silly babel-plugin-mx
14 silly runScript preinstall mx-cli
15 silly mx-cli
16 silly runScript preinstall mx-loader
17 silly mx-loader
18 silly runScript preinstall undefined
19 silly
20 silly runScript preinstall undefined
21 silly
22 silly hasMatchingDependency babel-plugin-mx mx
23 silly hasMatchingDependency mx-cli mx
24 silly hasMatchingDependency mx-loader mx
25 silly hasMatchingDependency undefined 'babel-plugin-mx'
26 silly hasMatchingDependency undefined 'mx'
27 silly hasMatchingDependency undefined 'mx-loader'
28 silly hasDependencyInstalled babel-plugin-mx babylon
29 silly dependencyIsSatisfied [ 'babylon',
29 silly dependencyIsSatisfied   '^6.17.4',
29 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/babel-plugin-mx/node_modules' ]
30 verbose dependencyIsSatisfied babylon true
31 silly hasDependencyInstalled mx-cli async-foreach
32 silly dependencyIsSatisfied [ 'async-foreach',
32 silly dependencyIsSatisfied   '^0.1.3',
32 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-cli/node_modules' ]
33 verbose dependencyIsSatisfied async-foreach true
34 silly hasDependencyInstalled mx-cli chalk
35 silly dependencyIsSatisfied [ 'chalk',
35 silly dependencyIsSatisfied   'latest',
35 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-cli/node_modules' ]
36 verbose dependencyIsSatisfied chalk false
37 silly hasDependencyInstalled mx-cli chokidar
38 silly dependencyIsSatisfied [ 'chokidar',
38 silly dependencyIsSatisfied   '^1.7.0',
38 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-cli/node_modules' ]
39 verbose dependencyIsSatisfied chokidar true
40 silly hasDependencyInstalled mx-cli columnify
41 silly dependencyIsSatisfied [ 'columnify',
41 silly dependencyIsSatisfied   '^1.5.4',
41 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-cli/node_modules' ]
42 verbose dependencyIsSatisfied columnify true
43 silly hasDependencyInstalled mx-cli get-stdin
44 silly dependencyIsSatisfied [ 'get-stdin',
44 silly dependencyIsSatisfied   '^5.0.1',
44 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-cli/node_modules' ]
45 verbose dependencyIsSatisfied get-stdin true
46 silly hasDependencyInstalled mx-cli glob
47 silly dependencyIsSatisfied [ 'glob',
47 silly dependencyIsSatisfied   '^7.1.2',
47 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-cli/node_modules' ]
48 verbose dependencyIsSatisfied glob true
49 silly hasDependencyInstalled mx-cli meow
50 silly dependencyIsSatisfied [ 'meow',
50 silly dependencyIsSatisfied   '^3.7.0',
50 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-cli/node_modules' ]
51 verbose dependencyIsSatisfied meow true
52 silly hasDependencyInstalled mx-cli mkdirp
53 silly dependencyIsSatisfied [ 'mkdirp',
53 silly dependencyIsSatisfied   '^0.5.1',
53 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-cli/node_modules' ]
54 verbose dependencyIsSatisfied mkdirp true
55 silly hasDependencyInstalled mx-cli prettier
56 silly dependencyIsSatisfied [ 'prettier',
56 silly dependencyIsSatisfied   '^1.5.2',
56 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-cli/node_modules' ]
57 verbose dependencyIsSatisfied prettier true
58 silly hasDependencyInstalled mx prettier
59 silly dependencyIsSatisfied [ 'prettier',
59 silly dependencyIsSatisfied   '^1.4.4',
59 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx/node_modules' ]
60 verbose dependencyIsSatisfied prettier false
61 silly hasDependencyInstalled mx-cli pretty-error
62 silly dependencyIsSatisfied [ 'pretty-error',
62 silly dependencyIsSatisfied   '^2.1.1',
62 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-cli/node_modules' ]
63 verbose dependencyIsSatisfied pretty-error true
64 silly hasDependencyInstalled mx-cli stdout-stream
65 silly dependencyIsSatisfied [ 'stdout-stream',
65 silly dependencyIsSatisfied   '^1.4.0',
65 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-cli/node_modules' ]
66 verbose dependencyIsSatisfied stdout-stream true
67 silly hasDependencyInstalled mx-cli uppercamelcase
68 silly dependencyIsSatisfied [ 'uppercamelcase',
68 silly dependencyIsSatisfied   '^3.0.0',
68 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-cli/node_modules' ]
69 verbose dependencyIsSatisfied uppercamelcase true
70 silly hasDependencyInstalled mx-loader uppercamelcase
71 silly dependencyIsSatisfied [ 'uppercamelcase',
71 silly dependencyIsSatisfied   '^3.0.0',
71 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-loader/node_modules' ]
72 verbose dependencyIsSatisfied uppercamelcase false
73 silly hasDependencyInstalled mx-loader memory-fs
74 silly dependencyIsSatisfied [ 'memory-fs',
74 silly dependencyIsSatisfied   '^0.4.1',
74 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-loader/node_modules' ]
75 verbose dependencyIsSatisfied memory-fs false
76 silly hasDependencyInstalled mx-loader webpack
77 silly dependencyIsSatisfied [ 'webpack',
77 silly dependencyIsSatisfied   '^3.0.0',
77 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-loader/node_modules' ]
78 verbose dependencyIsSatisfied webpack false
79 silly hasDependencyInstalled undefined 'webpack'
80 silly dependencyIsSatisfied [ 'webpack',
80 silly dependencyIsSatisfied   undefined,
80 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/examples/babel/node_modules' ]
81 verbose dependencyIsSatisfied webpack false
82 silly hasDependencyInstalled mx-loader loader-utils
83 silly dependencyIsSatisfied [ 'loader-utils',
83 silly dependencyIsSatisfied   '^1.1.0',
83 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx-loader/node_modules' ]
84 verbose dependencyIsSatisfied loader-utils false
85 silly hasDependencyInstalled mx dedent
86 silly dependencyIsSatisfied [ 'dedent',
86 silly dependencyIsSatisfied   '^0.7.0',
86 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx/node_modules' ]
87 verbose dependencyIsSatisfied dedent false
88 silly hasDependencyInstalled mx jison-gho
89 silly dependencyIsSatisfied [ 'jison-gho',
89 silly dependencyIsSatisfied   '^0.4.18-180',
89 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx/node_modules' ]
90 verbose dependencyIsSatisfied jison-gho false
91 silly hasDependencyInstalled mx preprocessor
92 silly dependencyIsSatisfied [ 'preprocessor',
92 silly dependencyIsSatisfied   '^1.4.0',
92 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx/node_modules' ]
93 verbose dependencyIsSatisfied preprocessor false
94 silly hasDependencyInstalled mx source-map
95 silly dependencyIsSatisfied [ 'source-map',
95 silly dependencyIsSatisfied   '^0.5.6',
95 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/packages/mx/node_modules' ]
96 verbose dependencyIsSatisfied source-map false
97 silly hasDependencyInstalled undefined 'react'
98 silly dependencyIsSatisfied [ 'react',
98 silly dependencyIsSatisfied   undefined,
98 silly dependencyIsSatisfied   '/Users/anton/Projects/mx/examples/babel/node_modules' ]
99 verbose dependencyIsSatisfied react false
100 silly root dependencies []
101 silly leaf dependencies {
101 silly leaf dependencies   "babel-plugin-mx": [
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "babylon@^6.17.4",
101 silly leaf dependencies       "isSatisfied": true
101 silly leaf dependencies     }
101 silly leaf dependencies   ],
101 silly leaf dependencies   "mx-cli": [
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "async-foreach@^0.1.3",
101 silly leaf dependencies       "isSatisfied": true
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "chalk@latest",
101 silly leaf dependencies       "isSatisfied": false
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "chokidar@^1.7.0",
101 silly leaf dependencies       "isSatisfied": true
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "columnify@^1.5.4",
101 silly leaf dependencies       "isSatisfied": true
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "get-stdin@^5.0.1",
101 silly leaf dependencies       "isSatisfied": true
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "glob@^7.1.2",
101 silly leaf dependencies       "isSatisfied": true
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "meow@^3.7.0",
101 silly leaf dependencies       "isSatisfied": true
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "mkdirp@^0.5.1",
101 silly leaf dependencies       "isSatisfied": true
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "prettier@^1.5.2",
101 silly leaf dependencies       "isSatisfied": true
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "pretty-error@^2.1.1",
101 silly leaf dependencies       "isSatisfied": true
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "stdout-stream@^1.4.0",
101 silly leaf dependencies       "isSatisfied": true
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "uppercamelcase@^3.0.0",
101 silly leaf dependencies       "isSatisfied": true
101 silly leaf dependencies     }
101 silly leaf dependencies   ],
101 silly leaf dependencies   "mx": [
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "prettier@^1.4.4",
101 silly leaf dependencies       "isSatisfied": false
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "dedent@^0.7.0",
101 silly leaf dependencies       "isSatisfied": false
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "jison-gho@^0.4.18-180",
101 silly leaf dependencies       "isSatisfied": false
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "preprocessor@^1.4.0",
101 silly leaf dependencies       "isSatisfied": false
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "source-map@^0.5.6",
101 silly leaf dependencies       "isSatisfied": false
101 silly leaf dependencies     }
101 silly leaf dependencies   ],
101 silly leaf dependencies   "mx-loader": [
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "uppercamelcase@^3.0.0",
101 silly leaf dependencies       "isSatisfied": false
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "memory-fs@^0.4.1",
101 silly leaf dependencies       "isSatisfied": false
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "webpack@^3.0.0",
101 silly leaf dependencies       "isSatisfied": false
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "loader-utils@^1.1.0",
101 silly leaf dependencies       "isSatisfied": false
101 silly leaf dependencies     }
101 silly leaf dependencies   ],
101 silly leaf dependencies   "undefined": [
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "webpack@^3.0.0",
101 silly leaf dependencies       "isSatisfied": false
101 silly leaf dependencies     },
101 silly leaf dependencies     {
101 silly leaf dependencies       "dependency": "react@^15.6.1",
101 silly leaf dependencies       "isSatisfied": false
101 silly leaf dependencies     }
101 silly leaf dependencies   ]
101 silly leaf dependencies }
102 info Installing external dependencies
103 verbose actions 4 actions, concurrency 4
104 silly installInDir mx-cli [ 'async-foreach@^0.1.3',
104 silly installInDir   'chalk@latest',
104 silly installInDir   'chokidar@^1.7.0',
104 silly installInDir   'columnify@^1.5.4',
104 silly installInDir   'get-stdin@^5.0.1',
104 silly installInDir   'glob@^7.1.2',
104 silly installInDir   'meow@^3.7.0',
104 silly installInDir   'mkdirp@^0.5.1',
104 silly installInDir   'prettier@^1.5.2',
104 silly installInDir   'pretty-error@^2.1.1',
104 silly installInDir   'stdout-stream@^1.4.0',
104 silly installInDir   'uppercamelcase@^3.0.0' ]
105 silly installInDir backup /Users/anton/Projects/mx/packages/mx-cli/package.json
106 silly rename [ '/Users/anton/Projects/mx/packages/mx-cli/package.json',
106 silly rename   '/Users/anton/Projects/mx/packages/mx-cli/package.json.lerna_backup' ]
107 silly installInDir mx [ 'prettier@^1.4.4',
107 silly installInDir   'dedent@^0.7.0',
107 silly installInDir   'jison-gho@^0.4.18-180',
107 silly installInDir   'preprocessor@^1.4.0',
107 silly installInDir   'source-map@^0.5.6' ]
108 silly installInDir backup /Users/anton/Projects/mx/packages/mx/package.json
109 silly rename [ '/Users/anton/Projects/mx/packages/mx/package.json',
109 silly rename   '/Users/anton/Projects/mx/packages/mx/package.json.lerna_backup' ]
110 silly installInDir mx-loader [ 'uppercamelcase@^3.0.0',
110 silly installInDir   'memory-fs@^0.4.1',
110 silly installInDir   'webpack@^3.0.0',
110 silly installInDir   'loader-utils@^1.1.0' ]
111 silly installInDir backup /Users/anton/Projects/mx/packages/mx-loader/package.json
112 silly rename [ '/Users/anton/Projects/mx/packages/mx-loader/package.json',
112 silly rename   '/Users/anton/Projects/mx/packages/mx-loader/package.json.lerna_backup' ]
113 silly installInDir webpack [ 'webpack@^3.0.0', 'react@^15.6.1' ]
114 silly installInDir backup /Users/anton/Projects/mx/examples/webpack/package.json
115 silly rename [ '/Users/anton/Projects/mx/examples/webpack/package.json',
115 silly rename   '/Users/anton/Projects/mx/examples/webpack/package.json.lerna_backup' ]
116 silly installInDir writing tempJson { dependencies:
116 silly installInDir    { uppercamelcase: '^3.0.0',
116 silly installInDir      'memory-fs': '^0.4.1',
116 silly installInDir      webpack: '^3.0.0',
116 silly installInDir      'loader-utils': '^1.1.0' } }
117 silly installInDir writing tempJson { dependencies:
117 silly installInDir    { prettier: '^1.4.4',
117 silly installInDir      dedent: '^0.7.0',
117 silly installInDir      'jison-gho': '^0.4.18-180',
117 silly installInDir      preprocessor: '^1.4.0',
117 silly installInDir      'source-map': '^0.5.6' } }
118 silly installInDir writing tempJson { dependencies:
118 silly installInDir    { 'async-foreach': '^0.1.3',
118 silly installInDir      chalk: 'latest',
118 silly installInDir      chokidar: '^1.7.0',
118 silly installInDir      columnify: '^1.5.4',
118 silly installInDir      'get-stdin': '^5.0.1',
118 silly installInDir      glob: '^7.1.2',
118 silly installInDir      meow: '^3.7.0',
118 silly installInDir      mkdirp: '^0.5.1',
118 silly installInDir      prettier: '^1.5.2',
118 silly installInDir      'pretty-error': '^2.1.1',
118 silly installInDir      'stdout-stream': '^1.4.0',
118 silly installInDir      uppercamelcase: '^3.0.0' } }
119 silly installInDir writing tempJson { dependencies: { webpack: '^3.0.0', react: '^15.6.1' } }
120 silly getExecOpts { cwd: '/Users/anton/Projects/mx/packages/mx-cli' }
121 silly installInDir [ 'npm', [ 'install' ] ]
122 silly getExecOpts { cwd: '/Users/anton/Projects/mx/packages/mx' }
123 silly installInDir [ 'npm', [ 'install' ] ]
124 silly getExecOpts { cwd: '/Users/anton/Projects/mx/examples/webpack' }
125 silly installInDir [ 'npm', [ 'install' ] ]
126 silly getExecOpts { cwd: '/Users/anton/Projects/mx/packages/mx-loader' }
127 silly installInDir [ 'npm', [ 'install' ] ]
128 silly installInDir cleanup /Users/anton/Projects/mx/packages/mx-cli/package.json
129 silly renameSync [ '/Users/anton/Projects/mx/packages/mx-cli/package.json.lerna_backup',
129 silly renameSync   '/Users/anton/Projects/mx/packages/mx-cli/package.json' ]
130 verbose installed leaf mx-cli
131 silly installInDir cleanup /Users/anton/Projects/mx/examples/webpack/package.json
132 silly renameSync [ '/Users/anton/Projects/mx/examples/webpack/package.json.lerna_backup',
132 silly renameSync   '/Users/anton/Projects/mx/examples/webpack/package.json' ]
133 verbose installed leaf undefined
134 silly installInDir cleanup /Users/anton/Projects/mx/packages/mx-loader/package.json
135 silly renameSync [ '/Users/anton/Projects/mx/packages/mx-loader/package.json.lerna_backup',
135 silly renameSync   '/Users/anton/Projects/mx/packages/mx-loader/package.json' ]
136 verbose installed leaf mx-loader
137 error execute Error: Command failed: npm install
137 error execute npm WARN checkPermissions Missing write access to /Users/anton/Projects/mx/packages/mx-loader/node_modules/mx
137 error execute npm WARN checkPermissions Missing write access to /Users/anton/Projects/mx/packages/mx-loader/node_modules
137 error execute npm WARN mx-loader No description
137 error execute npm WARN mx-loader No repository field.
137 error execute npm WARN mx-loader No license field.
137 error execute
137 error execute npm ERR! path /Users/anton/Projects/mx/packages/mx-loader/node_modules/mx
137 error execute npm ERR! code ENOENT
137 error execute npm ERR! errno -2
137 error execute npm ERR! syscall access
137 error execute npm ERR! enoent ENOENT: no such file or directory, access '/Users/anton/Projects/mx/packages/mx-loader/node_modules/mx'
137 error execute npm ERR! enoent This is related to npm not being able to find a file.
137 error execute npm ERR! enoent
137 error execute
137 error execute npm ERR! A complete log of this run can be found in:
137 error execute npm ERR!     /Users/anton/.npm/_logs/2017-06-30T13_29_07_324Z-debug.log
137 error execute
137 error execute     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:210:11)
137 error execute     at process._tickCallback (internal/process/next_tick.js:109:7)
137 error execute  callback with error
137 error execute  { Error: Command failed: npm install
137 error execute npm WARN checkPermissions Missing write access to /Users/anton/Projects/mx/packages/mx-loader/node_modules/mx
137 error execute npm WARN checkPermissions Missing write access to /Users/anton/Projects/mx/packages/mx-loader/node_modules
137 error execute npm WARN mx-loader No description
137 error execute npm WARN mx-loader No repository field.
137 error execute npm WARN mx-loader No license field.
137 error execute
137 error execute npm ERR! path /Users/anton/Projects/mx/packages/mx-loader/node_modules/mx
137 error execute npm ERR! code ENOENT
137 error execute npm ERR! errno -2
137 error execute npm ERR! syscall access
137 error execute npm ERR! enoent ENOENT: no such file or directory, access '/Users/anton/Projects/mx/packages/mx-loader/node_modules/mx'
137 error execute npm ERR! enoent This is related to npm not being able to find a file.
137 error execute npm ERR! enoent
137 error execute
137 error execute npm ERR! A complete log of this run can be found in:
137 error execute npm ERR!     /Users/anton/.npm/_logs/2017-06-30T13_29_07_324Z-debug.log
137 error execute
137 error execute     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:210:11)
137 error execute     at process._tickCallback (internal/process/next_tick.js:109:7)
137 error execute   stack: 'Error: Command failed: npm install\nnpm WARN checkPermissions Missing write access to /Users/anton/Projects/mx/packages/mx-loader/node_modules/mx\nnpm WARN checkPermissions Missing write access to /Users/anton/Projects/mx/packages/mx-loader/node_modules\nnpm WARN mx-loader No description\nnpm WARN mx-loader No repository field.\nnpm WARN mx-loader No license field.\n\nnpm ERR! path /Users/anton/Projects/mx/packages/mx-loader/node_modules/mx\nnpm ERR! code ENOENT\nnpm ERR! errno -2\nnpm ERR! syscall access\nnpm ERR! enoent ENOENT: no such file or directory, access \'/Users/anton/Projects/mx/packages/mx-loader/node_modules/mx\'\nnpm ERR! enoent This is related to npm not being able to find a file.\nnpm ERR! enoent \n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/anton/.npm/_logs/2017-06-30T13_29_07_324Z-debug.log\n\n    at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:210:11)\n    at process._tickCallback (internal/process/next_tick.js:109:7)',
137 error execute   code: 254,
137 error execute   killed: false,
137 error execute   stdout: '',
137 error execute   stderr: 'npm WARN checkPermissions Missing write access to /Users/anton/Projects/mx/packages/mx-loader/node_modules/mx\nnpm WARN checkPermissions Missing write access to /Users/anton/Projects/mx/packages/mx-loader/node_modules\nnpm WARN mx-loader No description\nnpm WARN mx-loader No repository field.\nnpm WARN mx-loader No license field.\n\nnpm ERR! path /Users/anton/Projects/mx/packages/mx-loader/node_modules/mx\nnpm ERR! code ENOENT\nnpm ERR! errno -2\nnpm ERR! syscall access\nnpm ERR! enoent ENOENT: no such file or directory, access \'/Users/anton/Projects/mx/packages/mx-loader/node_modules/mx\'\nnpm ERR! enoent This is related to npm not being able to find a file.\nnpm ERR! enoent \n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/anton/.npm/_logs/2017-06-30T13_29_07_324Z-debug.log\n',
137 error execute   failed: true,
137 error execute   signal: null,
137 error execute   cmd: 'npm install',
137 error execute   timedOut: false }

```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.5 |
| `npm --version`  | 5.0.4 |
| `yarn --version` | 0.24.6 |
| `node --version` | v7.10.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.3 |

**Comment by gpltaylor** [comment]
I'm still learning Lerna 😄 but this might be related to the version number "0.0.0" used in the lerna.json.
I have mine set to "independent". If you want a central version, you might have to increment this version, but that's a guess.

Can you let us know what you mean by "get everything working". For example, it's not installing dependences, not creating symbolic links etc.

**Comment by antonmedv** [comment]
Now installing dependences lime memory-fs, etc. Some installed, some not. Maybe it's an npm bug.

**Comment by zxqfox** [comment]
Try to not use npm 5.x, it's because of hoisting for sure.

**Comment by richburdon** [comment]
I have the same problem using yarn.
Is lerna still actively being developed?

**Comment by evocateur** [comment]
@richburdon Yes. We're all volunteers with day jobs, doing the best we can, very reliant on community contributions.

**Comment by richburdon** [comment]
Hi @evocateur, thanks. Sorry perhaps that came across badly. I'm not quite sure from the docs what to expect. Lerna is really useful, but I have to run `lerna clean then lerna bootstrap --hoist` every time I need to install a package in any submodule. This doesn't seem like expected behavior, so would like to be able to provide better feedback to debug. Any suggestions?

**Comment by evocateur** [comment]
I'll be the first to admit we don't have especially great integration test coverage for the `--hoist` flag. I use it daily with no issues, but that's because I know the kinks and I don't use yarn, etc.

The best help would be to isolate an integration test that reproduces these issues, which hopefully would go a long way toward identifying the fix. I really want to make lerna a great tool, but I (and other maintainers) need a lot of help.

**Comment by richburdon** [comment]
The problem occurs with growing complexity. I've built small tests and they work. It's very difficult to strip down a large project until it stops breaking since the errors are hard to repro.

So, I should use npm 4 (not npm 5 or yarn?) If I can get something stable so that I don't have to clean/bootstrap every time, then I'll start to dig a bit deeper and try to debug.

Thanks.

**Comment by evocateur** [comment]
Yes, I would recommend staying on npm4 for the time being. Also, explicitly adding all of your hoisted deps to the root package.json doesn't hurt (which makes all the `packages/*` installs basically symlink-only).

**Comment by richburdon** [comment]
Thanks again. I'll start here.

**Comment by richburdon** [comment]
I switched to npm 4 and things are better, but installing new modules is still very unreliable when using --hoist.

First, I'm not even sure how to install a new module in a sub package. `npm install` fails when bootstrap has been used with hoist, because some sister module's dependencies cannot be resolved.

~~~~
cd /project/packages/services
npm i --save sanitize-html

npm ERR! enoent ENOENT: no such file or directory, rename '/project/packages/services/node_modules/.staging/moment-799c059d' -> '/project/packages/util/node_modules/moment'
~~~~ 

So I'm manually adding package info to the package.json file (I'm sure that's not the intended use case). But even then, calling my bootstrap script again, usually fails to install the new module. So the only reliable way I can build is to --clean every time I touch any package.json file, which isn't great.

However, the reason for today's issue is that even with --clean `sanitize-html` which is declared in packages/services/package.json is not install anywhere (neither the root or the sub node_modeuls). No errors.

~~~~
lerna bootstrap --hoist --nohoist=grunt-*
~~~~

With debugging I can see `sanitize-html` is being pruned -- it just doesn't get hoisted (all 400 other packages do):
~~~~
lerna sill rimraf /project/packages/services/node_modules/sanitize-html
lerna verb prune /project/packages/services/node_modules/sanitize-html
...
lerna sill execute success
~~~~

**Comment by gijswijs** [comment]
I suffered from the same issue. A single package wouldn't install properly with Lerna, resulting in the following error
```
ENOENT: no such file or directory, rename 'C:\repositories\es-git-new\packages\push-mixin\node_modules\.staging\@es-git\core-5f2d41df\node_modules\text-encoding' -> 'C:\repositories\es-git-new\packages\push-mixin\node_modules\.staging\text-encoding-4a8cc963'
```
After running `npm install` in that specific package folder `C:\repositories\es-git-new\packages\push-mixin` and then running `lerna bootstrap` again, it worked, and even replaced the installed package with a symlink.
```
lerna WARN EREPLACE_EXIST @es-git/core is already installed for @es-git/push-mixin. Replacing with symlink...
```

It's a workaround, but one I can live with.
