### ISSUE TITLE
Publish removes the version from lerna.json!

### ISSUE THREAD

**Issue by aminpaks** [lerna/lerna#933]
When I run `lerna publish` it removes the version from `lerna.json` and commits an undefine version!

## Expected Behavior
Not removing the versioning, and publish the packages!

## Current Behavior
Removes the version from `lerna.json`, and pushes `vundefine` tag!

## Possible Solution
Don't know!

## Steps to Reproduce (for bugs)
```sh
git clone https://github.com/aminpaks/lerna-test.git
lerna publish
```

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.5",
  "packages": [
    "packages/*"
  ],
  "version": "0.0.1"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'publish' ]
1 silly flags { _: [ 'publish' ], sort: true, concurrency: 4 }
2 verbose rootPath /[removed_path]/lerna-test
3 info version 2.0.0-rc.5
4 silly isInitialized
5 silly isInitialized true
6 silly existsSync /[removed_path]/lerna-test/VERSION
7 silly initialize attempt
8 info current version 0.0.1
9 silly getUpdates
10 info Checking for updated packages...
11 silly hasTags
12 verbose hasTags true
13 silly getLastTag
14 verbose getLastTag v0.0.1
15 info Comparing with tag v0.0.1
16 silly getLastTaggedCommitInBranch
17 silly getLastTag
18 verbose getLastTag v0.0.1
19 verbose getLastTaggedCommitInBranch f443230e3ceef310deb80cefba908bcf81effdc5
20 silly describeTag f443230e3ceef310deb80cefba908bcf81effdc5
21 silly describeTag v0.0.1
22 silly diffSinceIn v0.0.1 /[removed_path]/lerna-test/packages/useless
23 silly diff
24 silly collectDependents
25 silly collectUpdates
26 info No updated packages to publish.
27 silly initialize success
28 silly execute attempt
29 silly isDetachedHead
30 silly getCurrentBranch
31 verbose getCurrentBranch master
32 verbose isDetachedHead false
33 silly addFile /[removed_path]/lerna-test/lerna.json
34 silly commit vundefined
35 verbose commit [ 'commit', '-m', 'vundefined' ]
36 silly addTag vundefined
37 error execute Error: fatal: tag 'vundefined' already exists
37 error execute
37 error execute     at Function.module.exports.sync (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:277:26)
37 error execute     at Function.execSync (/usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
37 error execute     at Function.addTag (/usr/local/lib/node_modules/lerna/lib/GitUtilities.js:90:39)
37 error execute     at PublishCommand.gitCommitAndTagVersion (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:592:30)
37 error execute     at PublishCommand.commitAndTagUpdates (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:562:27)
37 error execute     at PublishCommand.execute (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:246:16)
37 error execute     at PublishCommand._attempt (/usr/local/lib/node_modules/lerna/lib/Command.js:265:21)
37 error execute     at /usr/local/lib/node_modules/lerna/lib/Command.js:252:15
37 error execute     at /usr/local/lib/node_modules/lerna/lib/Command.js:274:13
37 error execute     at PublishCommand.initialize (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:205:9)
37 error execute  callback with error
37 error execute  { Error: fatal: tag 'vundefined' already exists
37 error execute
37 error execute     at Function.module.exports.sync (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:277:26)
37 error execute     at Function.execSync (/usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
37 error execute     at Function.addTag (/usr/local/lib/node_modules/lerna/lib/GitUtilities.js:90:39)
37 error execute     at PublishCommand.gitCommitAndTagVersion (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:592:30)
37 error execute     at PublishCommand.commitAndTagUpdates (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:562:27)
37 error execute     at PublishCommand.execute (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:246:16)
37 error execute     at PublishCommand._attempt (/usr/local/lib/node_modules/lerna/lib/Command.js:265:21)
37 error execute     at /usr/local/lib/node_modules/lerna/lib/Command.js:252:15
37 error execute     at /usr/local/lib/node_modules/lerna/lib/Command.js:274:13
37 error execute     at PublishCommand.initialize (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:205:9)
37 error execute   stack: 'Error: fatal: tag \'vundefined\' already exists\n\n    at Function.module.exports.sync (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:277:26)\n    at Function.execSync (/usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)\n    at Function.addTag (/usr/local/lib/node_modules/lerna/lib/GitUtilities.js:90:39)\n    at PublishCommand.gitCommitAndTagVersion (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:592:30)\n    at PublishCommand.commitAndTagUpdates (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:562:27)\n    at PublishCommand.execute (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:246:16)\n    at PublishCommand._attempt (/usr/local/lib/node_modules/lerna/lib/Command.js:265:21)\n    at /usr/local/lib/node_modules/lerna/lib/Command.js:252:15\n    at /usr/local/lib/node_modules/lerna/lib/Command.js:274:13\n    at PublishCommand.initialize (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:205:9)' }

```
</p></details>

## Context
I cannot publish with lerna at all!

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.5 or 2.0.0 |
| `npm --version`  | 5.3.0 |
| `yarn --version` | 0.27.5 |
| `node --version` | v7.10.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.5 |

**Comment by aminpaks** [comment]
So it turns out, before `lerna publish` we need to install the root packages with `npm` otherwise it won't work properly.
I had installed `lerna` with yarn that's why I was getting that error.

Thanks.
