### ISSUE TITLE
TypeError on any lerna command when using workspaces

### ISSUE THREAD

**Issue by sdeleon28** [lerna/lerna#969]
TypeError on any lerna command when using workspaces

## Expected Behavior

Should be able to run commands like `lerna clean`.

## Current Behavior

Lerna crashes.

## Steps to Reproduce (for bugs)

* Clone https://github.com/sdeleon28/lerna-workspaces-test/
* Install Lerna and Yarn in the way described in the `README.md` file
* Run `lerna clean`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0",
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ 'clean' ]
1 silly flags { _: [ 'clean' ] }
2 verbose rootPath /Users/santi/react_projects/lerna-workspaces-test
3 info version 2.0.0
4 silly existsSync /Users/santi/react_projects/lerna-workspaces-test/VERSION
5 error EPACKAGES TypeError: Cannot read property 'some' of undefined
5 error EPACKAGES     at Function.getPackages (/usr/local/lib/node_modules/lerna/lib/PackageUtilities.js:98:42)
5 error EPACKAGES     at Repository.buildPackageGraph (/usr/local/lib/node_modules/lerna/lib/Repository.js:82:51)
5 error EPACKAGES     at CleanCommand.runPreparations (/usr/local/lib/node_modules/lerna/lib/Command.js:245:25)
5 error EPACKAGES     at CleanCommand.run (/usr/local/lib/node_modules/lerna/lib/Command.js:159:12)
5 error EPACKAGES     at Object.handler (/usr/local/lib/node_modules/lerna/lib/commands/CleanCommand.js:41:41)
5 error EPACKAGES     at Object.self.runCommand (/usr/local/lib/node_modules/lerna/node_modules/yargs/lib/command.js:233:22)
5 error EPACKAGES     at Object.Yargs.self._parseArgs (/usr/local/lib/node_modules/lerna/node_modules/yargs/yargs.js:990:30)
5 error EPACKAGES     at Object.Yargs.self.parse (/usr/local/lib/node_modules/lerna/node_modules/yargs/yargs.js:532:23)
5 error EPACKAGES     at Object.<anonymous> (/usr/local/lib/node_modules/lerna/bin/lerna.js:4:25)
5 error EPACKAGES     at Module._compile (module.js:569:30)
5 error EPACKAGES  Errored while collecting packages and package graph { TypeError: Cannot read property 'some' of undefined
5 error EPACKAGES     at Function.getPackages (/usr/local/lib/node_modules/lerna/lib/PackageUtilities.js:98:42)
5 error EPACKAGES     at Repository.buildPackageGraph (/usr/local/lib/node_modules/lerna/lib/Repository.js:82:51)
5 error EPACKAGES     at CleanCommand.runPreparations (/usr/local/lib/node_modules/lerna/lib/Command.js:245:25)
5 error EPACKAGES     at CleanCommand.run (/usr/local/lib/node_modules/lerna/lib/Command.js:159:12)
5 error EPACKAGES     at Object.handler (/usr/local/lib/node_modules/lerna/lib/commands/CleanCommand.js:41:41)
5 error EPACKAGES     at Object.self.runCommand (/usr/local/lib/node_modules/lerna/node_modules/yargs/lib/command.js:233:22)
5 error EPACKAGES     at Object.Yargs.self._parseArgs (/usr/local/lib/node_modules/lerna/node_modules/yargs/yargs.js:990:30)
5 error EPACKAGES     at Object.Yargs.self.parse (/usr/local/lib/node_modules/lerna/node_modules/yargs/yargs.js:532:23)
5 error EPACKAGES     at Object.<anonymous> (/usr/local/lib/node_modules/lerna/bin/lerna.js:4:25)
5 error EPACKAGES     at Module._compile (module.js:569:30)
5 error EPACKAGES   stack: 'TypeError: Cannot read property \'some\' of undefined\n    at Function.getPackages (/usr/local/lib/node_modules/lerna/lib/PackageUtilities.js:98:42)\n    at Repository.buildPackageGraph (/usr/local/lib/node_modules/lerna/lib/Repository.js:82:51)\n    at CleanCommand.runPreparations (/usr/local/lib/node_modules/lerna/lib/Command.js:245:25)\n    at CleanCommand.run (/usr/local/lib/node_modules/lerna/lib/Command.js:159:12)\n    at Object.handler (/usr/local/lib/node_modules/lerna/lib/commands/CleanCommand.js:41:41)\n    at Object.self.runCommand (/usr/local/lib/node_modules/lerna/node_modules/yargs/lib/command.js:233:22)\n    at Object.Yargs.self._parseArgs (/usr/local/lib/node_modules/lerna/node_modules/yargs/yargs.js:990:30)\n    at Object.Yargs.self.parse (/usr/local/lib/node_modules/lerna/node_modules/yargs/yargs.js:532:23)\n    at Object.<anonymous> (/usr/local/lib/node_modules/lerna/bin/lerna.js:4:25)\n    at Module._compile (module.js:569:30)' }
```
</p></details>

## Context

I'm trying to set up a monorepo for a universal React app. Trying to find the safest way (with locks) that is also performant and doesn't have a major impact on the rest of my team.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0 |
| `npm --version`  | 5.3.0 |
| `yarn --version` | 0.28.4 |
| `node --version` | v8.2.1 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.5 |

**Comment by viliusl** [comment]
@sdeleon28 I had the same happenning. Though feedback is not amazing, but when using workspaces you should declare your packages in `package.json` - https://github.com/lerna/lerna#--use-workspaces.

Afaik better feedback from lerna would do the trick.

**Comment by evocateur** [comment]
@sdeleon28 Couple things:
1. Your root package.json needs a `workspaces` key, which is missing.
2. Your `packages/package.json` is not actually a package. The glob refers to every subdirectory of `packages` that contains a package.json, so it has to be something like `packages/pkg-1/package.json`.

https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/

**Comment by cdaringe** [comment]
hi all.  thx for the leads.  whilst this was a configuration bug, the error message presented is arguably also a bug, from a UX perspective.  we ought consider detecting that bad state and throwing an expected error
