### ISSUE TITLE
Feature Proposal: Cleaner bootstrap logs

### ISSUE THREAD

**Issue by gauntface** [lerna/lerna#977]
If a project fails to bootstrap, it gets pretty hard to understand what is going on:

1.) Hard to differentiate logs from the `prepublish` commands output, the NPM logs from `npm run prepublish` and from lerna
2.) Hard to understand which package(s) failed to build.

## Current Behavior
For example, a project I'm working on runs on a *single* package and this is the log it outputs when that one module fails:

```
lerna info version 2.0.0
lerna info scope workbox-core
lerna info Bootstrapping 1 packages
lerna info lifecycle preinstall
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna ERR! execute Error: Command failed: npm run prepublish
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute [Workbox Gulp Log]: Could not find the browser bundle: workbox-core
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute [13:59:18] 'build-package (workbox-core) ["dev"]' errored after 2.35 ms
lerna ERR! execute [13:59:18] Error: Could not find the browser bundle: workbox-core
lerna ERR! execute     at formatError (/home/travis/build/GoogleChrome/workbox/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/formatError.js:20:10)
lerna ERR! execute     at Gulp.<anonymous> (/home/travis/build/GoogleChrome/workbox/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:30:15)
lerna ERR! execute     at emitOne (events.js:120:20)
lerna ERR! execute     at Gulp.emit (events.js:210:7)
lerna ERR! execute     at Object.error (/home/travis/build/GoogleChrome/workbox/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
lerna ERR! execute     at handler (/home/travis/build/GoogleChrome/workbox/node_modules/now-and-later/lib/mapSeries.js:43:14)
lerna ERR! execute     at f (/home/travis/build/GoogleChrome/workbox/node_modules/once/once.js:25:25)
lerna ERR! execute     at f (/home/travis/build/GoogleChrome/workbox/node_modules/once/once.js:25:25)
lerna ERR! execute     at done (/home/travis/build/GoogleChrome/workbox/node_modules/async-done/index.js:24:15)
lerna ERR! execute     at onError (/home/travis/build/GoogleChrome/workbox/node_modules/async-done/index.js:32:12)
lerna ERR! execute [13:59:18] 'build-packages:build' errored after 3.51 ms
lerna ERR! execute [13:59:18] 'build-packages' errored after 9.35 ms
lerna ERR! execute npm ERR! code ELIFECYCLE
lerna ERR! execute npm ERR! errno 1
lerna ERR! execute npm ERR! workbox-core@1.2.0 prepublish: `gulp build-packages --package workbox-core`
lerna ERR! execute npm ERR! Exit status 1
lerna ERR! execute npm ERR! 
lerna ERR! execute npm ERR! Failed at the workbox-core@1.2.0 prepublish script.
lerna ERR! execute npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR! execute npm WARN Local package.json exists, but node_modules missing, did you mean to install?
lerna ERR! execute 
lerna ERR! execute npm ERR! A complete log of this run can be found in:
lerna ERR! execute npm ERR!     /home/travis/.npm/_logs/2017-08-21T13_59_18_218Z-debug.log
lerna ERR! execute 
lerna ERR! execute > workbox-core@1.2.0 prepublish /home/travis/build/GoogleChrome/workbox/packages/workbox-core
lerna ERR! execute > gulp build-packages --package workbox-core
lerna ERR! execute 
lerna ERR! execute [13:59:17] Working directory changed to ~/build/GoogleChrome/workbox
lerna ERR! execute [13:59:18] Using gulpfile ~/build/GoogleChrome/workbox/gulpfile.js
lerna ERR! execute [13:59:18] Starting 'build-packages'...
lerna ERR! execute [13:59:18] Starting 'build-packages:clean'...
lerna ERR! execute [13:59:18] Starting 'build-packages:clean (workbox-core)'...
lerna ERR! execute [13:59:18] Finished 'build-packages:clean (workbox-core)' after 2.49 ms
lerna ERR! execute [13:59:18] Finished 'build-packages:clean' after 3.61 ms
lerna ERR! execute [13:59:18] Starting 'build-packages:build'...
lerna ERR! execute [13:59:18] Starting 'build-package (workbox-core) ["dev"]'...
lerna ERR! execute 
lerna ERR! execute     at Promise.all.then.arr (/home/travis/build/GoogleChrome/workbox/node_modules/execa/index.js:210:11)
lerna ERR! execute     at <anonymous>
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:188:7)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: Command failed: npm run prepublish
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute [Workbox Gulp Log]: Could not find the browser bundle: workbox-core
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute [13:59:18] 'build-package (workbox-core) ["dev"]' errored after 2.35 ms
lerna ERR! execute [13:59:18] Error: Could not find the browser bundle: workbox-core
lerna ERR! execute     at formatError (/home/travis/build/GoogleChrome/workbox/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/formatError.js:20:10)
lerna ERR! execute     at Gulp.<anonymous> (/home/travis/build/GoogleChrome/workbox/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:30:15)
lerna ERR! execute     at emitOne (events.js:120:20)
lerna ERR! execute     at Gulp.emit (events.js:210:7)
lerna ERR! execute     at Object.error (/home/travis/build/GoogleChrome/workbox/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
lerna ERR! execute     at handler (/home/travis/build/GoogleChrome/workbox/node_modules/now-and-later/lib/mapSeries.js:43:14)
lerna ERR! execute     at f (/home/travis/build/GoogleChrome/workbox/node_modules/once/once.js:25:25)
lerna ERR! execute     at f (/home/travis/build/GoogleChrome/workbox/node_modules/once/once.js:25:25)
lerna ERR! execute     at done (/home/travis/build/GoogleChrome/workbox/node_modules/async-done/index.js:24:15)
lerna ERR! execute     at onError (/home/travis/build/GoogleChrome/workbox/node_modules/async-done/index.js:32:12)
lerna ERR! execute [13:59:18] 'build-packages:build' errored after 3.51 ms
lerna ERR! execute [13:59:18] 'build-packages' errored after 9.35 ms
lerna ERR! execute npm ERR! code ELIFECYCLE
lerna ERR! execute npm ERR! errno 1
lerna ERR! execute npm ERR! workbox-core@1.2.0 prepublish: `gulp build-packages --package workbox-core`
lerna ERR! execute npm ERR! Exit status 1
lerna ERR! execute npm ERR! 
lerna ERR! execute npm ERR! Failed at the workbox-core@1.2.0 prepublish script.
lerna ERR! execute npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR! execute npm WARN Local package.json exists, but node_modules missing, did you mean to install?
lerna ERR! execute 
lerna ERR! execute npm ERR! A complete log of this run can be found in:
lerna ERR! execute npm ERR!     /home/travis/.npm/_logs/2017-08-21T13_59_18_218Z-debug.log
lerna ERR! execute 
lerna ERR! execute > workbox-core@1.2.0 prepublish /home/travis/build/GoogleChrome/workbox/packages/workbox-core
lerna ERR! execute > gulp build-packages --package workbox-core
lerna ERR! execute 
lerna ERR! execute [13:59:17] Working directory changed to ~/build/GoogleChrome/workbox
lerna ERR! execute [13:59:18] Using gulpfile ~/build/GoogleChrome/workbox/gulpfile.js
lerna ERR! execute [13:59:18] Starting 'build-packages'...
lerna ERR! execute [13:59:18] Starting 'build-packages:clean'...
lerna ERR! execute [13:59:18] Starting 'build-packages:clean (workbox-core)'...
lerna ERR! execute [13:59:18] Finished 'build-packages:clean (workbox-core)' after 2.49 ms
lerna ERR! execute [13:59:18] Finished 'build-packages:clean' after 3.61 ms
lerna ERR! execute [13:59:18] Starting 'build-packages:build'...
lerna ERR! execute [13:59:18] Starting 'build-package (workbox-core) ["dev"]'...
lerna ERR! execute 
lerna ERR! execute     at Promise.all.then.arr (/home/travis/build/GoogleChrome/workbox/node_modules/execa/index.js:210:11)
lerna ERR! execute     at <anonymous>
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:188:7)
lerna ERR! execute   stack: 'Error: Command failed: npm run prepublish\n\n\n[Workbox Gulp Log]: Could not find the browser bundle: workbox-core\n\n\n[13:59:18] \'build-package (workbox-core) ["dev"]\' errored after 2.35 ms\n[13:59:18] Error: Could not find the browser bundle: workbox-core\n    at formatError (/home/travis/build/GoogleChrome/workbox/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/formatError.js:20:10)\n    at Gulp.<anonymous> (/home/travis/build/GoogleChrome/workbox/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:30:15)\n    at emitOne (events.js:120:20)\n    at Gulp.emit (events.js:210:7)\n    at Object.error (/home/travis/build/GoogleChrome/workbox/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)\n    at handler (/home/travis/build/GoogleChrome/workbox/node_modules/now-and-later/lib/mapSeries.js:43:14)\n    at f (/home/travis/build/GoogleChrome/workbox/node_modules/once/once.js:25:25)\n    at f (/home/travis/build/GoogleChrome/workbox/node_modules/once/once.js:25:25)\n    at done (/home/travis/build/GoogleChrome/workbox/node_modules/async-done/index.js:24:15)\n    at onError (/home/travis/build/GoogleChrome/workbox/node_modules/async-done/index.js:32:12)\n[13:59:18] \'build-packages:build\' errored after 3.51 ms\n[13:59:18] \'build-packages\' errored after 9.35 ms\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! workbox-core@1.2.0 prepublish: `gulp build-packages --package workbox-core`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the workbox-core@1.2.0 prepublish script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\nnpm WARN Local package.json exists, but node_modules missing, did you mean to install?\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/travis/.npm/_logs/2017-08-21T13_59_18_218Z-debug.log\n\n> workbox-core@1.2.0 prepublish /home/travis/build/GoogleChrome/workbox/packages/workbox-core\n> gulp build-packages --package workbox-core\n\n[13:59:17] Working directory changed to ~/build/GoogleChrome/workbox\n[13:59:18] Using gulpfile ~/build/GoogleChrome/workbox/gulpfile.js\n[13:59:18] Starting \'build-packages\'...\n[13:59:18] Starting \'build-packages:clean\'...\n[13:59:18] Starting \'build-packages:clean (workbox-core)\'...\n[13:59:18] Finished \'build-packages:clean (workbox-core)\' after 2.49 ms\n[13:59:18] Finished \'build-packages:clean\' after 3.61 ms\n[13:59:18] Starting \'build-packages:build\'...\n[13:59:18] Starting \'build-package (workbox-core) ["dev"]\'...\n\n    at Promise.all.then.arr (/home/travis/build/GoogleChrome/workbox/node_modules/execa/index.js:210:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
lerna ERR! execute   code: 1,
lerna ERR! execute   killed: false,
lerna ERR! execute   stdout: '\n> workbox-core@1.2.0 prepublish /home/travis/build/GoogleChrome/workbox/packages/workbox-core\n> gulp build-packages --package workbox-core\n\n[13:59:17] Working directory changed to ~/build/GoogleChrome/workbox\n[13:59:18] Using gulpfile ~/build/GoogleChrome/workbox/gulpfile.js\n[13:59:18] Starting \'build-packages\'...\n[13:59:18] Starting \'build-packages:clean\'...\n[13:59:18] Starting \'build-packages:clean (workbox-core)\'...\n[13:59:18] Finished \'build-packages:clean (workbox-core)\' after 2.49 ms\n[13:59:18] Finished \'build-packages:clean\' after 3.61 ms\n[13:59:18] Starting \'build-packages:build\'...\n[13:59:18] Starting \'build-package (workbox-core) ["dev"]\'...\n',
lerna ERR! execute   stderr: '\n\n[Workbox Gulp Log]: Could not find the browser bundle: workbox-core\n\n\n[13:59:18] \'build-package (workbox-core) ["dev"]\' errored after 2.35 ms\n[13:59:18] Error: Could not find the browser bundle: workbox-core\n    at formatError (/home/travis/build/GoogleChrome/workbox/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/formatError.js:20:10)\n    at Gulp.<anonymous> (/home/travis/build/GoogleChrome/workbox/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:30:15)\n    at emitOne (events.js:120:20)\n    at Gulp.emit (events.js:210:7)\n    at Object.error (/home/travis/build/GoogleChrome/workbox/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)\n    at handler (/home/travis/build/GoogleChrome/workbox/node_modules/now-and-later/lib/mapSeries.js:43:14)\n    at f (/home/travis/build/GoogleChrome/workbox/node_modules/once/once.js:25:25)\n    at f (/home/travis/build/GoogleChrome/workbox/node_modules/once/once.js:25:25)\n    at done (/home/travis/build/GoogleChrome/workbox/node_modules/async-done/index.js:24:15)\n    at onError (/home/travis/build/GoogleChrome/workbox/node_modules/async-done/index.js:32:12)\n[13:59:18] \'build-packages:build\' errored after 3.51 ms\n[13:59:18] \'build-packages\' errored after 9.35 ms\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! workbox-core@1.2.0 prepublish: `gulp build-packages --package workbox-core`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the workbox-core@1.2.0 prepublish script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\nnpm WARN Local package.json exists, but node_modules missing, did you mean to install?\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/travis/.npm/_logs/2017-08-21T13_59_18_218Z-debug.log\n',
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'npm run prepublish',
lerna ERR! execute   timedOut: false }
```

## Possible Solution
Would be immensely helpful for Lerna to format this output a little better, one pull out `lerna ERR!` from a modules output and add summary of errors at the end. It also looks like the error logs is duplicated, confusing matters futher

```
lerna info version 2.0.0
lerna info scope workbox-core
lerna info Bootstrapping 1 packages
lerna info lifecycle preinstall
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna ERR! 
lerna ERR! 
lerna ERR! Failed to build "package-name"
lerna ERR!   Log from npm run prepublish


[13:59:17] Working directory changed to ~/build/GoogleChrome/workbox
[13:59:18] Using gulpfile ~/build/GoogleChrome/workbox/gulpfile.js
[13:59:18] Starting 'build-packages'...
[13:59:18] Starting 'build-packages:clean'...
[13:59:18] Starting 'build-packages:clean (workbox-core)'...
[13:59:18] Finished 'build-packages:clean (workbox-core)' after 2.49 ms
[13:59:18] Finished 'build-packages:clean' after 3.61 ms
[13:59:18] Starting 'build-packages:build'...
[13:59:18] Starting 'build-package (workbox-core) ["dev"]'...

    at Promise.all.then.arr (/home/travis/build/GoogleChrome/workbox/node_modules/execa/index.js:210:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) callback with error { Error: Command failed: npm run prepublish


[Workbox Gulp Log]: Could not find the browser bundle: workbox-core
 

[13:59:18] 'build-package (workbox-core) ["dev"]' errored after 2.35 ms
[13:59:18] Error: Could not find the browser bundle: workbox-core
    at formatError (/home/travis/build/GoogleChrome/workbox/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/formatError.js:20:10)
    at Gulp.<anonymous> (/home/travis/build/GoogleChrome/workbox/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:30:15)
    at emitOne (events.js:120:20)
    at Gulp.emit (events.js:210:7)
    at Object.error (/home/travis/build/GoogleChrome/workbox/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/home/travis/build/GoogleChrome/workbox/node_modules/now-and-later/lib/mapSeries.js:43:14)
    at f (/home/travis/build/GoogleChrome/workbox/node_modules/once/once.js:25:25)
    at f (/home/travis/build/GoogleChrome/workbox/node_modules/once/once.js:25:25)
    at done (/home/travis/build/GoogleChrome/workbox/node_modules/async-done/index.js:24:15)
    at onError (/home/travis/build/GoogleChrome/workbox/node_modules/async-done/index.js:32:12)
[13:59:18] 'build-packages:build' errored after 3.51 ms
[13:59:18] 'build-packages' errored after 9.35 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! workbox-core@1.2.0 prepublish: `gulp build-packages --package workbox-core`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the workbox-core@1.2.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-08-21T13_59_18_218Z-debug.log


lerna info Unable to bootstrap due to errors in the following packages:
lerna info   - package-name-1
lerna info   - package-name-2
```

I'm more than happy to have a crack at this in a PR if Lerna is open to it.

**Comment by evocateur** [comment]
We're definitely open to improvements to our error logging!
