### ISSUE TITLE
lerna diff - can't diff

### ISSUE THREAD

**Issue by iMoses** [lerna/lerna#980]
Nothing much to say other than the fact that it doesn't seem to work. It claims that "There are no commits in this repository" and I'm not sure what it means, since there most definitely are commits, I use lerna to publish and commit the new versions all the time.

## Expected Behavior

I don't know what the expected behavior is, I've never seen it, though I'm assuming it includes not throwing errors :)

## Current Behavior

```
lerna info version 2.0.0
lerna info versioning independent
lerna ERR! initialize Error: Can't diff. There are no commits in this repository, yet.
lerna ERR! initialize     at DiffCommand.initialize (/usr/lib/node_modules/lerna/lib/commands/DiffCommand.js:85:18)
lerna ERR! initialize     at DiffCommand._attempt (/usr/lib/node_modules/lerna/lib/Command.js:289:21)
lerna ERR! initialize     at DiffCommand.runCommand (/usr/lib/node_modules/lerna/lib/Command.js:275:12)
lerna ERR! initialize     at DiffCommand.run (/usr/lib/node_modules/lerna/lib/Command.js:160:12)
lerna ERR! initialize     at Object.handler (/usr/lib/node_modules/lerna/lib/commands/DiffCommand.js:37:44)
lerna ERR! initialize     at Object.self.runCommand (/usr/lib/node_modules/lerna/node_modules/yargs/lib/command.js:233:22)
lerna ERR! initialize     at Object.Yargs.self._parseArgs (/usr/lib/node_modules/lerna/node_modules/yargs/yargs.js:990:30)
lerna ERR! initialize     at Object.Yargs.self.parse (/usr/lib/node_modules/lerna/node_modules/yargs/yargs.js:532:23)
lerna ERR! initialize     at Object.<anonymous> (/usr/lib/node_modules/lerna/bin/lerna.js:4:25)
lerna ERR! initialize     at Module._compile (module.js:573:30)
lerna ERR! initialize  callback with error
lerna ERR! initialize  { Error: Can't diff. There are no commits in this repository, yet.
lerna ERR! initialize     at DiffCommand.initialize (/usr/lib/node_modules/lerna/lib/commands/DiffCommand.js:85:18)
lerna ERR! initialize     at DiffCommand._attempt (/usr/lib/node_modules/lerna/lib/Command.js:289:21)
lerna ERR! initialize     at DiffCommand.runCommand (/usr/lib/node_modules/lerna/lib/Command.js:275:12)
lerna ERR! initialize     at DiffCommand.run (/usr/lib/node_modules/lerna/lib/Command.js:160:12)
lerna ERR! initialize     at Object.handler (/usr/lib/node_modules/lerna/lib/commands/DiffCommand.js:37:44)
lerna ERR! initialize     at Object.self.runCommand (/usr/lib/node_modules/lerna/node_modules/yargs/lib/command.js:233:22)
lerna ERR! initialize     at Object.Yargs.self._parseArgs (/usr/lib/node_modules/lerna/node_modules/yargs/yargs.js:990:30)
lerna ERR! initialize     at Object.Yargs.self.parse (/usr/lib/node_modules/lerna/node_modules/yargs/yargs.js:532:23)
lerna ERR! initialize     at Object.<anonymous> (/usr/lib/node_modules/lerna/bin/lerna.js:4:25)
lerna ERR! initialize     at Module._compile (module.js:573:30)
lerna ERR! initialize   stack: 'Error: Can\'t diff. There are no commits in this repository, yet.\n    at DiffCommand.initialize (/usr/lib/node_modules/lerna/lib/commands/DiffCommand.js:85:18)\n    at DiffCommand._attempt (/usr/lib/node_modules/lerna/lib/Command.js:289:21)\n    at DiffCommand.runCommand (/usr/lib/node_modules/lerna/lib/Command.js:275:12)\n    at DiffCommand.run (/usr/lib/node_modules/lerna/lib/Command.js:160:12)\n    at Object.handler (/usr/lib/node_modules/lerna/lib/commands/DiffCommand.js:37:44)\n    at Object.self.runCommand (/usr/lib/node_modules/lerna/node_modules/yargs/lib/command.js:233:22)\n    at Object.Yargs.self._parseArgs (/usr/lib/node_modules/lerna/node_modules/yargs/yargs.js:990:30)\n    at Object.Yargs.self.parse (/usr/lib/node_modules/lerna/node_modules/yargs/yargs.js:532:23)\n    at Object.<anonymous> (/usr/lib/node_modules/lerna/bin/lerna.js:4:25)\n    at Module._compile (module.js:573:30)' }
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0",
  "packages": [
    "applications/*",
    "packages/*",
    "."
  ],
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly input [ undefined ]
1 silly flags { _: [ 'diff' ] }
2 verbose rootPath /home/ido/repos/shopymate/web
3 info version 2.0.0
4 info versioning independent
5 silly isInitialized
6 silly isInitialized true
7 silly existsSync /home/ido/repos/shopymate/web/VERSION
8 silly initialize attempt
9 silly hasCommit
10 verbose hasCommit false
11 error initialize Error: Can't diff. There are no commits in this repository, yet.
11 error initialize     at DiffCommand.initialize (/usr/lib/node_modules/lerna/lib/commands/DiffCommand.js:85:18)
11 error initialize     at DiffCommand._attempt (/usr/lib/node_modules/lerna/lib/Command.js:289:21)
11 error initialize     at DiffCommand.runCommand (/usr/lib/node_modules/lerna/lib/Command.js:275:12)
11 error initialize     at DiffCommand.run (/usr/lib/node_modules/lerna/lib/Command.js:160:12)
11 error initialize     at Object.handler (/usr/lib/node_modules/lerna/lib/commands/DiffCommand.js:37:44)
11 error initialize     at Object.self.runCommand (/usr/lib/node_modules/lerna/node_modules/yargs/lib/command.js:233:22)
11 error initialize     at Object.Yargs.self._parseArgs (/usr/lib/node_modules/lerna/node_modules/yargs/yargs.js:990:30)
11 error initialize     at Object.Yargs.self.parse (/usr/lib/node_modules/lerna/node_modules/yargs/yargs.js:532:23)
11 error initialize     at Object.<anonymous> (/usr/lib/node_modules/lerna/bin/lerna.js:4:25)
11 error initialize     at Module._compile (module.js:573:30)
11 error initialize  callback with error
11 error initialize  { Error: Can't diff. There are no commits in this repository, yet.
11 error initialize     at DiffCommand.initialize (/usr/lib/node_modules/lerna/lib/commands/DiffCommand.js:85:18)
11 error initialize     at DiffCommand._attempt (/usr/lib/node_modules/lerna/lib/Command.js:289:21)
11 error initialize     at DiffCommand.runCommand (/usr/lib/node_modules/lerna/lib/Command.js:275:12)
11 error initialize     at DiffCommand.run (/usr/lib/node_modules/lerna/lib/Command.js:160:12)
11 error initialize     at Object.handler (/usr/lib/node_modules/lerna/lib/commands/DiffCommand.js:37:44)
11 error initialize     at Object.self.runCommand (/usr/lib/node_modules/lerna/node_modules/yargs/lib/command.js:233:22)
11 error initialize     at Object.Yargs.self._parseArgs (/usr/lib/node_modules/lerna/node_modules/yargs/yargs.js:990:30)
11 error initialize     at Object.Yargs.self.parse (/usr/lib/node_modules/lerna/node_modules/yargs/yargs.js:532:23)
11 error initialize     at Object.<anonymous> (/usr/lib/node_modules/lerna/bin/lerna.js:4:25)
11 error initialize     at Module._compile (module.js:573:30)
11 error initialize   stack: 'Error: Can\'t diff. There are no commits in this repository, yet.\n    at DiffCommand.initialize (/usr/lib/node_modules/lerna/lib/commands/DiffCommand.js:85:18)\n    at DiffCommand._attempt (/usr/lib/node_modules/lerna/lib/Command.js:289:21)\n    at DiffCommand.runCommand (/usr/lib/node_modules/lerna/lib/Command.js:275:12)\n    at DiffCommand.run (/usr/lib/node_modules/lerna/lib/Command.js:160:12)\n    at Object.handler (/usr/lib/node_modules/lerna/lib/commands/DiffCommand.js:37:44)\n    at Object.self.runCommand (/usr/lib/node_modules/lerna/node_modules/yargs/lib/command.js:233:22)\n    at Object.Yargs.self._parseArgs (/usr/lib/node_modules/lerna/node_modules/yargs/yargs.js:990:30)\n    at Object.Yargs.self.parse (/usr/lib/node_modules/lerna/node_modules/yargs/yargs.js:532:23)\n    at Object.<anonymous> (/usr/lib/node_modules/lerna/bin/lerna.js:4:25)\n    at Module._compile (module.js:573:30)' }
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0 |
| `npm --version`  | 5.3.0 |
| `node --version` | 8.4.0 |

| OS | Version |
| --- | --- |
| Ubuntu | 16.04 |

**Comment by evocateur** [comment]
I don't suppose you could whip up a sample repo that reproduces this? I'm a little suspicious of the `packages` globs in lerna.json (lacking any other context).
