### ISSUE TITLE
lerna exec -- npm outdated causes Error: spawn npm ENOENT

### ISSUE THREAD

**Issue by Arikael** [lerna/lerna#983]
First of all, really nice project. Already saved me time and nerves :)

When I try to run `lerna exec -- npm outdated` or `lerna exec  -scope mypackage -- npm outdated`
I get an error message (see lerna-debug.log). When I run `npm outdated` directly in the package's directory the command works as expected.
The error also doesn't occur when no packages are outdated. 
When multiple packages are need of update it seems to fail at a random project, but I noticed that it always seems to process 2 of 3 projects when all 3 had outdated projects. When I have one outdated project it would display the output of `npm outdated` and then throw the error.
so maybe it's not the command itself that fails but "something in between".

**EDIT**
Don't know if important but we use a custom registry (our own hosted on Visual Studio Online) for npm.

## Expected Behavior
the command should return the results of `npm outdated` for every package

## Current Behavior
one random project fails (see above)

## Steps to Reproduce (for bugs)
1. open IDE (WebStorm) as admin
2. init a new lerna project
3. bootstrap it (i actually did that multiple times)
4. install dependencies (two of my packages depend on a third one from the same project)
5. just to reproduce install a dependency with an old version so step 6 yields results (and the error occurs)
6. run lerna exec -- npm outdated

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0",
  "packages": [
    "packages/*"
  ],
  "version": "0.1.2"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
lerna ERR! exec Errored while executing 'npm outdated' in '@project/core'
lerna ERR! execute Error: spawn npm ENOENT
lerna ERR! execute     at notFoundError (C:\Users\MyUser\AppData\Roaming\npm\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:11:11)
lerna ERR! execute     at verifyENOENT (C:\Users\MyUser\AppData\Roaming\npm\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:46:16)
lerna ERR! execute     at ChildProcess.cp.emit (C:\Users\MyUser\AppData\Roaming\npm\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:33:19)
lerna ERR! execute     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: spawn npm ENOENT
lerna ERR! execute     at notFoundError (C:\Users\MyUser\AppData\Roaming\npm\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:11:11)
lerna ERR! execute     at verifyENOENT (C:\Users\MyUser\AppData\Roaming\npm\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:46:16)
lerna ERR! execute     at ChildProcess.cp.emit (C:\Users\MyUser\AppData\Roaming\npm\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:33:19)
lerna ERR! execute     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
lerna ERR! execute   stack: 'Error: spawn npm ENOENT\n    at notFoundError (C:\\Users\\MyUser\\AppData\\Roaming\\npm\\node_modules\\lerna\\node_modules\\cross-spawn\\lib\\enoent.js:11:11)\n    at verifyENOENT (C:\\Users\\MyUser\\AppData\\Roaming\\npm\\node_modules\\lerna\\node_modules\\cross-spawn\\lib\\enoent.js:46:16)\n    at ChildProcess.cp.emit
 (C:\\Users\\MyUser\\AppData\\Roaming\\npm\\node_modules\\lerna\\node_modules\\cross-spawn\\lib\\enoent.js:33:19)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)',
lerna ERR! execute   errno: 'ENOENT',
lerna ERR! execute   code: 'ENOENT',
lerna ERR! execute   syscall: 'spawn npm',
lerna ERR! execute   killed: false,
lerna ERR! execute   stdout: null,
lerna ERR! execute   stderr: null,
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'npm outdated',
lerna ERR! execute   timedOut: false }
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0|
| `npm --version`  | 5.3.0 |
| `node --version` | 8.4.0 |

| OS | Version |
| --- | --- |
| Windows 10 Enterprise | 1607 |

**Comment by evocateur** [comment]
My immediate hunch is that this is probably npm5-related, as I've seen lots of (seemingly) random CI failures on Windows due to permissions or ENOENT errors on "shared" files like caches and whatnot.

What happens when you run the command without concurrency?
```
lerna exec --concurrency=1 -- npm outdated
```

**Comment by Arikael** [comment]
unfortunately the error persists.

**Comment by dptoot** [comment]
We are running npm 4 and getting a similar error

```
lerna ERR! exec Errored while executing 'npm outdated' in 'reaxl'
lerna ERR! execute Error: spawn npm ENOENT
lerna ERR! execute     at notFoundError (C:\Users\jelewis1\AppData\Roaming\npm\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:11:11)
lerna ERR! execute     at verifyENOENT (C:\Users\jelewis1\AppData\Roaming\npm\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:46:16)
lerna ERR! execute     at ChildProcess.cp.emit (C:\Users\jelewis1\AppData\Roaming\npm\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:33:19)
lerna ERR! execute     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: spawn npm ENOENT
lerna ERR! execute     at notFoundError (C:\Users\jelewis1\AppData\Roaming\npm\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:11:11)
lerna ERR! execute     at verifyENOENT (C:\Users\jelewis1\AppData\Roaming\npm\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:46:16)
lerna ERR! execute     at ChildProcess.cp.emit (C:\Users\jelewis1\AppData\Roaming\npm\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:33:19)
lerna ERR! execute     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
lerna ERR! execute   stack: 'Error: spawn npm ENOENT\n    at notFoundError (C:\\Users\\jelewis1\\AppData\\Roaming\\npm\\node_modules\\lerna\\node_modules\\cross-spawn\\lib\\enoent.js:11:11)\n    at verifyENOENT (C:\\Users\\jelewis1\\AppData\\Roaming\\npm\\node_modules\\lerna\\node_modules\\cross-spawn\\lib\\enoent.js:46:16)\n    at ChildProcess.cp.emit (C:\\Users\\jelewis1\\AppData\\Roaming\\npm\\node_modules\\lerna\\node_modules\\cross-spawn\\lib\\enoent.js:33:19)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)',
lerna ERR! execute   errno: 'ENOENT',
lerna ERR! execute   code: 'ENOENT',
lerna ERR! execute   syscall: 'spawn npm',
lerna ERR! execute   killed: false,
lerna ERR! execute   stdout: null,
lerna ERR! execute   stderr: null,
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'npm outdated',
lerna ERR! execute   timedOut: false }
```

**Comment by sgrishchenko** [comment]
I have same error and **--bail false** helped me
