### ISSUE TITLE
Lerna publish --conventional-commits fails to increment the fixed version properly

### ISSUE THREAD

**Issue by canercandan** [lerna/lerna#988]
## Expected Behavior

I tried to used the --conventional-commits that comes along with `lerna publish` command and when I used the following setup it failed to increment properly the semantic version.

That's the result I was expecting to see:

```bash
$ mkdir /tmp/monorepo && cd $_
$ lerna init
$ mkdir -p packages/{pkg1,pkg2,pkg3}
$ find packages -name pkg\* -exec sh -c 'cd {} && yarn init -y' \;
$ git add . && git commit -a -m "build(npm): add setup"
$ lerna publish --conventional-commits --skip-npm --yes
lerna info version 2.1.0
lerna info current version 0.0.0
lerna info Checking for updated packages...
lerna info Comparing with initial commit.

Changes:
 - pkg1: 1.0.0 => 1.0.1
 - pkg2: 1.0.0 => 1.0.1
 - pkg3: 1.0.0 => 1.0.1

lerna info auto-confirmed
$ echo "console.log('test')" > packages/pkg1/index.js
$ git add . && git commit -a -m "feat(pkg1): add index.js"
$ lerna publish --conventional-commits --skip-npm --yes
lerna info version 2.1.0
lerna info current version 1.0.1
lerna info Checking for updated packages...
lerna info Comparing with v1.0.1.

Changes:
 - pkg1: 1.0.1 => 1.1.0

lerna info auto-confirmed
$ echo "console.log('test')" > packages/pkg2/index.js
$ git add . && git commit -a -m "feat(pkg2): add index.js"
$ lerna publish --conventional-commits --skip-npm --yes
lerna info version 2.1.0
lerna info current version 1.1.0
lerna info Checking for updated packages...
lerna info Comparing with v1.1.0.

Changes:
 - pkg2: 1.0.1 => 1.2.0

lerna info auto-confirmed 
```

## Current Behavior

But instead I got an error because `lerna publish` tried to re-create a tag that already exists:

```bash
$ mkdir /tmp/monorepo && cd $_
$ lerna init
$ mkdir -p packages/{pkg1,pkg2,pkg3}
$ find packages -name pkg\* -exec sh -c 'cd {} && yarn init -y' \;
$ git add . && git commit -a -m "build(npm): add setup"
$ lerna publish --conventional-commits --skip-npm --yes
lerna info version 2.1.0
lerna info current version 0.0.0
lerna info Checking for updated packages...
lerna info Comparing with initial commit.

Changes:
 - pkg1: 1.0.0 => 1.0.1
 - pkg2: 1.0.0 => 1.0.1
 - pkg3: 1.0.0 => 1.0.1

lerna info auto-confirmed
$ echo "console.log('test')" > packages/pkg1/index.js
$ git add . && git commit -a -m "feat(pkg1): add index.js"
$ lerna publish --conventional-commits --skip-npm --yes
lerna info version 2.1.0
lerna info current version 1.0.1
lerna info Checking for updated packages...
lerna info Comparing with v1.0.1.

Changes:
 - pkg1: 1.0.1 => 1.1.0

lerna info auto-confirmed
$ echo "console.log('test')" > packages/pkg2/index.js
$ git add . && git commit -a -m "feat(pkg2): add index.js"
$ lerna publish --conventional-commits --skip-npm --yes
lerna info version 2.1.0
lerna info current version 1.1.0
lerna info Checking for updated packages...
lerna info Comparing with v1.1.0.

Changes:
 - pkg2: 1.0.1 => 1.1.0

lerna info auto-confirmed 
lerna ERR! execute Error: fatal: tag 'v1.1.0' already exists
…
…
…
```

## Possible Solution

No clue so far.

## Steps to Reproduce (for bugs)

(see below)

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "lerna": "2.1.0",
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
0 silly input [ 'publish' ]
1 silly flags { _: [ 'publish' ],
1 silly flags   'conventional-commits': true,
1 silly flags   conventionalCommits: true,
1 silly flags   yes: true,
1 silly flags   'skip-npm': true,
1 silly flags   skipNpm: true }
2 verbose rootPath /tmp/monorepo
3 info version 2.1.0
4 silly isInitialized
5 silly isInitialized true
6 silly existsSync /tmp/monorepo/VERSION
7 silly initialize attempt
8 info current version 1.1.0
9 silly getUpdates
10 info Checking for updated packages...
11 silly hasTags
12 verbose hasTags true
13 silly getLastTag
14 verbose getLastTag v1.1.0
15 info Comparing with v1.1.0.
16 silly diffSinceIn v1.1.0 /tmp/monorepo/packages/pkg1
17 silly diff
18 silly diffSinceIn v1.1.0 /tmp/monorepo/packages/pkg2
19 silly diff packages/pkg2/index.js
20 silly diffSinceIn v1.1.0 /tmp/monorepo/packages/pkg3
21 silly diff
22 verbose updated pkg2
23 silly collectDependents
24 silly isPackageDependentOf pkg1 pkg2
25 silly isPackageDependentOf pkg2 pkg2
26 silly isPackageDependentOf pkg3 pkg2
27 silly collectUpdates
28 verbose has filtered update pkg2
29 silly recommendFixedVersion for pkg2 at /tmp/monorepo/packages/pkg2
30 verbose recommendFixedVersion increment 1.0.1 by minor
31 info auto-confirmed
32 silly initialize success
33 silly execute attempt
34 silly isDetachedHead
35 silly getCurrentBranch
36 verbose getCurrentBranch master
37 verbose isDetachedHead false
38 silly addFile /tmp/monorepo/lerna.json
39 silly updateFixedChangelog for pkg2 at /tmp/monorepo/packages/pkg2
40 silly existsSync /tmp/monorepo/packages/pkg2/CHANGELOG.md
41 silly readFileSync /tmp/monorepo/packages/pkg2/CHANGELOG.md
42 silly updateIndependentChangelog writing new entry: "**Note:** Version bump only for package pkg2"
43 silly writeFileSync [ '/tmp/monorepo/packages/pkg2/CHANGELOG.md',
43 silly writeFileSync   '# Change Log\n\nAll notable changes to this project will be documented in this file.\nSee [Conventional Commits](https://conventionalcommits.org) for commit guidelines.\n\n**Note:** Version bump only for package pkg2\n\n<a name="1.0.1"></a>\n## 1.0.1 (2017-08-26)\n\n\n\n\n**Note:** Version bump only for package pkg2' ]
44 verbose updateFixedChangelog wrote /tmp/monorepo/packages/pkg2/CHANGELOG.md
45 silly addFile /tmp/monorepo/packages/pkg2/CHANGELOG.md
46 silly addFile /tmp/monorepo/packages/pkg2/package.json
47 silly commit v1.1.0
48 verbose commit [ 'commit', '-m', 'v1.1.0' ]
49 silly addTag v1.1.0
50 error execute Error: fatal: tag 'v1.1.0' already exists
50 error execute
50 error execute     at Function.module.exports.sync (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:303:26)
50 error execute     at Function.execSync (/usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
50 error execute     at Function.addTag (/usr/local/lib/node_modules/lerna/lib/GitUtilities.js:90:39)
50 error execute     at PublishCommand.gitCommitAndTagVersion (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:658:30)
50 error execute     at PublishCommand.commitAndTagUpdates (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:627:27)
50 error execute     at PublishCommand.execute (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:270:16)
50 error execute     at PublishCommand._attempt (/usr/local/lib/node_modules/lerna/lib/Command.js:289:21)
50 error execute     at /usr/local/lib/node_modules/lerna/lib/Command.js:276:15
50 error execute     at /usr/local/lib/node_modules/lerna/lib/Command.js:301:13
50 error execute     at PublishCommand.confirmVersions (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:528:9)
50 error execute  callback with error
50 error execute  { Error: fatal: tag 'v1.1.0' already exists
50 error execute
50 error execute     at Function.module.exports.sync (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:303:26)
50 error execute     at Function.execSync (/usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
50 error execute     at Function.addTag (/usr/local/lib/node_modules/lerna/lib/GitUtilities.js:90:39)
50 error execute     at PublishCommand.gitCommitAndTagVersion (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:658:30)
50 error execute     at PublishCommand.commitAndTagUpdates (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:627:27)
50 error execute     at PublishCommand.execute (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:270:16)
50 error execute     at PublishCommand._attempt (/usr/local/lib/node_modules/lerna/lib/Command.js:289:21)
50 error execute     at /usr/local/lib/node_modules/lerna/lib/Command.js:276:15
50 error execute     at /usr/local/lib/node_modules/lerna/lib/Command.js:301:13
50 error execute     at PublishCommand.confirmVersions (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:528:9)
50 error execute   stack: 'Error: fatal: tag \'v1.1.0\' already exists\n\n    at Function.module.exports.sync (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:303:26)\n    at Function.execSync (/usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)\n    at Function.addTag (/usr/local/lib/node_modules/lerna/lib/GitUtilities.js:90:39)\n    at PublishCommand.gitCommitAndTagVersion (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:658:30)\n    at PublishCommand.commitAndTagUpdates (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:627:27)\n    at PublishCommand.execute (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:270:16)\n    at PublishCommand._attempt (/usr/local/lib/node_modules/lerna/lib/Command.js:289:21)\n    at /usr/local/lib/node_modules/lerna/lib/Command.js:276:15\n    at /usr/local/lib/node_modules/lerna/lib/Command.js:301:13\n    at PublishCommand.confirmVersions (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:528:9)' }
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.1.0 |
| `npm --version`  | 4.2.0 |
| `yarn --version` | 0.27.5 |
| `node --version` | v7.7.4 |
| `git --version` | 2.7.4 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Ubuntu | 16.04.1 |

**Comment by canercandan** [comment]
I am currently using the option `--force-publish=*` to bypass this issue but obviously it removes the whole benefit of using the fixed version mode

**Comment by jezzay** [comment]
@canercandan I've raised PR https://github.com/lerna/lerna/pull/992 to address this. Can you verify if this fixes this issue for you?

**Comment by canercandan** [comment]
Hi @jezzay many thanks for your help on this, can you provide a quick way to install a non-npm-published version of lerna including your PR? I guess that I need to clone the whole repo checkout your commit and yarn link the whole packages locally but I need you to confirm. Thanks ;-)

**Comment by canercandan** [comment]
@jezzay I manage to install lerna with you commit (downloaded the ZIP of the PR from github, extracted the ZIP locally, called yarn to install the deps and used `sudo yarn link` to get the `lerna` binary linked to `/usr/local/bin`) but when I try to reproduce the steps described here https://github.com/lerna/lerna/issues/988#issue-253047587 it still try to re-create the same git tag that have been already created at the previous `lerna publish` call

**Comment by canercandan** [comment]
here is the complete error I got this time:

```
 
lerna info version 2.1.0
lerna info current version 1.3.0
lerna info Checking for updated packages...
lerna info Comparing with v1.3.0.

Changes:
 - pkg3: 1.2.0 => 1.3.0

lerna info auto-confirmed 
lerna ERR! execute Error: fatal: tag 'v1.3.0' already exists
lerna ERR! execute 
lerna ERR! execute     at Function.module.exports.sync (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:303:26)
lerna ERR! execute     at Function.execSync (/usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
lerna ERR! execute     at Function.addTag (/usr/local/lib/node_modules/lerna/lib/GitUtilities.js:90:39)
lerna ERR! execute     at PublishCommand.gitCommitAndTagVersion (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:658:30)
lerna ERR! execute     at PublishCommand.commitAndTagUpdates (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:627:27)
lerna ERR! execute     at PublishCommand.execute (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:270:16)
lerna ERR! execute     at PublishCommand._attempt (/usr/local/lib/node_modules/lerna/lib/Command.js:289:21)
lerna ERR! execute     at /usr/local/lib/node_modules/lerna/lib/Command.js:276:15
lerna ERR! execute     at /usr/local/lib/node_modules/lerna/lib/Command.js:301:13
lerna ERR! execute     at PublishCommand.confirmVersions (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:528:9)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: fatal: tag 'v1.3.0' already exists
lerna ERR! execute 
lerna ERR! execute     at Function.module.exports.sync (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:303:26)
lerna ERR! execute     at Function.execSync (/usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
lerna ERR! execute     at Function.addTag (/usr/local/lib/node_modules/lerna/lib/GitUtilities.js:90:39)
lerna ERR! execute     at PublishCommand.gitCommitAndTagVersion (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:658:30)
lerna ERR! execute     at PublishCommand.commitAndTagUpdates (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:627:27)
lerna ERR! execute     at PublishCommand.execute (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:270:16)
lerna ERR! execute     at PublishCommand._attempt (/usr/local/lib/node_modules/lerna/lib/Command.js:289:21)
lerna ERR! execute     at /usr/local/lib/node_modules/lerna/lib/Command.js:276:15
lerna ERR! execute     at /usr/local/lib/node_modules/lerna/lib/Command.js:301:13
lerna ERR! execute     at PublishCommand.confirmVersions (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:528:9)
lerna ERR! execute   stack: 'Error: fatal: tag \'v1.3.0\' already exists\n\n    at Function.module.exports.sync (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:303:26)\n    at Function.execSync (/usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)\n    at Function.addTag (/usr/local/lib/node_modules/lerna/lib/GitUtilities.js:90:39)\n    at PublishCommand.gitCommitAndTagVersion (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:658:30)\n    at PublishCommand.commitAndTagUpdates (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:627:27)\n    at PublishCommand.execute (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:270:16)\n    at PublishCommand._attempt (/usr/local/lib/node_modules/lerna/lib/Command.js:289:21)\n    at /usr/local/lib/node_modules/lerna/lib/Command.js:276:15\n    at /usr/local/lib/node_modules/lerna/lib/Command.js:301:13\n    at PublishCommand.confirmVersions (/usr/local/lib/node_modules/lerna/lib/commands/PublishCommand.js:528:9)' }
```

**Comment by canercandan** [comment]
ohhh nooooo my bad the `sudo yarn link` did not prevent not using the previously installed `lerna` (2.1.0) version (see the path `/usr/local/lib/node_modules/lerna` in the error trace) so I will try to use the `lerna` bin generated in @jezzay version of `lerna` with the absolute path rather than through `yarn link`

**Comment by canercandan** [comment]
@jezzay and it works ;-) awesome :-p thanks dude

```
$ node /tmp/lerna/bin/lerna.js publish --conventional-commits --yes --skip-npm
lerna info version 2.1.0
lerna info current version 1.3.0
lerna info Checking for updated packages...
lerna info Comparing with v1.3.0.

Changes:
 - pkg3: 1.3.0 => 1.4.0

lerna info auto-confirmed 
```

**Comment by canercandan** [comment]
I am looking forward to seeing this PR merged and released now ;-)

**Comment by jezzay** [comment]
@canercandan Awesome, maybe reopen this issue until the PR is able to be reviewed and merged.

**Comment by canercandan** [comment]
@jezzay you are certainly right, it's reopened ;-)
